vrpRouting: breaks_input.c File Reference
breaks_input.c File Reference
#include "c_common/vroom/breaks_input.h"
Functions
static void db_get_breaks (char *breaks_sql, Vroom_break_t **breaks, size_t *total_breaks, Column_info_t *info, const int column_count, bool is_plain)
static void fetch_breaks (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t *info, Vroom_break_t *vroom_break, bool is_plain)
void get_vroom_breaks (char *sql, Vroom_break_t **rows, size_t *total_rows, bool is_plain)
Reads the VROOM breaks.
Function Documentation
db_get_breaks()
static void db_get_breaks (char * breaks_sql, Vroom_break_t ** breaks, size_t * total_breaks, Column_info_t * info, const int column_count, bool is_plain) static
Definition at line 78 of file breaks_input.c.
                    {
 #ifdef PROFILE
   clock_t start_t = clock();
   PGR_DBG("%s", breaks_sql);
 #endif
   const int tuple_limit = 1000000;
   size_t total_tuples;
   void *SPIplan;
   SPIplan = pgr_SPI_prepare(breaks_sql);
   Portal SPIportal;
   SPIportal = pgr_SPI_cursor_open(SPIplan);
   bool moredata = true;
   (*total_breaks) = total_tuples = 0;
   /* on the first tuple get the column numbers */
   while (moredata == true) {
     SPI_cursor_fetch(SPIportal, true, tuple_limit);
     if (total_tuples == 0) {
       pgr_fetch_column_info(info, column_count);
     }
     size_t ntuples = SPI_processed;
     total_tuples += ntuples;
     if (ntuples > 0) {
       if ((*breaks) == NULL)
         (*breaks) = (Vroom_break_t *)palloc0(
             total_tuples * sizeof(Vroom_break_t));
       else
         (*breaks) = (Vroom_break_t *)repalloc(
             (*breaks),
             total_tuples * sizeof(Vroom_break_t));
       if ((*breaks) == NULL) {
         elog(ERROR, "Out of memory");
       }
       size_t t;
       SPITupleTable *tuptable = SPI_tuptable;
       TupleDesc tupdesc = SPI_tuptable->tupdesc;
       for (t = 0; t < ntuples; t++) {
         HeapTuple tuple = tuptable->vals[t];
         fetch_breaks(&tuple, &tupdesc, info,
             &(*breaks)[total_tuples - ntuples + t], is_plain);
       }
       SPI_freetuptable(tuptable);
     } else {
       moredata = false;
     }
   }
   SPI_cursor_close(SPIportal);
   if (total_tuples == 0) {
     (*total_breaks) = 0;
     return;
   }
   (*total_breaks) = total_tuples;
 #ifdef PROFILE
   time_msg("reading breaks", start_t, clock());
 #endif
 }
References fetch_breaks(), PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), and time_msg().
Referenced by get_vroom_breaks().
fetch_breaks()
static void fetch_breaks (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t * info, Vroom_break_t * vroom_break, bool is_plain) static
Definition at line 57 of file breaks_input.c.
                    {
   vroom_break->id = get_Idx(tuple, tupdesc, info[0], 0);
   vroom_break->vehicle_id = get_Idx(tuple, tupdesc, info[1], 0);
   if (is_plain) {
     vroom_break->service = get_Duration(tuple, tupdesc, info[2], 0);
   } else {
     vroom_break->service =
         (Duration)get_PositiveTInterval(tuple, tupdesc, info[2], 0);
   }
   vroom_break->data = column_found(info[3].colNumber)
                           ? spi_getText(tuple, tupdesc, info[3])
                           : strdup("{}");
 }
References column_found(), Vroom_break_t::data, get_Duration(), get_Idx(), get_PositiveTInterval(), Vroom_break_t::id, Vroom_break_t::service, spi_getText(), and Vroom_break_t::vehicle_id.
Referenced by db_get_breaks().
get_vroom_breaks()
void get_vroom_breaks (char * sql, Vroom_break_t ** rows, size_t * total_rows, bool is_plain)
Reads the VROOM breaks.
Parameters
[in] sql SQL query to execute
[out] rows C Container that holds the data
[out] total_rows Total rows recieved
Definition at line 160 of file breaks_input.c.
                    {
   int kColumnCount = 4;
   Column_info_t info[kColumnCount];
   for (int i = 0; i < kColumnCount; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "id";
   info[1].name = "vehicle_id";
   info[2].name = "service";
   info[3].name = "data";
   info[2].eType = INTEGER;  // service
   info[3].eType = JSONB;    // data
   if (!is_plain) {
     info[2].eType = INTERVAL;  // service
   }
   /* service and data are not mandatory */
   info[2].strict = false;
   info[3].strict = false;
   db_get_breaks(sql, rows, total_rows, info, kColumnCount, is_plain);
 }
References ANY_INTEGER, Column_info_t::colNumber, db_get_breaks(), Column_info_t::eType, INTEGER, INTERVAL, JSONB, Column_info_t::name, Column_info_t::strict, and Column_info_t::type.
Referenced by process().