vrpRouting: vrprouting::problem::Vehicle Class Reference
vrprouting::problem::Vehicle Class Reference
Vehicle with time windows.
#include "vehicle.h"
Public Member Functions
PAmount capacity () const
returns the capacity of the vehicle
int cvTot () const
TInterval duration () const
duration of vehicle while not in a "depot"
bool empty () const
const Vehicle_node & end_site () const
std::vector< Solution_rt > get_postgres_result (int vid) const
std::vector< Id > get_stops () const
bool has_cv () const
bool has_twv () const
void invariant () const
bool is_feasible () const
bool is_ok () const
bool is_phony () const
bool is_real () const
size_t length () const
std::string path_str () const
Speed speed () const
the speed of the vehicle
const Vehicle_node & start_site () const
std::string tau () const
TInterval total_service_time () const
total time spent moving from one node to another
TInterval total_travel_time () const
total time spent moving from one node to another
TInterval total_wait_time () const
duration of vehicle while waiting for a node to open
int twvTot () const
Protected Member Functions
Vehicle ()=delete
Vehicle (const Vehicle &)=default
Vehicle (Idx idx, Id id, const Vehicle_node &p_starting_site, const Vehicle_node &p_ending_site, PAmount p_capacity, Speed p_speed=1.0)
std::pair< size_t, size_t > drop_position_limits (const Vehicle_node &node) const
void erase (const Vehicle_node &node)
deletes a node if it exists
void erase (size_t pos)
void erase_node (size_t pos)
void evaluate ()
void evaluate (size_t from)
size_t getDropPosLowLimit (const Vehicle_node &node) const
size_t getPosHighLimit (const Vehicle_node &node) const
Get the highest position on the path where node can be placed.
size_t getPosLowLimit (const Vehicle_node &node) const
Get the lowest position on the path where node can be placed.
void insert (size_t pos, const Vehicle_node &node)
void insert_node (size_t pos, const Vehicle_node &node)
void pop_back ()
void pop_front ()
std::pair< size_t, size_t > position_limits (const Vehicle_node &node) const
Get the limits to insert the node.
void push_back (const Vehicle_node &node)
void push_back_node (const Vehicle_node &node)
void push_front (const Vehicle_node &node)
void push_front_node (const Vehicle_node &node)
void swap (size_t i, size_t j)
Protected Attributes
T elements
STL member.
int m_user_cv {0}
Time window violations on solution.
int m_user_twv {0}
Time window violations on solution.
Private Attributes
PAmount m_capacity
int64_t m_id
size_t m_idx
Speed m_speed = 1.0
Friends
bool operator< (const Vehicle &lhs, const Vehicle &rhs)
Detailed Description
Vehicle with time windows.
General functionality for a vehicle in a PROBLEM problem
Recommended use:
Class my_vehicle : public vehicle
A vehicle is a sequence of N from starting site to ending site. has: capacity
Definition at line 61 of file vehicle.h.
Constructor & Destructor Documentation
Vehicle() [1/3]
vrprouting::problem::Vehicle::Vehicle () protected delete
Vehicle() [2/3]
vrprouting::problem::Vehicle::Vehicle (const Vehicle &) protected default
Vehicle() [3/3]
vrprouting::problem::Vehicle::Vehicle (Idx idx, Id id, const Vehicle_node & p_starting_site, const Vehicle_node & p_ending_site, PAmount p_capacity, Speed p_speed = 1.0) protected
Definition at line 235 of file vehicle.cpp.
                    :
   Identifier(idx, id),
   m_capacity(p_capacity),
   m_speed(p_speed) {
     std::deque<Vehicle_node>::push_back(p_starting_site);
     std::deque<Vehicle_node>::push_back(p_ending_site);
     evaluate();
   }
References evaluate().
Member Function Documentation
capacity()
PAmount vrprouting::problem::Vehicle::capacity () const
returns the capacity of the vehicle
Returns
the capacity of the vehicle
Definition at line 66 of file vehicle.cpp.
 {return m_capacity;}
References m_capacity.
Referenced by evaluate().
cvTot()
int vrprouting::problem::Vehicle::cvTot () const
Definition at line 94 of file vehicle.cpp.
 {return back().cvTot();}
Referenced by vrprouting::problem::Solution::cvTot(), has_cv(), vrprouting::problem::operator<(), vrprouting::problem::Vehicle_pickDeliver::set_initial_solution(), and tau().
drop_position_limits()
std::pair< size_t, size_t > vrprouting::problem::Vehicle::drop_position_limits (const Vehicle_node & node) const protected
Definition at line 426 of file vehicle.cpp.
{
   size_t high = getPosHighLimit(node);
   size_t low = getDropPosLowLimit(node);
   return std::make_pair(low, high);
 }
References getDropPosLowLimit(), and getPosHighLimit().
Referenced by vrprouting::problem::Vehicle_pickDeliver::semiLIFO().
duration()
TInterval vrprouting::problem::Vehicle::duration () const
duration of vehicle while not in a "depot"
Returns
0 when the Vehicle is phony
duration of vehicle while not in a stop or ending site
Definition at line 72 of file vehicle.cpp.
 {return is_phony()? 0 : back().arrival_time() - front().departure_time();}
References is_phony().
Referenced by vrprouting::problem::Solution::duration(), vrprouting::problem::operator<(), and tau().
empty()
bool vrprouting::problem::Vehicle::empty () const
Definition at line 112 of file vehicle.cpp.
 {return size() <= 2;}
Referenced by vrprouting::problem::Vehicle_pickDeliver::get_first_order(), vrprouting::problem::Vehicle_pickDeliver::pop_back(), and vrprouting::problem::Vehicle_pickDeliver::pop_front().
end_site()
const Vehicle_node & vrprouting::problem::Vehicle::end_site () const
Definition at line 124 of file vehicle.cpp.
 {return back();}
Referenced by is_ok().
erase() [1/2]
void vrprouting::problem::Vehicle::erase (const Vehicle_node & node) protected
deletes a node if it exists
Parameters
[in] node
Precondition
the node can not be S or E
S .... [node.idx()] .... E
Postcondition
S .... .... E
Definition at line 184 of file vehicle.cpp.
{
   pgassert(!node.is_start() && !node.is_end());
 #if 0
   /* TODO this works, but somehow gives docqueries give different results */
   std::deque<Vehicle_node>::erase(
       std::remove_if(begin(), end(),
         [&](const Vehicle_node& n) {return n.idx() == idx();}), end());
   evaluate();
 #else
   for (size_t pos = 0 ; pos < size() ; ++pos) {
     if (node.idx() == at(pos).idx()) {
       erase(pos);
       break;
     }
   }
 #endif
 }
References erase(), evaluate(), vrprouting::Identifier::idx(), vrprouting::problem::Tw_node::is_end(), vrprouting::problem::Tw_node::is_start(), and pgassert.
erase() [2/2]
void vrprouting::problem::Vehicle::erase (size_t pos) protected
Definition at line 172 of file vehicle.cpp.
{
   erase_node(pos);
   evaluate(pos);
 }
References erase_node(), and evaluate().
Referenced by erase().
erase_node()
void vrprouting::problem::Vehicle::erase_node (size_t pos) protected
Definition at line 152 of file vehicle.cpp.
{
   using difference_type = std::vector<double>::difference_type;
   pgassert(pos < size() - 1 && static_cast<difference_type>(pos) > 0);
   std::deque<Vehicle_node>::erase(std::deque<Vehicle_node>::begin() + static_cast<difference_type>(pos));
 }
References pgassert.
Referenced by erase(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), pop_back(), and pop_front().
evaluate() [1/2]
void vrprouting::problem::Vehicle::evaluate () protected
Definition at line 126 of file vehicle.cpp.
 {evaluate(0);}
Referenced by erase(), insert(), pop_back(), pop_front(), vrprouting::problem::Vehicle_pickDeliver::push_back(), push_back(), vrprouting::problem::Vehicle_pickDeliver::push_front(), push_front(), vrprouting::problem::Vehicle_pickDeliver::set_initial_solution(), swap(), and Vehicle().
evaluate() [2/2]
void vrprouting::problem::Vehicle::evaluate (size_t from) protected
Parameters
[in] from The position in the path for evaluation to the end of the path.
Definition at line 131 of file vehicle.cpp.
{
   invariant();
   // preconditions
   pgassert(from < size());
   using difference_type = std::vector<Vehicle_node>::difference_type;
   auto node = begin() + static_cast<difference_type>(from);
   while (node != end()) {
     if (node == begin()) {
       node->evaluate(capacity());
     } else {
       node->evaluate(*(node - 1), capacity(), speed());
     }
     ++node;
   }
   invariant();
 }
References capacity(), invariant(), pgassert, and speed().
get_postgres_result()
std::vector< Solution_rt > vrprouting::problem::Vehicle::get_postgres_result (int vid) const
Returns
the vehicle's path in a structure for postgres
Parameters
[in] vid it is the vid-th vehicle in the solution
Definition at line 292 of file vehicle.cpp.
{
   std::vector<Solution_rt> result;
   int stop_seq(1);
   for (const auto &p_stop : *this) {
     result.push_back(p_stop.get_postgres_result(vid, id(), stop_seq));
     ++stop_seq;
   }
   return result;
 }
get_stops()
std::vector< Id > vrprouting::problem::Vehicle::get_stops () const
Returns
container for postgres
Definition at line 306 of file vehicle.cpp.
{
   if (is_phony()) return std::vector<Id>();
   std::vector<Id> result;
   for (const auto &p_stop : *this) {
     if (p_stop.is_start() || p_stop.is_end()) continue;
     result.push_back(p_stop.order());
   }
   return result;
 }
References is_phony().
getDropPosLowLimit()
size_t vrprouting::problem::Vehicle::getDropPosLowLimit (const Vehicle_node & node) const protected
Definition at line 331 of file vehicle.cpp.
{
   invariant();
   size_t low = 0;
   size_t high = size();
   size_t low_limit = high;
   /* J == m_path[low_limit - 1] */
   while (low_limit > low
       && at(low_limit - 1).is_compatible_IJ(nodeI, speed())
       && !at(low_limit - 1).is_pickup()) {
     --low_limit;
   }
   invariant();
   return low_limit;
 }
References invariant(), and speed().
Referenced by drop_position_limits().
getPosHighLimit()
size_t vrprouting::problem::Vehicle::getPosHighLimit (const Vehicle_node & node) const protected
Get the highest position on the path where node can be placed.
Definition at line 397 of file vehicle.cpp.
{
   invariant();
   size_t low = 0;
   size_t high = size();
   size_t high_limit = low;
   /* I == m_path[high_limit] */
   while (high_limit < high
       && nodeJ.is_compatible_IJ(at(high_limit), speed())) {
     ++high_limit;
   }
   invariant();
   return high_limit;
 }
References invariant(), vrprouting::problem::Tw_node::is_compatible_IJ(), and speed().
Referenced by drop_position_limits(), and position_limits().
getPosLowLimit()
size_t vrprouting::problem::Vehicle::getPosLowLimit (const Vehicle_node & nodeI) const protected
Get the lowest position on the path where node can be placed.
Returns
the lowest position where the node can be placed
Parameters
[in] nodeI start searching from postition low = pos(E)
S 1 2 3 4 5 6 7 ..... E node -> E node -> ... node -> 7 node -> 6 node -> 5 node /-> 4
return low_limit = 5
Definition at line 366 of file vehicle.cpp.
{
   invariant();
   size_t low = 0;
   size_t high = size();
   size_t low_limit = high;
   /* J == m_path[low_limit - 1] */
   while (low_limit > low
       && at(low_limit - 1).is_compatible_IJ(nodeI)) {
     --low_limit;
   }
   invariant();
   return low_limit;
 }
References invariant().
Referenced by position_limits().
has_cv()
bool vrprouting::problem::Vehicle::has_cv () const
Definition at line 98 of file vehicle.cpp.
 {return cvTot() > m_user_cv;}
References cvTot(), and m_user_cv.
Referenced by is_feasible(), and vrprouting::problem::Vehicle_pickDeliver::semiLIFO().
has_twv()
bool vrprouting::problem::Vehicle::has_twv () const
Definition at line 96 of file vehicle.cpp.
 {return twvTot() > m_user_twv;}
References m_user_twv, and twvTot().
Referenced by is_feasible(), and vrprouting::problem::Vehicle_pickDeliver::semiLIFO().
id()
int64_t vrprouting::Identifier::id () const inherited
get the original id
Definition at line 42 of file identifier.cpp.
                      {
     return m_id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::problem::Vehicle_node::get_postgres_result(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), is_phony(), vrprouting::operator<<(), vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), vrprouting::problem::Vehicle_pickDeliver::set_initial_solution(), vrprouting::problem::Vehicle_pickDeliver::set_unmovable(), tau(), and vrprouting::problem::Tw_node::travel_time_to().
idx()
size_t vrprouting::Identifier::idx () const inherited
get the internal index
Definition at line 37 of file identifier.cpp.
                       {
     return m_idx;
 }
References vrprouting::Identifier::m_idx.
Referenced by vrprouting::problem::Vehicle_pickDeliver::erase(), erase(), vrprouting::problem::Vehicle_pickDeliver::has_order(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::operator<<(), vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), vrprouting::problem::Vehicle_pickDeliver::push_back(), vrprouting::problem::Vehicle_pickDeliver::push_front(), vrprouting::problem::Vehicle_pickDeliver::semiLIFO(), vrprouting::problem::Order::set_compatibles(), and tau().
insert()
void vrprouting::problem::Vehicle::insert (size_t pos, const Vehicle_node & node) protected
Definition at line 202 of file vehicle.cpp.
{
   insert_node(pos, node);
   evaluate(pos);
 }
References evaluate(), and insert_node().
Referenced by vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::problem::Vehicle_pickDeliver::semiLIFO(), and vrprouting::problem::Vehicle_pickDeliver::set_initial_solution().
insert_node()
void vrprouting::problem::Vehicle::insert_node (size_t pos, const Vehicle_node & node) protected
Definition at line 158 of file vehicle.cpp.
{
   using difference_type = std::vector<double>::difference_type;
   pgassert(pos < size() && static_cast<difference_type>(pos) > 0);
   std::deque<Vehicle_node>::insert(std::deque<Vehicle_node>::begin() + static_cast<difference_type>(pos), node);
 }
References pgassert.
Referenced by insert(), vrprouting::problem::Vehicle_pickDeliver::push_back(), push_back(), push_back_node(), vrprouting::problem::Vehicle_pickDeliver::push_front(), push_front(), and push_front_node().
invariant()
void vrprouting::problem::Vehicle::invariant () const
Definition at line 100 of file vehicle.cpp.
{
     pgassert(size() >= 2);
     pgassert(front().is_start());
     pgassert(back().is_end());
 }
References pgassert.
Referenced by evaluate(), getDropPosLowLimit(), getPosHighLimit(), getPosLowLimit(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::problem::Vehicle_pickDeliver::pop_back(), vrprouting::problem::Vehicle_pickDeliver::pop_front(), vrprouting::problem::Vehicle_pickDeliver::semiLIFO(), and tau().
is_feasible()
bool vrprouting::problem::Vehicle::is_feasible () const
Definition at line 120 of file vehicle.cpp.
 {return !(has_twv() ||  has_cv());}
References has_cv(), and has_twv().
Referenced by vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::problem::Vehicle_pickDeliver::semiLIFO(), and vrprouting::problem::Vehicle_pickDeliver::set_initial_solution().
is_ok()
bool vrprouting::problem::Vehicle::is_ok () const
Definition at line 106 of file vehicle.cpp.
{
     return (start_site().opens() <= start_site().closes())
         && (end_site().opens() <= end_site().closes())
         && (m_capacity > 0);
 }
References vrprouting::problem::Tw_node::closes(), end_site(), m_capacity, vrprouting::problem::Tw_node::opens(), and start_site().
is_phony()
bool vrprouting::problem::Vehicle::is_phony () const
Definition at line 116 of file vehicle.cpp.
 {return id() < 0;}
References vrprouting::Identifier::id().
Referenced by duration(), get_stops(), is_real(), vrprouting::optimizers::simple::Optimize::move_order(), vrprouting::problem::Vehicle_pickDeliver::objective(), vrprouting::optimizers::tabu::Optimize::swap_between_routes(), total_service_time(), total_travel_time(), and total_wait_time().
is_real()
bool vrprouting::problem::Vehicle::is_real () const
Definition at line 118 of file vehicle.cpp.
 {return !is_phony();}
References is_phony().
length()
size_t vrprouting::problem::Vehicle::length () const
Definition at line 114 of file vehicle.cpp.
 {return size() - 2;}
path_str()
std::string vrprouting::problem::Vehicle::path_str () const
Definition at line 272 of file vehicle.cpp.
{
   std::ostringstream key;
   for (const auto &p_stop : *this) {
     if (!(p_stop == front())) key << ",";
     if (p_stop.is_start() || p_stop.is_end()) {
       key << p_stop.type_str();
     } else {
       key << p_stop.type_str() << p_stop.order();
     }
   }
   return key.str();
 }
pop_back()
void vrprouting::problem::Vehicle::pop_back () protected
Definition at line 218 of file vehicle.cpp.
{
   erase_node(size() - 2);
   evaluate(size() - 1);
 }
References erase_node(), and evaluate().
pop_front()
void vrprouting::problem::Vehicle::pop_front () protected
Definition at line 223 of file vehicle.cpp.
{
   erase_node(1);
   evaluate();
 }
References erase_node(), and evaluate().
position_limits()
std::pair< size_t, size_t > vrprouting::problem::Vehicle::position_limits (const Vehicle_node & node) const protected
Get the limits to insert the node.
Returns
the upper and lower position on the path where the node can be inserted
Parameters
[in] node to try to be tested
Definition at line 419 of file vehicle.cpp.
{
   size_t high = getPosHighLimit(node);
   size_t low = getPosLowLimit(node);
   return std::make_pair(low, high);
 }
References getPosHighLimit(), and getPosLowLimit().
Referenced by vrprouting::problem::Vehicle_pickDeliver::hillClimb().
push_back()
void vrprouting::problem::Vehicle::push_back (const Vehicle_node & node) protected
Definition at line 208 of file vehicle.cpp.
{
   insert_node(size() - 1, node);
   evaluate(size() - 2);
 }
References evaluate(), and insert_node().
push_back_node()
void vrprouting::problem::Vehicle::push_back_node (const Vehicle_node & node) protected
Definition at line 164 of file vehicle.cpp.
{
   insert_node(1, node);
 }
References insert_node().
push_front()
void vrprouting::problem::Vehicle::push_front (const Vehicle_node & node) protected
Definition at line 213 of file vehicle.cpp.
{
   insert_node(1, node);
   evaluate();
 }
References evaluate(), and insert_node().
push_front_node()
void vrprouting::problem::Vehicle::push_front_node (const Vehicle_node & node) protected
Definition at line 168 of file vehicle.cpp.
{
   insert_node(size() - 1, node);
 }
References insert_node().
reset_id()
void vrprouting::Identifier::reset_id (int64_t _id) inherited
change the original id
Definition at line 47 of file identifier.cpp.
{
     m_id = _id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::problem::Tw_node::Tw_node().
speed()
Speed vrprouting::problem::Vehicle::speed () const
the speed of the vehicle
Returns
the value of the speed
When the matrix is a time matrix: speed should be in t / t^2 When the matrix is a distance matrix: speed should be in d / t^2
where: d = distance units t = time units
The calculated value of the traveling time will become tt(a, b) = matrix(a,b) / speed;
Definition at line 63 of file vehicle.cpp.
 {return m_speed;}
References m_speed.
Referenced by evaluate(), getDropPosLowLimit(), and getPosHighLimit().
start_site()
const Vehicle_node & vrprouting::problem::Vehicle::start_site () const
Definition at line 122 of file vehicle.cpp.
 {return front();}
Referenced by is_ok().
swap()
void vrprouting::problem::Vehicle::swap (size_t i, size_t j) protected
Definition at line 228 of file vehicle.cpp.
{
   pgassert(i < size() - 1 && i > 0);
   pgassert(j < size() - 1 && j > 0);
   std::swap(at(i), at(j));
   i < j ? evaluate(i) : evaluate(j);
 }
References evaluate(), and pgassert.
Referenced by vrprouting::problem::Vehicle_pickDeliver::hillClimb().
tau()
std::string vrprouting::problem::Vehicle::tau () const
Definition at line 251 of file vehicle.cpp.
                    {
   invariant();
   std::ostringstream log;
   log << "truck " << id() << "(" << idx() << ")" << " (";
   for (const auto &p_stop : *this) {
     if (!(p_stop == front())) log << ", ";
     p_stop.is_start() || p_stop.is_end()?
       log << p_stop.type_str() << id() :
       log << p_stop.type_str() << p_stop.order();
   }
   log << std::fixed << std::setprecision(4) << ")\t"
     << "twv=" << twvTot()
     << " cv=" << cvTot()
     << " wait=" << total_wait_time()
     << " duration=" << duration()
     << " tt=" << total_travel_time()
     << "\t";
   return log.str();
 }
References cvTot(), duration(), vrprouting::Identifier::id(), vrprouting::Identifier::idx(), invariant(), total_travel_time(), total_wait_time(), and twvTot().
Referenced by vrprouting::problem::Vehicle_pickDeliver::set_initial_solution().
total_service_time()
TInterval vrprouting::problem::Vehicle::total_service_time () const
total time spent moving from one node to another
Returns
duration of vehicle while moving for a node to open
0 when the Vehicle is phony
Definition at line 90 of file vehicle.cpp.
 {return is_phony()? 0 : back().total_service_time();}
References is_phony().
Referenced by vrprouting::problem::Solution::total_service_time().
total_travel_time()
TInterval vrprouting::problem::Vehicle::total_travel_time () const
total time spent moving from one node to another
Returns
total time vehicle spent moving from a node to another
0 when the Vehicle is phony
Definition at line 84 of file vehicle.cpp.
 {return is_phony()? 0 : back().total_travel_time();}
References is_phony().
Referenced by vrprouting::problem::Vehicle_pickDeliver::objective(), vrprouting::problem::operator<(), tau(), and vrprouting::problem::Solution::total_travel_time().
total_wait_time()
TInterval vrprouting::problem::Vehicle::total_wait_time () const
duration of vehicle while waiting for a node to open
Returns
duration of vehicle while waiting for a node to open
0 when the Vehicle is phony
Definition at line 78 of file vehicle.cpp.
 {return is_phony()? 0 : back().total_wait_time(); }
References is_phony().
Referenced by vrprouting::problem::operator<(), tau(), and vrprouting::problem::Solution::wait_time().
twvTot()
int vrprouting::problem::Vehicle::twvTot () const
Definition at line 92 of file vehicle.cpp.
 {return back().twvTot();}
Referenced by has_twv(), vrprouting::problem::operator<(), vrprouting::problem::Vehicle_pickDeliver::set_initial_solution(), tau(), and vrprouting::problem::Solution::twvTot().
Friends And Related Function Documentation
operator<
bool operator< (const Vehicle & lhs, const Vehicle & rhs) friend
Definition at line 433 of file vehicle.cpp.
{
   /*
    * capacity violations
    */
   if (lhs.cvTot() < rhs.cvTot()) return true;
   if (lhs.cvTot() > rhs.cvTot()) return false;
   /*
    * time window violations
    */
   if (lhs.twvTot() < rhs.twvTot()) return true;
   if (lhs.twvTot() > rhs.twvTot()) return false;
   /*
    * waiting time
    */
   if (lhs.total_wait_time() < rhs.total_wait_time()) return true;
   if (lhs.total_wait_time() > rhs.total_wait_time()) return false;
   /*
    * travel time
    */
   if (lhs.total_travel_time() < rhs.total_travel_time()) return true;
   if (lhs.total_travel_time() > rhs.total_travel_time()) return false;
   /*
    * duration
    */
   if (lhs.duration() < rhs.duration()) return true;
   if (lhs.duration() > rhs.duration()) return false;
   /*
    * truck size
    */
   if (lhs.size() < rhs.size()) return true;
   return false;
 }
Member Data Documentation
elements
T std::deque< T >::elements inherited
STL member.
m_capacity
PAmount vrprouting::problem::Vehicle::m_capacity private
Definition at line 182 of file vehicle.h.
Referenced by capacity(), and is_ok().
m_id
int64_t vrprouting::Identifier::m_id private inherited
Definition at line 87 of file identifier.h.
Referenced by vrprouting::Identifier::id(), and vrprouting::Identifier::reset_id().
m_idx
size_t vrprouting::Identifier::m_idx private inherited
Definition at line 86 of file identifier.h.
Referenced by vrprouting::Identifier::idx().
m_speed
Speed vrprouting::problem::Vehicle::m_speed = 1.0 private
Definition at line 183 of file vehicle.h.
Referenced by speed().
m_user_cv
int vrprouting::problem::Vehicle::m_user_cv {0} protected
Time window violations on solution.
The user can give a solution that has capacity violations
Definition at line 179 of file vehicle.h.
Referenced by has_cv(), and vrprouting::problem::Vehicle_pickDeliver::set_initial_solution().
m_user_twv
int vrprouting::problem::Vehicle::m_user_twv {0} protected
Time window violations on solution.
The user can give a solution that has time window violations
Definition at line 173 of file vehicle.h.
Referenced by has_twv(), and vrprouting::problem::Vehicle_pickDeliver::set_initial_solution().
The documentation for this class was generated from the following files:
vehicle.h
vehicle.cpp