vrpRouting: vrprouting::vrp::Tw_node Class Reference
vrprouting::vrp::Tw_node Class Reference
Extends the Node class to create a Node with time window attributes.
#include "tw_node.h"
Public Types
enum NodeType {
kStart = 0, kPickup, kDelivery, kDump,
kLoad, kEnd
}
Public Member Functions
Tw_node ()=default
Tw_node (const Tw_node &)=default
Tw_node (size_t id, PickDeliveryOrders_t data, NodeType type)
Tw_node (size_t id, Vehicle_t data, NodeType type)
double distance (const Dnode &other) const
bool operator== (const Dnode &other) const
Protected Member Functions
bool is_valid () const
Static Protected Member Functions
static Pgr_messages & msg ()
Static Protected Attributes
static Pgr_pickDeliver * problem
The problem.
Private Attributes
double m_closes
closing time of the node
double m_demand
The demand for the Node.
int64_t m_id
size_t m_idx
double m_opens
opening time of the node
int64_t m_order
order to which it belongs
double m_service_time
NodeType m_type
The demand for the Node.
friend PD_problem
Friends
std::ostream & operator<< (std::ostream &log, const Tw_node &node)
Print the contents of a Twnode object.
Detailed Description
Extends the Node class to create a Node with time window attributes.
A Time Window node is a Node with addition attributes and methods to to support Time Windows and to model a more complex Node need in many vehicle routing problems.
Most application specific code will extend this class and define the specific values and requirements for type and streetid.
Definition at line 57 of file tw_node.h.
Member Enumeration Documentation
NodeType
enum vrprouting::vrp::Tw_node::NodeType
Enumerator
kStart
starting site
kPickup
pickup site
kDelivery
delivery site
kDump
dump site, empties truck
kLoad
load site, fills the truck
kEnd
ending site
Definition at line 59 of file tw_node.h.
                   {
          kStart = 0,
          kPickup,
          kDelivery,
          kDump,
          kLoad,
          kEnd
      } NodeType;
Constructor & Destructor Documentation
Tw_node() [1/4]
vrprouting::vrp::Tw_node::Tw_node () default
Tw_node() [2/4]
vrprouting::vrp::Tw_node::Tw_node (const Tw_node &) default
Tw_node() [3/4]
vrprouting::vrp::Tw_node::Tw_node (size_t id, PickDeliveryOrders_t data, NodeType type)
Definition at line 246 of file tw_node.cpp.
                        :
     Dnode(id, data.pick_node_id),
     m_order(data.id),
     m_opens(data.pick_open_t),
     m_closes(data.pick_close_t),
     m_service_time(data.pick_service_t),
     m_demand(data.demand),
     m_type(type)  {
         if (m_type == kDelivery) {
             reset_id(data.deliver_node_id);
             m_opens = data.deliver_open_t;
             m_closes = data.deliver_close_t;
             m_service_time = data.deliver_service_t;
             m_demand *= -1;
         }
     }
References PickDeliveryOrders_t::deliver_close_t, PickDeliveryOrders_t::deliver_node_id, PickDeliveryOrders_t::deliver_open_t, PickDeliveryOrders_t::deliver_service_t, kDelivery, m_closes, m_demand, m_opens, m_service_time, m_type, and vrprouting::Identifier::reset_id().
Tw_node() [4/4]
vrprouting::vrp::Tw_node::Tw_node (size_t id, Vehicle_t data, NodeType type)
Definition at line 266 of file tw_node.cpp.
                        :
     Dnode(id, data.start_node_id),
     m_opens(data.start_open_t),
     m_closes(data.start_close_t),
     m_service_time(data.start_service_t),
     m_demand(0),
     m_type(type) {
         if (m_type == kEnd) {
             reset_id(data.end_node_id);
             m_opens = data.end_open_t;
             m_closes = data.end_close_t;
             m_service_time = data.end_service_t;
         }
     }
References Vehicle_t::end_close_t, Vehicle_t::end_node_id, Vehicle_t::end_open_t, Vehicle_t::end_service_t, kEnd, m_closes, m_opens, m_service_time, m_type, and vrprouting::Identifier::reset_id().
Member Function Documentation
arrival_j_closes_i()
double vrprouting::vrp::Tw_node::arrival_j_closes_i (const Tw_node & I, double speed) const
The actual arrival time at this node, given that: this node is visited directly after other node and that the actual arrival time at other node was closes(other)
Definition at line 68 of file tw_node.cpp.
{
     if (m_type == kStart) return  (std::numeric_limits<double>::max)();
     return I.closes() + I.service_time() + I.travel_time_to(*this, speed);
 }
References closes(), kStart, m_type, service_time(), and travel_time_to().
Referenced by is_partially_compatible_IJ(), and is_tight_compatible_IJ().
arrival_j_opens_i()
double vrprouting::vrp::Tw_node::arrival_j_opens_i (const Tw_node & I, double speed) const
The actual arrival time at This node, given that: this node is visited directly after other node and that the actual arrival time at other node was opens(other)
Definition at line 62 of file tw_node.cpp.
{
     if (m_type == kStart) return (std::numeric_limits<double>::max)();
     return I.opens() + I.service_time() + I.travel_time_to(*this, speed);
 }
References kStart, m_type, opens(), service_time(), and travel_time_to().
Referenced by is_compatible_IJ(), is_partially_compatible_IJ(), is_partially_waitTime_compatible_IJ(), is_tight_compatible_IJ(), and is_waitTime_compatible_IJ().
closes()
double vrprouting::vrp::Tw_node::closes () const inline
Returns the closing time.
Definition at line 79 of file tw_node.h.
 {return m_closes;}
References m_closes.
Referenced by vrprouting::vrp::Fleet::add_vehicle(), arrival_j_closes_i(), vrprouting::vrp::Vehicle::deltaTime(), is_delivery(), is_dump(), is_end(), is_load(), vrprouting::vrp::Vehicle::is_ok(), is_pickup(), is_start(), and vrprouting::vrp::Vehicle::Vehicle().
demand() [1/2]
double vrprouting::vrp::Tw_node::demand () const inline
Returns the demand associated with this node.
Definition at line 82 of file tw_node.h.
 {return m_demand;}
References m_demand.
Referenced by vrprouting::vrp::Vehicle_node::evaluate(), is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), and is_start().
demand() [2/2]
void vrprouting::vrp::Tw_node::demand (double value) inline
Definition at line 83 of file tw_node.h.
 {m_demand = value;}
References m_demand.
distance()
double vrprouting::vrp::Dnode::distance (const Dnode & other) const inherited
Definition at line 43 of file dnode.cpp.
{
     return problem->m_cost_matrix.distance(
             problem->m_cost_matrix.get_index(id()),
             problem->m_cost_matrix.get_index(other.id()));
 }
References vrprouting::Matrix::distance(), vrprouting::Matrix::get_index(), vrprouting::Identifier::id(), vrprouting::vrp::Pgr_pickDeliver::m_cost_matrix, and vrprouting::vrp::Dnode::problem.
Referenced by travel_time_to().
id()
int64_t vrprouting::Identifier::id () const inherited
get the original id
Definition at line 42 of file identifier.cpp.
                      {
     return m_id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::vrp::Dnode::distance(), vrprouting::vrp::Vehicle::get_postgres_result(), vrprouting::vrp::Vehicle::is_phony(), vrprouting::vrp::operator<<(), vrprouting::operator<<(), vrprouting::vrp::Node::operator==(), vrprouting::vrp::Base_node::operator==(), vrprouting::vrp::Dnode::operator==(), operator==(), vrprouting::vrp::Node::print(), vrprouting::vrp::Vehicle::tau(), and vrprouting::vrp::Vehicle::Vehicle().
idx()
size_t vrprouting::Identifier::idx () const inherited
get the internal index
Definition at line 37 of file identifier.cpp.
                       {
     return m_idx;
 }
References vrprouting::Identifier::m_idx.
Referenced by vrprouting::vrp::Vehicle_pickDeliver::erase(), vrprouting::vrp::Vehicle::erase(), vrprouting::vrp::Fleet::get_truck(), vrprouting::vrp::Vehicle_pickDeliver::has_order(), vrprouting::vrp::Vehicle_pickDeliver::insert(), vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::operator<<(), vrprouting::operator<<(), vrprouting::vrp::Node::operator==(), vrprouting::vrp::Base_node::operator==(), vrprouting::vrp::Dnode::operator==(), operator==(), vrprouting::vrp::Node::print(), vrprouting::vrp::Vehicle_pickDeliver::push_back(), vrprouting::vrp::Vehicle_pickDeliver::push_front(), vrprouting::vrp::Vehicle_pickDeliver::semiLIFO(), vrprouting::vrp::Order::set_compatibles(), vrprouting::vrp::Vehicle::tau(), travel_time_to(), and vrprouting::vrp::Vehicle::Vehicle().
is_compatible_IJ()
bool vrprouting::vrp::Tw_node::is_compatible_IJ (const Tw_node & I, double speed) const
Definition at line 77 of file tw_node.cpp.
{
     /*
      * I /->  kStart
      */
     if (m_type == kStart) return false;
     /*
      * kEnd /-> (*this)
      */
     if (I.m_type == kEnd) return false;
     return !is_late_arrival(arrival_j_opens_i(I, speed));
 }
References arrival_j_opens_i(), is_late_arrival(), kEnd, kStart, and m_type.
Referenced by vrprouting::vrp::Vehicle::getPosHighLimit(), is_partially_compatible_IJ(), is_partially_waitTime_compatible_IJ(), is_tight_compatible_IJ(), vrprouting::vrp::Order::is_valid(), is_waitTime_compatible_IJ(), and vrprouting::vrp::Order::isCompatibleIJ().
is_delivery()
bool vrprouting::vrp::Tw_node::is_delivery () const
is_delivery
To be a delivery node:
type is kDelivery
demand < 0
Definition at line 154 of file tw_node.cpp.
{
     return m_type == kDelivery
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() < 0);
 }
References closes(), demand(), kDelivery, m_type, opens(), and service_time().
Referenced by vrprouting::vrp::Order::is_valid(), and is_valid().
is_dump()
bool vrprouting::vrp::Tw_node::is_dump () const
is_dump
To be a dump node:
type is kDump
demand <= 0
Definition at line 163 of file tw_node.cpp.
{
     return m_type == kDump
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() <= 0);
 }
References closes(), demand(), kDump, m_type, opens(), and service_time().
Referenced by vrprouting::vrp::Vehicle_node::evaluate(), and is_valid().
is_early_arrival()
bool vrprouting::vrp::Tw_node::is_early_arrival (double arrival_time) const inline
True when arrivalTime is before it opens.
Definition at line 187 of file tw_node.h.
{
          return arrival_time < m_opens;
      }
References m_opens.
Referenced by vrprouting::vrp::Vehicle::deltaTime(), vrprouting::vrp::Vehicle_node::evaluate(), is_on_time(), is_partially_compatible_IJ(), is_partially_waitTime_compatible_IJ(), is_tight_compatible_IJ(), and is_waitTime_compatible_IJ().
is_end()
bool vrprouting::vrp::Tw_node::is_end () const
is_end
To be a End node:
type is kEnd
demand == 0
Definition at line 181 of file tw_node.cpp.
                       {
     return m_type == kEnd
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() == 0);
 }
References closes(), demand(), kEnd, m_type, opens(), and service_time().
Referenced by vrprouting::vrp::Fleet::add_vehicle(), vrprouting::vrp::Vehicle_node::has_cv(), and is_valid().
is_late_arrival()
bool vrprouting::vrp::Tw_node::is_late_arrival (double arrival_time) const inline
True when arrivalTime is after it closes.
Definition at line 192 of file tw_node.h.
{
          return arrival_time > m_closes;
      }
References m_closes.
Referenced by vrprouting::vrp::Vehicle_node::deltaGeneratesTWV(), vrprouting::vrp::Vehicle_node::has_twv(), is_compatible_IJ(), is_on_time(), is_partially_compatible_IJ(), and is_tight_compatible_IJ().
is_load()
bool vrprouting::vrp::Tw_node::is_load () const
is_Load
To be a Load node:
type is kLoad
demand >= 0
Definition at line 172 of file tw_node.cpp.
{
     return m_type == kLoad
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() >= 0);
 }
References closes(), demand(), kLoad, m_type, opens(), and service_time().
Referenced by is_valid().
is_on_time()
bool vrprouting::vrp::Tw_node::is_on_time (double arrival_time) const inline
True when arrivalTime in the time window.
Definition at line 196 of file tw_node.h.
{
          return !is_early_arrival(arrival_time)
              && !is_late_arrival(arrival_time);
      }
References is_early_arrival(), and is_late_arrival().
is_partially_compatible_IJ()
bool vrprouting::vrp::Tw_node::is_partially_compatible_IJ (const Tw_node & I, double speed) const
Definition at line 91 of file tw_node.cpp.
{
     return
         is_compatible_IJ(I, speed)
         && !is_early_arrival(arrival_j_opens_i(I, speed))
         && is_late_arrival(arrival_j_closes_i(I, speed));
 }
References arrival_j_closes_i(), arrival_j_opens_i(), is_compatible_IJ(), is_early_arrival(), and is_late_arrival().
is_partially_waitTime_compatible_IJ()
bool vrprouting::vrp::Tw_node::is_partially_waitTime_compatible_IJ (const Tw_node & I, double speed) const
Definition at line 107 of file tw_node.cpp.
{
     return
         is_compatible_IJ(I, speed)
         && is_early_arrival(arrival_j_opens_i(I, speed));
 }
References arrival_j_opens_i(), is_compatible_IJ(), and is_early_arrival().
is_pickup()
bool vrprouting::vrp::Tw_node::is_pickup () const
is_pickup
To be a pickup node:
type is kPickup
demand > 0
Definition at line 145 of file tw_node.cpp.
{
     return m_type == kPickup
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() > 0);
 }
References closes(), demand(), kPickup, m_type, opens(), and service_time().
Referenced by vrprouting::vrp::Order::is_valid(), and is_valid().
is_start()
bool vrprouting::vrp::Tw_node::is_start () const
is_start
To be a start node:
type is kStart
demand == 0
Definition at line 136 of file tw_node.cpp.
{
     return
         m_type == kStart
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() == 0);
 }
References closes(), demand(), kStart, m_type, opens(), and service_time().
Referenced by vrprouting::vrp::Fleet::add_vehicle(), vrprouting::vrp::Vehicle_node::evaluate(), vrprouting::vrp::Vehicle_node::has_cv(), and is_valid().
is_tight_compatible_IJ()
bool vrprouting::vrp::Tw_node::is_tight_compatible_IJ (const Tw_node & I, double speed) const
Definition at line 99 of file tw_node.cpp.
{
     return
         is_compatible_IJ(I, speed)
         && !is_early_arrival(arrival_j_opens_i(I, speed))
         && !is_late_arrival(arrival_j_closes_i(I, speed));
 }
References arrival_j_closes_i(), arrival_j_opens_i(), is_compatible_IJ(), is_early_arrival(), and is_late_arrival().
is_valid()
bool vrprouting::vrp::Tw_node::is_valid () const protected
Definition at line 211 of file tw_node.cpp.
{
     switch (type()) {
         case kStart:
             return is_start();
             break;
         case kEnd:
             return is_end();
             break;
         case kDump:
             return is_dump();
             break;
         case kDelivery:
             return is_delivery();
             break;
         case kPickup:
             return is_pickup();
             break;
         case kLoad:
             return is_load();
             break;
         default:
             return false;
             break;
     }
     return false;
 }
References is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), is_start(), kDelivery, kDump, kEnd, kLoad, kPickup, kStart, and type().
is_waitTime_compatible_IJ()
bool vrprouting::vrp::Tw_node::is_waitTime_compatible_IJ (const Tw_node & I, double speed) const
Definition at line 116 of file tw_node.cpp.
{
     return
         is_compatible_IJ(I, speed)
         && is_early_arrival(arrival_j_opens_i(I, speed));
 }
References arrival_j_opens_i(), is_compatible_IJ(), and is_early_arrival().
msg()
Pgr_messages & vrprouting::vrp::Dnode::msg () static protected inherited
Definition at line 63 of file dnode.cpp.
            {
     return problem->msg;
 }
References vrprouting::vrp::Pgr_pickDeliver::msg, and vrprouting::vrp::Dnode::problem.
opens()
double vrprouting::vrp::Tw_node::opens () const inline
Returns the opening time.
Definition at line 76 of file tw_node.h.
 {return m_opens;}
References m_opens.
Referenced by vrprouting::vrp::Fleet::add_vehicle(), arrival_j_opens_i(), vrprouting::vrp::Vehicle_node::evaluate(), is_delivery(), is_dump(), is_end(), is_load(), vrprouting::vrp::Vehicle::is_ok(), is_pickup(), is_start(), and vrprouting::vrp::Vehicle::Vehicle().
operator==() [1/2]
bool vrprouting::vrp::Dnode::operator== (const Dnode & other) const inherited
Definition at line 55 of file dnode.cpp.
{
     if (&rhs == this) return true;
     return
         (idx() == rhs.idx())
          && (id() == rhs.id());
 }
References vrprouting::Identifier::id(), and vrprouting::Identifier::idx().
operator==() [2/2]
bool vrprouting::vrp::Tw_node::operator== (const Tw_node & rhs) const
Definition at line 190 of file tw_node.cpp.
{
     if (&other == this) return true;
     return m_order == other.m_order
         && m_opens == other.m_opens
         && m_closes == other.m_closes
         && m_service_time == other.m_service_time
         && m_demand == other.m_demand
         && m_type == other.m_type
         && id() == other.id()
         && idx() == other.idx();
 #if 0
     auto lhs = static_cast<const Node&>(
             *problem->m_base_nodes[idx()].get());
     auto rhs = static_cast<const Node&>(
             *problem->m_base_nodes[other.idx()].get());
     return lhs == rhs;
 #endif
 }
References vrprouting::Identifier::id(), vrprouting::Identifier::idx(), m_closes, m_demand, m_opens, m_order, m_service_time, m_type, and vrprouting::vrp::Dnode::problem.
order()
int64_t vrprouting::vrp::Tw_node::order () const inline
Returns the opening time.
Definition at line 73 of file tw_node.h.
 {return m_order;}
References m_order.
reset_id()
void vrprouting::Identifier::reset_id (int64_t _id) inherited
change the original id
Definition at line 47 of file identifier.cpp.
{
     m_id = _id;
 }
References vrprouting::Identifier::m_id.
Referenced by Tw_node().
service_time()
double vrprouting::vrp::Tw_node::service_time () const inline
Returns the service time for this node.
Definition at line 86 of file tw_node.h.
 {return m_service_time;}
References m_service_time.
Referenced by vrprouting::vrp::Vehicle_node::arrival_i_arrives_j(), arrival_j_closes_i(), arrival_j_opens_i(), vrprouting::vrp::Vehicle::deltaTime(), vrprouting::vrp::Vehicle_node::evaluate(), is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), is_start(), and vrprouting::vrp::operator<<().
travel_time_to()
double vrprouting::vrp::Tw_node::travel_time_to (const Tw_node & other, double speed) const
time = distance / speed.
Definition at line 40 of file tw_node.cpp.
{
     pgassert(speed != 0);
     return distance(to) / speed;
 #if 0
     auto from =  problem->m_base_nodes[idx()].get();
     auto destination = problem->m_base_nodes[to.idx()].get();
     pgassert(speed != 0);
     return from->distance(destination) / speed;
 #endif
 }
References vrprouting::vrp::Dnode::distance(), vrprouting::Identifier::idx(), pgassert, and vrprouting::vrp::Dnode::problem.
Referenced by vrprouting::vrp::Vehicle_node::arrival_i_arrives_j(), arrival_j_closes_i(), arrival_j_opens_i(), vrprouting::vrp::Vehicle::deltaTime(), vrprouting::vrp::Vehicle_node::evaluate(), and vrprouting::vrp::operator<<().
type()
NodeType vrprouting::vrp::Tw_node::type () const inline
Returns the type of this node.
Definition at line 89 of file tw_node.h.
 {return m_type;}
References m_type.
Referenced by is_valid(), and type_str().
type_str()
std::string vrprouting::vrp::Tw_node::type_str () const
Definition at line 123 of file tw_node.cpp.
{
     switch (type()) {
         case kStart: return "START"; break;
         case kEnd: return "END"; break;
         case kDump: return "DUMP"; break;
         case kLoad: return "LOAD"; break;
         case kPickup: return "PICKUP"; break;
         case kDelivery: return "DELIVERY"; break;
         default: return "UNKNOWN";
     }
 }
References kDelivery, kDump, kEnd, kLoad, kPickup, kStart, and type().
Referenced by vrprouting::vrp::operator<<().
window_length()
double vrprouting::vrp::Tw_node::window_length () const inline
Returns the length of time between the opening and closing.
Definition at line 92 of file tw_node.h.
 {return m_closes - m_opens;}
References m_closes, and m_opens.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Tw_node & node) friend
Print the contents of a Twnode object.
Definition at line 286 of file tw_node.cpp.
{
     log << n.id()
         << "[opens = " << n.m_opens
         << "\tcloses = " << n.m_closes
         << "\tservice = " << n.m_service_time
         << "\tdemand = " << n.m_demand
         << "\ttype = " << n.type_str()
         << "]"
         << "\n";
     return log;
 }
Member Data Documentation
m_closes
double vrprouting::vrp::Tw_node::m_closes private
closing time of the node
Definition at line 275 of file tw_node.h.
Referenced by closes(), is_late_arrival(), vrprouting::vrp::operator<<(), operator==(), Tw_node(), and window_length().
m_demand
double vrprouting::vrp::Tw_node::m_demand private
The demand for the Node.
Definition at line 277 of file tw_node.h.
Referenced by demand(), vrprouting::vrp::operator<<(), operator==(), and Tw_node().
m_id
int64_t vrprouting::Identifier::m_id private inherited
Definition at line 87 of file identifier.h.
Referenced by vrprouting::Identifier::id(), and vrprouting::Identifier::reset_id().
m_idx
size_t vrprouting::Identifier::m_idx private inherited
Definition at line 86 of file identifier.h.
Referenced by vrprouting::Identifier::idx().
m_opens
double vrprouting::vrp::Tw_node::m_opens private
opening time of the node
Definition at line 274 of file tw_node.h.
Referenced by is_early_arrival(), opens(), vrprouting::vrp::operator<<(), operator==(), Tw_node(), and window_length().
m_order
int64_t vrprouting::vrp::Tw_node::m_order private
order to which it belongs
Definition at line 273 of file tw_node.h.
Referenced by operator==(), and order().
m_service_time
double vrprouting::vrp::Tw_node::m_service_time private
Definition at line 276 of file tw_node.h.
Referenced by vrprouting::vrp::operator<<(), operator==(), service_time(), and Tw_node().
m_type
NodeType vrprouting::vrp::Tw_node::m_type private
The demand for the Node.
Definition at line 278 of file tw_node.h.
Referenced by arrival_j_closes_i(), arrival_j_opens_i(), is_compatible_IJ(), is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), is_start(), operator==(), Tw_node(), and type().
PD_problem
friend vrprouting::vrp::Dnode::PD_problem private inherited
Definition at line 49 of file dnode.h.
problem
Pgr_pickDeliver * vrprouting::vrp::Dnode::problem static protected inherited
The problem.
Definition at line 71 of file dnode.h.
Referenced by vrprouting::vrp::Dnode::distance(), vrprouting::vrp::Dnode::msg(), operator==(), vrprouting::vrp::PD_problem::PD_problem(), and travel_time_to().
The documentation for this class was generated from the following files:
tw_node.h
tw_node.cpp