vrpRouting: vrprouting::vrp::Solution Class Reference
vrprouting::vrp::Solution Class Reference
#include "solution.h"
Public Member Functions
Solution ()
Solution (const Solution &sol)
Vehicle::Cost cost () const
std::string cost_str () const
int cvTot () const
double duration () const
size_t fleet_size () const
Initials_code get_kind () const
std::vector< General_vehicle_orders_t > get_postgres_result () const
bool is_feasable () const
bool operator< (const Solution &s_rhs) const
Solution & operator= (const Solution &sol)
void sort_by_id ()
std::string tau (const std::string &title="Tau") const
double total_service_time () const
double total_travel_time () const
int twvTot () const
double wait_time () const
Static Public Member Functions
static Pgr_messages & msg ()
The problem's message.
Protected Attributes
double EPSILON
std::deque< Vehicle_pickDeliver > fleet
Fleet trucks
Static Private Attributes
static Pgr_pickDeliver * problem
this solution belongs to this problem
Friends
std::ostream & operator<< (std::ostream &log, const Solution &solution)
class Optimize
class PD_problem
Detailed Description
Definition at line 44 of file solution.h.
Constructor & Destructor Documentation
Solution() [1/2]
vrprouting::vrp::Solution::Solution ()
Definition at line 249 of file solution.cpp.
                    :
     EPSILON(0.0001),
     trucks(problem->trucks()) {
     ENTERING(msg());
     for (const auto &t : trucks) {
         msg().log << t.tau() << "\n";
     }
     EXITING(msg());
 }
References ENTERING, EXITING, vrprouting::Pgr_messages::log, msg(), and trucks.
Solution() [2/2]
vrprouting::vrp::Solution::Solution (const Solution & sol) inline
Definition at line 71 of file solution.h.
                                    :
          EPSILON(0.0001),
          fleet(sol.fleet),
          trucks(sol.trucks)
     {};
Member Function Documentation
cost()
Vehicle::Cost vrprouting::vrp::Solution::cost () const
Definition at line 130 of file solution.cpp.
                      {
     double total_duration(0);
     double total_wait_time(0);
     int total_twv(0);
     int total_cv(0);
     for (const auto &v : fleet) {
         total_duration += v.duration();
         total_wait_time += v.total_wait_time();
         total_twv += v.twvTot();
         total_cv += v.cvTot();
     }
     return std::make_tuple(
             total_twv, total_cv, fleet.size(),
             total_wait_time, total_duration);
 }
References fleet.
Referenced by cost_str(), and operator<().
cost_str()
std::string vrprouting::vrp::Solution::cost_str () const
Definition at line 149 of file solution.cpp.
{
     Vehicle::Cost s_cost(cost());
     std::ostringstream log;
     log << "(twv, cv, fleet, wait, duration) = ("
         << std::get<0>(s_cost) << ", "
         << std::get<1>(s_cost) << ", "
         << std::get<2>(s_cost) << ", "
         << std::get<3>(s_cost) << ", "
         << std::get<4>(s_cost) << ")";
     return log.str();
 }
References cost().
Referenced by vrprouting::vrp::Optimize::save_if_best(), and tau().
cvTot()
int vrprouting::vrp::Solution::cvTot () const
Definition at line 121 of file solution.cpp.
                       {
     int total(0);
     for (const auto &v : fleet) {
         total += v.cvTot();
     }
     return total;
 }
References fleet.
duration()
double vrprouting::vrp::Solution::duration () const
Definition at line 76 of file solution.cpp.
{
     double total(0);
     for (const auto &v : fleet) {
         total += v.duration();
     }
     return total;
 }
References fleet.
Referenced by vrprouting::vrp::Optimize::move_reduce_cost(), vrprouting::vrp::Optimize::save_if_best(), and vrprouting::vrp::Optimize::swap_worse().
fleet_size()
size_t vrprouting::vrp::Solution::fleet_size () const inline
Definition at line 103 of file solution.h.
 {return fleet.size();}
References fleet.
get_kind()
Initials_code vrprouting::vrp::Solution::get_kind () const
Definition at line 245 of file solution.cpp.
{
     return problem->get_kind();
 }
References vrprouting::vrp::Pgr_pickDeliver::get_kind(), and problem.
Referenced by vrprouting::vrp::Optimize::move_order(), vrprouting::vrp::Optimize::move_reduce_cost(), vrprouting::vrp::Optimize::swap_order(), and vrprouting::vrp::Optimize::swap_worse().
get_postgres_result()
std::vector< General_vehicle_orders_t > vrprouting::vrp::Solution::get_postgres_result () const
Definition at line 42 of file solution.cpp.
{
     std::vector<General_vehicle_orders_t> result;
     /* postgres numbering starts with 1 */
     int i(1);
     for (const auto& truck : fleet) {
         std::vector<General_vehicle_orders_t> data =
             truck.get_postgres_result(i);
         result.insert(result.end(), data.begin(), data.end());
         ++i;
     }
     return result;
 }
References fleet.
is_feasable()
bool vrprouting::vrp::Solution::is_feasable () const
Definition at line 67 of file solution.cpp.
{
     for (const auto& v : fleet) {
         if (v.is_feasable()) continue;
         return false;
     }
     return true;
 }
References fleet.
Referenced by vrprouting::vrp::Optimize::decrease_truck(), and vrprouting::vrp::Initial_solution::do_while_foo().
msg()
Pgr_messages & vrprouting::vrp::Solution::msg () static
The problem's message.
Returns
The problem's message for logging
Definition at line 60 of file solution.cpp.
               {
     return problem->msg;
 }
References vrprouting::vrp::Pgr_pickDeliver::msg, and problem.
Referenced by vrprouting::vrp::Initial_solution::do_while_foo(), vrprouting::vrp::Optimize::inter_swap(), vrprouting::vrp::Initial_solution::one_truck_all_orders(), vrprouting::vrp::Optimize::Optimize(), vrprouting::vrp::Optimize::save_if_best(), and Solution().
operator<()
bool vrprouting::vrp::Solution::operator< (const Solution & s_rhs) const
Definition at line 197 of file solution.cpp.
{
     Vehicle::Cost lhs(cost());
     Vehicle::Cost rhs(s_rhs.cost());
     /*
      * capacity violations
      */
     if (std::get<0>(lhs) < std::get<0>(rhs))
         return true;
     if (std::get<0>(lhs) > std::get<0>(rhs))
         return false;
     /*
      * time window violations
      */
     if (std::get<1>(lhs) < std::get<1>(rhs))
         return true;
     if (std::get<1>(lhs) > std::get<1>(rhs))
         return false;
     /*
      * fleet size
      */
     if (std::get<2>(lhs) < std::get<2>(rhs))
         return true;
     if (std::get<2>(lhs) > std::get<2>(rhs))
         return false;
     /*
      * waiting time
      */
     if (std::get<3>(lhs) < std::get<3>(rhs))
         return true;
     if (std::get<3>(lhs) > std::get<3>(rhs))
         return false;
     /*
      * duration
      */
     if (std::get<4>(lhs) < std::get<4>(rhs))
         return true;
     if (std::get<4>(lhs) > std::get<4>(rhs))
         return false;
     return false;
 }
References cost().
operator=()
Solution& vrprouting::vrp::Solution::operator= (const Solution & sol) inline
Definition at line 78 of file solution.h.
{
          EPSILON = 0.0001,
          fleet = sol.fleet;
          trucks = sol.trucks;
          return *this;
      };
References EPSILON, fleet, and trucks.
sort_by_id()
void vrprouting::vrp::Solution::sort_by_id ()
Definition at line 176 of file solution.cpp.
                      {
     std::sort(fleet.begin(), fleet.end(), []
             (const Vehicle_pickDeliver &lhs, const Vehicle_pickDeliver &rhs)
             -> bool {
             return lhs.idx() < rhs.idx();
             });
 }
References fleet.
tau()
std::string vrprouting::vrp::Solution::tau (const std::string & title = "Tau") const
Definition at line 164 of file solution.cpp.
{
     std::ostringstream log;
     log << "\n" << title << ": " << std::endl;
     for (const auto &v : fleet) {
         log << "\n" << v.tau();
     }
     log << "\n" << cost_str() << "\n";
     return log.str();
 }
References cost_str(), and fleet.
Referenced by vrprouting::vrp::Optimize::inter_swap(), vrprouting::vrp::operator<<(), vrprouting::vrp::Optimize::Optimize(), vrprouting::vrp::Pgr_pickDeliver::optimize(), and vrprouting::vrp::Optimize::save_if_best().
total_service_time()
double vrprouting::vrp::Solution::total_service_time () const
Definition at line 112 of file solution.cpp.
{
     double total(0);
     for (const auto &v : fleet) {
         total += v.total_service_time();
     }
     return total;
 }
References fleet.
total_travel_time()
double vrprouting::vrp::Solution::total_travel_time () const
Definition at line 103 of file solution.cpp.
{
     double total(0);
     for (const auto &v : fleet) {
         total += v.total_travel_time();
     }
     return total;
 }
References fleet.
twvTot()
int vrprouting::vrp::Solution::twvTot () const
Definition at line 85 of file solution.cpp.
{
     int total(0);
     for (const auto &v : fleet) {
         total += v.twvTot();
     }
     return total;
 }
References fleet.
wait_time()
double vrprouting::vrp::Solution::wait_time () const
Definition at line 94 of file solution.cpp.
{
     double total(0);
     for (const auto &v : fleet) {
         total += v.total_wait_time();
     }
     return total;
 }
References fleet.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Solution & solution) friend
Definition at line 185 of file solution.cpp.
{
     for (const auto &vehicle : solution.fleet) {
         log << vehicle;
     }
     log << "\n SOLUTION:\n\n "
         << solution.tau();
     return log;
 }
Optimize
friend class Optimize friend
Definition at line 45 of file solution.h.
PD_problem
friend class PD_problem friend
Definition at line 46 of file solution.h.
Member Data Documentation
EPSILON
double vrprouting::vrp::Solution::EPSILON protected
Definition at line 48 of file solution.h.
Referenced by operator=().
fleet
std::deque<Vehicle_pickDeliver> vrprouting::vrp::Solution::fleet protected
Definition at line 49 of file solution.h.
Referenced by cost(), cvTot(), vrprouting::vrp::Optimize::decrease_truck(), vrprouting::vrp::Optimize::delete_empty_truck(), vrprouting::vrp::Initial_solution::do_while_foo(), duration(), fleet_size(), get_postgres_result(), vrprouting::vrp::Optimize::inter_swap(), is_feasable(), vrprouting::vrp::Initial_solution::one_truck_all_orders(), vrprouting::vrp::operator<<(), operator=(), vrprouting::vrp::Optimize::Optimize(), vrprouting::vrp::Optimize::save_if_best(), vrprouting::vrp::Optimize::sort_by_duration(), vrprouting::vrp::Optimize::sort_by_id(), sort_by_id(), vrprouting::vrp::Optimize::sort_by_size(), vrprouting::vrp::Optimize::sort_for_move(), tau(), total_service_time(), total_travel_time(), twvTot(), and wait_time().
problem
Pgr_pickDeliver * vrprouting::vrp::Solution::problem static private
this solution belongs to this problem
Definition at line 120 of file solution.h.
Referenced by get_kind(), msg(), and vrprouting::vrp::PD_problem::PD_problem().
trucks
Fleet vrprouting::vrp::Solution::trucks protected
Definition at line 52 of file solution.h.
Referenced by vrprouting::vrp::Initial_solution::do_while_foo(), vrprouting::vrp::Initial_solution::one_truck_all_orders(), operator=(), and Solution().
The documentation for this class was generated from the following files:
solution.h
solution.cpp