vrpRouting: vrprouting::vrp::Node Class Reference
vrprouting::vrp::Node Class Reference
The Node class defines a point in 2D space with an id.
#include "node.h"
Public Member Functions
Node ()=default
Node (size_t id, int64_t original_id, double _x, double _y)
double distance (const Base_node *) const
Calculates distance between two Node.
to be or not to be
virtual bool operator== (const Base_node &rhs) const
to be or not to be
bool operator== (const Node &rhs) const
to be or not to be
virtual bool operator== (const Base_node &rhs) const
Private Member Functions
double distance (const Node &) const
void print (std::ostream &os) const
Private Attributes
int64_t m_id
size_t m_idx
Bpoint m_point
Friends
std::ostream & operator<< (std::ostream &log, const Node &node)
Detailed Description
The Node class defines a point in 2D space with an id.
A Node is a point that defines a location in 2D space. It maintains a user id and an internal nid along with its x, y location. This is the base object that things like depots, customer locations, etc. are built upon.
Definition at line 48 of file node.h.
Constructor & Destructor Documentation
Node() [1/2]
vrprouting::vrp::Node::Node () default
Node() [2/2]
vrprouting::vrp::Node::Node (size_t _idx, int64_t _id, double _x, double _y)
Parameters
[in] _idx index to a container
[in] _id original identifier
[in] _x coordinate value
[in] _y coordinate value
Definition at line 84 of file node.cpp.
     : Base_node(_idx, _id),
         m_point(_x, _y) {
     }
Member Function Documentation
distance() [1/2]
double vrprouting::vrp::Node::distance (const Base_node * n) const virtual
Calculates distance between two Node.
para[in] n bas node to be casted as Node
Implements vrprouting::vrp::Base_node.
Definition at line 74 of file node.cpp.
{
     return distance(*dynamic_cast<const Node*>(n));
 }
distance() [2/2]
double vrprouting::vrp::Node::distance (const Node & other) const private
Definition at line 64 of file node.cpp.
{
     auto dx = m_point.x() - other.m_point.x();
     auto dy = m_point.y() - other.m_point.y();
     return sqrt(dx * dx + dy * dy);
 }
References m_point.
id()
int64_t vrprouting::Identifier::id () const inherited
get the original id
Definition at line 42 of file identifier.cpp.
                      {
     return m_id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::vrp::Dnode::distance(), vrprouting::vrp::Vehicle::get_postgres_result(), vrprouting::vrp::Vehicle::is_phony(), vrprouting::vrp::operator<<(), vrprouting::operator<<(), operator==(), vrprouting::vrp::Base_node::operator==(), vrprouting::vrp::Dnode::operator==(), vrprouting::vrp::Tw_node::operator==(), print(), vrprouting::vrp::Vehicle::tau(), and vrprouting::vrp::Vehicle::Vehicle().
idx()
size_t vrprouting::Identifier::idx () const inherited
get the internal index
Definition at line 37 of file identifier.cpp.
                       {
     return m_idx;
 }
References vrprouting::Identifier::m_idx.
Referenced by vrprouting::vrp::Vehicle_pickDeliver::erase(), vrprouting::vrp::Vehicle::erase(), vrprouting::vrp::Fleet::get_truck(), vrprouting::vrp::Vehicle_pickDeliver::has_order(), vrprouting::vrp::Vehicle_pickDeliver::insert(), vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::operator<<(), vrprouting::operator<<(), operator==(), vrprouting::vrp::Base_node::operator==(), vrprouting::vrp::Dnode::operator==(), vrprouting::vrp::Tw_node::operator==(), print(), vrprouting::vrp::Vehicle_pickDeliver::push_back(), vrprouting::vrp::Vehicle_pickDeliver::push_front(), vrprouting::vrp::Vehicle_pickDeliver::semiLIFO(), vrprouting::vrp::Order::set_compatibles(), vrprouting::vrp::Vehicle::tau(), vrprouting::vrp::Tw_node::travel_time_to(), and vrprouting::vrp::Vehicle::Vehicle().
operator==() [1/2]
bool vrprouting::vrp::Base_node::operator== (const Base_node & rhs) const virtual inherited
Definition at line 43 of file base_node.cpp.
{
     if (&rhs == this) return true;
     return
         (idx() == rhs.idx())
          && (id() == rhs.id());
 }
References vrprouting::Identifier::id(), and vrprouting::Identifier::idx().
operator==() [2/2]
bool vrprouting::vrp::Node::operator== (const Node & rhs) const
Definition at line 90 of file node.cpp.
{
     if (&rhs == this) return true;
     return
         (idx() == rhs.idx())
          && (id() == rhs.id())
          && almost_equal(m_point.x(), rhs.m_point.x(), 2)
          && almost_equal(m_point.y(), rhs.m_point.y(), 2);
 }
References anonymous_namespace{node.cpp}::almost_equal(), vrprouting::Identifier::id(), vrprouting::Identifier::idx(), and m_point.
print()
void vrprouting::vrp::Node::print (std::ostream & os) const private
Definition at line 55 of file node.cpp.
{
     os << id()
 #ifndef NDEBUG
         << "(" << idx() << ")"
 #endif
        << " (x,y) = (" << m_point.x() << ", " << m_point.y() << ")";
 }
References vrprouting::Identifier::id(), vrprouting::Identifier::idx(), and m_point.
Referenced by vrprouting::vrp::operator<<().
reset_id()
void vrprouting::Identifier::reset_id (int64_t _id) inherited
change the original id
Definition at line 47 of file identifier.cpp.
{
     m_id = _id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::vrp::Tw_node::Tw_node().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Node & node) friend
Definition at line 49 of file node.cpp.
{
     node.print(log);
     return log;
 }
Member Data Documentation
m_id
int64_t vrprouting::Identifier::m_id private inherited
Definition at line 87 of file identifier.h.
Referenced by vrprouting::Identifier::id(), and vrprouting::Identifier::reset_id().
m_idx
size_t vrprouting::Identifier::m_idx private inherited
Definition at line 86 of file identifier.h.
Referenced by vrprouting::Identifier::idx().
m_point
Bpoint vrprouting::vrp::Node::m_point private
Definition at line 69 of file node.h.
Referenced by distance(), operator==(), and print().
The documentation for this class was generated from the following files:
node.h
node.cpp