vrpRouting: vrprouting::vrp::Pgr_pickDeliver Class Reference
vrprouting::vrp::Pgr_pickDeliver Class Reference
#include "pgr_pickDeliver.h"
Public Member Functions
Pgr_pickDeliver (const std::vector< PickDeliveryOrders_t > &pd_orders, const std::vector< Vehicle_t > &vehicles, const vrprouting::Matrix &cost_matrix, double factor, size_t max_cycles, int initial)
Constructor for the matrix version.
void add_node (const Vehicle_node &node)
Initials_code get_kind () const
std::vector< General_vehicle_orders_t > get_postgres_result () const
size_t max_cycles () const
bool nodesOK () const
Solution optimize (const Solution init_solution)
void solve ()
Fleet trucks () const
Public Attributes
vrprouting::Matrix m_cost_matrix
std::vector< Vehicle_node > m_nodes
Pgr_messages msg
message controller for all classes
Private Attributes
friend Dnode
friend Fleet
friend Initial_solution
int m_initial_id
used define the initial solution algorithm to be used
size_t m_max_cycles
maximum cycles in the optimization
PD_Orders m_orders
Fleet m_trucks
friend PD_Orders
friend Solution
std::vector< Solution > solutions
Detailed Description
Definition at line 60 of file pgr_pickDeliver.h.
Constructor & Destructor Documentation
Pgr_pickDeliver()
vrprouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver (const std::vector< PickDeliveryOrders_t > & pd_orders, const std::vector< Vehicle_t > & vehicles, const vrprouting::Matrix & cost_matrix, double factor, size_t p_max_cycles, int initial)
Constructor for the matrix version.
Definition at line 170 of file pgr_pickDeliver.cpp.
                      :
     PD_problem(this),
     m_initial_id(initial),
     m_max_cycles(p_max_cycles),
 #if 0
     m_node_id(0),
 #endif
     m_nodes(),
 #if 0
     m_base_nodes(),
 #endif
     m_cost_matrix(cost_matrix),
     m_orders(pd_orders),
     m_trucks(vehicles, factor) {
         pgassert(!pd_orders.empty());
         pgassert(!vehicles.empty());
         pgassert(!m_cost_matrix.empty());
         if (!(m_initial_id > 0 && m_initial_id < OneDepot)) {
             msg.log << "\n m_initial_id " << m_initial_id;
         }
         pgassertwm(m_initial_id > 0 && m_initial_id <= OneDepot, msg.get_log().c_str());
         pgassert(nodesOK());
         if (!msg.get_error().empty()) {
             return;
         }
 #if 0
         pgassert(m_trucks.msg().get_error().empty());
         pgassert(msg().get_error().empty());
 #endif
         msg.log << "\n Checking fleet ...";
         if (!m_trucks.is_fleet_ok()) {
             pgassert(msg.get_error().empty());
 #if 0
             pgassert(!m_trucks.msg.get_error().empty());
             msg.error << m_trucks.msg.get_error();
 #endif
             return;
         }
         msg.log << "fleet OK \n";
 #if 0
         for (const auto t : m_trucks) {
             msg.log << t << "\n";
         }
         for (const auto &o : m_orders) {
             msg.log << o << "\n";
         }
 #endif
         /*
          * check the (S, P, D, E) order on all vehicles
          * stop when a feasible truck is found
          */
         msg.log << "\n Checking orders";
         for (const auto &o : m_orders) {
             if (!m_trucks.is_order_ok(o)) {
                 msg.error << "Order not feasible on any truck was found";
                 msg.log << "The order "
                     << o.id()
                     << " is not feasible on any truck";
                 msg.log << "\n" << o;
 #if 0
                 double old_speed(0);
                 for (auto t : m_trucks) {
                     if (old_speed == t.speed()) continue;
                     old_speed = t.speed();
                     msg.log << "****** With speed: " << t.speed() << "\n";
                     msg.log << t.start_site() << "\n";
                     msg.log << o.pickup() << "\n";
                     msg.log << "travel time to "
                         << t.start_site().travel_time_to(
                                 o.pickup(), t.speed()) << "\n";
                     msg.log << o.delivery() << "\n";
                     msg.log << t.end_site() << "\n";
                     msg.log << "travel time to "
                         << t.start_site().travel_time_to(
                                 o.delivery(), t.speed())
                         << "\n";
                     t.push_back(o);
                 }
 #endif
                 return;
             }
         }
         msg.log << "orders OK \n";
         m_trucks.set_compatibles(m_orders);
 #if 0
         msg.error << "foo";
         for (const auto t : m_trucks) {
             msg.log << t << "\n";
         }
 #endif
     }  //  constructor
References vrprouting::Matrix::empty(), vrprouting::Pgr_messages::error, vrprouting::Pgr_messages::get_error(), vrprouting::Pgr_messages::get_log(), vrprouting::vrp::Fleet::is_fleet_ok(), vrprouting::vrp::Fleet::is_order_ok(), vrprouting::Pgr_messages::log, m_cost_matrix, m_initial_id, m_orders, m_trucks, vrprouting::vrp::Fleet::msg(), msg, nodesOK(), vrprouting::vrp::OneDepot, pgassert, pgassertwm, and vrprouting::vrp::Fleet::set_compatibles().
Member Function Documentation
add_node()
void vrprouting::vrp::Pgr_pickDeliver::add_node (const Vehicle_node & node)
Definition at line 163 of file pgr_pickDeliver.cpp.
{
     m_nodes.push_back(node);
 }
References m_nodes.
Referenced by vrprouting::vrp::PD_Orders::add_order(), vrprouting::vrp::Fleet::add_vehicle(), vrprouting::vrp::Fleet::build_fleet(), and vrprouting::vrp::PD_Orders::build_orders().
get_kind()
Initials_code vrprouting::vrp::Pgr_pickDeliver::get_kind () const inline
Definition at line 106 of file pgr_pickDeliver.h.
{
         return (Initials_code) m_initial_id;
     }
References m_initial_id.
Referenced by vrprouting::vrp::Solution::get_kind().
get_postgres_result()
std::vector< General_vehicle_orders_t > vrprouting::vrp::Pgr_pickDeliver::get_postgres_result () const
Definition at line 129 of file pgr_pickDeliver.cpp.
{
     auto result = solutions.back().get_postgres_result();
     General_vehicle_orders_t aggregates = {
             /*
              * Vehicle id = -2 indicates its an aggregate row
              *
              * (twv, cv, fleet, wait, duration)
              */
             -2,  // summary row on vehicle_number
             solutions.back().twvTot(),  // on vehicle_id
             solutions.back().cvTot(),   // on vehicle_seq
             -1,  // on order_id
             -1,  // on stop_id
             -2,  // on stop_type (gets increased later by one so it gets -1)
             -1,  // not accounting total loads
             solutions.back().total_travel_time(),
             -1,  // not accounting arrival_travel_time
             solutions.back().wait_time(),
             solutions.back().total_service_time(),
             solutions.back().duration(),
             };
     result.push_back(aggregates);
 #ifndef NDEBUG
     for (const auto &sol : solutions) {
         msg.log << sol.tau();
     }
 #endif
     return result;
 }
References vrprouting::Pgr_messages::log, msg, and solutions.
Referenced by do_pgr_pickDeliver(), and do_pgr_pickDeliverEuclidean().
max_cycles()
size_t vrprouting::vrp::Pgr_pickDeliver::max_cycles () const inline
Definition at line 92 of file pgr_pickDeliver.h.
 {return m_max_cycles;}
References m_max_cycles.
nodesOK()
bool vrprouting::vrp::Pgr_pickDeliver::nodesOK () const
Definition at line 51 of file pgr_pickDeliver.cpp.
{
     ENTERING(msg);
     return !(m_nodes.empty());
 #if 0
     if (m_nodes.empty() && m_base_nodes.empty()) return true;
     pgassertwm(m_nodes.size() == m_base_nodes.size(), msg.get_log().c_str());
     for (size_t i = 0; i < m_nodes.size() ; ++i) {
         pgassertwm(m_nodes[i].id() ==  m_base_nodes[i]->id(),
                 msg.get_log().c_str());
         pgassertwm(m_nodes[i].idx() ==  m_base_nodes[i]->idx(),
                 msg.get_log().c_str());
     }
     EXITING();
     return true;
 #endif
 }
References ENTERING, EXITING, vrprouting::Pgr_messages::get_log(), m_nodes, msg, and pgassertwm.
Referenced by Pgr_pickDeliver().
optimize()
Solution vrprouting::vrp::Pgr_pickDeliver::optimize (const Solution init_solution)
Definition at line 70 of file pgr_pickDeliver.cpp.
{
     pgassert(false);
     /*
      * Optimize a solution
      */
 #if 1
     msg.log << "max_cycles: " << m_max_cycles << "\n";
     Optimize opt_solution(solution, m_max_cycles);
 #else
     Optimize opt_solution(solution, 1);
 #endif
     msg.log << opt_solution.best_solution.tau("optimized");
     return opt_solution.best_solution;
 }
References vrprouting::vrp::Optimize::best_solution, vrprouting::Pgr_messages::log, m_max_cycles, msg, pgassert, and vrprouting::vrp::Solution::tau().
solve()
void vrprouting::vrp::Pgr_pickDeliver::solve ()
Definition at line 86 of file pgr_pickDeliver.cpp.
{
     auto initial_sols = solutions;
     if (m_initial_id == 0) {
         msg.log << "trying all \n";
         for (int i = 1; i < 7; ++i) {
             initial_sols.push_back(Initial_solution((Initials_code)i, m_orders.size()));
             msg.log << "solution " << i << "\n" << initial_sols.back().tau();
             // TODO(vicky) calculate the time it takes
             msg.log << "Initial solution " << i
                 << " duration: " << initial_sols.back().duration();
         }
     } else {
         msg.log << "only trying " << m_initial_id << "\n";
         initial_sols.push_back(Initial_solution((Initials_code)m_initial_id, m_orders.size()));
         // TODO(vicky) calculate the time it takes
         msg.log << "Initial solution " << m_initial_id
             << " duration: " << initial_sols[0].duration();
     }
     /*
      * Sorting solutions: the best is at the back
      */
     pgassert(!initial_sols.empty());
     std::sort(initial_sols.begin(), initial_sols.end(), []
             (const Solution &lhs, const Solution &rhs) -> bool {
             return rhs < lhs;
             });
 #if 1
     solutions.push_back(Optimize(initial_sols.back(), m_max_cycles));
 #else
     solutions.push_back(initial_sols.back());
 #endif
     pgassert(!solutions.empty());
     msg.log << "best solution duration = " << solutions.back().duration();
 }
References Initial_solution, vrprouting::Pgr_messages::log, m_initial_id, m_max_cycles, m_orders, msg, pgassert, vrprouting::vrp::PD_Orders::size(), and solutions.
Referenced by do_pgr_pickDeliver(), and do_pgr_pickDeliverEuclidean().
trucks()
Fleet vrprouting::vrp::Pgr_pickDeliver::trucks () const inline
Definition at line 114 of file pgr_pickDeliver.h.
 {return m_trucks;}
References m_trucks.
Member Data Documentation
Dnode
friend vrprouting::vrp::Pgr_pickDeliver::Dnode private
Definition at line 62 of file pgr_pickDeliver.h.
Fleet
friend vrprouting::vrp::Pgr_pickDeliver::Fleet private
Definition at line 61 of file pgr_pickDeliver.h.
Initial_solution
friend vrprouting::vrp::Pgr_pickDeliver::Initial_solution private
Definition at line 65 of file pgr_pickDeliver.h.
Referenced by solve().
m_cost_matrix
vrprouting::Matrix vrprouting::vrp::Pgr_pickDeliver::m_cost_matrix
Definition at line 139 of file pgr_pickDeliver.h.
Referenced by vrprouting::vrp::Fleet::build_fleet(), vrprouting::vrp::PD_Orders::build_orders(), vrprouting::vrp::Dnode::distance(), and Pgr_pickDeliver().
m_initial_id
int vrprouting::vrp::Pgr_pickDeliver::m_initial_id private
used define the initial solution algorithm to be used
Definition at line 122 of file pgr_pickDeliver.h.
Referenced by get_kind(), Pgr_pickDeliver(), and solve().
m_max_cycles
size_t vrprouting::vrp::Pgr_pickDeliver::m_max_cycles private
maximum cycles in the optimization
Definition at line 125 of file pgr_pickDeliver.h.
Referenced by max_cycles(), optimize(), and solve().
m_nodes
std::vector<Vehicle_node> vrprouting::vrp::Pgr_pickDeliver::m_nodes
Definition at line 135 of file pgr_pickDeliver.h.
Referenced by add_node(), vrprouting::vrp::Fleet::build_fleet(), vrprouting::vrp::PD_Orders::build_orders(), and nodesOK().
m_orders
PD_Orders vrprouting::vrp::Pgr_pickDeliver::m_orders private
Definition at line 142 of file pgr_pickDeliver.h.
Referenced by Pgr_pickDeliver(), and solve().
m_trucks
Fleet vrprouting::vrp::Pgr_pickDeliver::m_trucks private
Definition at line 143 of file pgr_pickDeliver.h.
Referenced by Pgr_pickDeliver(), and trucks().
msg
Pgr_messages vrprouting::vrp::Pgr_pickDeliver::msg
message controller for all classes
Definition at line 117 of file pgr_pickDeliver.h.
Referenced by do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), get_postgres_result(), vrprouting::vrp::Dnode::msg(), vrprouting::vrp::Fleet::msg(), vrprouting::vrp::Solution::msg(), vrprouting::vrp::Vehicle::msg(), nodesOK(), optimize(), Pgr_pickDeliver(), and solve().
PD_Orders
friend vrprouting::vrp::Pgr_pickDeliver::PD_Orders private
Definition at line 63 of file pgr_pickDeliver.h.
Solution
friend vrprouting::vrp::Pgr_pickDeliver::Solution private
Definition at line 64 of file pgr_pickDeliver.h.
solutions
std::vector<Solution> vrprouting::vrp::Pgr_pickDeliver::solutions private
Definition at line 144 of file pgr_pickDeliver.h.
Referenced by get_postgres_result(), and solve().
The documentation for this class was generated from the following files:
pgr_pickDeliver.h
pgr_pickDeliver.cpp