vrpRouting: vrprouting::problem::Order Class Reference
vrprouting::problem::Order Class Reference
#include "order.h"
Public Member Functions
Order ()=delete
Order without data is not permitted.
Order (const Order &)=default
copy constructor
Order (Idx o_idx, Id o_id, const Vehicle_node &p_pickup, const Vehicle_node &p_delivery)
initializing an order with the pick & drop information
bool is_valid (Speed speed=1.0) const
is the order valid?
bool isCompatibleIJ (const Order &I, Speed speed=1.0) const
Can order I be placed before this order?
void set_compatibles (const Order &, Speed speed=1.0)
set compatability of this orther with the other order
Accessors
const Vehicle_node & pickup () const
The pickup node identifier.
const Vehicle_node & delivery () const
The delivery node identifier.
Identifiers< size_t > subsetJ (const Identifiers< size_t > &J) const
Get a subset of the orders that can be placed after this order.
Identifiers< size_t > subsetI (const Identifiers< size_t > &I) const
Get a subset of the orders that can be placed before this order.
Protected Attributes
Identifiers< size_t > m_compatibleI
Storage for the orders that can be placed before this order.
Identifiers< size_t > m_compatibleJ
Storage for the orders that can be placed after this order.
Vehicle_node m_delivery
The delivery node identifier.
Vehicle_node m_pickup
The pick up node identifier.
Private Attributes
int64_t m_id
size_t m_idx
Friends
std::ostream & operator<< (std::ostream &, const Order &)
Print the order.
Detailed Description
Definition at line 40 of file order.h.
Constructor & Destructor Documentation
Order() [1/3]
vrprouting::problem::Order::Order () delete
Order without data is not permitted.
Order() [2/3]
vrprouting::problem::Order::Order (const Order &) default
copy constructor
Order() [3/3]
vrprouting::problem::Order::Order (Idx o_idx, Id o_id, const Vehicle_node & p_pickup, const Vehicle_node & p_delivery) inline
initializing an order with the pick & drop information
Definition at line 52 of file order.h.
                                         :
       Identifier(o_idx, o_id),
       m_pickup(p_pickup),
       m_delivery(p_delivery) {
       }
Member Function Documentation
delivery()
const Vehicle_node& vrprouting::problem::Order::delivery () const inline
The delivery node identifier.
Definition at line 68 of file order.h.
 {return m_delivery;}
References m_delivery.
Referenced by vrprouting::problem::Vehicle_pickDeliver::erase(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), is_valid(), isCompatibleIJ(), vrprouting::problem::operator<<(), vrprouting::problem::Vehicle_pickDeliver::push_back(), vrprouting::problem::Vehicle_pickDeliver::push_front(), and vrprouting::problem::Vehicle_pickDeliver::semiLIFO().
id()
int64_t vrprouting::Identifier::id () const inherited
get the original id
Definition at line 42 of file identifier.cpp.
                      {
     return m_id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::problem::Vehicle_node::get_postgres_result(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::problem::Vehicle::is_phony(), vrprouting::operator<<(), vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), vrprouting::problem::Vehicle_pickDeliver::set_initial_solution(), vrprouting::problem::Vehicle_pickDeliver::set_unmovable(), vrprouting::problem::Vehicle::tau(), and vrprouting::problem::Tw_node::travel_time_to().
idx()
size_t vrprouting::Identifier::idx () const inherited
get the internal index
Definition at line 37 of file identifier.cpp.
                       {
     return m_idx;
 }
References vrprouting::Identifier::m_idx.
Referenced by vrprouting::problem::Vehicle_pickDeliver::erase(), vrprouting::problem::Vehicle::erase(), vrprouting::problem::Vehicle_pickDeliver::has_order(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::operator<<(), vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), vrprouting::problem::Vehicle_pickDeliver::push_back(), vrprouting::problem::Vehicle_pickDeliver::push_front(), vrprouting::problem::Vehicle_pickDeliver::semiLIFO(), set_compatibles(), and vrprouting::problem::Vehicle::tau().
is_valid()
bool vrprouting::problem::Order::is_valid (Speed speed = 1.0) const
is the order valid?
Parameters
[in] speed value to do the calculation
Returns
ture when:
Validate a pickup/delivery order
The pickup is well formed
The delivery is well formed
isCompatibleIJ to go to delivery after immediately visiting pickup
Definition at line 109 of file order.cpp.
{
   return
     pickup().is_pickup()
     && delivery().is_delivery()
     /* IS P -> D */
     && delivery().is_compatible_IJ(pickup(), speed);
 }
References delivery(), vrprouting::problem::Tw_node::is_compatible_IJ(), vrprouting::problem::Tw_node::is_delivery(), vrprouting::problem::Tw_node::is_pickup(), and pickup().
Referenced by vrprouting::problem::Fleet::is_order_ok().
isCompatibleIJ()
bool vrprouting::problem::Order::isCompatibleIJ (const Order & I, Speed speed = 1.0) const
Can order I be placed before this order?
Returns
True when I -> this
Parameters
[in] I order
[in] speed value to do the calculation
Returns
true when order I can be placed before this order
Definition at line 161 of file order.cpp.
{
   /* this is true in all cases */
   auto all_cases(
       pickup().is_compatible_IJ(I.pickup(), speed)
       && delivery().is_compatible_IJ(I.pickup(), speed));
   /* case other(P) other(D) this(P) this(D) */
   auto case1(pickup().is_compatible_IJ(I.delivery(), speed)
       && delivery().is_compatible_IJ(I.delivery(), speed));
   /* case other(P) this(P) other(D) this(D) */
   auto case2(I.delivery().is_compatible_IJ(pickup(), speed)
       && delivery().is_compatible_IJ(I.delivery(), speed));
   /* case other(P) this(P) this(D) other(D) */
   auto case3(I.delivery().is_compatible_IJ(pickup(), speed)
       && I.delivery().is_compatible_IJ(delivery(), speed));
   return all_cases &&  (case1 ||  case2 ||  case3);
 }
References delivery(), vrprouting::problem::Tw_node::is_compatible_IJ(), and pickup().
Referenced by set_compatibles().
pickup()
const Vehicle_node& vrprouting::problem::Order::pickup () const inline
The pickup node identifier.
Definition at line 65 of file order.h.
 {return m_pickup;}
References m_pickup.
Referenced by vrprouting::problem::Vehicle_pickDeliver::erase(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), is_valid(), isCompatibleIJ(), vrprouting::problem::operator<<(), vrprouting::problem::Vehicle_pickDeliver::push_back(), vrprouting::problem::Vehicle_pickDeliver::push_front(), and vrprouting::problem::Vehicle_pickDeliver::semiLIFO().
reset_id()
void vrprouting::Identifier::reset_id (int64_t _id) inherited
change the original id
Definition at line 47 of file identifier.cpp.
{
     m_id = _id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::problem::Tw_node::Tw_node().
set_compatibles()
void vrprouting::problem::Order::set_compatibles (const Order & J, Speed speed = 1.0)
set compatability of this orther with the other order
Initializing the set of nodes that can be placed immediately after this node.
(this) -> J
Parameters
[in] J order after this node
[in] speed value to do the calculation
Postcondition
m_compatibleJ has order when this -> order
m_compatibleI has order when order -> this
Definition at line 130 of file order.cpp.
{
   if (J.idx() == idx()) return;
   if (J.isCompatibleIJ(*this, speed)) {
     m_compatibleJ += J.idx();
   }
   if (this->isCompatibleIJ(J, speed)) {
     m_compatibleI += J.idx();
   }
 }
References vrprouting::Identifier::idx(), isCompatibleIJ(), m_compatibleI, and m_compatibleJ.
subsetI()
Identifiers< size_t > vrprouting::problem::Order::subsetI (const Identifiers< size_t > & I) const
Get a subset of the orders that can be placed before this order.
Returns
Orders from I that are compatible with this order
Parameters
[in] I Set of orders that possibly are I -> this
Definition at line 45 of file order.cpp.
{
   return m_compatibleI * I;
 }
References m_compatibleI.
subsetJ()
Identifiers< size_t > vrprouting::problem::Order::subsetJ (const Identifiers< size_t > & J) const
Get a subset of the orders that can be placed after this order.
Returns
Orders from J that are compatible with this order
Parameters
[in] J Set of orders that possibly are this -> J
Definition at line 62 of file order.cpp.
{
   return m_compatibleJ * J;
 }
References m_compatibleJ.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Order & order) friend
Print the order.
the pickup
dropoff
Set of orders I than are I -> this
Set of orders J than are this -> I
Parameters
[in,out] log
[in] order
Returns
the ostream
Definition at line 77 of file order.cpp.
{
   log << "\n\nOrder "
     << static_cast<Identifier>(order) << ": \n"
     << "\tPickup: " << order.pickup() << "\n"
     << "\tDropoff: " << order.delivery() << "\n";
   log << "\nThere are | {I}| = "
     << order.m_compatibleI.size()
     << " -> order(" << order.idx()
     << ") -> | {J}| = " << order.m_compatibleJ.size()
     << "\n\n {";
   for (const auto o : order.m_compatibleI) {
     log << o << ", ";
   }
   log << "} -> " << order.idx() << " -> {";
   for (const auto o : order.m_compatibleJ) {
     log << o << ", ";
   }
   log << "}";
   return log;
 }
Member Data Documentation
m_compatibleI
Identifiers<size_t> vrprouting::problem::Order::m_compatibleI protected
Storage for the orders that can be placed before this order.
Definition at line 110 of file order.h.
Referenced by vrprouting::problem::operator<<(), set_compatibles(), and subsetI().
m_compatibleJ
Identifiers<size_t> vrprouting::problem::Order::m_compatibleJ protected
Storage for the orders that can be placed after this order.
Definition at line 98 of file order.h.
Referenced by vrprouting::problem::operator<<(), set_compatibles(), and subsetJ().
m_delivery
Vehicle_node vrprouting::problem::Order::m_delivery protected
The delivery node identifier.
It hold's the idx of the node
Definition at line 122 of file order.h.
Referenced by delivery().
m_id
int64_t vrprouting::Identifier::m_id private inherited
Definition at line 87 of file identifier.h.
Referenced by vrprouting::Identifier::id(), and vrprouting::Identifier::reset_id().
m_idx
size_t vrprouting::Identifier::m_idx private inherited
Definition at line 86 of file identifier.h.
Referenced by vrprouting::Identifier::idx().
m_pickup
Vehicle_node vrprouting::problem::Order::m_pickup protected
The pick up node identifier.
It hold's the idx of the node
Definition at line 116 of file order.h.
Referenced by pickup().
The documentation for this class was generated from the following files:
order.h
order.cpp