vrpRouting: vrprouting::optimizers::tabu::Move Class Reference
vrprouting::optimizers::tabu::Move Class Reference
The Move class defines moves that are evaluated and set as tabu.
#include "move.h"
Public Member Functions
Move ()=delete
empty move is not allowed
Move (const problem::Vehicle_pickDeliver &, const problem::Vehicle_pickDeliver &, const problem::Order &, const problem::Order &, double, double)
The Move constructor for a "swap" move.
Move (const problem::Vehicle_pickDeliver &, const problem::Vehicle_pickDeliver &, const problem::Order &, double, double)
The Move constructor for a "move" move.
double from_objective () const
Objective value of the "from" vehicle.
bool is_swap () const
is the move a swap move?
int64_t oid1 () const
The identifier of the order to move or swap.
int64_t oid2 () const
The identifier of the order to swap.
double to_objective () const
Objective value of the "to" vehicle.
int64_t vid1 () const
The identifier of the vehicle to move the order to.
int64_t vid2 () const
The identifier of the vehicle to move the order to.
Private Attributes
bool m_is_swap
flag == true when belongs to swap
double m_obj1
The objective value of the vehicle to move the order to.
double m_obj2
The objective value of the vehicle to move the order from.
int64_t m_oid1
The identifier of the first moved order.
int64_t m_oid2
The identifier of the second moved order (valid only for swap moves)
int64_t m_vid1
The identifier of the vehicle to move the order from.
int64_t m_vid2
The identifier of the vehicle to move the order to.
Friends
std::ostream & operator<< (std::ostream &, const Move &)
printing function
bool operator== (const Move &, const Move &)
equality operator
Detailed Description
The Move class defines moves that are evaluated and set as tabu.
Definition at line 46 of file move.h.
Constructor & Destructor Documentation
Move() [1/3]
vrprouting::optimizers::tabu::Move::Move () delete
empty move is not allowed
Move() [2/3]
vrprouting::optimizers::tabu::Move::Move (const problem::Vehicle_pickDeliver & from_v, const problem::Vehicle_pickDeliver & to_v, const problem::Order & order, double to_obj, double from_obj)
The Move constructor for a "move" move.
Definition at line 39 of file move.cpp.
                                                                :
   m_vid1(from_v.id()),
   m_vid2(to_v.id()),
   m_oid1(order.id()),
   m_oid2(0),
   m_is_swap(false),
   m_obj1(to_obj),
   m_obj2(from_obj) { }
Move() [3/3]
vrprouting::optimizers::tabu::Move::Move (const problem::Vehicle_pickDeliver & from_v, const problem::Vehicle_pickDeliver & to_v, const problem::Order & from_order, const problem::Order & to_order, double to_obj, double from_obj)
The Move constructor for a "swap" move.
Definition at line 49 of file move.cpp.
                                                                                                   :
   m_vid1(from_v.id()),
   m_vid2(to_v.id()),
   m_oid1(from_order.id()),
   m_oid2(to_order.id()),
   m_is_swap(true),
   m_obj1(to_obj),
   m_obj2(from_obj) { }
Member Function Documentation
from_objective()
double vrprouting::optimizers::tabu::Move::from_objective () const inline
Objective value of the "from" vehicle.
Currently unused.
Definition at line 78 of file move.h.
 {return m_obj2;}
References m_obj2.
Referenced by vrprouting::optimizers::tabu::operator==().
is_swap()
bool vrprouting::optimizers::tabu::Move::is_swap () const inline
is the move a swap move?
Definition at line 72 of file move.h.
 {return m_is_swap;}
References m_is_swap.
Referenced by vrprouting::optimizers::tabu::operator==().
oid1()
int64_t vrprouting::optimizers::tabu::Move::oid1 () const inline
The identifier of the order to move or swap.
Definition at line 60 of file move.h.
 {return m_oid1;}
References m_oid1.
Referenced by vrprouting::optimizers::tabu::operator==().
oid2()
int64_t vrprouting::optimizers::tabu::Move::oid2 () const inline
The identifier of the order to swap.
Definition at line 63 of file move.h.
 {return m_oid2;}
References m_oid2.
Referenced by vrprouting::optimizers::tabu::operator==().
to_objective()
double vrprouting::optimizers::tabu::Move::to_objective () const inline
Objective value of the "to" vehicle.
Currently unused.
Definition at line 75 of file move.h.
 {return m_obj1;}
References m_obj1.
Referenced by vrprouting::optimizers::tabu::operator==().
vid1()
int64_t vrprouting::optimizers::tabu::Move::vid1 () const inline
The identifier of the vehicle to move the order to.
Definition at line 66 of file move.h.
 {return m_vid1;}
References m_vid1.
Referenced by vrprouting::optimizers::tabu::operator==().
vid2()
int64_t vrprouting::optimizers::tabu::Move::vid2 () const inline
The identifier of the vehicle to move the order to.
Definition at line 69 of file move.h.
 {return m_vid2;}
References m_vid2.
Referenced by vrprouting::optimizers::tabu::operator==().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Move & m) friend
printing function
Parameters
[in,out] log - where to write
[in] m - move to write
Returns
log with move information
Definition at line 66 of file move.cpp.
{
     log << m.m_oid1 << ":" << m.m_oid2 << ":"
       << m.m_vid1 << ":" << m.m_vid2 << ":"
       << m.m_is_swap;
     return log;
   }
operator==
bool operator== (const Move & a, const Move & b) friend
equality operator
Parameters
[in] a - left hand side move
[in] b - right hand side move
Returns
true when the left hand side move move is the same as the right hand side move
Definition at line 80 of file move.cpp.
{
     /*
      * possible cases are captured in TabuList::has_move and TabuList::has_swap:
      */
     return (
         a.oid1() == b.oid1()
         && a.oid2() == b.oid2()
         && a.vid1() == b.vid1()
         && a.vid2() == b.vid2()
 #if 0
         && a.to_objective() == b.to_objective()
         && a.from_objective() == b.from_objective()
 #endif
         && a.is_swap() == b.is_swap());
   }
Member Data Documentation
m_is_swap
bool vrprouting::optimizers::tabu::Move::m_is_swap private
flag == true when belongs to swap
Definition at line 100 of file move.h.
Referenced by is_swap(), and vrprouting::optimizers::tabu::operator<<().
m_obj1
double vrprouting::optimizers::tabu::Move::m_obj1 private
The objective value of the vehicle to move the order to.
Definition at line 103 of file move.h.
Referenced by to_objective().
m_obj2
double vrprouting::optimizers::tabu::Move::m_obj2 private
The objective value of the vehicle to move the order from.
Definition at line 106 of file move.h.
Referenced by from_objective().
m_oid1
int64_t vrprouting::optimizers::tabu::Move::m_oid1 private
The identifier of the first moved order.
Definition at line 94 of file move.h.
Referenced by oid1(), and vrprouting::optimizers::tabu::operator<<().
m_oid2
int64_t vrprouting::optimizers::tabu::Move::m_oid2 private
The identifier of the second moved order (valid only for swap moves)
Definition at line 97 of file move.h.
Referenced by oid2(), and vrprouting::optimizers::tabu::operator<<().
m_vid1
int64_t vrprouting::optimizers::tabu::Move::m_vid1 private
The identifier of the vehicle to move the order from.
Definition at line 88 of file move.h.
Referenced by vrprouting::optimizers::tabu::operator<<(), and vid1().
m_vid2
int64_t vrprouting::optimizers::tabu::Move::m_vid2 private
The identifier of the vehicle to move the order to.
Definition at line 91 of file move.h.
Referenced by vrprouting::optimizers::tabu::operator<<(), and vid2().
The documentation for this class was generated from the following files:
move.h
move.cpp