vrpRouting: vrprouting::Vrp_vroom_problem Class Reference
vrprouting::Vrp_vroom_problem Class Reference
#include "vrp_vroom_problem.hpp"
Public Member Functions
void add_matrix (vrprouting::base::Base_Matrix matrix)
void clear ()
Clears all the messages.
void get_amount (vroom::Amount vroom_amount, Amount **amount)
std::string get_error () const
gets the contents of error message
StepType get_job_step_type (vroom::JOB_TYPE vroom_job_type)
std::string get_log () const
gets the contents of log message
std::string get_notice () const
gets the contents of notice message
std::vector< Vroom_rt > get_results (vroom::Solution solution)
StepType get_step_type (vroom::Step step)
bool has_error () const
gets the contents of notice message
std::vector< vroom::Job > jobs () const
vrprouting::base::Base_Matrix matrix () const
std::vector< std::pair< vroom::Job, vroom::Job > > shipments () const
std::vector< Vroom_rt > solve (int32_t exploration_level, int32_t timeout, int32_t loading_time)
std::vector< vroom::Vehicle > vehicles () const
vroom time window wrapper
vroom::TimeWindow get_vroom_time_window (const Vroom_time_window_t &time_window) const
Gets the vroom time window from the C-style struct.
vroom::TimeWindow get_vroom_time_window (Duration tw_open, Duration tw_close) const
std::vector< vroom::TimeWindow > get_vroom_time_windows (const std::vector< Vroom_time_window_t > &time_windows) const
vroom amounts wrapper
vroom::Amount get_vroom_amounts (const std::vector< Amount > &amounts) const
Gets the vroom amounts from C-style array.
vroom::Amount get_vroom_amounts (const Amount *amounts, size_t count) const
vroom skills wrapper
vroom::Skills get_vroom_skills (const Skill *skills, size_t count) const
Gets the vroom skills.
vroom jobs wrapper
vroom::Job get_vroom_job (const Vroom_job_t &job, const std::vector< Vroom_time_window_t > &job_tws) const
Gets the vroom jobs.
void problem_add_job (const Vroom_job_t &job, const std::vector< Vroom_time_window_t > &job_tws)
void add_jobs (const std::vector< Vroom_job_t > &jobs, const std::vector< Vroom_time_window_t > &jobs_tws)
void add_jobs (const Vroom_job_t *jobs, size_t count, const Vroom_time_window_t *jobs_tws, size_t total_jobs_tws)
vroom shipments wrapper
std::pair< vroom::Job, vroom::Job > get_vroom_shipment (const Vroom_shipment_t &shipment, const std::vector< Vroom_time_window_t > &pickup_tws, const std::vector< Vroom_time_window_t > &delivery_tws) const
Gets the vroom shipments.
void problem_add_shipment (const Vroom_shipment_t &shipment, const std::vector< Vroom_time_window_t > &pickup_tws, const std::vector< Vroom_time_window_t > &delivery_tws)
void add_shipments (const std::vector< Vroom_shipment_t > &shipments, const std::vector< Vroom_time_window_t > &shipments_tws)
void add_shipments (const Vroom_shipment_t *shipments, size_t count, const Vroom_time_window_t *shipment_tws, size_t total_shipment_tws)
vroom breaks wrapper
vroom::Break get_vroom_break (const Vroom_break_t &v_break, const std::vector< Vroom_time_window_t > &break_tws) const
Gets the vehicle breaks from C-style breaks struct.
std::vector< vroom::Break > get_vroom_breaks (const std::vector< Vroom_break_t > &breaks, const std::vector< Vroom_time_window_t > &breaks_tws) const
vroom vehicles wrapper
vroom::Vehicle get_vroom_vehicle (const Vroom_vehicle_t &vehicle, const std::vector< Vroom_break_t > &breaks, const std::vector< Vroom_time_window_t > &breaks_tws) const
Gets the vroom vehicles.
void problem_add_vehicle (const Vroom_vehicle_t &vehicle, const std::vector< Vroom_break_t > &breaks, const std::vector< Vroom_time_window_t > &breaks_tws)
void add_vehicles (const std::vector< Vroom_vehicle_t > &vehicles, const std::vector< Vroom_break_t > &breaks, const std::vector< Vroom_time_window_t > &breaks_tws)
void add_vehicles (const Vroom_vehicle_t *vehicles, size_t count, const Vroom_break_t *breaks, size_t total_breaks, const Vroom_time_window_t *breaks_tws, size_t total_breaks_tws)
Public Attributes
std::ostringstream error
Stores the error information.
std::ostringstream log
Stores the hint information.
std::ostringstream notice
Stores the notice information.
Private Attributes
std::vector< vroom::Job > m_jobs
vrprouting::base::Base_Matrix m_matrix
std::vector< std::pair< vroom::Job, vroom::Job > > m_shipments
std::vector< vroom::Vehicle > m_vehicles
Detailed Description
Definition at line 54 of file vrp_vroom_problem.hpp.
Member Function Documentation
add_jobs() [1/2]
void vrprouting::Vrp_vroom_problem::add_jobs (const std::vector< Vroom_job_t > & jobs, const std::vector< Vroom_time_window_t > & jobs_tws) inline
Definition at line 190 of file vrp_vroom_problem.hpp.
{
     std::map<Idx, std::vector<Vroom_time_window_t>> job_tws_map;
     for (auto job_tw : jobs_tws) {
       Idx id = job_tw.id;
       if (job_tws_map.find(id) == job_tws_map.end()) {
         job_tws_map[id] = std::vector<Vroom_time_window_t>();
       }
       job_tws_map[id].push_back(job_tw);
     }
     for (auto job : jobs) {
       problem_add_job(job, job_tws_map[job.id]);
     }
   }
References jobs(), and problem_add_job().
Referenced by add_jobs(), and do_vrp_vroom().
add_jobs() [2/2]
void vrprouting::Vrp_vroom_problem::add_jobs (const Vroom_job_t * jobs, size_t count, const Vroom_time_window_t * jobs_tws, size_t total_jobs_tws) inline
Definition at line 205 of file vrp_vroom_problem.hpp.
{
     add_jobs(
         std::vector<Vroom_job_t>(jobs, jobs + count),
         std::vector<Vroom_time_window_t>(jobs_tws, jobs_tws + total_jobs_tws));
   }
References add_jobs(), and jobs().
add_matrix()
void vrprouting::Vrp_vroom_problem::add_matrix (vrprouting::base::Base_Matrix matrix) inline
Definition at line 424 of file vrp_vroom_problem.hpp.
{
     m_matrix = matrix;
   }
References m_matrix, and matrix().
Referenced by do_vrp_vroom().
add_shipments() [1/2]
void vrprouting::Vrp_vroom_problem::add_shipments (const std::vector< Vroom_shipment_t > & shipments, const std::vector< Vroom_time_window_t > & shipments_tws) inline
Definition at line 262 of file vrp_vroom_problem.hpp.
{
     std::map<Idx, std::vector<Vroom_time_window_t>> pickup_tws_map;
     std::map<Idx, std::vector<Vroom_time_window_t>> delivery_tws_map;
     for (auto shipment_tw : shipments_tws) {
       Idx id = shipment_tw.id;
       if (shipment_tw.kind == 'p') {
         if (pickup_tws_map.find(id) == pickup_tws_map.end()) {
           pickup_tws_map[id] = std::vector<Vroom_time_window_t>();
         }
         pickup_tws_map[id].push_back(shipment_tw);
       } else if (shipment_tw.kind == 'd') {
         if (delivery_tws_map.find(id) == delivery_tws_map.end()) {
           delivery_tws_map[id] = std::vector<Vroom_time_window_t>();
         }
         delivery_tws_map[id].push_back(shipment_tw);
       }
     }
     for (auto shipment : shipments) {
       problem_add_shipment(shipment, pickup_tws_map[shipment.id],
                            delivery_tws_map[shipment.id]);
     }
   }
References problem_add_shipment(), and shipments().
Referenced by add_shipments(), and do_vrp_vroom().
add_shipments() [2/2]
void vrprouting::Vrp_vroom_problem::add_shipments (const Vroom_shipment_t * shipments, size_t count, const Vroom_time_window_t * shipment_tws, size_t total_shipment_tws) inline
Definition at line 286 of file vrp_vroom_problem.hpp.
{
     add_shipments(
         std::vector<Vroom_shipment_t>(shipments, shipments + count),
         std::vector<Vroom_time_window_t>(shipment_tws, shipment_tws + total_shipment_tws));
   }
References add_shipments(), and shipments().
add_vehicles() [1/2]
void vrprouting::Vrp_vroom_problem::add_vehicles (const std::vector< Vroom_vehicle_t > & vehicles, const std::vector< Vroom_break_t > & breaks, const std::vector< Vroom_time_window_t > & breaks_tws) inline
Definition at line 382 of file vrp_vroom_problem.hpp.
{
     std::map<Idx, std::vector<Vroom_time_window_t>> breaks_tws_map;
     for (auto break_tw : breaks_tws) {
       Idx id = break_tw.id;
       if (breaks_tws_map.find(id) == breaks_tws_map.end()) {
         breaks_tws_map[id] = std::vector<Vroom_time_window_t>();
       }
       breaks_tws_map[id].push_back(break_tw);
     }
     std::map<Idx, std::vector<Vroom_break_t>> v_breaks_map;
     for (auto v_break : breaks) {
       Idx v_id = v_break.vehicle_id;
       if (v_breaks_map.find(v_id) == v_breaks_map.end()) {
         v_breaks_map[v_id] = std::vector<Vroom_break_t>();
       }
       v_breaks_map[v_id].push_back(v_break);
     }
     for (auto vehicle : vehicles) {
       std::vector<Vroom_break_t> v_breaks = v_breaks_map[vehicle.id];
       std::vector<Vroom_time_window_t> v_breaks_tws;
       for (auto v_break : v_breaks) {
         std::vector<Vroom_time_window_t> tws = breaks_tws_map[v_break.id];
         v_breaks_tws.insert(v_breaks_tws.end(), tws.begin(), tws.end());
       }
       problem_add_vehicle(vehicle, v_breaks, v_breaks_tws);
     }
   }
References problem_add_vehicle(), and vehicles().
Referenced by add_vehicles(), and do_vrp_vroom().
add_vehicles() [2/2]
void vrprouting::Vrp_vroom_problem::add_vehicles (const Vroom_vehicle_t * vehicles, size_t count, const Vroom_break_t * breaks, size_t total_breaks, const Vroom_time_window_t * breaks_tws, size_t total_breaks_tws) inline
Definition at line 414 of file vrp_vroom_problem.hpp.
{
     add_vehicles(std::vector<Vroom_vehicle_t>(vehicles, vehicles + count),
                  std::vector<Vroom_break_t>(breaks, breaks + total_breaks),
                  std::vector<Vroom_time_window_t>(breaks_tws, breaks_tws + total_breaks_tws));
   }
References add_vehicles(), and vehicles().
clear()
void vrprouting::Pgr_messages::clear () inherited
Clears all the messages.
Definition at line 59 of file pgr_messages.cpp.
                     {
     log.str("");
     log.clear();
     notice.str("");
     notice.clear();
     error.str("");
     error.clear();
 }
References vrprouting::Pgr_messages::error, vrprouting::Pgr_messages::log, and vrprouting::Pgr_messages::notice.
Referenced by do_compatibleVehicles(), do_pgr_pickDeliver(), and do_pickDeliver().
get_amount()
void vrprouting::Vrp_vroom_problem::get_amount (vroom::Amount vroom_amount, Amount ** amount) inline
Definition at line 428 of file vrp_vroom_problem.hpp.
{
     size_t amount_size = vroom_amount.size();
     for (size_t i = 0; i < amount_size; i++) {
       *((*amount) + i) = vroom_amount[i];
     }
   }
Referenced by get_results().
get_error()
std::string vrprouting::Pgr_messages::get_error () const inherited
gets the contents of error message
Returns
the current contents of error
Definition at line 53 of file pgr_messages.cpp.
{
     auto str = error.str();
     return str;
 }
References vrprouting::Pgr_messages::error.
Referenced by vrprouting::problem::Fleet::add_vehicle(), do_compatibleVehicles(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pickDeliver(), vrprouting::problem::Fleet::is_fleet_ok(), anonymous_namespace{optimize_driver.cpp}::one_processing(), and vrprouting::problem::PickDeliver::PickDeliver().
get_job_step_type()
StepType vrprouting::Vrp_vroom_problem::get_job_step_type (vroom::JOB_TYPE vroom_job_type) inline
Definition at line 435 of file vrp_vroom_problem.hpp.
{
     StepType step_type;
     switch (vroom_job_type) {
       case vroom::JOB_TYPE::SINGLE:
         step_type = 2;
         break;
       case vroom::JOB_TYPE::PICKUP:
         step_type = 3;
         break;
       case vroom::JOB_TYPE::DELIVERY:
         step_type = 4;
         break;
     }
     return step_type;
   }
Referenced by get_results(), and get_step_type().
get_log()
std::string vrprouting::Pgr_messages::get_log () const inherited
gets the contents of log message
Returns
the current contents of log
Definition at line 36 of file pgr_messages.cpp.
{
     auto str = log.str();
     return str;
 }
References vrprouting::Pgr_messages::log.
Referenced by do_compatibleVehicles(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pickDeliver(), vrprouting::problem::Fleet::get_unused_trucks(), vrprouting::problem::Fleet::invariant(), and anonymous_namespace{optimize_driver.cpp}::one_processing().
get_notice()
std::string vrprouting::Pgr_messages::get_notice () const inherited
gets the contents of notice message
Returns
the current contents of notice
Definition at line 42 of file pgr_messages.cpp.
{
     auto str = notice.str();
     return str;
 }
References vrprouting::Pgr_messages::notice.
get_results()
std::vector< Vroom_rt > vrprouting::Vrp_vroom_problem::get_results (vroom::Solution solution) inline
Definition at line 470 of file vrp_vroom_problem.hpp.
{
     std::vector < Vroom_rt > results;
     std::vector<vroom::Route> routes = solution.routes;
     Idx vehicle_seq = 1;
     char *empty_desc = strdup("{}");
     for (auto route : routes) {
       Idx step_seq = 1;
       Duration prev_duration = 0;
       char *vehicle_data = strdup(route.description.c_str());
       for (auto step : route.steps) {
         Idx task_id = step.id;
         MatrixIndex location_id = m_matrix.get_original_id(step.location.index());
         char *task_data = strdup(step.description.c_str());
         StepType step_type = get_step_type(step);
         if (step_type == 1 || step_type == 6) {
           task_id = static_cast<Idx>(-1);
           task_data = empty_desc;
         }
         size_t load_size = step.load.size();
         Amount *load = reinterpret_cast<Amount*>(malloc(load_size * sizeof(Amount)));
         get_amount(step.load, &load);
         Duration travel_time = step.duration - prev_duration;
         prev_duration = step.duration;
         Duration departure = step.arrival + step.setup + step.service + step.waiting_time;
         results.push_back({
             vehicle_seq,        // vehicles_seq
             route.vehicle,      // vehicles_id
             vehicle_data,       // vehicle_data
             step_seq,           // step_seq
             step_type,          // step_type
             task_id,            // task_id
             location_id,        // location_id
             task_data,          // task_data
             step.arrival,       // arrival
             travel_time,        // travel_time
             step.setup,         // setup_time
             step.service,       // service_time
             step.waiting_time,  // waiting_time
             departure,          // departure
             load,               // load
             load_size           // load size
         });
         step_seq++;
       }
       // The summary of this route
       Idx task_id = 0;
       results.push_back({
           vehicle_seq,         // vehicles_seq
           route.vehicle,       // vehicles_id
           vehicle_data,        // vehicle_data
           0,                   // step_seq = 0 for route summary
           0,                   // step_type = 0 for route summary
           task_id,             // task_id = 0 for route summary
           0,                   // location_id = 0 for route summary
           empty_desc,          // task_data
           0,                   // No arrival time
           route.duration,      // Total travel time
           route.setup,         // Total setup time
           route.service,       // Total service time
           route.waiting_time,  // Total waiting time
           0,                   // No departure time
           {},                  // load
           0                    // load size
       });
       vehicle_seq++;
     }
     std::vector<vroom::Job> unassigned = solution.unassigned;
     Idx step_seq = 1;
     for (auto job : unassigned) {
       StepType job_step = get_job_step_type(job.type);
       Idx vehicle_id = static_cast<Idx>(-1);
       Idx job_id = job.id;
       MatrixIndex location_id = m_matrix.get_original_id(job.location.index());
       char *task_data = strdup(job.description.c_str());
       results.push_back({
           vehicle_seq,      // vehicles_seq
           vehicle_id,       // vehicles_id = -1 for unassigned jobs
           empty_desc,       // vehicle_data
           step_seq,         // step_seq
           job_step,         // step_type
           job_id,           // task_id
           location_id,      // location_id
           task_data,        // task_data
           0,                // No arrival time
           0,                // No travel_time
           0,                // No setup_time
           0,                // No service_time
           0,                // No waiting_time
           0,                // No departure time
           {},               // load
           0                 // load size
       });
       step_seq++;
     }
     // The summary of the entire problem
     vroom::Summary summary = solution.summary;
     Idx vehicle_id = 0;
     Idx job_id = 0;
     results.push_back({
         0,                     // vehicles_seq = 0 for problem summary
         vehicle_id,            // vehicles_id = 0 for problem summary
         empty_desc,            // vehicle_data
         0,                     // step_seq = 0 for problem summary
         0,                     // step_type = 0 for problem summary
         job_id,                // task_id = 0 for problem summary
         0,                     // location_id = 0 for problem summary
         empty_desc,            // task_data
         0,                     // No arrival time
         summary.duration,      // Total travel time
         summary.setup,         // Total setup time
         summary.service,       // Total service time
         summary.waiting_time,  // Total waiting time
         0,                     // No departure time
         {},                    // load
         0                      // load size
     });
     return results;
   }
References get_amount(), get_job_step_type(), vrprouting::base::Base_Matrix::get_original_id(), get_step_type(), and m_matrix.
Referenced by solve().
get_step_type()
StepType vrprouting::Vrp_vroom_problem::get_step_type (vroom::Step step) inline
Definition at line 451 of file vrp_vroom_problem.hpp.
{
     StepType step_type = 0;
     switch (step.step_type) {
       case vroom::STEP_TYPE::START:
         step_type = 1;
         break;
       case vroom::STEP_TYPE::END:
         step_type = 6;
         break;
       case vroom::STEP_TYPE::BREAK:
         step_type = 5;
         break;
       case vroom::STEP_TYPE::JOB:
         step_type = get_job_step_type(step.job_type);
         break;
     }
     return step_type;
   }
References get_job_step_type().
Referenced by get_results().
get_vroom_amounts() [1/2]
vroom::Amount vrprouting::Vrp_vroom_problem::get_vroom_amounts (const Amount * amounts, size_t count) const inline
Definition at line 131 of file vrp_vroom_problem.hpp.
{
     return get_vroom_amounts(std::vector <Amount>(amounts, amounts + count));
   }
References get_vroom_amounts().
get_vroom_amounts() [2/2]
vroom::Amount vrprouting::Vrp_vroom_problem::get_vroom_amounts (const std::vector< Amount > & amounts) const inline
Gets the vroom amounts from C-style array.
Parameters
[in] amounts The amounts array (pickup or delivery)
Returns
The vroom amounts.
Definition at line 112 of file vrp_vroom_problem.hpp.
{
     vroom::Amount amt;
     if (amounts.size()) {
       for (auto amount : amounts) {
         amt.push_back(amount);
       }
     } else {
       const unsigned int amount_size =
           m_vehicles.size() ? static_cast<unsigned int>(m_vehicles[0].capacity.size()) : 0;
       // Default to zero amount with provided size.
       amt = vroom::Amount(amount_size);
       for (size_t i = 0; i < amounts.size(); i++) {
         amt[i] = amounts[i];
       }
     }
     return amt;
   }
References m_vehicles.
Referenced by get_vroom_amounts(), get_vroom_job(), get_vroom_shipment(), and get_vroom_vehicle().
get_vroom_break()
vroom::Break vrprouting::Vrp_vroom_problem::get_vroom_break (const Vroom_break_t & v_break, const std::vector< Vroom_time_window_t > & break_tws) const inline
Gets the vehicle breaks from C-style breaks struct.
Parameters
[in] v_break The vehicle break struct
Returns
The vroom vehicle break.
Definition at line 307 of file vrp_vroom_problem.hpp.
{
     std::vector <vroom::TimeWindow> tws = get_vroom_time_windows(break_tws);
     return vroom::Break(v_break.id, tws, v_break.service, v_break.data);
   }
References Vroom_break_t::data, get_vroom_time_windows(), Vroom_break_t::id, and Vroom_break_t::service.
Referenced by get_vroom_breaks().
get_vroom_breaks()
std::vector< vroom::Break > vrprouting::Vrp_vroom_problem::get_vroom_breaks (const std::vector< Vroom_break_t > & breaks, const std::vector< Vroom_time_window_t > & breaks_tws) const inline
Definition at line 315 of file vrp_vroom_problem.hpp.
{
     std::map<Idx, std::vector<Vroom_time_window_t>> breaks_tws_map;
     for (auto break_tw : breaks_tws) {
       Idx id = break_tw.id;
       if (breaks_tws_map.find(id) == breaks_tws_map.end()) {
         breaks_tws_map[id] = std::vector<Vroom_time_window_t>();
       }
       breaks_tws_map[id].push_back(break_tw);
     }
     std::vector < vroom::Break > v_breaks;
     for (auto v_break : breaks) {
       v_breaks.push_back(get_vroom_break(v_break, breaks_tws_map[v_break.id]));
     }
     return v_breaks;
   }
References get_vroom_break().
Referenced by get_vroom_vehicle().
get_vroom_job()
vroom::Job vrprouting::Vrp_vroom_problem::get_vroom_job (const Vroom_job_t & job, const std::vector< Vroom_time_window_t > & job_tws) const inline
Gets the vroom jobs.
Parameters
[in] job The job C-style struct
[in] job_tws The job time windows
Returns
The vroom job.
Definition at line 169 of file vrp_vroom_problem.hpp.
{
     vroom::Amount delivery =
         get_vroom_amounts(job.delivery, job.delivery_size);
     vroom::Amount pickup =
         get_vroom_amounts(job.pickup, job.pickup_size);
     vroom::Skills skills =
         get_vroom_skills(job.skills, job.skills_size);
     std::vector<vroom::TimeWindow> time_windows =
         get_vroom_time_windows(job_tws);
     vroom::Index location_id =
         static_cast<vroom::Index>(m_matrix.get_index(job.location_id));
     return vroom::Job(job.id, location_id, job.setup, job.service, delivery, pickup,
                       skills, job.priority, time_windows, job.data);
   }
References Vroom_job_t::data, Vroom_job_t::delivery, Vroom_job_t::delivery_size, vrprouting::base::Base_Matrix::get_index(), get_vroom_amounts(), get_vroom_skills(), get_vroom_time_windows(), Vroom_job_t::id, Vroom_job_t::location_id, m_matrix, Vroom_job_t::pickup, Vroom_job_t::pickup_size, Vroom_job_t::priority, Vroom_job_t::service, Vroom_job_t::setup, Vroom_job_t::skills, and Vroom_job_t::skills_size.
Referenced by problem_add_job().
get_vroom_shipment()
std::pair<vroom::Job, vroom::Job> vrprouting::Vrp_vroom_problem::get_vroom_shipment (const Vroom_shipment_t & shipment, const std::vector< Vroom_time_window_t > & pickup_tws, const std::vector< Vroom_time_window_t > & delivery_tws) const inline
Gets the vroom shipments.
Parameters
[in] shipment The shipment C-style struct
[in] pickup_tws The pickup time windows
[in] delivery_tws The delivery time windows
Returns
The vroom shipment.
Definition at line 227 of file vrp_vroom_problem.hpp.
{
     vroom::Amount amount =
         get_vroom_amounts(shipment.amount, shipment.amount_size);
     vroom::Skills skills =
         get_vroom_skills(shipment.skills, shipment.skills_size);
     std::vector<vroom::TimeWindow> p_time_windows =
         get_vroom_time_windows(pickup_tws);
     std::vector<vroom::TimeWindow> d_time_windows =
         get_vroom_time_windows(delivery_tws);
     vroom::Index p_location_id = static_cast<vroom::Index>(
         m_matrix.get_index(shipment.p_location_id));
     vroom::Index d_location_id = static_cast<vroom::Index>(
         m_matrix.get_index(shipment.d_location_id));
     vroom::Job pickup = vroom::Job(
         shipment.id, vroom::JOB_TYPE::PICKUP, p_location_id,
         shipment.p_setup, shipment.p_service, amount,
         skills, shipment.priority, p_time_windows, shipment.p_data);
     vroom::Job delivery = vroom::Job(
         shipment.id, vroom::JOB_TYPE::DELIVERY, d_location_id,
         shipment.d_setup, shipment.d_service, amount,
         skills, shipment.priority, d_time_windows, shipment.d_data);
     return std::make_pair(pickup, delivery);
   }
References Vroom_shipment_t::amount, Vroom_shipment_t::amount_size, Vroom_shipment_t::d_data, Vroom_shipment_t::d_location_id, Vroom_shipment_t::d_service, Vroom_shipment_t::d_setup, vrprouting::base::Base_Matrix::get_index(), get_vroom_amounts(), get_vroom_skills(), get_vroom_time_windows(), Vroom_shipment_t::id, m_matrix, Vroom_shipment_t::p_data, Vroom_shipment_t::p_location_id, Vroom_shipment_t::p_service, Vroom_shipment_t::p_setup, Vroom_shipment_t::priority, Vroom_shipment_t::skills, and Vroom_shipment_t::skills_size.
Referenced by problem_add_shipment().
get_vroom_skills()
vroom::Skills vrprouting::Vrp_vroom_problem::get_vroom_skills (const Skill * skills, size_t count) const inline
Gets the vroom skills.
Parameters
[in] skills The skills array
[in] count The size of skills array
Returns
The vroom skills.
Definition at line 150 of file vrp_vroom_problem.hpp.
{
     return std::unordered_set <Skill>(skills, skills + count);
   }
Referenced by get_vroom_job(), get_vroom_shipment(), and get_vroom_vehicle().
get_vroom_time_window() [1/2]
vroom::TimeWindow vrprouting::Vrp_vroom_problem::get_vroom_time_window (const Vroom_time_window_t & time_window) const inline
Gets the vroom time window from the C-style struct.
Parameters
[in] time_window The C-style time window struct
Returns
The vroom time window.
Definition at line 73 of file vrp_vroom_problem.hpp.
{
     return
     vroom::TimeWindow(time_window.tw_open,
                       time_window.tw_close);
   }
References Vroom_time_window_t::tw_close, and Vroom_time_window_t::tw_open.
Referenced by get_vroom_time_windows(), and get_vroom_vehicle().
get_vroom_time_window() [2/2]
vroom::TimeWindow vrprouting::Vrp_vroom_problem::get_vroom_time_window (Duration tw_open, Duration tw_close) const inline
Definition at line 80 of file vrp_vroom_problem.hpp.
{
     return vroom::TimeWindow(tw_open, tw_close);
   }
get_vroom_time_windows()
std::vector<vroom::TimeWindow> vrprouting::Vrp_vroom_problem::get_vroom_time_windows (const std::vector< Vroom_time_window_t > & time_windows) const inline
Definition at line 85 of file vrp_vroom_problem.hpp.
{
     std::vector < vroom::TimeWindow > tws;
     for (auto time_window : time_windows) {
       tws.push_back(get_vroom_time_window(time_window));
     }
     if (tws.size()) {
       return tws;
     } else {
       return std::vector<vroom::TimeWindow>(1, vroom::TimeWindow());
     }
   }
References get_vroom_time_window().
Referenced by get_vroom_break(), get_vroom_job(), and get_vroom_shipment().
get_vroom_vehicle()
vroom::Vehicle vrprouting::Vrp_vroom_problem::get_vroom_vehicle (const Vroom_vehicle_t & vehicle, const std::vector< Vroom_break_t > & breaks, const std::vector< Vroom_time_window_t > & breaks_tws) const inline
Gets the vroom vehicles.
Parameters
[in] vehicle The vehicle C-style struct
[in] breaks_tws The breaks time windows
Returns
The vroom vehicle.
Definition at line 347 of file vrp_vroom_problem.hpp.
{
     vroom::Amount capacity =
         get_vroom_amounts(vehicle.capacity, vehicle.capacity_size);
     vroom::Skills skills =
         get_vroom_skills(vehicle.skills, vehicle.skills_size);
     vroom::TimeWindow time_window =
         get_vroom_time_window(vehicle.tw_open,
                               vehicle.tw_close);
     std::vector<vroom::Break> v_breaks = get_vroom_breaks(breaks, breaks_tws);
     std::optional<vroom::Location> start_id;
     std::optional<vroom::Location> end_id;
     // Set the value of start or end index only if they are present
     if (vehicle.start_id != -1) {
       start_id = static_cast<vroom::Index>(m_matrix.get_index(vehicle.start_id));
     }
     if (vehicle.end_id != -1) {
       end_id = static_cast<vroom::Index>(m_matrix.get_index(vehicle.end_id));
     }
     return vroom::Vehicle(vehicle.id, start_id, end_id,
                           vroom::DEFAULT_PROFILE, capacity, skills, time_window,
                           v_breaks, vehicle.data, vehicle.speed_factor,
                           static_cast<size_t>(vehicle.max_tasks));
   }
References Vroom_vehicle_t::capacity, Vroom_vehicle_t::capacity_size, Vroom_vehicle_t::data, Vroom_vehicle_t::end_id, vrprouting::base::Base_Matrix::get_index(), get_vroom_amounts(), get_vroom_breaks(), get_vroom_skills(), get_vroom_time_window(), Vroom_vehicle_t::id, m_matrix, Vroom_vehicle_t::max_tasks, Vroom_vehicle_t::skills, Vroom_vehicle_t::skills_size, Vroom_vehicle_t::speed_factor, Vroom_vehicle_t::start_id, Vroom_vehicle_t::tw_close, and Vroom_vehicle_t::tw_open.
Referenced by problem_add_vehicle().
has_error()
bool vrprouting::Pgr_messages::has_error () const inherited
gets the contents of notice message
Returns
true when error message is not empty
Definition at line 48 of file pgr_messages.cpp.
{
     return  !error.str().empty();
 }
References vrprouting::Pgr_messages::error.
jobs()
std::vector<vroom::Job> vrprouting::Vrp_vroom_problem::jobs () const inline
Definition at line 56 of file vrp_vroom_problem.hpp.
 { return m_jobs; }
References m_jobs.
Referenced by add_jobs().
matrix()
vrprouting::base::Base_Matrix vrprouting::Vrp_vroom_problem::matrix () const inline
Definition at line 59 of file vrp_vroom_problem.hpp.
 { return m_matrix; }
References m_matrix.
Referenced by add_matrix().
problem_add_job()
void vrprouting::Vrp_vroom_problem::problem_add_job (const Vroom_job_t & job, const std::vector< Vroom_time_window_t > & job_tws) inline
Definition at line 185 of file vrp_vroom_problem.hpp.
{
     m_jobs.push_back(get_vroom_job(job, job_tws));
   }
References get_vroom_job(), and m_jobs.
Referenced by add_jobs().
problem_add_shipment()
void vrprouting::Vrp_vroom_problem::problem_add_shipment (const Vroom_shipment_t & shipment, const std::vector< Vroom_time_window_t > & pickup_tws, const std::vector< Vroom_time_window_t > & delivery_tws) inline
Definition at line 254 of file vrp_vroom_problem.hpp.
{
     m_shipments.push_back(
         get_vroom_shipment(shipment, pickup_tws, delivery_tws));
   }
References get_vroom_shipment(), and m_shipments.
Referenced by add_shipments().
problem_add_vehicle()
void vrprouting::Vrp_vroom_problem::problem_add_vehicle (const Vroom_vehicle_t & vehicle, const std::vector< Vroom_break_t > & breaks, const std::vector< Vroom_time_window_t > & breaks_tws) inline
Definition at line 375 of file vrp_vroom_problem.hpp.
{
     m_vehicles.push_back(get_vroom_vehicle(vehicle, breaks, breaks_tws));
   }
References get_vroom_vehicle(), and m_vehicles.
Referenced by add_vehicles().
shipments()
std::vector<std::pair<vroom::Job, vroom::Job> > vrprouting::Vrp_vroom_problem::shipments () const inline
Definition at line 57 of file vrp_vroom_problem.hpp.
 { return m_shipments; }
References m_shipments.
Referenced by add_shipments().
solve()
std::vector<Vroom_rt> vrprouting::Vrp_vroom_problem::solve (int32_t exploration_level, int32_t timeout, int32_t loading_time) inline
Definition at line 593 of file vrp_vroom_problem.hpp.
{
     std::vector <Vroom_rt> results;
     /* abort in case an interruption occurs (e.g. the query is being cancelled) */
     CHECK_FOR_INTERRUPTS();
     try {
       const unsigned int amount_size =
           m_vehicles.size()
               ? static_cast<unsigned int>(m_vehicles[0].capacity.size())
               : 0;
       vroom::Input problem_instance(amount_size);
       for (const auto &vehicle : m_vehicles) {
         problem_instance.add_vehicle(vehicle);
       }
       for (const auto &job : m_jobs) {
         problem_instance.add_job(job);
       }
       for (const auto &shipment : m_shipments) {
         problem_instance.add_shipment(shipment.first, shipment.second);
       }
       vroom::Matrix<vroom::Duration> duration_matrix = m_matrix.get_vroom_duration_matrix();
       vroom::Matrix<vroom::Cost> cost_matrix = m_matrix.get_vroom_cost_matrix();
       problem_instance.set_durations_matrix(vroom::DEFAULT_PROFILE, std::move(duration_matrix));
       problem_instance.set_costs_matrix(vroom::DEFAULT_PROFILE, std::move(cost_matrix));
       unsigned threads = 4;
       if (timeout < 0) {
         auto solution = problem_instance.solve(
             static_cast<unsigned>(exploration_level), threads);
         results = get_results(solution);
       } else {
         int timeout_ms = (loading_time <= timeout * 1000) ? (timeout * 1000 - loading_time) : 0;
         auto solution = problem_instance.solve(
             static_cast<unsigned>(exploration_level), threads, timeout_ms);
         results = get_results(solution);
       }
     } catch (const vroom::Exception &ex) {
       throw;
     } catch (const std::exception &ex) {
       throw;
     } catch (...) {
       throw;
     }
     return results;
   }
References CHECK_FOR_INTERRUPTS, get_results(), vrprouting::base::Base_Matrix::get_vroom_cost_matrix(), vrprouting::base::Base_Matrix::get_vroom_duration_matrix(), m_jobs, m_matrix, m_shipments, and m_vehicles.
Referenced by do_vrp_vroom().
vehicles()
std::vector<vroom::Vehicle> vrprouting::Vrp_vroom_problem::vehicles () const inline
Definition at line 58 of file vrp_vroom_problem.hpp.
 { return m_vehicles; }
References m_vehicles.
Referenced by add_vehicles().
Member Data Documentation
error
std::ostringstream vrprouting::Pgr_messages::error mutable inherited
Stores the error information.
Definition at line 95 of file pgr_messages.h.
Referenced by vrprouting::problem::Fleet::add_vehicle(), vrprouting::Pgr_messages::clear(), vrprouting::Pgr_messages::get_error(), vrprouting::Pgr_messages::has_error(), vrprouting::problem::Fleet::is_fleet_ok(), and vrprouting::initialsol::tabu::Initial_solution::process_unassigned().
log
std::ostringstream vrprouting::Pgr_messages::log mutable inherited
Stores the hint information.
Definition at line 91 of file pgr_messages.h.
Referenced by vrprouting::problem::Fleet::add_vehicle(), vrprouting::Pgr_messages::clear(), vrprouting::Pgr_messages::get_log(), vrprouting::problem::Fleet::get_unused_trucks(), vrprouting::optimizers::simple::Optimize::inter_swap(), vrprouting::problem::Fleet::invariant(), vrprouting::problem::Fleet::is_fleet_ok(), vrprouting::initialsol::simple::Initial_solution::one_truck_all_orders(), vrprouting::optimizers::simple::Optimize::Optimize(), vrprouting::optimizers::tabu::Optimize::Optimize(), vrprouting::optimizers::simple::Optimize::save_if_best(), vrprouting::problem::Fleet::set_compatibles(), vrprouting::problem::Vehicle_pickDeliver::set_initial_solution(), and vrprouting::problem::Vehicle_pickDeliver::set_unmovable().
m_jobs
std::vector<vroom::Job> vrprouting::Vrp_vroom_problem::m_jobs private
Definition at line 642 of file vrp_vroom_problem.hpp.
Referenced by jobs(), problem_add_job(), and solve().
m_matrix
vrprouting::base::Base_Matrix vrprouting::Vrp_vroom_problem::m_matrix private
Definition at line 645 of file vrp_vroom_problem.hpp.
Referenced by add_matrix(), get_results(), get_vroom_job(), get_vroom_shipment(), get_vroom_vehicle(), matrix(), and solve().
m_shipments
std::vector<std::pair<vroom::Job, vroom::Job> > vrprouting::Vrp_vroom_problem::m_shipments private
Definition at line 643 of file vrp_vroom_problem.hpp.
Referenced by problem_add_shipment(), shipments(), and solve().
m_vehicles
std::vector<vroom::Vehicle> vrprouting::Vrp_vroom_problem::m_vehicles private
Definition at line 644 of file vrp_vroom_problem.hpp.
Referenced by get_vroom_amounts(), problem_add_vehicle(), solve(), and vehicles().
notice
std::ostringstream vrprouting::Pgr_messages::notice mutable inherited
Stores the notice information.
Definition at line 93 of file pgr_messages.h.
Referenced by vrprouting::Pgr_messages::clear(), and vrprouting::Pgr_messages::get_notice().
The documentation for this class was generated from the following file:
vrp_vroom_problem.hpp