vrpRouting: vrprouting::vrp::Vehicle_pickDeliver Class Reference
vrprouting::vrp::Vehicle_pickDeliver Class Reference
#include "vehicle_pickDeliver.h"
Public Types
typedef std::tuple< int, int, size_t, double, double > Cost
Public Member Functions
Vehicle_pickDeliver (const Vehicle_pickDeliver &)=default
Vehicle_pickDeliver (size_t idx, int64_t id, const Vehicle_node &starting_site, const Vehicle_node &ending_site, double p_capacity, double p_speed, double factor)
double deltaTime (const Vehicle_node &node, POS pos) const
void do_while_feasable (Initials_code kind, Identifiers< size_t > &unassigned, Identifiers< size_t > &assigned)
std::pair< POS, POS > drop_position_limits (const Vehicle_node node) const
void erase (const Order &order)
Identifiers< size_t > feasable_orders () const
Order get_first_order () const
std::vector< General_vehicle_orders_t > get_postgres_result (int vid) const
Order get_worse_order (Identifiers< size_t > of_this_subset) const
bool has_order (const Order &order) const
bool insert (const Order &order)
Inserts an order.
POS insert_less_travel_time (const Vehicle_node &node, POS after_pos=0)
bool is_order_feasable (const Order &order) const
bool is_phony () const
const PD_Orders & orders () const
Identifiers< size_t > orders_in_vehicle () const
size_t orders_size () const
size_t pop_back ()
The order that is picked last is removed.
size_t pop_front ()
std::pair< POS, POS > position_limits (const Vehicle_node node) const
void push_back (const Order &order)
puts an order at the end of the truck
void push_front (const Order &order)
Puts an order at the end front of the truck.
bool semiLIFO (const Order &order)
Inserts an order In semi-Lifo order.
void set_compatibles (const PD_Orders &orders)
double speed () const
void swap (POS i, POS j)
Swap two nodes in the path.
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Cost cost () const
bool cost_compare (const Cost &, const Cost &) const
double duration () const
double total_wait_time () const
double total_travel_time () const
double total_service_time () const
double free_time () const
int twvTot () const
int cvTot () const
bool has_twv () const
bool has_cv () const
bool is_feasable () const
bool is_ok () const
Vehicle_node start_site () const
Vehicle_node end_site () const
double capacity () const
Evaluation
Path evaluation is done incrementally: from a given position to the end of the path, and intermediate values are cached on each node.
So, for example, changing the path at position 100: the evaluation function should be called as evaluate(100, maxcapacity) and from that position to the end of the path will be evaluated. None of the "unaffected" positions get reevaluated
void evaluate ()
Evaluate: Evaluate the whole path from the start.
void evaluate (POS from)
Evaluate: Evaluate a path from the given position.
accessors
std::deque< Vehicle_node > path () const
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
deque like functions
Returns
True if the operation was performed
Warning
Assertions are performed for out of range operations
no feasability nor time window or capacity violations checks are performed
Todo:
TODO more deque like functions here
void invariant () const
Invariant The path must:
void insert (POS pos, Vehicle_node node)
Insert node at pos position.
POS insert (std::pair< POS, POS > position_limits, const Vehicle_node &node)
Insert node in best position of the position_limits.
void push_back (const Vehicle_node &node)
Evaluated: push_back a node to the path.
void push_front (const Vehicle_node &node)
Evaluated: push_back a node to the path.
void erase (const Vehicle_node &node)
Erase node.id()
void erase (POS pos)
Erase node at pos from the path.
bool empty () const
return true when no nodes are in the truck
size_t size () const
return number of nodes in the truck
Cost cost () const
bool cost_compare (const Cost &, const Cost &) const
double duration () const
double total_wait_time () const
double total_travel_time () const
double total_service_time () const
double free_time () const
int twvTot () const
int cvTot () const
bool has_twv () const
bool has_cv () const
bool is_feasable () const
bool is_ok () const
Vehicle_node start_site () const
Vehicle_node end_site () const
double capacity () const
Evaluation
Path evaluation is done incrementally: from a given position to the end of the path, and intermediate values are cached on each node.
So, for example, changing the path at position 100: the evaluation function should be called as evaluate(100, maxcapacity) and from that position to the end of the path will be evaluated. None of the "unaffected" positions get reevaluated
void evaluate ()
Evaluate: Evaluate the whole path from the start.
void evaluate (POS from)
Evaluate: Evaluate a path from the given position.
accessors
std::deque< Vehicle_node > path () const
operators
std::string tau () const
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Static Public Member Functions
static Pgr_messages & msg ()
Access to the problem's message.
Static Public Attributes
static Pgr_pickDeliver * problem
Pointer to problem.
Protected Types
using difference_type = std::deque< Vehicle_node >::difference_type
typedef size_t POS
Protected Attributes
double cost
Identifiers< size_t > m_feasable_orders
orders that fit in the truck
PD_Orders m_orders
Identifiers< size_t > m_orders_in_vehicle
orders inserted in this vehicle
std::deque< Vehicle_node > m_path
Private Member Functions
POS getDropPosLowLimit (const Vehicle_node &node) const
POS getPosHighLimit (const Vehicle_node &node) const
POS getPosLowLimit (const Vehicle_node &node) const
Private Attributes
double m_capacity
double m_factor
int64_t m_id
size_t m_idx
double m_speed
Friends
class Initial_solution
class Optimize
Detailed Description
Definition at line 47 of file vehicle_pickDeliver.h.
Member Typedef Documentation
Cost
typedef std::tuple< int, int, size_t, double, double > vrprouting::vrp::Vehicle::Cost inherited
Definition at line 92 of file vehicle.h.
difference_type
using vrprouting::vrp::Vehicle::difference_type = std::deque<Vehicle_node>::difference_type protected inherited
Definition at line 77 of file vehicle.h.
POS
typedef size_t vrprouting::vrp::Vehicle::POS protected inherited
Definition at line 76 of file vehicle.h.
Constructor & Destructor Documentation
Vehicle_pickDeliver() [1/2]
vrprouting::vrp::Vehicle_pickDeliver::Vehicle_pickDeliver (size_t idx, int64_t id, const Vehicle_node & starting_site, const Vehicle_node & ending_site, double p_capacity, double p_speed, double factor)
Definition at line 80 of file vehicle_pickDeliver.cpp.
                        :
     Vehicle(idx, id, starting_site, ending_site, p_capacity, p_speed, factor),
     cost((std::numeric_limits<double>::max)()),
     m_orders_in_vehicle(),
     m_orders(),
     m_feasable_orders() {
 #if 0
         ENTERING();
 #endif
         invariant();
 #if 0
         EXITING();
 #endif
     }
References ENTERING, EXITING, and vrprouting::vrp::Vehicle::invariant().
Vehicle_pickDeliver() [2/2]
vrprouting::vrp::Vehicle_pickDeliver::Vehicle_pickDeliver (const Vehicle_pickDeliver &) default
Member Function Documentation
capacity()
double vrprouting::vrp::Vehicle::capacity () const inline inherited
Definition at line 287 of file vehicle.h.
 {return m_capacity;}
References vrprouting::vrp::Vehicle::m_capacity.
Referenced by vrprouting::vrp::Vehicle::Vehicle().
cost()
Vehicle::Cost vrprouting::vrp::Vehicle::cost () const inherited
Definition at line 177 of file vehicle.cpp.
                     {
     return std::make_tuple(
             twvTot(), cvTot(), m_path.size(),
             total_wait_time(), duration());
 }
References vrprouting::vrp::Vehicle::cvTot(), vrprouting::vrp::Vehicle::duration(), vrprouting::vrp::Vehicle::m_path, vrprouting::vrp::Vehicle::total_wait_time(), and vrprouting::vrp::Vehicle::twvTot().
Referenced by vrprouting::vrp::Vehicle::insert().
cost_compare()
bool vrprouting::vrp::Vehicle::cost_compare (const Cost & lhs, const Cost & rhs) const inherited
Definition at line 99 of file vehicle.cpp.
{
     /*
      * capacity violations
      */
     if (std::get<1>(lhs) < std::get<1>(rhs))
         return true;
     if (std::get<1>(lhs) > std::get<1>(rhs))
         return false;
     /*
      * time window violations
      */
     if (std::get<0>(lhs) < std::get<0>(rhs))
         return true;
     if (std::get<0>(lhs) > std::get<0>(rhs))
         return false;
     /*
      * waiting time
      */
     if (std::get<3>(lhs) < std::get<3>(rhs))
         return true;
     if (std::get<3>(lhs) > std::get<3>(rhs))
         return false;
     /*
      * duration
      */
     if (std::get<4>(lhs) < std::get<4>(rhs))
         return true;
     if (std::get<4>(lhs) > std::get<4>(rhs))
         return false;
     /*
      * truck size
      */
     if (std::get<2>(lhs) < std::get<2>(rhs))
         return true;
     if (std::get<2>(lhs) > std::get<2>(rhs))
         return false;
     return false;
 }
Referenced by vrprouting::vrp::Vehicle::insert().
cvTot()
int vrprouting::vrp::Vehicle::cvTot () const inline inherited
Definition at line 262 of file vehicle.h.
{
          return m_path.back().cvTot();
      }
References vrprouting::vrp::Vehicle::m_path.
Referenced by vrprouting::vrp::Vehicle::cost(), vrprouting::vrp::Vehicle::has_cv(), and vrprouting::vrp::Vehicle::tau().
deltaTime()
double vrprouting::vrp::Vehicle::deltaTime (const Vehicle_node & node, POS pos) const inherited
Definition at line 199 of file vehicle.cpp.
{
     /*
      * .... POS POS+1 ....
      * .... POS node POS+1 ....
      *
      */
     auto prev = m_path[pos-1];
     auto next = m_path[pos];
     auto original_time = next.travel_time();
     auto tt_p_n = prev.travel_time_to(node, speed());
     tt_p_n = node.is_early_arrival(prev.departure_time() + tt_p_n) ?
         node.closes() - prev.departure_time()
         : tt_p_n;
     auto tt_n_x = node.travel_time_to(next, speed());
     tt_p_n = next.is_early_arrival(
             prev.departure_time() + tt_p_n + node.service_time() + tt_n_x) ?
         next.closes() - (prev.departure_time() + tt_p_n + node.service_time())
         : tt_n_x;
     return (tt_p_n + tt_n_x) - original_time;
 }
References vrprouting::vrp::Tw_node::closes(), vrprouting::vrp::Tw_node::is_early_arrival(), vrprouting::vrp::Vehicle::m_path, vrprouting::vrp::Tw_node::service_time(), vrprouting::vrp::Vehicle::speed(), and vrprouting::vrp::Tw_node::travel_time_to().
Referenced by vrprouting::vrp::Vehicle::insert_less_travel_time().
do_while_feasable()
void vrprouting::vrp::Vehicle_pickDeliver::do_while_feasable (Initials_code kind, Identifiers< size_t > & unassigned, Identifiers< size_t > & assigned)
Definition at line 265 of file vehicle_pickDeliver.cpp.
{
     pgassert(is_feasable());
 #if 0
     msg.log << "unasigned" << unassigned << "\n";
     msg.log << "m_feasable_orders" << m_feasable_orders << "\n";
 #endif
     auto current_feasable = m_feasable_orders * unassigned;
     while (!current_feasable.empty()) {
 #if 0
         msg.log << "current_feasable" << current_feasable << "\n";
 #endif
         auto order = m_orders[current_feasable.front()];
         switch (kind) {
             case OnePerTruck:
                 push_back(order);
                 pgassert(is_feasable());
                 assigned += order.idx();
                 unassigned -= order.idx();
                 invariant();
                 return;
                 break;
             case FrontTruck:
                 push_front(order);
                 break;
             case BackTruck:
                 push_back(order);
                 break;
             case BestInsert:
                 insert(order);
                 break;
             case BestBack:
                 order = m_orders[m_orders.find_best_J(current_feasable)];
                 insert(order);
                 break;
             case BestFront:
                 order = m_orders[m_orders.find_best_I(current_feasable)];
                 insert(order);
                 break;
             case OneDepot:
                 semiLIFO(order);
                 break;
             default: pgassert(false);
         }
         if (orders_size() == 1 && !is_feasable()) {
             pgassert(false);
         }
         if (!is_feasable()) {
             erase(order);
         } else if (has_order(order)) {
             assigned += order.idx();
             unassigned -= order.idx();
             if (kind == BestBack) {
                 current_feasable = m_orders[order.idx()].subsetJ(
                         current_feasable);
             }
             if (kind == BestFront) {
                 current_feasable = m_orders[order.idx()].subsetI(
                         current_feasable);
             }
         }
         current_feasable -= order.idx();
         invariant();
     }
     pgassert(is_feasable());
     invariant();
 }
References vrprouting::vrp::BackTruck, vrprouting::vrp::BestBack, vrprouting::vrp::BestFront, vrprouting::vrp::BestInsert, erase(), vrprouting::vrp::PD_Orders::find_best_I(), vrprouting::vrp::PD_Orders::find_best_J(), vrprouting::vrp::FrontTruck, has_order(), insert(), vrprouting::vrp::Vehicle::invariant(), vrprouting::vrp::Vehicle::is_feasable(), vrprouting::Pgr_messages::log, m_feasable_orders, m_orders, vrprouting::vrp::Vehicle::msg(), vrprouting::vrp::OneDepot, vrprouting::vrp::OnePerTruck, orders_size(), pgassert, push_back(), push_front(), and semiLIFO().
drop_position_limits()
std::pair< size_t, size_t > vrprouting::vrp::Vehicle::drop_position_limits (const Vehicle_node node) const inherited
Definition at line 412 of file vehicle.cpp.
{
     POS high = getPosHighLimit(node);
     POS low = getDropPosLowLimit(node);
     return std::make_pair(low, high);
 }
References vrprouting::vrp::Vehicle::getDropPosLowLimit(), and vrprouting::vrp::Vehicle::getPosHighLimit().
Referenced by semiLIFO().
duration()
double vrprouting::vrp::Vehicle::duration () const inline inherited
Definition at line 244 of file vehicle.h.
{
          return m_path.back().departure_time();
      }
References vrprouting::vrp::Vehicle::m_path.
Referenced by vrprouting::vrp::Vehicle::cost(), vrprouting::vrp::Vehicle::free_time(), get_worse_order(), insert(), and vrprouting::vrp::Vehicle::tau().
empty()
bool vrprouting::vrp::Vehicle::empty () const inherited
return true when no nodes are in the truck
True: S E
False: S <nodes> E
Definition at line 365 of file vehicle.cpp.
                      {
     invariant();
     return m_path.size() <= 2;
 }
References vrprouting::vrp::Vehicle::invariant(), and vrprouting::vrp::Vehicle::m_path.
Referenced by get_first_order(), get_worse_order(), vrprouting::vrp::Optimize::move_order(), pop_back(), and pop_front().
end_site()
Vehicle_node vrprouting::vrp::Vehicle::end_site () const inline inherited
Definition at line 281 of file vehicle.h.
{
          return m_path.back();
      }
References vrprouting::vrp::Vehicle::m_path.
Referenced by vrprouting::vrp::Vehicle::is_ok().
erase() [1/3]
void vrprouting::vrp::Vehicle_pickDeliver::erase (const Order & order)
Definition at line 343 of file vehicle_pickDeliver.cpp.
{
     invariant();
     pgassert(has_order(order));
     Vehicle::erase(order.pickup());
     Vehicle::erase(order.delivery());
     m_orders_in_vehicle -= order.idx();
     invariant();
     pgassert(!has_order(order));
 }
References vrprouting::vrp::Order::delivery(), vrprouting::vrp::Vehicle::erase(), has_order(), vrprouting::Identifier::idx(), vrprouting::vrp::Vehicle::invariant(), m_orders_in_vehicle, pgassert, and vrprouting::vrp::Order::pickup().
Referenced by do_while_feasable(), vrprouting::vrp::Optimize::move_order(), pop_back(), pop_front(), and vrprouting::vrp::Optimize::swap_order().
erase() [2/3]
void vrprouting::vrp::Vehicle::erase (const Vehicle_node & node) inherited
Erase node.id()
Note
start and ending nodes cannot be erased
Numbers are positions before: S .... node.id() .... E after: S .... .... E
Todo:
TODO evaluate with matrix also
Definition at line 249 of file vehicle.cpp.
{
     invariant();
     POS pos = 0;
     for ( ; pos < m_path.size() ; ++pos) {
         if (node.idx() == m_path[pos].idx())
             break;
     }
     erase(pos);
     evaluate(pos);
     invariant();
 }
References vrprouting::vrp::Vehicle::evaluate(), vrprouting::Identifier::idx(), vrprouting::vrp::Vehicle::invariant(), and vrprouting::vrp::Vehicle::m_path.
Referenced by erase(), insert(), vrprouting::vrp::Vehicle::pop_back(), vrprouting::vrp::Vehicle::pop_front(), and semiLIFO().
erase() [3/3]
void vrprouting::vrp::Vehicle::erase (POS pos) inherited
Erase node at pos from the path.
Note
start and ending nodes cannot be erased
Numbers are positions before: S 1 2 3 4 5 6 pos 8 9 E after: S 1 2 3 4 5 6 8 9 E
Parameters
[in] pos to be erased.
Definition at line 325 of file vehicle.cpp.
                      {
     invariant();
     pgassert(m_path.size() > 2);
     pgassert(at < m_path.size());
     pgassert(!m_path[at].is_start());
     pgassert(!m_path[at].is_end());
     m_path.erase(m_path.begin() + static_cast<difference_type>(at));
     evaluate(at);
     invariant();
 }
References vrprouting::vrp::Vehicle::evaluate(), vrprouting::vrp::Vehicle::invariant(), vrprouting::vrp::Vehicle::m_path, and pgassert.
evaluate() [1/2]
void vrprouting::vrp::Vehicle::evaluate () inherited
Evaluate: Evaluate the whole path from the start.
Definition at line 356 of file vehicle.cpp.
                   {
     invariant();
     evaluate(0);
     invariant();
 }
References vrprouting::vrp::Vehicle::invariant().
Referenced by vrprouting::vrp::Vehicle::erase(), vrprouting::vrp::Vehicle::insert(), push_back(), push_front(), vrprouting::vrp::Vehicle::swap(), and vrprouting::vrp::Vehicle::Vehicle().
evaluate() [2/2]
void vrprouting::vrp::Vehicle::evaluate (POS from) inherited
Evaluate: Evaluate a path from the given position.
Parameters
[in] from The starting position in the path for evaluation to the end of the path.
Definition at line 377 of file vehicle.cpp.
{
     invariant();
     // preconditions
     pgassert(from < m_path.size());
     auto node = m_path.begin() + static_cast<difference_type>(from);
     while (node != m_path.end()) {
         if (node == m_path.begin()) {
             node->evaluate(m_capacity);
         } else {
             node->evaluate(*(node - 1), m_capacity, speed());
         }
         ++node;
     }
     invariant();
 }
References vrprouting::vrp::Vehicle::invariant(), vrprouting::vrp::Vehicle::m_capacity, vrprouting::vrp::Vehicle::m_path, pgassert, and vrprouting::vrp::Vehicle::speed().
feasable_orders()
Identifiers<size_t> vrprouting::vrp::Vehicle_pickDeliver::feasable_orders () const inline
Definition at line 75 of file vehicle_pickDeliver.h.
 {return m_feasable_orders;}
References m_feasable_orders.
free_time()
double vrprouting::vrp::Vehicle::free_time () const inline inherited
Definition at line 256 of file vehicle.h.
{
          return total_wait_time() + (m_path[0].closes() - duration());
      }
References vrprouting::vrp::Vehicle::duration(), vrprouting::vrp::Vehicle::m_path, and vrprouting::vrp::Vehicle::total_wait_time().
get_first_order()
Order vrprouting::vrp::Vehicle_pickDeliver::get_first_order () const
Definition at line 73 of file vehicle_pickDeliver.cpp.
{
     invariant();
     pgassert(!empty());
     return m_orders[m_path[1].idx()];
 }
References vrprouting::vrp::Vehicle::empty(), vrprouting::vrp::Vehicle::invariant(), m_orders, vrprouting::vrp::Vehicle::m_path, and pgassert.
get_postgres_result()
std::vector< General_vehicle_orders_t > vrprouting::vrp::Vehicle::get_postgres_result (int vid) const inherited
Definition at line 146 of file vehicle.cpp.
{
     std::vector<General_vehicle_orders_t> result;
     /* postgres numbering starts with 1 */
     int stop_seq(1);
     msg().log << "getting solution: " << tau() << "\n";
     for (const auto &p_stop : m_path) {
         General_vehicle_orders_t data = {
             vid,
             id(),
             stop_seq,
             /* order_id
              * The order_id is invalid for stops type 0 and 5
              */
             (p_stop.type() == 0 || p_stop.type() == 5)? -1 : p_stop.order(),
             p_stop.id(),
             p_stop.type(),
             p_stop.cargo(),
             p_stop.travel_time(),
             p_stop.arrival_time(),
             p_stop.wait_time(),
             p_stop.service_time(),
             p_stop.departure_time()};
         result.push_back(data);
         ++stop_seq;
     }
     return result;
 }
References vrprouting::Identifier::id(), vrprouting::Pgr_messages::log, vrprouting::vrp::Vehicle::m_path, vrprouting::vrp::Vehicle::msg(), and vrprouting::vrp::Vehicle::tau().
get_worse_order()
Order vrprouting::vrp::Vehicle_pickDeliver::get_worse_order (Identifiers< size_t > of_this_subset) const
Definition at line 47 of file vehicle_pickDeliver.cpp.
{
     invariant();
     pgassert(!empty());
     // auto orders(of_this_subset);
     auto worse_order(m_orders[*orders.begin()]);
     auto delta_duration((std::numeric_limits<double>::max)());
     auto curr_duration(duration());
     while (!orders.empty()) {
         auto truck(*this);
         auto order = m_orders[*orders.begin()];
         pgassert(truck.has_order(order));
         orders -= order.idx();
         truck.erase(order);
         auto delta = truck.duration() - curr_duration;
         if (delta < delta_duration) {
             worse_order = order;
             delta_duration = delta;
         }
     }
     return worse_order;
 }
References vrprouting::vrp::PD_Orders::begin(), vrprouting::vrp::Vehicle::duration(), vrprouting::vrp::Vehicle::empty(), vrprouting::vrp::Vehicle::invariant(), m_orders, orders(), and pgassert.
getDropPosLowLimit()
size_t vrprouting::vrp::Vehicle::getDropPosLowLimit (const Vehicle_node & node) const private inherited
Definition at line 433 of file vehicle.cpp.
{
     invariant();
     POS low = 0;
     POS high = m_path.size();
     POS low_limit = high;
     /* J == m_path[low_limit - 1] */
     while (low_limit > low
             && m_path[low_limit - 1].is_compatible_IJ(nodeI, speed())
             && !m_path[low_limit - 1].is_pickup()) {
         --low_limit;
     }
     invariant();
     return low_limit;
 }
References vrprouting::vrp::Vehicle::invariant(), vrprouting::vrp::Vehicle::m_path, and vrprouting::vrp::Vehicle::speed().
Referenced by vrprouting::vrp::Vehicle::drop_position_limits().
getPosHighLimit()
size_t vrprouting::vrp::Vehicle::getPosHighLimit (const Vehicle_node & node) const private inherited
Definition at line 498 of file vehicle.cpp.
{
     invariant();
     POS low = 0;
     POS high = m_path.size();
     POS high_limit = low;
     /* I == m_path[high_limit] */
     while (high_limit < high
             && nodeJ.is_compatible_IJ(m_path[high_limit], speed())) {
         ++high_limit;
     }
     invariant();
     return high_limit;
 }
References vrprouting::vrp::Vehicle::invariant(), vrprouting::vrp::Tw_node::is_compatible_IJ(), vrprouting::vrp::Vehicle::m_path, and vrprouting::vrp::Vehicle::speed().
Referenced by vrprouting::vrp::Vehicle::drop_position_limits(), and vrprouting::vrp::Vehicle::position_limits().
getPosLowLimit()
size_t vrprouting::vrp::Vehicle::getPosLowLimit (const Vehicle_node & node) const private inherited
Definition at line 466 of file vehicle.cpp.
{
     invariant();
     POS low = 0;
     POS high = m_path.size();
     POS low_limit = high;
     /* J == m_path[low_limit - 1] */
     while (low_limit > low
             && m_path[low_limit - 1].is_compatible_IJ(nodeI, speed())) {
         --low_limit;
     }
     invariant();
     return low_limit;
 }
References vrprouting::vrp::Vehicle::invariant(), vrprouting::vrp::Vehicle::m_path, and vrprouting::vrp::Vehicle::speed().
Referenced by vrprouting::vrp::Vehicle::position_limits().
has_cv()
bool vrprouting::vrp::Vehicle::has_cv () const inline inherited
Definition at line 268 of file vehicle.h.
{
          return cvTot() != 0;
      }
References vrprouting::vrp::Vehicle::cvTot().
Referenced by insert(), vrprouting::vrp::Vehicle::is_feasable(), push_back(), push_front(), and semiLIFO().
has_order()
bool vrprouting::vrp::Vehicle_pickDeliver::has_order (const Order & order) const
Definition at line 105 of file vehicle_pickDeliver.cpp.
{
     return m_orders_in_vehicle.has(order.idx());
 }
References Identifiers< T >::has(), vrprouting::Identifier::idx(), and m_orders_in_vehicle.
Referenced by do_while_feasable(), erase(), insert(), vrprouting::vrp::Optimize::move_order(), push_back(), push_front(), semiLIFO(), vrprouting::vrp::Optimize::swap_order(), and vrprouting::vrp::Optimize::swap_worse().
has_twv()
bool vrprouting::vrp::Vehicle::has_twv () const inline inherited
Definition at line 265 of file vehicle.h.
{
          return twvTot() != 0;
      }
References vrprouting::vrp::Vehicle::twvTot().
Referenced by vrprouting::vrp::Vehicle::is_feasable(), and semiLIFO().
id()
int64_t vrprouting::Identifier::id () const inherited
get the original id
Definition at line 42 of file identifier.cpp.
                      {
     return m_id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::vrp::Dnode::distance(), vrprouting::vrp::Vehicle::get_postgres_result(), vrprouting::vrp::Vehicle::is_phony(), vrprouting::vrp::operator<<(), vrprouting::operator<<(), vrprouting::vrp::Node::operator==(), vrprouting::vrp::Base_node::operator==(), vrprouting::vrp::Dnode::operator==(), vrprouting::vrp::Tw_node::operator==(), vrprouting::vrp::Node::print(), vrprouting::vrp::Vehicle::tau(), and vrprouting::vrp::Vehicle::Vehicle().
idx()
size_t vrprouting::Identifier::idx () const inherited
get the internal index
Definition at line 37 of file identifier.cpp.
                       {
     return m_idx;
 }
References vrprouting::Identifier::m_idx.
Referenced by erase(), vrprouting::vrp::Vehicle::erase(), vrprouting::vrp::Fleet::get_truck(), has_order(), insert(), vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::operator<<(), vrprouting::operator<<(), vrprouting::vrp::Node::operator==(), vrprouting::vrp::Base_node::operator==(), vrprouting::vrp::Dnode::operator==(), vrprouting::vrp::Tw_node::operator==(), vrprouting::vrp::Node::print(), push_back(), push_front(), semiLIFO(), vrprouting::vrp::Order::set_compatibles(), vrprouting::vrp::Vehicle::tau(), vrprouting::vrp::Tw_node::travel_time_to(), and vrprouting::vrp::Vehicle::Vehicle().
insert() [1/3]
bool vrprouting::vrp::Vehicle_pickDeliver::insert (const Order & order)
Inserts an order.
Precondition: !has_order(order)
Postcondition: has_order(order) !has_cv();
Before: S <nodes> E
  After: S ....P .... D .... E
push_back is performed when
pickup
Can generate time window violation No capacity violation
Definition at line 111 of file vehicle_pickDeliver.cpp.
{
     invariant();
     pgassert(!has_order(order));
     auto pick_pos(position_limits(order.pickup()));
     auto deliver_pos(position_limits(order.delivery()));
 #ifndef NDEBUG
     std::ostringstream err_log;
     err_log << "\n\tpickup limits (low, high) = ("
         << pick_pos.first << ", "
         << pick_pos.second << ") "
         << "\n\tdeliver limits (low, high) = ("
         << deliver_pos.first << ", "
         << deliver_pos.second << ") "
         << "\noriginal" << tau();
 #endif
     if (pick_pos.second < pick_pos.first) {
         /*
          *  pickup generates twv evrywhere
          */
         return false;
     }
     if (deliver_pos.second < deliver_pos.first) {
         /*
          *  delivery generates twv evrywhere
          */
         return false;
     }
     /*
      * Because delivery positions were estimated without
      * the pickup:
      *   - increase the upper limit position estimation
      */
     ++deliver_pos.first;
     ++deliver_pos.second;
     auto d_pos_backup(deliver_pos);
     auto best_pick_pos = m_path.size();
     auto best_deliver_pos = m_path.size() + 1;
     auto current_duration(duration());
     auto min_delta_duration = (std::numeric_limits<double>::max)();
     auto found(false);
     pgassertwm(!has_order(order), err_log.str());
     while (pick_pos.first <= pick_pos.second) {
 #ifndef NDEBUG
         err_log << "\n\tpickup cycle limits (low, high) = ("
             << pick_pos.first << ", "
             << pick_pos.second << ") ";
 #endif
         Vehicle::insert(pick_pos.first, order.pickup());
 #ifndef NDEBUG
         err_log << "\npickup inserted: " << tau();
 #endif
         if (deliver_pos.first <= pick_pos.first) deliver_pos.first = pick_pos.first + 1;
         while (deliver_pos.first <= deliver_pos.second) {
             Vehicle::insert(deliver_pos.first, order.delivery());
             m_orders_in_vehicle += order.idx();
             pgassertwm(has_order(order), err_log.str());
 #ifndef NDEBUG
             err_log << "\ndelivery inserted: " << tau();
 #endif
             if (is_feasable()) {
                 pgassert(is_feasable());
                 auto delta_duration = duration() - current_duration;
                 if (delta_duration < min_delta_duration) {
 #ifndef NDEBUG
                     err_log << "\nsuccess" << tau();
 #endif
                     min_delta_duration = delta_duration;
                     best_pick_pos = pick_pos.first;
                     best_deliver_pos = deliver_pos.first;
                     found = true;
                 }
             }
             Vehicle::erase(deliver_pos.first);
 #ifndef NDEBUG
             err_log << "\ndelivery erased: " << tau();
 #endif
             ++deliver_pos.first;
         }
         Vehicle::erase(pick_pos.first);
 #ifndef NDEBUG
         err_log << "\npickup erased: " << tau();
 #endif
         m_orders_in_vehicle -= order.idx();
         pgassertwm(!has_order(order), err_log.str());
         deliver_pos = d_pos_backup;
 #ifndef NDEBUG
         err_log << "\n\trestoring deliver limits (low, high) = ("
             << deliver_pos.first << ", "
             << deliver_pos.second << ") ";
 #endif
         ++pick_pos.first;
     }
     pgassertwm(!has_order(order), err_log.str());
     if (!found) {
         /* order causes twv or cv */
         return false;
     }
     Vehicle::insert(best_pick_pos, order.pickup());
     Vehicle::insert(best_deliver_pos, order.delivery());
     m_orders_in_vehicle += order.idx();
     pgassertwm(is_feasable(), err_log.str());
     pgassertwm(has_order(order), err_log.str());
     pgassertwm(!has_cv(), err_log.str());
     invariant();
     return true;
 }
References vrprouting::vrp::Order::delivery(), vrprouting::vrp::Vehicle::duration(), vrprouting::vrp::Vehicle::erase(), vrprouting::vrp::Vehicle::has_cv(), has_order(), vrprouting::Identifier::idx(), vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::Vehicle::invariant(), vrprouting::vrp::Vehicle::is_feasable(), m_orders_in_vehicle, vrprouting::vrp::Vehicle::m_path, pgassert, pgassertwm, vrprouting::vrp::Order::pickup(), vrprouting::vrp::Vehicle::position_limits(), and vrprouting::vrp::Vehicle::tau().
Referenced by do_while_feasable(), vrprouting::vrp::Optimize::move_order(), and vrprouting::vrp::Optimize::swap_order().
insert() [2/3]
void vrprouting::vrp::Vehicle::insert (POS pos, Vehicle_node node) inherited
Insert node at pos position.
Parameters
[in] pos The position that the node should be inserted.
[in] node The node to insert.
Definition at line 185 of file vehicle.cpp.
{
     invariant();
     pgassert(at <= m_path.size());
     m_path.insert(m_path.begin() + static_cast<difference_type>(at), node);
     evaluate(at);
     pgassert(at < m_path.size());
     pgassert(m_path[at].idx() == node.idx());
     invariant();
 }
References vrprouting::vrp::Vehicle::evaluate(), vrprouting::Identifier::idx(), vrprouting::vrp::Vehicle::invariant(), vrprouting::vrp::Vehicle::m_path, and pgassert.
Referenced by insert(), vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::Vehicle::insert_less_travel_time(), vrprouting::vrp::Vehicle::push_back(), vrprouting::vrp::Vehicle::push_front(), and semiLIFO().
insert() [3/3]
size_t vrprouting::vrp::Vehicle::insert (std::pair< POS, POS > position_limits, const Vehicle_node & node) inherited
Insert node in best position of the position_limits.
Parameters
[in] position_limits
[in] node The node to insert
Returns
position where it was inserted
Definition at line 65 of file vehicle.cpp.
{
     invariant();
     pgassert(position_limits.first <= m_path.size());
     pgassert(position_limits.second <= m_path.size());
     auto low = position_limits.first;
     auto high = position_limits.second;
     auto best = low;
     insert(low, node);
     Vehicle::Cost best_cost(cost());
     while (low < high) {
         swap(low, low + 1);
         ++low;
         if (cost_compare(best_cost, cost())) {
             best_cost = cost();
             best = low;
         }
     }
     return best;
     pgassert(best < m_path.size());
     pgassert(m_path[best].idx() == node.idx());
     invariant();
 }
References vrprouting::vrp::Vehicle::cost(), vrprouting::vrp::Vehicle::cost_compare(), vrprouting::Identifier::idx(), vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::Vehicle::invariant(), vrprouting::vrp::Vehicle::m_path, pgassert, vrprouting::vrp::Vehicle::position_limits(), and vrprouting::vrp::Vehicle::swap().
insert_less_travel_time()
size_t vrprouting::vrp::Vehicle::insert_less_travel_time (const Vehicle_node & node, POS after_pos = 0) inherited
Definition at line 226 of file vehicle.cpp.
{
     invariant();
     double min_delta = (std::numeric_limits<double>::max)();
     POS min_pos = after_pos;
     for (POS pos = after_pos; pos < m_path.size(); ++pos) {
         if (!m_path[pos].is_start()) {
             auto tt = deltaTime(node, pos);
             if (tt < min_delta) {
                 min_delta = tt;
                 min_pos = pos;
             }
         }
     }
     insert(min_pos, node);
     invariant();
     return min_pos;
 }
References vrprouting::vrp::Vehicle::deltaTime(), vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::Vehicle::invariant(), and vrprouting::vrp::Vehicle::m_path.
invariant()
void vrprouting::vrp::Vehicle::invariant () const inherited
Invariant The path must:
have at least 2 nodes
first node of the path must be Start node
last node of the path must be End node
path: S ..... E
Definition at line 58 of file vehicle.cpp.
{
     pgassert(m_path.size() >= 2);
     pgassert(m_path.front().is_start());
     pgassert(m_path.back().is_end());
 }
References vrprouting::vrp::Vehicle::m_path, and pgassert.
Referenced by do_while_feasable(), vrprouting::vrp::Vehicle::empty(), erase(), vrprouting::vrp::Vehicle::erase(), vrprouting::vrp::Vehicle::evaluate(), get_first_order(), get_worse_order(), vrprouting::vrp::Vehicle::getDropPosLowLimit(), vrprouting::vrp::Vehicle::getPosHighLimit(), vrprouting::vrp::Vehicle::getPosLowLimit(), insert(), vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::Vehicle::insert_less_travel_time(), vrprouting::vrp::operator<(), vrprouting::vrp::operator<<(), vrprouting::vrp::Vehicle::path(), vrprouting::vrp::Vehicle::pop_back(), pop_back(), vrprouting::vrp::Vehicle::pop_front(), pop_front(), push_back(), vrprouting::vrp::Vehicle::push_back(), push_front(), vrprouting::vrp::Vehicle::push_front(), semiLIFO(), vrprouting::vrp::Vehicle::size(), vrprouting::vrp::Vehicle::swap(), vrprouting::vrp::Vehicle::Vehicle(), and Vehicle_pickDeliver().
is_feasable()
bool vrprouting::vrp::Vehicle::is_feasable () const inline inherited
Definition at line 272 of file vehicle.h.
{
          return !(has_twv() ||  has_cv());
      }
References vrprouting::vrp::Vehicle::has_cv(), and vrprouting::vrp::Vehicle::has_twv().
Referenced by do_while_feasable(), insert(), semiLIFO(), and vrprouting::vrp::Optimize::swap_order().
is_ok()
bool vrprouting::vrp::Vehicle::is_ok () const inherited
Definition at line 516 of file vehicle.cpp.
                      {
     pgassert((m_path.front().opens() <= m_path.front().closes())
         && (m_path.back().opens() <= m_path.back().closes())
         && (m_capacity > 0));
     return (start_site().opens() <= start_site().closes())
         && (end_site().opens() <= end_site().closes())
         && (m_capacity > 0);
 }
References vrprouting::vrp::Tw_node::closes(), vrprouting::vrp::Vehicle::end_site(), vrprouting::vrp::Vehicle::m_capacity, vrprouting::vrp::Vehicle::m_path, vrprouting::vrp::Tw_node::opens(), pgassert, and vrprouting::vrp::Vehicle::start_site().
is_order_feasable()
bool vrprouting::vrp::Vehicle_pickDeliver::is_order_feasable (const Order & order) const
Definition at line 421 of file vehicle_pickDeliver.cpp.
{
     auto test_truck =  *this;
     test_truck.push_back(order);
     return test_truck.is_feasable();
 }
Referenced by set_compatibles().
is_phony()
bool vrprouting::vrp::Vehicle::is_phony () const inline inherited
Definition at line 107 of file vehicle.h.
 {return id() < 0;}
References vrprouting::Identifier::id().
Referenced by vrprouting::vrp::Optimize::move_order().
msg()
Pgr_messages & vrprouting::vrp::Vehicle::msg () static inherited
Access to the problem's message.
Returns
reference to the problem's message
Definition at line 51 of file vehicle.cpp.
              {
     return problem->msg;
 }
References vrprouting::vrp::Pgr_pickDeliver::msg, and vrprouting::vrp::Vehicle::problem.
Referenced by do_while_feasable(), vrprouting::vrp::Vehicle::get_postgres_result(), and vrprouting::vrp::Vehicle::Vehicle().
orders()
const PD_Orders& vrprouting::vrp::Vehicle_pickDeliver::orders () const inline
Definition at line 77 of file vehicle_pickDeliver.h.
 {return m_orders;}
References m_orders.
Referenced by get_worse_order(), set_compatibles(), and vrprouting::vrp::Optimize::swap_worse().
orders_in_vehicle()
Identifiers<size_t> vrprouting::vrp::Vehicle_pickDeliver::orders_in_vehicle () const inline
Definition at line 79 of file vehicle_pickDeliver.h.
 {return m_orders_in_vehicle;}
References m_orders_in_vehicle.
Referenced by vrprouting::vrp::Optimize::move_reduce_cost(), and vrprouting::vrp::Optimize::swap_worse().
orders_size()
size_t vrprouting::vrp::Vehicle_pickDeliver::orders_size () const inline
Definition at line 78 of file vehicle_pickDeliver.h.
 {return m_orders_in_vehicle.size();}
References m_orders_in_vehicle, and Identifiers< T >::size().
Referenced by do_while_feasable().
path()
std::deque< Vehicle_node > vrprouting::vrp::Vehicle::path () const inherited
Definition at line 398 of file vehicle.cpp.
                     {
     invariant();
     return m_path;
 }
References vrprouting::vrp::Vehicle::invariant(), and vrprouting::vrp::Vehicle::m_path.
Referenced by vrprouting::vrp::operator<<().
pop_back()
size_t vrprouting::vrp::Vehicle_pickDeliver::pop_back ()
The order that is picked last is removed.
Returns
id of the removed order
Definition at line 359 of file vehicle_pickDeliver.cpp.
{
     invariant();
     pgassert(!empty());
     auto pick_itr = m_path.rbegin();
     while (pick_itr != m_path.rend() &&  !pick_itr->is_pickup()) {
         ++pick_itr;
     }
     pgassert(pick_itr->is_pickup());
     auto deleted_pick_idx = pick_itr->idx();
     for (const auto &o : m_orders) {
         if (o.pickup().idx() == deleted_pick_idx) {
             erase(o);
             invariant();
             return o.idx();
         }
     }
     pgassert(false);
     return 0;
 }
References vrprouting::vrp::Vehicle::empty(), erase(), vrprouting::vrp::Vehicle::invariant(), m_orders, vrprouting::vrp::Vehicle::m_path, and pgassert.
pop_front()
size_t vrprouting::vrp::Vehicle_pickDeliver::pop_front ()
Definition at line 386 of file vehicle_pickDeliver.cpp.
{
     invariant();
     pgassert(!empty());
     auto pick_itr = m_path.begin();
     while (pick_itr != m_path.end() &&  !pick_itr->is_pickup()) {
         ++pick_itr;
     }
     pgassert(pick_itr->is_pickup());
     auto deleted_pick_idx = pick_itr->idx();
     for (const auto &o : m_orders) {
         if (o.pickup().idx() == deleted_pick_idx) {
             erase(o);
             invariant();
             return o.idx();
         }
     }
     pgassert(false);
     return 0;
 }
References vrprouting::vrp::Vehicle::empty(), erase(), vrprouting::vrp::Vehicle::invariant(), m_orders, vrprouting::vrp::Vehicle::m_path, and pgassert.
position_limits()
std::pair< size_t, size_t > vrprouting::vrp::Vehicle::position_limits (const Vehicle_node node) const inherited
Definition at line 405 of file vehicle.cpp.
{
     POS high = getPosHighLimit(node);
     POS low = getPosLowLimit(node);
     return std::make_pair(low, high);
 }
References vrprouting::vrp::Vehicle::getPosHighLimit(), and vrprouting::vrp::Vehicle::getPosLowLimit().
Referenced by insert(), and vrprouting::vrp::Vehicle::insert().
push_back() [1/2]
void vrprouting::vrp::Vehicle_pickDeliver::push_back (const Order & order)
puts an order at the end of the truck
Precondition: !has_order(order)
Postcondition: has_order(order) !has_cv();
Before: S <nodes> E
  After: S <nodes> P D E
Can generate time window violation No capacity violation
Definition at line 229 of file vehicle_pickDeliver.cpp.
{
     invariant();
     pgassert(!has_order(order));
     m_orders_in_vehicle += order.idx();
     m_path.insert(m_path.end() - 1, order.pickup());
     m_path.insert(m_path.end() - 1, order.delivery());
     evaluate(m_path.size() - 3);
     pgassert(has_order(order));
 #if 0
     pgassert(!has_cv());
 #endif
     invariant();
 }
References vrprouting::vrp::Order::delivery(), vrprouting::vrp::Vehicle::evaluate(), vrprouting::vrp::Vehicle::has_cv(), has_order(), vrprouting::Identifier::idx(), vrprouting::vrp::Vehicle::invariant(), m_orders_in_vehicle, vrprouting::vrp::Vehicle::m_path, pgassert, and vrprouting::vrp::Order::pickup().
Referenced by do_while_feasable().
push_back() [2/2]
void vrprouting::vrp::Vehicle::push_back (const Vehicle_node & node) inherited
Evaluated: push_back a node to the path.
before: S <nodes> E
after: S <nodes> n E
Parameters
[in] node to be push_back.
Definition at line 291 of file vehicle.cpp.
{
     invariant();
     /* insert evaluates */
     insert(m_path.size() - 1, node);
     invariant();
 }
References vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::Vehicle::invariant(), and vrprouting::vrp::Vehicle::m_path.
push_front() [1/2]
void vrprouting::vrp::Vehicle_pickDeliver::push_front (const Order & order)
Puts an order at the end front of the truck.
Precondition: !has_order(order)
Postcondition: has_order(order) !has_cv();
Before: S <nodes> E
  After: S P D <nodes> E
Can generate time window violation No capacity violation
Definition at line 247 of file vehicle_pickDeliver.cpp.
{
     invariant();
     pgassert(!has_order(order));
     m_orders_in_vehicle += order.idx();
     m_path.insert(m_path.begin() + 1, order.delivery());
     m_path.insert(m_path.begin() + 1, order.pickup());
     evaluate(1);
     pgassert(has_order(order));
 #if 0
     pgassert(!has_cv());
 #endif
     invariant();
 }
References vrprouting::vrp::Order::delivery(), vrprouting::vrp::Vehicle::evaluate(), vrprouting::vrp::Vehicle::has_cv(), has_order(), vrprouting::Identifier::idx(), vrprouting::vrp::Vehicle::invariant(), m_orders_in_vehicle, vrprouting::vrp::Vehicle::m_path, pgassert, and vrprouting::vrp::Order::pickup().
Referenced by do_while_feasable().
push_front() [2/2]
void vrprouting::vrp::Vehicle::push_front (const Vehicle_node & node) inherited
Evaluated: push_back a node to the path.
before: S <nodes> E
after: S n <nodes> E
Parameters
[in] node to be push_back.
Definition at line 274 of file vehicle.cpp.
{
     invariant();
     /* insert evaluates */
     insert(1, node);
     invariant();
 }
References vrprouting::vrp::Vehicle::insert(), and vrprouting::vrp::Vehicle::invariant().
reset_id()
void vrprouting::Identifier::reset_id (int64_t _id) inherited
change the original id
Definition at line 47 of file identifier.cpp.
{
     m_id = _id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::vrp::Tw_node::Tw_node().
semiLIFO()
bool vrprouting::vrp::Vehicle_pickDeliver::semiLIFO (const Order & order)
Inserts an order In semi-Lifo order.
Precondition: !has_order(order)
Postcondition: has_order(order) !has_cv();
Before: S .... (P1 ....... P2) ... D2 .... D1 .... E
 After: S .... (P .. P1 .. P2) ... D2 .. D .. D1 .... E
push_back is performed when
drop generates a time window violation
Can generate time window violation No capacity violation
Definition at line 428 of file vehicle_pickDeliver.cpp.
{
     invariant();
     pgassert(!has_order(order));
     /*
      * Insert pick up as first picked
      */
     Vehicle::insert(1, order.pickup());
     auto deliver_pos(drop_position_limits(order.delivery()));
     /*
      * delivery generates twv in all positions
      */
     if (deliver_pos.second < deliver_pos.first) {
         /*
          * Remove inserted pickup
          */
         Vehicle::erase(1);
         invariant();
         return false;
     }
     pgassert(!has_order(order));
     while (deliver_pos.first <= deliver_pos.second) {
         Vehicle::insert(deliver_pos.second, order.delivery());
         if (is_feasable() && !m_path[deliver_pos.second + 1].is_pickup()) {
             /*
              * Found a position to insert the delivery
              */
             m_orders_in_vehicle += order.idx();
             /*
              * There is one more order in the vehicle
              */
             pgassert(has_order(order));
             pgassert(is_feasable());
             pgassert(!has_cv());
             pgassert(!has_twv());
             pgassert(has_order(order));
             invariant();
             return true;
         }
         /*
          * This position in path is not suitable
          */
         Vehicle::erase(deliver_pos.second);
         /*
          * got to next position
          */
         --deliver_pos.second;
     }
     /*
      * Order could not be inserted
      */
     Vehicle::erase(1);
     pgassert(!has_order(order));
     invariant();
     return false;
 }
References vrprouting::vrp::Order::delivery(), vrprouting::vrp::Vehicle::drop_position_limits(), vrprouting::vrp::Vehicle::erase(), vrprouting::vrp::Vehicle::has_cv(), has_order(), vrprouting::vrp::Vehicle::has_twv(), vrprouting::Identifier::idx(), vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::Vehicle::invariant(), vrprouting::vrp::Vehicle::is_feasable(), m_orders_in_vehicle, vrprouting::vrp::Vehicle::m_path, pgassert, and vrprouting::vrp::Order::pickup().
Referenced by do_while_feasable(), vrprouting::vrp::Optimize::move_order(), and vrprouting::vrp::Optimize::swap_order().
set_compatibles()
void vrprouting::vrp::Vehicle_pickDeliver::set_compatibles (const PD_Orders & orders)
Definition at line 412 of file vehicle_pickDeliver.cpp.
{
     m_orders = orders;
     for (const auto &o : orders) {
         if (is_order_feasable(o)) m_feasable_orders += o.idx();
     }
     m_orders.set_compatibles(speed());
 }
References is_order_feasable(), m_feasable_orders, m_orders, orders(), vrprouting::vrp::PD_Orders::set_compatibles(), and vrprouting::vrp::Vehicle::speed().
size()
size_t vrprouting::vrp::Vehicle::size () const inherited
return number of nodes in the truck
True: S E
False: S <nodes> E
Definition at line 371 of file vehicle.cpp.
                     {
     invariant();
     return m_path.size() - 2;
 }
References vrprouting::vrp::Vehicle::invariant(), and vrprouting::vrp::Vehicle::m_path.
Referenced by vrprouting::vrp::Optimize::move_order().
speed()
double vrprouting::vrp::Vehicle::speed () const inherited
Definition at line 600 of file vehicle.cpp.
                      {
     return m_speed/m_factor;
 }
References vrprouting::vrp::Vehicle::m_factor, and vrprouting::vrp::Vehicle::m_speed.
Referenced by vrprouting::vrp::Vehicle::deltaTime(), vrprouting::vrp::Vehicle::evaluate(), vrprouting::vrp::Vehicle::getDropPosLowLimit(), vrprouting::vrp::Vehicle::getPosHighLimit(), vrprouting::vrp::Vehicle::getPosLowLimit(), vrprouting::vrp::operator<<(), and set_compatibles().
start_site()
Vehicle_node vrprouting::vrp::Vehicle::start_site () const inline inherited
Definition at line 278 of file vehicle.h.
{
          return m_path.front();
      }
References vrprouting::vrp::Vehicle::m_path.
Referenced by vrprouting::vrp::Vehicle::is_ok().
swap()
void vrprouting::vrp::Vehicle::swap (POS i, POS j) inherited
Swap two nodes in the path.
Before: S <nodesA> I <nodesB> J <nodesC> E
After: S <nodesA> J <nodesB> I <nodesC> E
Parameters
[in] i The position of the first node to swap.
[in] j The position of the second node to swap.
Definition at line 340 of file vehicle.cpp.
{
     invariant();
     pgassert(m_path.size() > 3);
     pgassert(!m_path[i].is_start());
     pgassert(!m_path[i].is_end());
     pgassert(!m_path[j].is_start());
     pgassert(!m_path[j].is_end());
     std::swap(m_path[i], m_path[j]);
     i < j ? evaluate(i) : evaluate(j);
     invariant();
 }
References vrprouting::vrp::Vehicle::evaluate(), vrprouting::vrp::Vehicle::invariant(), vrprouting::vrp::Vehicle::m_path, and pgassert.
Referenced by vrprouting::vrp::Vehicle::insert().
tau()
std::string vrprouting::vrp::Vehicle::tau () const inherited
Definition at line 580 of file vehicle.cpp.
                    {
     pgassert(m_path.size() > 1);
     std::ostringstream log;
     log << "Truck " << id() << "(" << idx() << ")"
         << " (";
     for (const auto &p_stop : m_path) {
         if (!(p_stop == m_path.front()))
             log << ", ";
         log << p_stop.id();
     }
     log << ")" << " \t(cv, twv, wait_time, duration) = ("
         << cvTot() << ", "
         << twvTot() << ", "
         << total_wait_time() << ", "
         << duration() << ")";
     return log.str();
 }
References vrprouting::vrp::Vehicle::cvTot(), vrprouting::vrp::Vehicle::duration(), vrprouting::Identifier::id(), vrprouting::Identifier::idx(), vrprouting::vrp::Vehicle::m_path, pgassert, vrprouting::vrp::Vehicle::total_wait_time(), and vrprouting::vrp::Vehicle::twvTot().
Referenced by vrprouting::vrp::Vehicle::get_postgres_result(), insert(), and vrprouting::vrp::Vehicle::Vehicle().
total_service_time()
double vrprouting::vrp::Vehicle::total_service_time () const inline inherited
Definition at line 253 of file vehicle.h.
{
          return m_path.back().total_service_time();
      }
References vrprouting::vrp::Vehicle::m_path.
total_travel_time()
double vrprouting::vrp::Vehicle::total_travel_time () const inline inherited
Definition at line 250 of file vehicle.h.
{
          return m_path.back().total_travel_time();
      }
References vrprouting::vrp::Vehicle::m_path.
total_wait_time()
double vrprouting::vrp::Vehicle::total_wait_time () const inline inherited
Definition at line 247 of file vehicle.h.
{
          return m_path.back().total_wait_time();
      }
References vrprouting::vrp::Vehicle::m_path.
Referenced by vrprouting::vrp::Vehicle::cost(), vrprouting::vrp::Vehicle::free_time(), and vrprouting::vrp::Vehicle::tau().
twvTot()
int vrprouting::vrp::Vehicle::twvTot () const inline inherited
Definition at line 259 of file vehicle.h.
{
          return m_path.back().twvTot();
      }
References vrprouting::vrp::Vehicle::m_path.
Referenced by vrprouting::vrp::Vehicle::cost(), vrprouting::vrp::Vehicle::has_twv(), and vrprouting::vrp::Vehicle::tau().
Friends And Related Function Documentation
Initial_solution
friend class Initial_solution friend
Definition at line 58 of file vehicle_pickDeliver.h.
Optimize
friend class Optimize friend
Definition at line 59 of file vehicle_pickDeliver.h.
Member Data Documentation
cost
double vrprouting::vrp::Vehicle_pickDeliver::cost protected
Definition at line 49 of file vehicle_pickDeliver.h.
m_capacity
double vrprouting::vrp::Vehicle::m_capacity private inherited
Definition at line 84 of file vehicle.h.
Referenced by vrprouting::vrp::Vehicle::capacity(), vrprouting::vrp::Vehicle::evaluate(), vrprouting::vrp::Vehicle::is_ok(), and vrprouting::vrp::operator<<().
m_factor
double vrprouting::vrp::Vehicle::m_factor private inherited
Definition at line 85 of file vehicle.h.
Referenced by vrprouting::vrp::operator<<(), and vrprouting::vrp::Vehicle::speed().
m_feasable_orders
Identifiers<size_t> vrprouting::vrp::Vehicle_pickDeliver::m_feasable_orders protected
orders that fit in the truck
Definition at line 54 of file vehicle_pickDeliver.h.
Referenced by do_while_feasable(), feasable_orders(), and set_compatibles().
m_id
int64_t vrprouting::Identifier::m_id private inherited
Definition at line 87 of file identifier.h.
Referenced by vrprouting::Identifier::id(), and vrprouting::Identifier::reset_id().
m_idx
size_t vrprouting::Identifier::m_idx private inherited
Definition at line 86 of file identifier.h.
Referenced by vrprouting::Identifier::idx().
m_orders
PD_Orders vrprouting::vrp::Vehicle_pickDeliver::m_orders protected
Definition at line 52 of file vehicle_pickDeliver.h.
Referenced by do_while_feasable(), get_first_order(), get_worse_order(), orders(), pop_back(), pop_front(), and set_compatibles().
m_orders_in_vehicle
Identifiers<size_t> vrprouting::vrp::Vehicle_pickDeliver::m_orders_in_vehicle protected
orders inserted in this vehicle
Definition at line 51 of file vehicle_pickDeliver.h.
Referenced by erase(), has_order(), insert(), orders_in_vehicle(), orders_size(), push_back(), push_front(), and semiLIFO().
m_path
std::deque< Vehicle_node > vrprouting::vrp::Vehicle::m_path protected inherited
Definition at line 78 of file vehicle.h.
Referenced by vrprouting::vrp::Vehicle::cost(), vrprouting::vrp::Vehicle::cvTot(), vrprouting::vrp::Vehicle::deltaTime(), vrprouting::vrp::Vehicle::duration(), vrprouting::vrp::Vehicle::empty(), vrprouting::vrp::Vehicle::end_site(), vrprouting::vrp::Vehicle::erase(), vrprouting::vrp::Vehicle::evaluate(), vrprouting::vrp::Vehicle::free_time(), get_first_order(), vrprouting::vrp::Vehicle::get_postgres_result(), vrprouting::vrp::Vehicle::getDropPosLowLimit(), vrprouting::vrp::Vehicle::getPosHighLimit(), vrprouting::vrp::Vehicle::getPosLowLimit(), insert(), vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::Vehicle::insert_less_travel_time(), vrprouting::vrp::Vehicle::invariant(), vrprouting::vrp::Vehicle::is_ok(), vrprouting::vrp::operator<(), vrprouting::vrp::Vehicle::path(), vrprouting::vrp::Vehicle::pop_back(), pop_back(), vrprouting::vrp::Vehicle::pop_front(), pop_front(), push_back(), vrprouting::vrp::Vehicle::push_back(), push_front(), semiLIFO(), vrprouting::vrp::Vehicle::size(), vrprouting::vrp::Vehicle::start_site(), vrprouting::vrp::Vehicle::swap(), vrprouting::vrp::Vehicle::tau(), vrprouting::vrp::Vehicle::total_service_time(), vrprouting::vrp::Vehicle::total_travel_time(), vrprouting::vrp::Vehicle::total_wait_time(), vrprouting::vrp::Vehicle::twvTot(), and vrprouting::vrp::Vehicle::Vehicle().
m_speed
double vrprouting::vrp::Vehicle::m_speed private inherited
Definition at line 86 of file vehicle.h.
Referenced by vrprouting::vrp::operator<<(), and vrprouting::vrp::Vehicle::speed().
problem
Pgr_pickDeliver * vrprouting::vrp::Vehicle::problem static inherited
Pointer to problem.
Definition at line 367 of file vehicle.h.
Referenced by vrprouting::vrp::Vehicle::msg(), and vrprouting::vrp::PD_problem::PD_problem().
The documentation for this class was generated from the following files:
vehicle_pickDeliver.h
vehicle_pickDeliver.cpp