vrpRouting: vrprouting::vrp::Dnode Class Reference
vrprouting::vrp::Dnode Class Reference
The Dnode class defines a the basic operations when data is a matrix.
#include "dnode.h"
Public Member Functions
double distance (const Dnode &other) const
bool operator== (const Dnode &other) const
constructors
Dnode ()=default
Dnode (size_t id, int64_t original_id)
data constructor
Static Protected Member Functions
static Pgr_messages & msg ()
Static Protected Attributes
static Pgr_pickDeliver * problem
The problem.
Private Attributes
int64_t m_id
size_t m_idx
friend PD_problem
Friends
std::ostream & operator<< (std::ostream &log, const Dnode &node)
Detailed Description
The Dnode class defines a the basic operations when data is a matrix.
currently needs the PD_problem
Definition at line 48 of file dnode.h.
Constructor & Destructor Documentation
Dnode() [1/2]
vrprouting::vrp::Dnode::Dnode () default
Dnode() [2/2]
vrprouting::vrp::Dnode::Dnode (size_t id, int64_t original_id)
data constructor
Definition at line 50 of file dnode.cpp.
                                    :
     Identifier(idx, id) {
     }
Member Function Documentation
distance()
double vrprouting::vrp::Dnode::distance (const Dnode & other) const
Definition at line 43 of file dnode.cpp.
{
     return problem->m_cost_matrix.distance(
             problem->m_cost_matrix.get_index(id()),
             problem->m_cost_matrix.get_index(other.id()));
 }
References vrprouting::Matrix::distance(), vrprouting::Matrix::get_index(), vrprouting::Identifier::id(), vrprouting::vrp::Pgr_pickDeliver::m_cost_matrix, and problem.
Referenced by vrprouting::vrp::Tw_node::travel_time_to().
id()
int64_t vrprouting::Identifier::id () const inherited
get the original id
Definition at line 42 of file identifier.cpp.
                      {
     return m_id;
 }
References vrprouting::Identifier::m_id.
Referenced by distance(), vrprouting::vrp::Vehicle::get_postgres_result(), vrprouting::vrp::Vehicle::is_phony(), vrprouting::vrp::operator<<(), vrprouting::operator<<(), vrprouting::vrp::Node::operator==(), vrprouting::vrp::Base_node::operator==(), operator==(), vrprouting::vrp::Tw_node::operator==(), vrprouting::vrp::Node::print(), vrprouting::vrp::Vehicle::tau(), and vrprouting::vrp::Vehicle::Vehicle().
idx()
size_t vrprouting::Identifier::idx () const inherited
get the internal index
Definition at line 37 of file identifier.cpp.
                       {
     return m_idx;
 }
References vrprouting::Identifier::m_idx.
Referenced by vrprouting::vrp::Vehicle_pickDeliver::erase(), vrprouting::vrp::Vehicle::erase(), vrprouting::vrp::Fleet::get_truck(), vrprouting::vrp::Vehicle_pickDeliver::has_order(), vrprouting::vrp::Vehicle_pickDeliver::insert(), vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::operator<<(), vrprouting::operator<<(), vrprouting::vrp::Node::operator==(), vrprouting::vrp::Base_node::operator==(), operator==(), vrprouting::vrp::Tw_node::operator==(), vrprouting::vrp::Node::print(), vrprouting::vrp::Vehicle_pickDeliver::push_back(), vrprouting::vrp::Vehicle_pickDeliver::push_front(), vrprouting::vrp::Vehicle_pickDeliver::semiLIFO(), vrprouting::vrp::Order::set_compatibles(), vrprouting::vrp::Vehicle::tau(), vrprouting::vrp::Tw_node::travel_time_to(), and vrprouting::vrp::Vehicle::Vehicle().
msg()
Pgr_messages & vrprouting::vrp::Dnode::msg () static protected
Definition at line 63 of file dnode.cpp.
            {
     return problem->msg;
 }
References vrprouting::vrp::Pgr_pickDeliver::msg, and problem.
operator==()
bool vrprouting::vrp::Dnode::operator== (const Dnode & other) const
Definition at line 55 of file dnode.cpp.
{
     if (&rhs == this) return true;
     return
         (idx() == rhs.idx())
          && (id() == rhs.id());
 }
References vrprouting::Identifier::id(), and vrprouting::Identifier::idx().
reset_id()
void vrprouting::Identifier::reset_id (int64_t _id) inherited
change the original id
Definition at line 47 of file identifier.cpp.
{
     m_id = _id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::vrp::Tw_node::Tw_node().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Dnode & node) friend
Definition at line 35 of file dnode.cpp.
{
     log << node.id()
         << "(" << node.idx() << ")";
     return log;
 }
Member Data Documentation
m_id
int64_t vrprouting::Identifier::m_id private inherited
Definition at line 87 of file identifier.h.
Referenced by vrprouting::Identifier::id(), and vrprouting::Identifier::reset_id().
m_idx
size_t vrprouting::Identifier::m_idx private inherited
Definition at line 86 of file identifier.h.
Referenced by vrprouting::Identifier::idx().
PD_problem
friend vrprouting::vrp::Dnode::PD_problem private
Definition at line 49 of file dnode.h.
problem
Pgr_pickDeliver * vrprouting::vrp::Dnode::problem static protected
The problem.
Definition at line 71 of file dnode.h.
Referenced by distance(), msg(), vrprouting::vrp::Tw_node::operator==(), vrprouting::vrp::PD_problem::PD_problem(), and vrprouting::vrp::Tw_node::travel_time_to().
The documentation for this class was generated from the following files:
dnode.h
dnode.cpp