vrpRouting: vrprouting::vrp::Order Class Reference
vrprouting::vrp::Order Class Reference
#include "order.h"
Public Member Functions
Constructors
Order (size_t p_id, int64_t p_idx, const Vehicle_node &p_pickup, const Vehicle_node &p_deliver)
Order (const Order &)=default
Accessors
const Vehicle_node & delivery () const
The delivery node identifier.
const Vehicle_node & pickup () const
The delivery node identifier.
Identifiers< size_t > subsetJ (const Identifiers< size_t > &J) const
Get a subset of the orders that can be placed after this order.
Identifiers< size_t > subsetI (const Identifiers< size_t > &I) const
Modifiers
void set_compatibles (const Order order, double speed)
To be or not to be
bool is_valid (double speed) const
validate a pickup/delivery order
bool isCompatibleIJ (const Order &I, double speed) const
Can order I be placed before this order?
Private Attributes
Identifiers< size_t > m_compatibleI
Stores all the orders that can be placed before this order.
Identifiers< size_t > m_compatibleJ
Stores all the orders that can be placed after this order.
Vehicle_node m_delivery
The delivery node identifier.
int64_t m_id
size_t m_idx
Vehicle_node m_pickup
The pick up node identifier.
Friends
Friends
std::ostream & operator<< (std::ostream &, const Order &)
Detailed Description
Definition at line 42 of file order.h.
Constructor & Destructor Documentation
Order() [1/2]
vrprouting::vrp::Order::Order (size_t p_id, int64_t p_idx, const Vehicle_node & p_pickup, const Vehicle_node & p_deliver)
Definition at line 45 of file order.cpp.
                                         :
     Identifier(p_idx, p_id),
     m_pickup(p_pickup),
     m_delivery(p_delivery) {
     }
Order() [2/2]
vrprouting::vrp::Order::Order (const Order &) default
Member Function Documentation
delivery()
const Vehicle_node & vrprouting::vrp::Order::delivery () const
The delivery node identifier.
It hold's the idx of the node
Definition at line 82 of file order.cpp.
                       {
     return m_delivery;
 }
References m_delivery.
Referenced by vrprouting::vrp::Vehicle_pickDeliver::erase(), vrprouting::vrp::Vehicle_pickDeliver::insert(), is_valid(), isCompatibleIJ(), vrprouting::vrp::operator<<(), vrprouting::vrp::Vehicle_pickDeliver::push_back(), vrprouting::vrp::Vehicle_pickDeliver::push_front(), and vrprouting::vrp::Vehicle_pickDeliver::semiLIFO().
id()
int64_t vrprouting::Identifier::id () const inherited
get the original id
Definition at line 42 of file identifier.cpp.
                      {
     return m_id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::vrp::Dnode::distance(), vrprouting::vrp::Vehicle::get_postgres_result(), vrprouting::vrp::Vehicle::is_phony(), vrprouting::vrp::operator<<(), vrprouting::operator<<(), vrprouting::vrp::Node::operator==(), vrprouting::vrp::Base_node::operator==(), vrprouting::vrp::Dnode::operator==(), vrprouting::vrp::Tw_node::operator==(), vrprouting::vrp::Node::print(), vrprouting::vrp::Vehicle::tau(), and vrprouting::vrp::Vehicle::Vehicle().
idx()
size_t vrprouting::Identifier::idx () const inherited
get the internal index
Definition at line 37 of file identifier.cpp.
                       {
     return m_idx;
 }
References vrprouting::Identifier::m_idx.
Referenced by vrprouting::vrp::Vehicle_pickDeliver::erase(), vrprouting::vrp::Vehicle::erase(), vrprouting::vrp::Fleet::get_truck(), vrprouting::vrp::Vehicle_pickDeliver::has_order(), vrprouting::vrp::Vehicle_pickDeliver::insert(), vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::operator<<(), vrprouting::operator<<(), vrprouting::vrp::Node::operator==(), vrprouting::vrp::Base_node::operator==(), vrprouting::vrp::Dnode::operator==(), vrprouting::vrp::Tw_node::operator==(), vrprouting::vrp::Node::print(), vrprouting::vrp::Vehicle_pickDeliver::push_back(), vrprouting::vrp::Vehicle_pickDeliver::push_front(), vrprouting::vrp::Vehicle_pickDeliver::semiLIFO(), set_compatibles(), vrprouting::vrp::Vehicle::tau(), vrprouting::vrp::Tw_node::travel_time_to(), and vrprouting::vrp::Vehicle::Vehicle().
is_valid()
bool vrprouting::vrp::Order::is_valid (double speed) const
validate a pickup/delivery order
An order is valid when:
The pickup is well formed
The delivery is well formed
isCompatibleIJ to go to delivery after inmediatly visiting pickup
Definition at line 94 of file order.cpp.
{
     return
         pickup().is_pickup()
         && delivery().is_delivery()
         /* IS P -> D */
         && delivery().is_compatible_IJ(pickup(), speed);
 }
References delivery(), vrprouting::vrp::Tw_node::is_compatible_IJ(), vrprouting::vrp::Tw_node::is_delivery(), vrprouting::vrp::Tw_node::is_pickup(), and pickup().
Referenced by vrprouting::vrp::Fleet::is_order_ok().
isCompatibleIJ()
bool vrprouting::vrp::Order::isCompatibleIJ (const Order & I, double speed) const
Can order I be placed before this order?
Parameters
[in] I order
[in] speed to be used for evaluating the order
Returns
true when order I can be placed before this order
Definition at line 135 of file order.cpp.
{
     /* this is true in all cases */
     auto all_cases(
             pickup().is_compatible_IJ(I.pickup(), speed)
             && delivery().is_compatible_IJ(I.pickup(), speed));
     /* case other(P) other(D) this(P) this(D) */
     auto case1(pickup().is_compatible_IJ(I.delivery(), speed)
             && delivery().is_compatible_IJ(I.delivery(), speed));
     /* case other(P) this(P) other(D) this(D) */
     auto case2(I.delivery().is_compatible_IJ(pickup(), speed)
             && delivery().is_compatible_IJ(I.delivery(), speed));
     /* case other(P) this(P) this(D) other(D) */
     auto case3(I.delivery().is_compatible_IJ(pickup(), speed)
             && I.delivery().is_compatible_IJ(delivery(), speed));
     return all_cases &&  (case1 ||  case2 ||  case3);
 }
References delivery(), vrprouting::vrp::Tw_node::is_compatible_IJ(), and pickup().
Referenced by set_compatibles().
pickup()
const Vehicle_node & vrprouting::vrp::Order::pickup () const
The delivery node identifier.
It hold's the idx of the node
Definition at line 88 of file order.cpp.
                     {
     return m_pickup;
 }
References m_pickup.
Referenced by vrprouting::vrp::Vehicle_pickDeliver::erase(), vrprouting::vrp::Vehicle_pickDeliver::insert(), is_valid(), isCompatibleIJ(), vrprouting::vrp::operator<<(), vrprouting::vrp::Vehicle_pickDeliver::push_back(), vrprouting::vrp::Vehicle_pickDeliver::push_front(), and vrprouting::vrp::Vehicle_pickDeliver::semiLIFO().
reset_id()
void vrprouting::Identifier::reset_id (int64_t _id) inherited
change the original id
Definition at line 47 of file identifier.cpp.
{
     m_id = _id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::vrp::Tw_node::Tw_node().
set_compatibles()
void vrprouting::vrp::Order::set_compatibles (const Order order, double speed)
Definition at line 111 of file order.cpp.
{
     if (J.idx() == idx()) return;
     if (J.isCompatibleIJ(*this, speed)) {
         /*
          * this -> {J}
          */
         m_compatibleJ += J.idx();
     }
     if (this->isCompatibleIJ(J, speed)) {
         /*
          * {J} -> this
          */
         m_compatibleI += J.idx();
     }
 }
References vrprouting::Identifier::idx(), isCompatibleIJ(), m_compatibleI, and m_compatibleJ.
subsetI()
Identifiers< size_t > vrprouting::vrp::Order::subsetI (const Identifiers< size_t > & I) const
Definition at line 35 of file order.cpp.
{
     return m_compatibleI * I;
 }
References m_compatibleI.
subsetJ()
Identifiers< size_t > vrprouting::vrp::Order::subsetJ (const Identifiers< size_t > & J) const
Get a subset of the orders that can be placed after this order.
Parameters
[in] J set of orders
Returns
ithe set intersection of the J orders with the compatible_J orders of this order
Definition at line 40 of file order.cpp.
{
     return m_compatibleJ * J;
 }
References m_compatibleJ.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Order & order) friend
Definition at line 55 of file order.cpp.
{
     log << "\n\nOrder "
         << static_cast<Identifier>(order) << ": \n"
         << "\tPickup: " << order.pickup() << "\n"
         << "\tDelivery: " << order.delivery() << "\n\n"
         << "\tTravel time: "
         << order.pickup().travel_time_to(order.delivery(), 1);
     log << "\nThere are | {I}| = "
         << order.m_compatibleI.size()
         << " -> order(" << order.idx()
         << ") -> | {J}| = " << order.m_compatibleJ.size()
         << "\n\n {";
     for (const auto o : order.m_compatibleI) {
         log << o << ", ";
     }
     log << "} -> " << order.idx() << " -> {";
     for (const auto o : order.m_compatibleJ) {
         log << o << ", ";
     }
     log << "}";
     return log;
 }
Member Data Documentation
m_compatibleI
Identifiers<size_t> vrprouting::vrp::Order::m_compatibleI private
Stores all the orders that can be placed before this order.
Definition at line 182 of file order.h.
Referenced by vrprouting::vrp::operator<<(), set_compatibles(), and subsetI().
m_compatibleJ
Identifiers<size_t> vrprouting::vrp::Order::m_compatibleJ private
Stores all the orders that can be placed after this order.
Todo:
TODO
compatibility changes based on the speed this is not taking that into account (here)
check where is it talking that into account
Definition at line 168 of file order.h.
Referenced by vrprouting::vrp::operator<<(), set_compatibles(), and subsetJ().
m_delivery
Vehicle_node vrprouting::vrp::Order::m_delivery private
The delivery node identifier.
It hold's the idx of the node
Definition at line 151 of file order.h.
Referenced by delivery().
m_id
int64_t vrprouting::Identifier::m_id private inherited
Definition at line 87 of file identifier.h.
Referenced by vrprouting::Identifier::id(), and vrprouting::Identifier::reset_id().
m_idx
size_t vrprouting::Identifier::m_idx private inherited
Definition at line 86 of file identifier.h.
Referenced by vrprouting::Identifier::idx().
m_pickup
Vehicle_node vrprouting::vrp::Order::m_pickup private
The pick up node identifier.
It hold's the idx of the node
Definition at line 145 of file order.h.
Referenced by pickup().
The documentation for this class was generated from the following files:
order.h
order.cpp