vrpRouting: vrprouting::vrp::Fleet Class Reference
vrprouting::vrp::Fleet Class Reference
#include "fleet.h"
Public Types
typedef std::vector< Vehicle_pickDeliver >::iterator iterator
Public Member Functions
Vehicle_pickDeliver get_truck ()
Vehicle_pickDeliver get_truck (const Order order)
Vehicle_pickDeliver get_truck (size_t order)
bool is_fleet_ok () const
bool is_order_ok (const Order &order) const
Given an order, Cycle trhugh all the trucks to verify if the order can be served by at least one truck.
Fleet & operator= (const Fleet &fleet)
void release_truck (size_t id)
void set_compatibles (const PD_Orders &orders)
constructor
Fleet ()=default
Fleet (const std::vector< Vehicle_t > &vehicles, double factor)
Fleet (const Fleet &fleet)
vector like functions
size_t size () const
Vehicle_pickDeliver & operator[] (size_t i)
iterator begin ()
iterator end ()
Public Attributes
std::vector< Vehicle_pickDeliver > m_trucks
Private Member Functions
void add_vehicle (Vehicle_t, double factor, const Vehicle_node &, const Vehicle_node &)
bool build_fleet (std::vector< Vehicle_t > vehicles, double factor)
build the fleet
Static Private Member Functions
static Pgr_messages & msg ()
the problem message
Private Attributes
Identifiers< size_t > un_used
Identifiers< size_t > used
Static Private Attributes
static Pgr_pickDeliver * problem
The problem.
Friends
std::ostream & operator<< (std::ostream &log, const Fleet &v)
class PD_problem
Detailed Description
Definition at line 47 of file fleet.h.
Member Typedef Documentation
iterator
typedef std::vector<Vehicle_pickDeliver>::iterator vrprouting::vrp::Fleet::iterator
Definition at line 51 of file fleet.h.
Constructor & Destructor Documentation
Fleet() [1/3]
vrprouting::vrp::Fleet::Fleet () default
Fleet() [2/3]
vrprouting::vrp::Fleet::Fleet (const std::vector< Vehicle_t > & vehicles, double factor)
Definition at line 60 of file fleet.cpp.
                                                              :
     used(),
     un_used() {
         build_fleet(vehicles, factor);
         Identifiers<size_t> unused(m_trucks.size());
         un_used = unused;
     }
References build_fleet(), m_trucks, and un_used.
Fleet() [3/3]
vrprouting::vrp::Fleet::Fleet (const Fleet & fleet)
Definition at line 54 of file fleet.cpp.
                                :
     m_trucks(fleet.m_trucks),
     used(fleet.used),
     un_used(fleet.un_used)
     {}
Member Function Documentation
add_vehicle()
void vrprouting::vrp::Fleet::add_vehicle (Vehicle_t vehicle, double factor, const Vehicle_node & starting_site, const Vehicle_node & ending_site) private
Definition at line 147 of file fleet.cpp.
{
     pgassert(starting_site.is_start() && ending_site.is_end());
     pgassert(starting_site.opens() <= starting_site.closes());
     pgassert(ending_site.opens() <= ending_site.closes());
 #if 0
     problem->add_base_node(std::move(b_start));
     problem->add_base_node(std::move(b_end));
     problem->add_node(starting_site);
     problem->add_node(ending_site);
 #endif
     for (int i = 0; i < vehicle.cant_v; ++i) {
         m_trucks.push_back(Vehicle_pickDeliver(
                     m_trucks.size(),
                     vehicle.id,
                     starting_site,
                     ending_site,
                     vehicle.capacity,
                     vehicle.speed,
                     factor));
 #if 0
         msg().log << "inserting vehicle: " << m_trucks.back().tau() << "\n";
 #endif
         pgassert((m_trucks.back().idx() + 1)  == m_trucks.size());
         pgassert(m_trucks.back().is_ok());
     }
 }
References vrprouting::vrp::Pgr_pickDeliver::add_node(), Vehicle_t::cant_v, Vehicle_t::capacity, vrprouting::vrp::Tw_node::closes(), Vehicle_t::id, vrprouting::vrp::Tw_node::is_end(), vrprouting::vrp::Tw_node::is_start(), vrprouting::Pgr_messages::log, m_trucks, msg(), vrprouting::vrp::Tw_node::opens(), pgassert, problem, and Vehicle_t::speed.
Referenced by build_fleet().
begin()
iterator vrprouting::vrp::Fleet::begin () inline
Definition at line 89 of file fleet.h.
 {return m_trucks.begin();}
References m_trucks.
build_fleet()
bool vrprouting::vrp::Fleet::build_fleet (std::vector< Vehicle_t > vehicles, double factor) private
build the fleet
builds a fleet from a vector of Vehicle_t
creates a phoney truck with unlimited capacity and unlimited closing times
checks that the number of vehicles is a legal value
creates the requested vehicles
Parameters
[in] vehicles the list of vehicles
[in] factor the multiplier to speed up or slow down
Definition at line 191 of file fleet.cpp.
{
     /*
      *  creating a phoney truck with max capacity and max window
      *  with the start & end points of the first vehicle given
      */
     vehicles.push_back({
             /*
              * id, capacity
              */
             -1,
             std::numeric_limits<double>::infinity(),
             vehicles[0].speed,
             vehicles[0].start_x,
             vehicles[0].start_y,
             vehicles[0].start_node_id,
             /*
              * cant_v, start_open_t, start_close_t, start_service_t
              */
             1,
             0,
             std::numeric_limits<double>::infinity(),
             0,
             vehicles[0].end_x,
             vehicles[0].end_y,
             vehicles[0].end_node_id,
             /*
              * end_open_t, end_close_t, end_service_t
              */
             0,
             std::numeric_limits<double>::infinity(),
             0});
     for (auto vehicle : vehicles) {
         if (vehicle.cant_v < 0) {
             throw std::make_pair(std::string("Illegal number of vehicles found"), vehicle.cant_v);
         }
         if (vehicle.capacity < 0) {
             throw std::make_pair(std::string("Illegal value for capacity found"), vehicle.capacity);
         }
         if  (!problem->m_cost_matrix.empty()) {
             if (!problem->m_cost_matrix.has_id(vehicle.start_node_id)) {
                 throw std::make_pair(std::string("Unable to find node on matrix"), vehicle.start_node_id);
             }
             if (!problem->m_cost_matrix.has_id(vehicle.end_node_id)) {
                 throw std::make_pair(std::string("Unable to find node on matrix"), vehicle.end_node_id);
             }
         }
         if (!(vehicle.start_open_t  <= vehicle.start_close_t
                     && vehicle.end_open_t <= vehicle.end_close_t
                     && vehicle.start_open_t <= vehicle.end_close_t)) {
             msg().error << "Illegal values found on vehicle";
             msg().log << "On vehicle " << vehicle.id
                 << " a condition is not met, verify that:"
                 << "\nvehicle.start_open_t  <= vehicle.start_close_t\t"
                 << vehicle.start_open_t << " <= " << vehicle.start_close_t
                 << "\nvehicle.end_open_t <= vehicle.end_close_t\t"
                 << vehicle.end_open_t << " <= " << vehicle.end_close_t
                 << "\nvehicle.start_open_t <= vehicle.end_close_t\t"
                 << vehicle.start_open_t << " <= " << vehicle.end_close_t;
             throw std::make_pair(msg().get_error(), msg().get_log());
         }
 #if 0
         if (vehicle.cant_v < 0) {
             msg().error << "Illegal number of vehicles found vehicle";
             msg().log << vehicle.cant_v << "< 0 on vehicle " << vehicle.id;
             return false;
         }
 #endif
         if  (problem->m_cost_matrix.empty()) {
 #if 0
             /*
              * Euclidean version
              */
             auto b_start = create_b_start<Node>(vehicle, problem->node_id());
             auto starting_site = Vehicle_node(
                     {problem->node_id()++, vehicle, Tw_node::NodeType::kStart});
             auto b_end = create_b_end<Node>(vehicle, problem->node_id());
             auto ending_site = Vehicle_node(
                     {problem->node_id()++, vehicle, Tw_node::NodeType::kEnd});
             if (!(starting_site.is_start() && ending_site.is_end()
                     && starting_site.opens() <= starting_site.closes()
                     && ending_site.opens() <= ending_site.closes())) {
                 msg().clear();
                 msg().error << "Illegal values found on vehicle";
                 msg().log << "On vehicle " << vehicle.id
                     << " a condition is not met:\n"
                     << "starting_site.is_start: "
                     << (starting_site.is_start()? "YES" : "NO") << "\n"
                     << "ending_site.is_end: "
                     << (ending_site.is_end()? "YES" : "NO") << "\n"
                     << "verify that:\n"
                     << "-  start_open <= start_close: "
                     << starting_site.opens()
                     << "<"  << starting_site.closes() << "\n"
                     << "-  end_open <= end_close: "
                     << ending_site.opens()
                     << "<"  << ending_site.closes() << "\n"
                     << "-  capacity > 0\n";
                 pgassert(!msg().get_error().empty());
                 return false;
             }
             pgassert(starting_site.is_start());
             pgassert(ending_site.is_end());
             pgassert(starting_site.opens() <= starting_site.closes());
             pgassert(ending_site.opens() <= ending_site.closes());
             pgassertwm(
                     starting_site.is_start() && ending_site.is_end(),
                     msg().get_error().c_str());
             add_vehicle(vehicle, factor,
                     std::move(b_start), starting_site,
                     std::move(b_end), ending_site);
 #endif
         } else {
             /*
              * Matrix version
              */
 #if 0
             auto b_start = create_b_start<Dnode>(vehicle, problem->node_id());
             auto starting_site = Vehicle_node(
                     {problem->node_id()++, vehicle, Tw_node::NodeType::kStart});
             auto b_end = create_b_end<Dnode>(vehicle, problem->node_id());
             auto ending_site = Vehicle_node(
                     {problem->node_id()++, vehicle, Tw_node::NodeType::kEnd});
             if (!(starting_site.is_start() && ending_site.is_end()
                     && starting_site.opens() <= starting_site.closes()
                     && ending_site.opens() <= ending_site.closes())) {
                 msg().clear();
                 msg().error << "Illegal values found on vehicle";
                 msg().log << "On vehicle " << vehicle.id
                     << " a condition is not met, verify that:\n"
                     << "starting_site.is_start()"
                     << starting_site.is_start() << "\n"
                     << "ending_site.is_start()"
                     << ending_site.is_end() << "\n"
                     << "-  start_open <= start_close\n"
                     << starting_site.opens() << "<"
                     << starting_site.closes() << "\n"
                     << "-  end_open <= end_close\n"
                     << ending_site.opens() << "<"
                     << ending_site.closes() << "\n"
                     << "-  capacity > 0\n";
                 pgassert(!msg().get_error().empty());
                 return false;
             }
             pgassert(starting_site.is_start());
             pgassert(ending_site.is_end());
 #endif
             auto starting_site = Vehicle_node({problem->m_nodes.size(), vehicle, Tw_node::NodeType::kStart});
             problem->add_node(starting_site);
             auto ending_site = Vehicle_node({problem->m_nodes.size(), vehicle, Tw_node::NodeType::kEnd});
             problem->add_node(ending_site);
             pgassert(starting_site.opens() <= starting_site.closes());
             pgassert(ending_site.opens() <= ending_site.closes());
             pgassert(starting_site.is_start() && ending_site.is_end());
             add_vehicle(vehicle, factor, starting_site, ending_site);
         }
     }
     Identifiers<size_t> unused(m_trucks.size());
     un_used = unused;
     return true;
 }
References vrprouting::vrp::Pgr_pickDeliver::add_node(), add_vehicle(), vrprouting::Pgr_messages::clear(), vrprouting::Matrix::empty(), vrprouting::Pgr_messages::error, vrprouting::Matrix::has_id(), vrprouting::Pgr_messages::log, vrprouting::vrp::Pgr_pickDeliver::m_cost_matrix, vrprouting::vrp::Pgr_pickDeliver::m_nodes, m_trucks, msg(), pgassert, pgassertwm, problem, and un_used.
Referenced by Fleet().
end()
iterator vrprouting::vrp::Fleet::end () inline
Definition at line 90 of file fleet.h.
 {return m_trucks.end();}
References m_trucks.
get_truck() [1/3]
Vehicle_pickDeliver vrprouting::vrp::Fleet::get_truck ()
Definition at line 71 of file fleet.cpp.
                  {
     ENTERING(msg());
     auto idx = un_used.front();
     msg().log << "Available vehicles: " << un_used << "\n";
     msg().log << "NOT Available vehicles: " << used << "\n";
     msg().log << "getting idx" << idx << "\n";
     pgassertwm(idx < m_trucks.size(), msg().log.str());
     used += idx;
     if (un_used.size() > 1) un_used -= idx;
     EXITING(msg());
     return m_trucks[idx];
 }
References ENTERING, EXITING, Identifiers< T >::front(), vrprouting::Pgr_messages::log, m_trucks, msg(), pgassertwm, Identifiers< T >::size(), un_used, and used.
Referenced by vrprouting::vrp::Initial_solution::do_while_foo(), and vrprouting::vrp::Initial_solution::one_truck_all_orders().
get_truck() [2/3]
Vehicle_pickDeliver vrprouting::vrp::Fleet::get_truck (const Order order)
Definition at line 129 of file fleet.cpp.
{
     auto id = m_trucks.front().idx();
     for (auto truck : m_trucks) {
         if (truck.feasable_orders().has(order.idx())) {
             id = truck.idx();
             msg().log << "id" << id
                 << "size" << m_trucks.size();
             pgassertwm(id < m_trucks.size(), msg().get_log());
             used += id;
             if (un_used.size() > 1) un_used -= id;
             break;
         }
     }
     return m_trucks[id];
 }
References vrprouting::Identifier::idx(), vrprouting::Pgr_messages::log, m_trucks, msg(), pgassertwm, Identifiers< T >::size(), un_used, and used.
get_truck() [3/3]
Vehicle_pickDeliver vrprouting::vrp::Fleet::get_truck (size_t order)
Definition at line 91 of file fleet.cpp.
{
 #if 0
     msg().log << "Available vehicles: " << un_used << "\n";
     msg().log << "NOT Available vehicles: " << used << "\n";
 #endif
     auto idx = un_used.front();
     for (const auto &i : un_used) {
         if (m_trucks[i].feasable_orders().has(order)) {
             idx = i;
             msg().log << "getting idx" << idx << "\n";
             used += idx;
             if (un_used.size() > 1) un_used -= idx;
             return m_trucks[idx];
         }
     }
     /*
      * using phoney truck
      */
     pgassert(false);
     return m_trucks.back();
     for (auto truck : m_trucks) {
         if (truck.feasable_orders().has(order)) {
             idx = truck.idx();
             msg().log << "idx" << idx << "size" << m_trucks.size();
             pgassertwm(idx < m_trucks.size(), msg().get_log());
             used += idx;
             if (un_used.size() > 1) un_used -= idx;
             break;
         }
     }
     return m_trucks[idx];
 }
References Identifiers< T >::front(), vrprouting::Pgr_messages::log, m_trucks, msg(), pgassert, pgassertwm, Identifiers< T >::size(), un_used, and used.
is_fleet_ok()
bool vrprouting::vrp::Fleet::is_fleet_ok () const
Definition at line 374 of file fleet.cpp.
{
     ENTERING(msg());
     if (!msg().get_error().empty()) return false;
     for (auto truck : m_trucks) {
         if (!truck.is_ok()) {
             msg().error << "Illegal values found on vehicle";
             msg().log << "On vehicle " << truck.id()
                 << " a condition is not met, verify that:\n"
                 << "-  start_open <= start_close\n"
                 << "-  end_open <= end_close\n"
                 << "-  capacity > 0\n";
             return false;
         }
         if (!(truck.start_site().is_start()
                     && truck.end_site().is_end())) {
             pgassertwm(false, "should never pass through here");
             msg().error << "Illegal values found on vehicle";
             return false;
         }
         if (!truck.is_feasable()) {
             msg().error << "Truck is not feasible";
             return false;
         }
     }
     EXITING(msg());
     return true;
 }
References ENTERING, vrprouting::Pgr_messages::error, EXITING, vrprouting::Pgr_messages::log, m_trucks, msg(), and pgassertwm.
Referenced by vrprouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
is_order_ok()
bool vrprouting::vrp::Fleet::is_order_ok (const Order & order) const
Given an order, Cycle trhugh all the trucks to verify if the order can be served by at least one truck.
Definition at line 409 of file fleet.cpp.
{
     for (const auto &truck : m_trucks) {
         if (!order.is_valid(truck.speed())) continue;
         if (truck.is_order_feasable(order)) {
             return true;
         }
     }
     return false;
 }
References vrprouting::vrp::Order::is_valid(), and m_trucks.
Referenced by vrprouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
msg()
Pgr_messages & vrprouting::vrp::Fleet::msg () static private
the problem message
Returns
reference to the problem's message
Definition at line 47 of file fleet.cpp.
            {
     return problem->msg;
 }
References vrprouting::vrp::Pgr_pickDeliver::msg, and problem.
Referenced by add_vehicle(), build_fleet(), get_truck(), is_fleet_ok(), and vrprouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
operator=()
Fleet& vrprouting::vrp::Fleet::operator= (const Fleet & fleet) inline
Definition at line 67 of file fleet.h.
{
          m_trucks = fleet.m_trucks;
          used = fleet.used;
          un_used = fleet.un_used;
          return *this;
      }
References m_trucks, un_used, and used.
operator[]()
Vehicle_pickDeliver & vrprouting::vrp::Fleet::operator[] (size_t i)
Definition at line 420 of file fleet.cpp.
{
     pgassert(i < m_trucks.size());
     return m_trucks[i];
 }
References m_trucks, and pgassert.
release_truck()
void vrprouting::vrp::Fleet::release_truck (size_t id)
Definition at line 85 of file fleet.cpp.
{
     used -= id;
     un_used += id;
 }
References un_used, and used.
Referenced by vrprouting::vrp::Initial_solution::do_while_foo().
set_compatibles()
void vrprouting::vrp::Fleet::set_compatibles (const PD_Orders & orders)
Definition at line 426 of file fleet.cpp.
{
     for (auto &truck : m_trucks) {
         truck.set_compatibles(orders);
     }
 }
References m_trucks.
Referenced by vrprouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
size()
size_t vrprouting::vrp::Fleet::size () const inline
Definition at line 87 of file fleet.h.
 {return m_trucks.size();}
References m_trucks.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Fleet & v) friend
Definition at line 437 of file fleet.cpp.
{
     log << "fleet\n";
     for (const auto &v : f.m_trucks) {
         log << v;
     }
     log << "end fleet\n";
     return log;
 }
PD_problem
friend class PD_problem friend
Definition at line 48 of file fleet.h.
Member Data Documentation
m_trucks
std::vector<Vehicle_pickDeliver> vrprouting::vrp::Fleet::m_trucks
Definition at line 52 of file fleet.h.
Referenced by add_vehicle(), begin(), build_fleet(), end(), Fleet(), get_truck(), is_fleet_ok(), is_order_ok(), vrprouting::vrp::operator<<(), operator=(), operator[](), set_compatibles(), and size().
problem
Pgr_pickDeliver * vrprouting::vrp::Fleet::problem static private
The problem.
Definition at line 115 of file fleet.h.
Referenced by add_vehicle(), build_fleet(), msg(), and vrprouting::vrp::PD_problem::PD_problem().
un_used
Identifiers<size_t> vrprouting::vrp::Fleet::un_used private
Definition at line 98 of file fleet.h.
Referenced by build_fleet(), Fleet(), get_truck(), operator=(), and release_truck().
used
Identifiers<size_t> vrprouting::vrp::Fleet::used private
Definition at line 97 of file fleet.h.
Referenced by get_truck(), operator=(), and release_truck().
The documentation for this class was generated from the following files:
fleet.h
fleet.cpp