vrpRouting: vrprouting::vrp::Base_node Class Reference
vrprouting::vrp::Base_node Class Reference abstract
The Base_node class defines the operations that can be performed in a 2D node.
#include "base_node.h"
Public Member Functions
Base_node ()=default
Base_node (size_t, int64_t)
virtual ~Base_node ()=default
distance
virtual double distance (const Base_node *node) const =0
Private Attributes
int64_t m_id
size_t m_idx
Friends
std::ostream & operator<< (std::ostream &log, const Base_node &node)
Detailed Description
The Base_node class defines the operations that can be performed in a 2D node.
A Base_node is an identifier of a Node or Dnode.
Definition at line 47 of file base_node.h.
Constructor & Destructor Documentation
Base_node() [1/2]
vrprouting::vrp::Base_node::Base_node () default
Base_node() [2/2]
vrprouting::vrp::Base_node::Base_node (size_t _idx, int64_t _id)
Definition at line 38 of file base_node.cpp.
     : Identifier(_idx, _id) {
     }
~Base_node()
virtual vrprouting::vrp::Base_node::~Base_node () virtual default
Member Function Documentation
distance()
virtual double vrprouting::vrp::Base_node::distance (const Base_node * node) const pure virtual
Implemented in vrprouting::vrp::Node.
id()
int64_t vrprouting::Identifier::id () const inherited
get the original id
Definition at line 42 of file identifier.cpp.
                      {
     return m_id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::vrp::Dnode::distance(), vrprouting::vrp::Vehicle::get_postgres_result(), vrprouting::vrp::Vehicle::is_phony(), vrprouting::vrp::operator<<(), vrprouting::operator<<(), vrprouting::vrp::Node::operator==(), operator==(), vrprouting::vrp::Dnode::operator==(), vrprouting::vrp::Tw_node::operator==(), vrprouting::vrp::Node::print(), vrprouting::vrp::Vehicle::tau(), and vrprouting::vrp::Vehicle::Vehicle().
idx()
size_t vrprouting::Identifier::idx () const inherited
get the internal index
Definition at line 37 of file identifier.cpp.
                       {
     return m_idx;
 }
References vrprouting::Identifier::m_idx.
Referenced by vrprouting::vrp::Vehicle_pickDeliver::erase(), vrprouting::vrp::Vehicle::erase(), vrprouting::vrp::Fleet::get_truck(), vrprouting::vrp::Vehicle_pickDeliver::has_order(), vrprouting::vrp::Vehicle_pickDeliver::insert(), vrprouting::vrp::Vehicle::insert(), vrprouting::vrp::operator<<(), vrprouting::operator<<(), vrprouting::vrp::Node::operator==(), operator==(), vrprouting::vrp::Dnode::operator==(), vrprouting::vrp::Tw_node::operator==(), vrprouting::vrp::Node::print(), vrprouting::vrp::Vehicle_pickDeliver::push_back(), vrprouting::vrp::Vehicle_pickDeliver::push_front(), vrprouting::vrp::Vehicle_pickDeliver::semiLIFO(), vrprouting::vrp::Order::set_compatibles(), vrprouting::vrp::Vehicle::tau(), vrprouting::vrp::Tw_node::travel_time_to(), and vrprouting::vrp::Vehicle::Vehicle().
operator==()
bool vrprouting::vrp::Base_node::operator== (const Base_node & rhs) const virtual
Definition at line 43 of file base_node.cpp.
{
     if (&rhs == this) return true;
     return
         (idx() == rhs.idx())
          && (id() == rhs.id());
 }
References vrprouting::Identifier::id(), and vrprouting::Identifier::idx().
reset_id()
void vrprouting::Identifier::reset_id (int64_t _id) inherited
change the original id
Definition at line 47 of file identifier.cpp.
{
     m_id = _id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::vrp::Tw_node::Tw_node().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Base_node & node) friend
Definition at line 33 of file base_node.cpp.
{
     return os << node.id()
         << "(" << node.idx() << ")";
 }
Member Data Documentation
m_id
int64_t vrprouting::Identifier::m_id private inherited
Definition at line 87 of file identifier.h.
Referenced by vrprouting::Identifier::id(), and vrprouting::Identifier::reset_id().
m_idx
size_t vrprouting::Identifier::m_idx private inherited
Definition at line 86 of file identifier.h.
Referenced by vrprouting::Identifier::idx().
The documentation for this class was generated from the following files:
base_node.h
base_node.cpp