vrpRouting: vrprouting::optimizers::simple::Optimize Class Reference
vrprouting::optimizers::simple::Optimize Class Reference
#include "simple.h"
Public Member Functions
Optimize (const problem::Solution &solution, size_t times, const Initials_code &)
std::tuple< int, int, size_t, TInterval, TInterval, TInterval > cost () const
Get all statistics in one cycle.
std::string cost_str () const
int cvTot () const
Total number of capacity constraint violations of the solution.
void decrease_truck ()
TInterval duration () const
Total duration of the solution.
const std::deque< Vehicle_pickDeliver > & fleet () const
Get the current fleet solution.
Initials_code get_kind () const
std::vector< Solution_rt > get_postgres_result () const
get solution like postgres needs it
std::vector< Short_vehicle > get_stops () const
get solution like postgres needs it
void inter_swap (size_t times)
bool is_feasible () const
is the solution feasible?
void move_duration_based ()
void move_wait_time_based ()
Pgr_messages & msg ()
double objective () const
Get the value of the objective function.
bool operator< (const Solution &) const
const Orders & orders () const
std::string tau (const std::string &title="Tau") const
writing the solution in compact form into a string
TInterval total_service_time () const
Total service time of the solution.
TInterval total_travel_time () const
Total travel time of the solution.
int twvTot () const
Total number of time windows constraint violations of the solution.
Fleet & vehicles ()
TInterval wait_time () const
Total waiting time of the solution.
Public Attributes
Solution best_solution
Protected Attributes
std::deque< Vehicle_pickDeliver > m_fleet
The current solution.
Pgr_messages m_msg
Orders m_orders
the problem info
Fleet m_trucks
Private Types
using Initials_code = initialsol::simple::Initials_code
Private Member Functions
bool decrease_truck (size_t)
void delete_empty_truck ()
bool inter_swap ()
bool move_order (problem::Order order, problem::Vehicle_pickDeliver &from_truck, problem::Vehicle_pickDeliver &to_truck)
moves an order to an non empty vehicle
bool move_reduce_cost (problem::Vehicle_pickDeliver &from, problem::Vehicle_pickDeliver &to)
void save_if_best ()
void sort_by_duration ()
void sort_by_id ()
void sort_by_size ()
void sort_for_move ()
bool swap_order ()
bool swap_order (problem::Order from_order, problem::Vehicle_pickDeliver &from_truck, problem::Order to_order, problem::Vehicle_pickDeliver &to_truck)
bool swap_worse (problem::Vehicle_pickDeliver &from, problem::Vehicle_pickDeliver &to)
Private Attributes
Initials_code m_kind
Detailed Description
Definition at line 40 of file optimizers/simple.h.
Member Typedef Documentation
Initials_code
using vrprouting::optimizers::simple::Optimize::Initials_code = initialsol::simple::Initials_code private
Definition at line 41 of file optimizers/simple.h.
Constructor & Destructor Documentation
Optimize()
vrprouting::optimizers::simple::Optimize::Optimize (const problem::Solution & solution, size_t times, const Initials_code & p_kind)
Definition at line 42 of file optimizers/simple.cpp.
                                      :
     problem::Solution(old_solution),
     best_solution(old_solution),
     m_kind(p_kind) {
         inter_swap(times);
         this->m_fleet = best_solution.fleet();
         msg().log << tau("bestSol before sort by size");
         sort_by_size();
         msg().log << tau("bestSol after sort by size");
         msg().log <<  tau();
     }
References best_solution, inter_swap(), vrprouting::Pgr_messages::log, vrprouting::problem::Solution::m_fleet, vrprouting::problem::Solution::msg(), sort_by_size(), and vrprouting::problem::Solution::tau().
Member Function Documentation
cost()
std::tuple< int, int, size_t, TInterval, TInterval, TInterval > Solution::cost () const inherited
Get all statistics in one cycle.
Returns
totals of
idx variable
0 twv
1 cv
2 fleet size
3 waiting time
4 duration
5 travel time
std::get<idx>
Definition at line 218 of file solution.cpp.
                      {
   TInterval total_duration(0);
   TInterval total_wait_time(0);
   TInterval total_tt(0);
   int total_twv(0);
   int total_cv(0);
   /*
    * Cycle the fleet
    */
   for (const auto& v : m_fleet) {
     total_duration += v.duration();
     total_wait_time += v.total_wait_time();
     total_twv += v.twvTot();
     total_cv += v.cvTot();
     total_tt += v.total_travel_time();
   }
   /*
    * build the tuple
    */
   return std::make_tuple(
       total_twv, total_cv, m_fleet.size(),
       total_wait_time, total_duration,
       total_tt);
 }
References vrprouting::problem::Solution::m_fleet.
Referenced by vrprouting::problem::Solution::cost_str(), and vrprouting::problem::Solution::operator<().
cost_str()
std::string Solution::cost_str () const inherited
Returns
The costs in one string
Definition at line 246 of file solution.cpp.
{
   /*
    * get the cost
    */
   auto s_cost(cost());
   std::ostringstream log;
   /*
    * Build the string
    */
   log << std::fixed << std::setprecision(4)
     << "twv=" << std::get<0>(s_cost)
     << " cv=" << std::get<1>(s_cost)
     << " wait=" << std::get<3>(s_cost)
     << " duration=" << std::get<4>(s_cost)
     << " tt=" << std::get<5>(s_cost);
   return log.str();
 }
References vrprouting::problem::Solution::cost().
Referenced by vrprouting::problem::Solution::tau().
cvTot()
int Solution::cvTot () const inherited
Total number of capacity constraint violations of the solution.
Returns
Total number of capacity violations The total capacity violations of the solution is the sum of the capacity violations of all vehicles
Definition at line 196 of file solution.cpp.
                       {
   return std::accumulate(begin(m_fleet), end(m_fleet), 0,
       [](int i, const Vehicle_pickDeliver& v) {return v.cvTot() + i;});
 }
References vrprouting::problem::Vehicle::cvTot(), and vrprouting::problem::Solution::m_fleet.
Referenced by vrprouting::problem::Solution::get_postgres_result().
decrease_truck() [1/2]
void vrprouting::optimizers::simple::Optimize::decrease_truck ()
Definition at line 534 of file optimizers/simple.cpp.
{
     bool decreased(false);
     for (size_t i = 1; i < m_fleet.size(); ++i) {
         decreased = decrease_truck(i) || decreased;
     }
     if (decreased) {
         delete_empty_truck();
         save_if_best();
         decrease_truck();
     }
     save_if_best();
 }
References delete_empty_truck(), vrprouting::problem::Solution::m_fleet, and save_if_best().
Referenced by inter_swap().
decrease_truck() [2/2]
bool vrprouting::optimizers::simple::Optimize::decrease_truck (size_t cycle) private
Definition at line 548 of file optimizers/simple.cpp.
{
     auto position = cycle;
     for (auto orders = m_fleet[position].orders_in_vehicle();
             !orders.empty();
             orders.pop_front()) {
         /* Step 2: grab an order */
         auto order = m_fleet[position].orders()[orders.front()];
         pgassert(order.idx() == orders.front());
         /* Step 3:
          * cycle the fleet
          * insert in first truck possible
          */
         for (size_t i = 0; i < position; ++i) {
             m_fleet[i].hillClimb(order);
             pgassert((m_fleet[i].has_order(order) && m_fleet[i].is_feasible()) || !m_fleet[i].has_order(order));
             if (m_fleet[i].has_order(order)) {
                 /*
                  * delete the order from the current truck
                  */
                 m_fleet[position].erase(order);
                 break;
             }
         }
     }
     return m_fleet[position].orders_in_vehicle().empty();
 }
References vrprouting::problem::Solution::is_feasible(), vrprouting::problem::Solution::m_fleet, vrprouting::problem::Solution::orders(), and pgassert.
delete_empty_truck()
void vrprouting::optimizers::simple::Optimize::delete_empty_truck () private
Definition at line 363 of file optimizers/simple.cpp.
{
     m_fleet.erase(std::remove_if(
                 m_fleet.begin(),
                 m_fleet.end(),
                 [](const problem::Vehicle_pickDeliver &v){
                 return v.orders_in_vehicle().empty();}),
             m_fleet.end());
     save_if_best();
 }
References vrprouting::problem::Solution::m_fleet, and save_if_best().
Referenced by decrease_truck(), and inter_swap().
duration()
TInterval Solution::duration () const inherited
Total duration of the solution.
Returns
the solution's duration
The solution duration is the sum of the durations of all vehicles
Definition at line 140 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), static_cast<TInterval>(0),
       [](TInterval i, const Vehicle_pickDeliver& v) {return v.duration() + i;});
 }
References vrprouting::problem::Vehicle::duration(), and vrprouting::problem::Solution::m_fleet.
Referenced by vrprouting::problem::Solution::get_postgres_result(), save_if_best(), and swap_worse().
fleet()
const std::deque<Vehicle_pickDeliver>& vrprouting::problem::Solution::fleet () const inline inherited
Get the current fleet solution.
Definition at line 107 of file solution.h.
 {return m_fleet;}
References vrprouting::problem::Solution::m_fleet.
Referenced by vrprouting::optimizers::tabu::Optimize::intensify(), and vrprouting::optimizers::tabu::Optimize::Optimize().
get_kind()
Initials_code vrprouting::optimizers::simple::Optimize::get_kind () const inline
Definition at line 56 of file optimizers/simple.h.
 {return m_kind;}
References m_kind.
Referenced by move_order(), move_reduce_cost(), swap_order(), and swap_worse().
get_postgres_result()
std::vector< Solution_rt > Solution::get_postgres_result () const inherited
get solution like postgres needs it
Returns
container for postgres
Definition at line 61 of file solution.cpp.
{
   std::vector<Solution_rt> result;
   /* postgres numbering starts with 1 */
   int i(1);
   for (auto v : m_fleet) {
     v.evaluate(0);
     auto data = v.get_postgres_result(i);
     /*
      * Results adjusted for the depot and the first stop
      * So the vehicle waits on the depot not on the first stop
      */
     data[1].arrivalTime = data[1].operationTime;
     data[0].waitDuration = data[1].waitDuration;
     data[1].waitDuration = 0;
     data[0].departureTime = data[0].arrivalTime + data[0].waitDuration;
     result.insert(result.end(), data.begin(), data.end());
     ++i;
   }
   Solution_rt aggregates = {
     /*
      * Vehicle id = -2 indicates its an aggregate row
      *
      * (twv, cv, fleet, wait, duration)
      */
     -2,  // summary row on vehicle_number
     twvTot(),  // on vehicle_id
     cvTot(),   // on vehicle_seq
     -1,  // on order_id
     -1,  // on stop_id
     -2,  // on stop_type (gets increased later by one so it gets -1)
     -1,  // not accounting total loads
     static_cast<int64_t>(total_travel_time()),
     -1,  // not accounting arrival_travel_time
     static_cast<int64_t>(wait_time()),
     -1,  // not accounting operation time
     static_cast<int64_t>(total_service_time()),
     static_cast<int64_t>(duration()),
     cvTot(),
     twvTot()
   };
   result.push_back(aggregates);
   return result;
 }
References vrprouting::problem::Solution::cvTot(), vrprouting::problem::Solution::duration(), vrprouting::problem::Solution::m_fleet, vrprouting::problem::Solution::total_service_time(), vrprouting::problem::Solution::total_travel_time(), vrprouting::problem::Solution::twvTot(), and vrprouting::problem::Solution::wait_time().
get_stops()
std::vector< Short_vehicle > Solution::get_stops () const inherited
get solution like postgres needs it
Returns
container for postgres
Definition at line 49 of file solution.cpp.
{
   std::vector<Short_vehicle> result;
   for (auto v : m_fleet) {
     result.push_back(Short_vehicle{v.id(), v.get_stops()});
   }
   return result;
 }
References Short_vehicle::id, and vrprouting::problem::Solution::m_fleet.
inter_swap() [1/2]
bool vrprouting::optimizers::simple::Optimize::inter_swap () private
Definition at line 87 of file optimizers/simple.cpp.
                      {
     msg().log
         << "\n" <<tau("before inter swap");
     delete_empty_truck();
     auto swapped_f = false;
     /*
      *   .. to ... from ....
      */
     for (auto &from : m_fleet) {
         for (auto &to : m_fleet) {
             if (&from == &to) break;
 #if 0
             msg().log
                 << "\n to " << to.id()
                 << "from " << from.id();
             auto swapped = false;
 #endif
             swap_worse(to, from);
             move_reduce_cost(from, to);
 #if 0
             msg().log << "++++++++" << p_swaps;
 #endif
         }
     }
 #if 0
     while (!p_swaps.empty()) {
         swapped_f = swap_order() || swapped_f;
     }
 #endif
     msg().log
         << "\n" <<tau("after");
     delete_empty_truck();
     return swapped_f;
 }
References delete_empty_truck(), vrprouting::Pgr_messages::log, vrprouting::problem::Solution::m_fleet, move_reduce_cost(), vrprouting::problem::Solution::msg(), swap_order(), swap_worse(), and vrprouting::problem::Solution::tau().
Referenced by inter_swap(), and Optimize().
inter_swap() [2/2]
void vrprouting::optimizers::simple::Optimize::inter_swap (size_t times)
Definition at line 59 of file optimizers/simple.cpp.
{
     msg().log << tau("before sort by size");
     sort_by_size();
     msg().log << tau("before decrease");
     decrease_truck();
     msg().log << tau("after decrease");
     sort_by_size();
     msg().log << tau("after sort by size");
     size_t i = 0;
     while (i++ < times) {
         msg().log << "\n*************************** CYCLE" << i;
         inter_swap();
         msg().log << tau("after inter swap");
         std::rotate(m_fleet.begin(), m_fleet.begin() + 1, m_fleet.end());
         msg().log << tau("before next cycle");
     }
 }
References decrease_truck(), inter_swap(), vrprouting::Pgr_messages::log, vrprouting::problem::Solution::m_fleet, vrprouting::problem::Solution::msg(), sort_by_size(), and vrprouting::problem::Solution::tau().
is_feasible()
bool Solution::is_feasible () const inherited
is the solution feasible?
The solution is feasible when all vehicles are feasible.
Returns
true when all vehicles in solution are feasible
Definition at line 129 of file solution.cpp.
{
   return std::find_if(m_fleet.begin(), m_fleet.end(),
       [] (const Vehicle_pickDeliver& v) -> bool {return !v.is_feasible();}) == m_fleet.end();
 }
References vrprouting::problem::Solution::m_fleet.
Referenced by decrease_truck(), vrprouting::initialsol::simple::Initial_solution::do_while_feasible(), vrprouting::initialsol::simple::Initial_solution::do_while_foo(), vrprouting::initialsol::tabu::Initial_solution::Initial_solution(), vrprouting::initialsol::tabu::Initial_solution::process_given_solution_from_user(), and vrprouting::initialsol::tabu::Initial_solution::process_unassigned().
move_duration_based()
void vrprouting::optimizers::simple::Optimize::move_duration_based ()
move_order()
bool vrprouting::optimizers::simple::Optimize::move_order (problem::Order order, problem::Vehicle_pickDeliver & from_truck, problem::Vehicle_pickDeliver & to_truck) private
moves an order to an non empty vehicle
order: order to be moved from_truck: here is the order to truck: truck to put the order
to check if the order was inserted: to_truck.has_order(order)
Returns
bool: when move was done
Definition at line 467 of file optimizers/simple.cpp.
{
     pgassert(from_truck.has_order(order));
     pgassert(!to_truck.has_order(order));
     /*
      * don't move to empty truck
      */
     if (to_truck.empty()) return false;
     /*
      * don't move from a real truck to a phoney truck
      */
     if (!from_truck.is_phony() && to_truck.is_phony()) return false;
     /*
      * Don't move from a vehicle with more orders
      */
     if (from_truck.size() > to_truck.size()) return false;
     /*
      * insert the order
      */
     get_kind() == initialsol::simple::Initials_code::OneDepot?
         to_truck.semiLIFO(order) :
         to_truck.hillClimb(order);
     if (to_truck.has_order(order)) {
         from_truck.erase(order);
         pgassert(!(from_truck.has_order(order) && to_truck.has_order(order)));
         pgassert(!from_truck.has_order(order));
         pgassert(to_truck.has_order(order));
         return true;
     }
     pgassert(!(from_truck.has_order(order) && to_truck.has_order(order)));
     pgassert(from_truck.has_order(order));
     pgassert(!to_truck.has_order(order));
     return false;
 }
References vrprouting::problem::Vehicle_pickDeliver::empty(), vrprouting::problem::Vehicle_pickDeliver::erase(), get_kind(), vrprouting::problem::Vehicle_pickDeliver::has_order(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::problem::Vehicle::is_phony(), vrprouting::initialsol::simple::OneDepot, pgassert, and vrprouting::problem::Vehicle_pickDeliver::semiLIFO().
Referenced by swap_worse().
move_reduce_cost()
bool vrprouting::optimizers::simple::Optimize::move_reduce_cost (problem::Vehicle_pickDeliver & from, problem::Vehicle_pickDeliver & to) private
Definition at line 385 of file optimizers/simple.cpp.
{
     pgassert(&from != &to);
     auto from_truck = from;
     auto to_truck = to;
     /*
      * don't move to empty truck
      */
     if (to_truck.empty()) return false;
     /*
      * don't move from a real truck to a phoney truck
      */
     if (!from_truck.is_phony() && to_truck.is_phony()) {
         return false;
     }
     auto moved = false;
     auto from_orders = from_truck.orders_in_vehicle();
     for (const auto o_id : from_orders) {
         /*
          * removing an order decreases the duration
          */
         auto order = from_truck.orders()[o_id];
         auto curr_duration = from_truck.duration() + to_truck.duration();
         /*
          * insert it in the "to" truck
          */
         pgassert(!to_truck.has_order(order));
         get_kind() == initialsol::simple::Initials_code::OneDepot?
             to_truck.semiLIFO(order) :
             to_truck.hillClimb(order);
         pgassert((to_truck.has_order(order) && to_truck.is_feasible()) || !to_truck.has_order(order));
         if (to_truck.has_order(order)) {
             from_truck.erase(order);
             auto new_duration = from_truck.duration() + to_truck.duration();
             /*
              * cost is reduced
              */
             if (new_duration < curr_duration
                    || from_truck.empty()
                    || new_duration < best_solution.duration()) {
                 moved = true;
                 save_if_best();
                 continue;
             }
             /*
              * cost is not reduced
              * revert changes
              */
             to_truck.erase(order);
             get_kind() == initialsol::simple::Initials_code::OneDepot?
                 from_truck.semiLIFO(order) :
                 from_truck.hillClimb(order);
         }
     }
     return moved;
 }
References best_solution, get_kind(), vrprouting::initialsol::simple::OneDepot, vrprouting::problem::Vehicle_pickDeliver::orders_in_vehicle(), pgassert, and save_if_best().
Referenced by inter_swap().
move_wait_time_based()
void vrprouting::optimizers::simple::Optimize::move_wait_time_based ()
msg()
Pgr_messages& vrprouting::problem::Solution::msg () inline inherited
Definition at line 119 of file solution.h.
 {return m_msg;}
References vrprouting::problem::Solution::m_msg.
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_foo(), inter_swap(), vrprouting::optimizers::tabu::Optimize::move_2_real(), vrprouting::initialsol::simple::Initial_solution::one_truck_all_orders(), Optimize(), vrprouting::optimizers::tabu::Optimize::Optimize(), vrprouting::initialsol::tabu::Initial_solution::process_unassigned(), save_if_best(), and vrprouting::optimizers::tabu::Optimize::tabu_search().
objective()
double vrprouting::problem::Solution::objective () const inline inherited
Get the value of the objective function.
Definition at line 110 of file solution.h.
 {return static_cast<double>(total_travel_time());}
References vrprouting::problem::Solution::total_travel_time().
Referenced by vrprouting::optimizers::tabu::Optimize::move_2_real(), vrprouting::optimizers::tabu::Optimize::single_pair_insertion(), vrprouting::optimizers::tabu::Optimize::swap_between_routes(), and vrprouting::optimizers::tabu::Optimize::tabu_search().
operator<()
bool Solution::operator< (const Solution & s_rhs) const inherited
Definition at line 267 of file solution.cpp.
{
   auto lhs(cost());
   auto rhs(s_rhs.cost());
   /*
    * time window violations
    */
   if (std::get<0>(lhs) < std::get<0>(rhs))
     return true;
   if (std::get<0>(lhs) > std::get<0>(rhs))
     return false;
   /*
    * capacity violations
    */
   if (std::get<1>(lhs) < std::get<1>(rhs))
     return true;
   if (std::get<1>(lhs) > std::get<1>(rhs))
     return false;
   /*
    * fleet size
    */
   if (std::get<2>(lhs) < std::get<2>(rhs))
     return true;
   if (std::get<2>(lhs) > std::get<2>(rhs))
     return false;
   /*
    * waiting time
    */
   if (std::get<3>(lhs) < std::get<3>(rhs))
     return true;
   if (std::get<3>(lhs) > std::get<3>(rhs))
     return false;
   /*
    * duration
    */
   if (std::get<4>(lhs) < std::get<4>(rhs))
     return true;
   if (std::get<4>(lhs) > std::get<4>(rhs))
     return false;
   return false;
 }
References vrprouting::problem::Solution::cost().
orders()
const Orders& vrprouting::problem::Solution::orders () const inline inherited
Definition at line 120 of file solution.h.
 {return m_orders;}
References vrprouting::problem::Solution::m_orders.
Referenced by decrease_truck(), vrprouting::optimizers::tabu::Optimize::diversify(), vrprouting::optimizers::tabu::Optimize::move_2_real(), vrprouting::initialsol::tabu::Initial_solution::process_given_solution_from_user(), vrprouting::initialsol::tabu::Initial_solution::process_unassigned(), vrprouting::optimizers::tabu::Optimize::set_tabu_list_length(), vrprouting::optimizers::tabu::Optimize::single_pair_insertion(), and vrprouting::optimizers::tabu::Optimize::swap_between_routes().
save_if_best()
void vrprouting::optimizers::simple::Optimize::save_if_best () private
Definition at line 579 of file optimizers/simple.cpp.
{
     if (duration() < best_solution.duration()) {
         best_solution = (*this);
         msg().log << "\n*********** best by duration"
             << best_solution.cost_str();
 #if 0
         msg().dbg_log << best_solution.tau("best by duration");
 #endif
     }
     if (m_fleet.size() < best_solution.fleet().size()) {
         best_solution = (*this);
         msg().log << "\n*********** best by fleet size"
             << best_solution.cost_str();
 #if 0
         msg().dbg_log << best_solution.tau("best by fleet size");
 #endif
     }
 }
References best_solution, vrprouting::problem::Solution::duration(), vrprouting::Pgr_messages::log, vrprouting::problem::Solution::m_fleet, and vrprouting::problem::Solution::msg().
Referenced by decrease_truck(), delete_empty_truck(), and move_reduce_cost().
sort_by_duration()
void vrprouting::optimizers::simple::Optimize::sort_by_duration () private
Definition at line 354 of file optimizers/simple.cpp.
{
     std::sort(m_fleet.begin(), m_fleet.end(), []
             (const problem::Vehicle_pickDeliver &lhs, const problem::Vehicle_pickDeliver &rhs)
             -> bool {
             return lhs.duration() > rhs.duration();
             });
 }
References vrprouting::problem::Solution::m_fleet.
Referenced by sort_by_size().
sort_by_id()
void vrprouting::optimizers::simple::Optimize::sort_by_id () private
Definition at line 333 of file optimizers/simple.cpp.
                      {
     std::sort(m_fleet.begin(), m_fleet.end(), []
             (const problem::Vehicle_pickDeliver &lhs, const problem::Vehicle_pickDeliver &rhs)
             -> bool {
             return lhs.orders_in_vehicle().size()
             > rhs.orders_in_vehicle().size();
             });
 }
References vrprouting::problem::Solution::m_fleet.
sort_by_size()
void vrprouting::optimizers::simple::Optimize::sort_by_size () private
Definition at line 343 of file optimizers/simple.cpp.
{
     sort_by_duration();
     std::stable_sort(m_fleet.begin(), m_fleet.end(), []
             (const problem::Vehicle_pickDeliver &lhs, const problem::Vehicle_pickDeliver &rhs)
             -> bool {
             return lhs.orders_in_vehicle().size()
             > rhs.orders_in_vehicle().size();
             });
 }
References vrprouting::problem::Solution::m_fleet, and sort_by_duration().
Referenced by inter_swap(), and Optimize().
sort_for_move()
void vrprouting::optimizers::simple::Optimize::sort_for_move () private
Definition at line 511 of file optimizers/simple.cpp.
{
     std::sort(m_fleet.begin(), m_fleet.end(), []
             (const problem::Vehicle_pickDeliver &lhs, const problem::Vehicle_pickDeliver &rhs)
             -> bool {
             return lhs.total_wait_time() > rhs.total_wait_time();
             });
     std::stable_sort(m_fleet.begin(), m_fleet.end(), []
             (const problem::Vehicle_pickDeliver &lhs, const problem::Vehicle_pickDeliver &rhs)
             -> bool {
             return lhs.orders_size() > rhs.orders_size();
             });
 }
References vrprouting::problem::Solution::m_fleet.
swap_order() [1/2]
bool vrprouting::optimizers::simple::Optimize::swap_order () private
Referenced by inter_swap().
swap_order() [2/2]
bool vrprouting::optimizers::simple::Optimize::swap_order (problem::Order from_order, problem::Vehicle_pickDeliver & from_truck, problem::Order to_order, problem::Vehicle_pickDeliver & to_truck) private
Definition at line 269 of file optimizers/simple.cpp.
{
     if (!from_truck.has_order(from_order)
             || !to_truck.has_order(to_order)) {
         return false;
     }
     pgassert(from_truck.has_order(from_order));
     pgassert(to_truck.has_order(to_order));
     from_truck.erase(from_order);
     to_truck.erase(to_order);
     /*
      * insert them in the other truck
      */
     if (get_kind() == initialsol::simple::Initials_code::OneDepot) {
         from_truck.semiLIFO(to_order);
         to_truck.semiLIFO(from_order);
     } else {
         from_truck.hillClimb(to_order);
         to_truck.hillClimb(from_order);
     }
     pgassert((from_truck.has_order(to_order) && from_truck.is_feasible()) || !from_truck.has_order(to_order));
     pgassert((to_truck.has_order(from_order) && to_truck.is_feasible()) || !to_truck.has_order(from_order));
     if (!from_truck.has_order(to_order) || !to_truck.has_order(from_order)) {
         /*
          * swap generates a violation: restore trucks
          */
         if (from_truck.has_order(to_order)) from_truck.erase(to_order);
         if (to_truck.has_order(from_order)) to_truck.erase(from_order);
         pgassert(!from_truck.has_order(to_order));
         pgassert(!from_truck.has_order(from_order));
         pgassert(!to_truck.has_order(from_order));
         pgassert(!to_truck.has_order(to_order));
         /*
          * insert them again in the truck
          */
         if (get_kind() == initialsol::simple::Initials_code::OneDepot) {
             from_truck.semiLIFO(from_order);
             to_truck.semiLIFO(to_order);
         } else {
             from_truck.hillClimb(from_order);
             to_truck.hillClimb(to_order);
         }
         pgassert((from_truck.has_order(from_order) && from_truck.is_feasible()) || !from_truck.has_order(from_order));
         pgassert((to_truck.has_order(to_order) && to_truck.is_feasible()) || !to_truck.has_order(to_order));
         return false;
     }
     pgassert(from_truck.has_order(to_order));
     pgassert(to_truck.has_order(from_order));
     return true;
 }
References vrprouting::problem::Vehicle_pickDeliver::erase(), get_kind(), vrprouting::problem::Vehicle_pickDeliver::has_order(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::problem::Vehicle_pickDeliver::is_feasible(), vrprouting::initialsol::simple::OneDepot, pgassert, and vrprouting::problem::Vehicle_pickDeliver::semiLIFO().
swap_worse()
bool vrprouting::optimizers::simple::Optimize::swap_worse (problem::Vehicle_pickDeliver & from, problem::Vehicle_pickDeliver & to) private
Definition at line 132 of file optimizers/simple.cpp.
{
     /*
      * working on a copy of the vehicles
      */
     auto from_truck = from;
     auto to_truck = to;
     auto swapped = false;
     /*
      * To avoid invalidation of cycles
      */
     auto o_from_orders = from_truck.orders_in_vehicle();
     auto o_to_orders = to_truck.orders_in_vehicle();
     pgassert((o_from_orders * o_to_orders).empty());
     for (auto from_orders = from_truck.orders_in_vehicle();
             !from_orders.empty();
             from_orders.pop_front()) {
         auto from_order = from_truck.orders()[from_orders.front()];
         pgassert(from_truck.has_order(from_order));
         if (move_order(from_order, from_truck, to_truck)) {
             pgassert(!from_truck.has_order(from_order));
             pgassert(to_truck.has_order(from_order));
             /*
              * The order could be moved to "to" truck
              */
             to = to_truck;
             from = from_truck;
             /*
              * go to next order
              */
             pgassert(!from.has_order(from_order));
             pgassert(to.has_order(from_order));
             pgassert(!from_truck.has_order(from_order));
             pgassert(to_truck.has_order(from_order));
             pgassert(!(from.has_order(from_order) && to.has_order(from_order)));
             pgassert(from.has_order(from_order) || to.has_order(from_order));
             continue;
         }
         pgassert(from_truck.has_order(from_order));
         auto curr_from_duration = from_truck.duration();
         for (auto to_order_id : o_to_orders) {
             auto to_order = to.orders()[to_order_id];
             /*
              * The orders might have being swapped before
              */
             if (!to_truck.has_order(to_order)) continue;
             // if (!from_truck.has_order(from_order)) break; // TODO delete line
             pgassert(from_truck.has_order(from_order));
             pgassert(to_truck.has_order(to_order));
             auto curr_to_duration = to_truck.duration();
             /*
              * delete from_order, and to order from their trucks
              */
             pgassert(from_truck.has_order(from_order));
             from_truck.erase(from_order);
             pgassert(to_truck.has_order(to_order));
             to_truck.erase(to_order);
             /*
              * insert them in the other truck
              */
             if (get_kind() == initialsol::simple::Initials_code::OneDepot) {
                 from_truck.semiLIFO(to_order);
                 to_truck.semiLIFO(from_order);
             } else {
                 from_truck.hillClimb(to_order);
                 to_truck.hillClimb(from_order);
             }
             pgassert((from_truck.has_order(to_order) && from_truck.is_feasible()) || !from_truck.has_order(to_order));
             pgassert((to_truck.has_order(from_order) && to_truck.is_feasible()) || !to_truck.has_order(from_order));
             if (from_truck.has_order(to_order) && to_truck.has_order(from_order)) {
                 auto new_from_duration = from_truck.duration();
                 auto new_to_duration = to_truck.duration();
                 auto estimated_delta =
                     - (curr_from_duration + curr_to_duration)
                     + (new_to_duration + new_from_duration);
                 auto estimated_duration = duration() + estimated_delta;
                 /*
                  * Can swap when:
                  *   - or from_truck duration is reduced
                  *   - the total fleet duration is reduced
                  *   - or the new fleet duration is better than best_solution duration
                  */
                 if (new_from_duration < curr_from_duration ||
                         estimated_delta < 0 ||
                         estimated_duration < best_solution.duration()) {
                     /*
                      * this acctually makes the swapping
                      */
                     to = to_truck;
                     from = from_truck;
                     pgassert(!(from.has_order(from_order) && to.has_order(from_order)));
                     pgassert(from.has_order(from_order) || to.has_order(from_order));
                     pgassert(!(from.has_order(to_order) && to.has_order(to_order)));
                     pgassert(from.has_order(to_order) || to.has_order(to_order));
                     swapped = true;
                     break;
                 }
             }
             /*
              * Can't swap, restore vehicles
              */
             to_truck = to;
             from_truck = from;
             pgassert(!(from.has_order(from_order) && to.has_order(from_order)));
             pgassert(from.has_order(from_order) || to.has_order(from_order));
             pgassert(!(from.has_order(to_order) && to.has_order(to_order)));
             pgassert(from.has_order(to_order) || to.has_order(to_order));
         }
     }
     return false && swapped;
 }
References best_solution, vrprouting::problem::Solution::duration(), get_kind(), vrprouting::problem::Vehicle_pickDeliver::has_order(), move_order(), vrprouting::initialsol::simple::OneDepot, vrprouting::problem::Vehicle_pickDeliver::orders(), vrprouting::problem::Vehicle_pickDeliver::orders_in_vehicle(), and pgassert.
Referenced by inter_swap().
tau()
std::string Solution::tau (const std::string & title = "Tau") const inherited
writing the solution in compact form into a string
Parameters
[in] title Title to Use for the tau
Returns
The solution in one compacted string
Definition at line 116 of file solution.cpp.
{
   std::string str {"\n" + title + ": " + '\n'};
   for (const auto& v : m_fleet) str += ("\n" + v.tau());
   str += "\n" + cost_str() + "\n";
   return str;
 }
References vrprouting::problem::Solution::cost_str(), and vrprouting::problem::Solution::m_fleet.
Referenced by inter_swap(), Optimize(), and vrprouting::optimizers::tabu::Optimize::Optimize().
total_service_time()
TInterval Solution::total_service_time () const inherited
Total service time of the solution.
Returns
the total service time of the solution
The total service time of the solution is the sum of the service times of all vehicles
Definition at line 174 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), static_cast<TInterval>(0),
       [](TInterval i, const Vehicle_pickDeliver& v) {return v.total_service_time() + i;});
 }
References vrprouting::problem::Solution::m_fleet, and vrprouting::problem::Vehicle::total_service_time().
Referenced by vrprouting::problem::Solution::get_postgres_result().
total_travel_time()
TInterval Solution::total_travel_time () const inherited
Total travel time of the solution.
Returns
the total waiting time
The total travel time of the solution is the sum of the travel times of all vehicles
Definition at line 162 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), static_cast<TInterval>(0),
       [](TInterval i, const Vehicle_pickDeliver& v) {return v.total_travel_time() + i;});
 }
References vrprouting::problem::Solution::m_fleet, and vrprouting::problem::Vehicle::total_travel_time().
Referenced by vrprouting::problem::Solution::get_postgres_result(), and vrprouting::problem::Solution::objective().
twvTot()
int Solution::twvTot () const inherited
Total number of time windows constraint violations of the solution.
Returns
the total number of time window violations
The total time window violations of the solution is the sum of the time window violations of all vehicles
Definition at line 185 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), 0,
       [](int i, const Vehicle_pickDeliver& v) {return v.twvTot() + i;});
 }
References vrprouting::problem::Solution::m_fleet, and vrprouting::problem::Vehicle::twvTot().
Referenced by vrprouting::problem::Solution::get_postgres_result().
vehicles()
Fleet& vrprouting::problem::Solution::vehicles () inline inherited
Definition at line 121 of file solution.h.
 {return m_trucks;}
References vrprouting::problem::Solution::m_trucks.
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_foo(), vrprouting::initialsol::tabu::Initial_solution::Initial_solution(), vrprouting::initialsol::simple::Initial_solution::one_truck_all_orders(), vrprouting::initialsol::tabu::Initial_solution::process_given_solution_from_user(), and vrprouting::initialsol::tabu::Initial_solution::process_unassigned().
wait_time()
TInterval Solution::wait_time () const inherited
Total waiting time of the solution.
Returns
the total waiting time
The total waiting time of the solution is the sum of the waiting time of all vehicles
Definition at line 151 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), static_cast<TInterval>(0),
       [](TInterval i, const Vehicle_pickDeliver& v) {return v.total_wait_time() + i;});
 }
References vrprouting::problem::Solution::m_fleet, and vrprouting::problem::Vehicle::total_wait_time().
Referenced by vrprouting::problem::Solution::get_postgres_result().
Member Data Documentation
best_solution
Solution vrprouting::optimizers::simple::Optimize::best_solution
Definition at line 54 of file optimizers/simple.h.
Referenced by move_reduce_cost(), Optimize(), save_if_best(), and swap_worse().
m_fleet
std::deque<Vehicle_pickDeliver> vrprouting::problem::Solution::m_fleet protected inherited
The current solution.
Definition at line 125 of file solution.h.
Referenced by vrprouting::problem::Solution::cost(), vrprouting::problem::Solution::cvTot(), decrease_truck(), delete_empty_truck(), vrprouting::optimizers::tabu::Optimize::diversify(), vrprouting::initialsol::simple::Initial_solution::do_while_foo(), vrprouting::problem::Solution::duration(), vrprouting::problem::Solution::fleet(), vrprouting::problem::Solution::get_postgres_result(), vrprouting::problem::Solution::get_stops(), vrprouting::initialsol::tabu::Initial_solution::Initial_solution(), vrprouting::optimizers::tabu::Optimize::intensify(), inter_swap(), vrprouting::problem::Solution::is_feasible(), vrprouting::optimizers::tabu::Optimize::move_2_real(), vrprouting::initialsol::simple::Initial_solution::one_truck_all_orders(), Optimize(), vrprouting::optimizers::tabu::Optimize::Optimize(), vrprouting::initialsol::tabu::Initial_solution::process_given_solution_from_user(), vrprouting::initialsol::tabu::Initial_solution::process_unassigned(), save_if_best(), vrprouting::optimizers::tabu::Optimize::single_pair_insertion(), sort_by_duration(), sort_by_id(), sort_by_size(), vrprouting::optimizers::tabu::Optimize::sort_by_size(), sort_for_move(), vrprouting::optimizers::tabu::Optimize::swap_between_routes(), vrprouting::optimizers::tabu::Optimize::tabu_search(), vrprouting::problem::Solution::tau(), vrprouting::problem::Solution::total_service_time(), vrprouting::problem::Solution::total_travel_time(), vrprouting::problem::Solution::twvTot(), and vrprouting::problem::Solution::wait_time().
m_kind
Initials_code vrprouting::optimizers::simple::Optimize::m_kind private
Definition at line 83 of file optimizers/simple.h.
Referenced by get_kind().
m_msg
Pgr_messages vrprouting::problem::Solution::m_msg protected inherited
Definition at line 130 of file solution.h.
Referenced by vrprouting::problem::Solution::msg().
m_orders
Orders vrprouting::problem::Solution::m_orders protected inherited
the problem info
Definition at line 128 of file solution.h.
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_feasible(), and vrprouting::problem::Solution::orders().
m_trucks
Fleet vrprouting::problem::Solution::m_trucks protected inherited
Definition at line 129 of file solution.h.
Referenced by vrprouting::problem::Solution::vehicles().
The documentation for this class was generated from the following files:
optimizers/simple.h
optimizers/simple.cpp