vrpRouting: jobs_input.c File Reference
jobs_input.c File Reference
#include "c_common/vroom/jobs_input.h"
Functions
static void db_get_jobs (char *jobs_sql, Vroom_job_t **jobs, size_t *total_jobs, Column_info_t *info, const int column_count, bool is_plain)
static void fetch_jobs (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t *info, Vroom_job_t *job, bool is_plain)
void get_vroom_jobs (char *sql, Vroom_job_t **rows, size_t *total_rows, bool is_plain)
Reads the VROOM jobs.
Function Documentation
db_get_jobs()
static void db_get_jobs (char * jobs_sql, Vroom_job_t ** jobs, size_t * total_jobs, Column_info_t * info, const int column_count, bool is_plain) static
Definition at line 124 of file jobs_input.c.
                    {
 #ifdef PROFILE
   clock_t start_t = clock();
   PGR_DBG("%s", jobs_sql);
 #endif
   const int tuple_limit = 1000000;
   size_t total_tuples;
   void *SPIplan;
   SPIplan = pgr_SPI_prepare(jobs_sql);
   Portal SPIportal;
   SPIportal = pgr_SPI_cursor_open(SPIplan);
   bool moredata = true;
   (*total_jobs) = total_tuples = 0;
   /* on the first tuple get the column numbers */
   while (moredata == true) {
     SPI_cursor_fetch(SPIportal, true, tuple_limit);
     if (total_tuples == 0) {
       pgr_fetch_column_info(info, column_count);
     }
     size_t ntuples = SPI_processed;
     total_tuples += ntuples;
     if (ntuples > 0) {
       if ((*jobs) == NULL)
         (*jobs) = (Vroom_job_t *)palloc0(
             total_tuples * sizeof(Vroom_job_t));
       else
         (*jobs) = (Vroom_job_t *)repalloc(
             (*jobs),
             total_tuples * sizeof(Vroom_job_t));
       if ((*jobs) == NULL) {
         elog(ERROR, "Out of memory");
       }
       size_t t;
       SPITupleTable *tuptable = SPI_tuptable;
       TupleDesc tupdesc = SPI_tuptable->tupdesc;
       for (t = 0; t < ntuples; t++) {
         HeapTuple tuple = tuptable->vals[t];
         fetch_jobs(&tuple, &tupdesc, info,
             &(*jobs)[total_tuples - ntuples + t], is_plain);
       }
       SPI_freetuptable(tuptable);
     } else {
       moredata = false;
     }
   }
   SPI_cursor_close(SPIportal);
   if (total_tuples == 0) {
     (*total_jobs) = 0;
     return;
   }
   (*total_jobs) = total_tuples;
 #ifdef PROFILE
   time_msg("reading jobs", start_t, clock());
 #endif
 }
References fetch_jobs(), PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), and time_msg().
Referenced by get_vroom_jobs().
fetch_jobs()
static void fetch_jobs (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t * info, Vroom_job_t * job, bool is_plain) static
Definition at line 83 of file jobs_input.c.
                    {
   job->id = get_Idx(tuple, tupdesc, info[0], 0);
   job->location_index = get_MatrixIndex(tuple, tupdesc, info[1], 0);
   if (is_plain) {
     job->service = get_Duration(tuple, tupdesc, info[2], 0);
   } else {
     job->service = (Duration)get_PositiveTInterval(tuple, tupdesc, info[2], 0);
   }
   /*
    * The deliveries
    */
   job->delivery_size = 0;
   job->delivery = column_found(info[3].colNumber) ?
     spi_getPositiveBigIntArr_allowEmpty(tuple, tupdesc, info[3], &job->delivery_size)
     : NULL;
   /*
    * The pickups
    */
   job->pickup_size = 0;
   job->pickup = column_found(info[4].colNumber) ?
     spi_getPositiveBigIntArr_allowEmpty(tuple, tupdesc, info[4], &job->pickup_size)
     : NULL;
   job->skills_size = 0;
   job->skills = column_found(info[5].colNumber) ?
     spi_getPositiveIntArr_allowEmpty(tuple, tupdesc, info[5], &job->skills_size)
     : NULL;
   job->priority = get_Priority(tuple, tupdesc, info[6], 0);
 }
References column_found(), Vroom_job_t::delivery, Vroom_job_t::delivery_size, get_Duration(), get_Idx(), get_MatrixIndex(), get_PositiveTInterval(), get_Priority(), Vroom_job_t::id, Vroom_job_t::location_index, Vroom_job_t::pickup, Vroom_job_t::pickup_size, Vroom_job_t::priority, Vroom_job_t::service, Vroom_job_t::skills, Vroom_job_t::skills_size, spi_getPositiveBigIntArr_allowEmpty(), and spi_getPositiveIntArr_allowEmpty().
Referenced by db_get_jobs().
get_vroom_jobs()
void get_vroom_jobs (char * sql, Vroom_job_t ** rows, size_t * total_rows, bool is_plain)
Reads the VROOM jobs.
Parameters
[in] sql SQL query to execute
[out] rows C Container that holds the data
[out] total_rows Total rows recieved
Definition at line 205 of file jobs_input.c.
                    {
   int kColumnCount = 7;
   Column_info_t info[kColumnCount];
   for (int i = 0; i < kColumnCount; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = false;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "id";
   info[1].name = "location_index";
   info[2].name = "service";
   info[3].name = "delivery";
   info[4].name = "pickup";
   info[5].name = "skills";
   info[6].name = "priority";
   info[2].eType = INTEGER;            // service
   info[3].eType = ANY_INTEGER_ARRAY;  // delivery
   info[4].eType = ANY_INTEGER_ARRAY;  // pickup
   info[5].eType = INTEGER_ARRAY;      // skills
   info[6].eType = INTEGER;            // priority
   if (!is_plain) {
     info[2].eType = INTERVAL;         // service
   }
   /* Only id and location_index are mandatory */
   info[0].strict = true;
   info[1].strict = true;
   db_get_jobs(sql, rows, total_rows, info, kColumnCount, is_plain);
 }
References ANY_INTEGER, ANY_INTEGER_ARRAY, Column_info_t::colNumber, db_get_jobs(), Column_info_t::eType, INTEGER, INTEGER_ARRAY, INTERVAL, Column_info_t::name, Column_info_t::strict, and Column_info_t::type.
Referenced by process().