vrpRouting: vrprouting Namespace Reference
vrprouting Namespace Reference
Namespaces
vrp
Classes
class Identifier
Class that stores the information about identifiers.
class Matrix
class Pgr_messages
Messages Handling.
Functions
double get_distance (std::pair< double, double > p1, std::pair< double, double > p2)
std::ostream & operator<< (std::ostream &log, const Identifier &ident)
std::ostream & operator<< (std::ostream &log, const Matrix &matrix)
Function Documentation
get_distance()
double vrprouting::get_distance (std::pair< double, double > p1, std::pair< double, double > p2)
Definition at line 106 of file matrix.cpp.
{
     auto dx = p1.first - p2.first;
     auto dy = p1.second - p2.second;
     return std::sqrt(dx * dx + dy * dy);
 }
Referenced by vrprouting::Matrix::Matrix().
operator<<() [1/2]
std::ostream& vrprouting::operator<< (std::ostream & log, const Identifier & ident)
Definition at line 51 of file identifier.cpp.
{
     log << "id(idx) = " << ident.id() << "(" << ident.idx() << ")";
     return log;
 }
References vrprouting::Identifier::id(), and vrprouting::Identifier::idx().
operator<<() [2/2]
std::ostream& vrprouting::operator<< (std::ostream & log, const Matrix & matrix)
Definition at line 195 of file matrix.cpp.
{
     for (const auto id : matrix.ids) {
         log << "\t" << id;
     }
     log << "\n";
     size_t i = 0;
     for (const auto &row : matrix.costs) {
         size_t j = 0;
         for (const auto cost : row) {
             log << "Internal(" << i << "," << j << ")"
                 << "\tUsers(" << matrix.ids[i] << "," << matrix.ids[j] << ")"
                 << "\t = " << cost
 #if 0
                 << "\t(" << matrix.get_index(matrix.ids[i])
                 << "," << matrix.get_index(matrix.ids[j]) << ")"
                 << "\t = " << matrix.costs[i][j]
                 << "\t = " << matrix.costs[j][i]
                 << "=inf:"
                 <<  (matrix.costs[i][j] ==
                         (std::numeric_limits<double>::infinity)())
                 << "=inf:"
                 <<  (matrix.costs[j][i] ==
                         (std::numeric_limits<double>::infinity)())
 #endif
                 << "\n";
             ++j;
         }
         ++i;
     }
 #if 0
     for (size_t i = 0; i < matrix.costs.size(); ++i) {
         for (size_t j = 0; j < matrix.costs.size(); ++j) {
             for (size_t k = 0; k < matrix.costs.size(); ++k) {
                 log << matrix.costs[i][k] << " <= ("
                     << matrix.costs[i][j] << " + "  << matrix.costs[j][k] << ")"
                     << (matrix.costs[i][k]
                             <= (matrix.costs[i][j] + matrix.costs[j][k]))
                     << "\n";
             }
         }
     }
 #endif
     return log;
 }
References vrprouting::Matrix::costs, vrprouting::Matrix::get_index(), and vrprouting::Matrix::ids.