vrpRouting: vrprouting::vrp Namespace Reference
vrprouting::vrp Namespace Reference
Classes
class Base_node
The Base_node class defines the operations that can be performed in a 2D node.
class Dnode
The Dnode class defines a the basic operations when data is a matrix.
class Fleet
class Initial_solution
class Node
The Node class defines a point in 2D space with an id.
class Optimize
class Order
class PD_Orders
class PD_problem
class Pgr_pickDeliver
class Solution
class Tw_node
Extends the Node class to create a Node with time window attributes.
class Vehicle
Vehicle with time windows.
class Vehicle_node
Extend Tw_node to evaluate the vehicle at node level.
class Vehicle_pickDeliver
Enumerations
enum Initials_code {
OneTruck, OnePerTruck, FrontTruck, BackTruck,
BestInsert, BestBack, BestFront, OneDepot
}
Different kinds to insert an order into the vehicle.
Functions
bool operator< (const Vehicle &lhs, const Vehicle &rhs)
std::ostream & operator<< (std::ostream &log, const Dnode &node)
std::ostream & operator<< (std::ostream &log, const Fleet &f)
std::ostream & operator<< (std::ostream &log, const Node &node)
std::ostream & operator<< (std::ostream &log, const Order &order)
std::ostream & operator<< (std::ostream &log, const Solution &solution)
std::ostream & operator<< (std::ostream &log, const Tw_node &n)
Print the contents of a Twnode object.
std::ostream & operator<< (std::ostream &log, const Vehicle &v)
std::ostream & operator<< (std::ostream &log, const Vehicle_node &v)
std::ostream & operator<< (std::ostream &os, const Base_node &node)
Enumeration Type Documentation
Initials_code
enum vrprouting::vrp::Initials_code
Different kinds to insert an order into the vehicle.
Enumerator
OneTruck
OnePerTruck
All orders in one truck.
FrontTruck
One Order per truck.
BackTruck
Insetion at the front of the truck.
BestInsert
Insetion at the back of the truck.
BestBack
Best place to insert Order.
BestFront
Push back order that allows more orders to be inserted at the back.
OneDepot
Push front order that allows more orders to be inserted at the front.
Pick at front, drop at back, OneDepot for all vehicles
Definition at line 36 of file initials_code.h.
                    {
     OneTruck,
     OnePerTruck,
     FrontTruck,
     BackTruck,
     BestInsert,
     BestBack,
     BestFront,
     OneDepot
 };
Function Documentation
operator<()
bool vrprouting::vrp::operator< (const Vehicle & lhs, const Vehicle & rhs)
Definition at line 625 of file vehicle.cpp.
{
     lhs.invariant();
     rhs.invariant();
     if (lhs.m_path.size() < rhs.m_path.size()) return true;
     /* here because sizes are equal */
     if (lhs.m_path.back().total_travel_time()
             < rhs.m_path.back().total_travel_time()) return true;
     return false;
 }
References vrprouting::vrp::Vehicle::invariant(), and vrprouting::vrp::Vehicle::m_path.
operator<<() [1/9]
std::ostream& vrprouting::vrp::operator<< (std::ostream & log, const Dnode & node)
Definition at line 35 of file dnode.cpp.
{
     log << node.id()
         << "(" << node.idx() << ")";
     return log;
 }
References vrprouting::Identifier::id(), and vrprouting::Identifier::idx().
operator<<() [2/9]
std::ostream& vrprouting::vrp::operator<< (std::ostream & log, const Fleet & f)
Definition at line 437 of file fleet.cpp.
{
     log << "fleet\n";
     for (const auto &v : f.m_trucks) {
         log << v;
     }
     log << "end fleet\n";
     return log;
 }
References vrprouting::vrp::Fleet::m_trucks.
operator<<() [3/9]
std::ostream& vrprouting::vrp::operator<< (std::ostream & log, const Node & node)
Definition at line 49 of file node.cpp.
{
     node.print(log);
     return log;
 }
References vrprouting::vrp::Node::print().
operator<<() [4/9]
std::ostream& vrprouting::vrp::operator<< (std::ostream & log, const Order & order)
Definition at line 55 of file order.cpp.
{
     log << "\n\nOrder "
         << static_cast<Identifier>(order) << ": \n"
         << "\tPickup: " << order.pickup() << "\n"
         << "\tDelivery: " << order.delivery() << "\n\n"
         << "\tTravel time: "
         << order.pickup().travel_time_to(order.delivery(), 1);
     log << "\nThere are | {I}| = "
         << order.m_compatibleI.size()
         << " -> order(" << order.idx()
         << ") -> | {J}| = " << order.m_compatibleJ.size()
         << "\n\n {";
     for (const auto o : order.m_compatibleI) {
         log << o << ", ";
     }
     log << "} -> " << order.idx() << " -> {";
     for (const auto o : order.m_compatibleJ) {
         log << o << ", ";
     }
     log << "}";
     return log;
 }
References vrprouting::vrp::Order::delivery(), vrprouting::Identifier::idx(), vrprouting::vrp::Order::m_compatibleI, vrprouting::vrp::Order::m_compatibleJ, vrprouting::vrp::Order::pickup(), Identifiers< T >::size(), and vrprouting::vrp::Tw_node::travel_time_to().
operator<<() [5/9]
std::ostream& vrprouting::vrp::operator<< (std::ostream & log, const Solution & solution)
Definition at line 185 of file solution.cpp.
{
     for (const auto &vehicle : solution.fleet) {
         log << vehicle;
     }
     log << "\n SOLUTION:\n\n "
         << solution.tau();
     return log;
 }
References vrprouting::vrp::Solution::fleet, and vrprouting::vrp::Solution::tau().
operator<<() [6/9]
std::ostream& vrprouting::vrp::operator<< (std::ostream & log, const Tw_node & n)
Print the contents of a Twnode object.
Definition at line 286 of file tw_node.cpp.
{
     log << n.id()
         << "[opens = " << n.m_opens
         << "\tcloses = " << n.m_closes
         << "\tservice = " << n.m_service_time
         << "\tdemand = " << n.m_demand
         << "\ttype = " << n.type_str()
         << "]"
         << "\n";
     return log;
 }
References vrprouting::Identifier::id(), vrprouting::vrp::Tw_node::m_closes, vrprouting::vrp::Tw_node::m_demand, vrprouting::vrp::Tw_node::m_opens, vrprouting::vrp::Tw_node::m_service_time, and vrprouting::vrp::Tw_node::type_str().
operator<<() [7/9]
std::ostream& vrprouting::vrp::operator<< (std::ostream & log, const Vehicle & v)
Definition at line 607 of file vehicle.cpp.
{
     v.invariant();
     int i(0);
     log << "\n\n****************** " << v.idx() << "th VEHICLE*************\n";
     log << "id = " << v.id()
         << "\tcapacity = " << v.m_capacity
         << "\tfactor = " << v.m_factor << "\n"
         << "\tspeed = " << v.m_speed << "\n"
         << "\tnew speed = " << v.speed() << "\n";
     for (const auto &path_stop : v.path()) {
         log << "Path_stop" << ++i << "\n";
         log << path_stop << "\n";
     }
     return log;
 }
References vrprouting::Identifier::id(), vrprouting::Identifier::idx(), vrprouting::vrp::Vehicle::invariant(), vrprouting::vrp::Vehicle::m_capacity, vrprouting::vrp::Vehicle::m_factor, vrprouting::vrp::Vehicle::m_speed, vrprouting::vrp::Vehicle::path(), and vrprouting::vrp::Vehicle::speed().
operator<<() [8/9]
std::ostream& vrprouting::vrp::operator<< (std::ostream & log, const Vehicle_node & v)
Definition at line 101 of file vehicle_node.cpp.
{
     log << static_cast<const Tw_node&>(v)
         << " twv = " << v.has_twv()
         << ", twvTot = " << v.twvTot()
         << ", cvTot = " << v.cvTot()
         << ", cargo = " << v.cargo()
         << ", travel_time = " << v.travel_time()
         << ", arrival_time = " << v.arrival_time()
         << ", wait_time = " << v.wait_time()
         << ", service_time = " << v.service_time()
         << ", departure_time = " << v.departure_time();
     return log;
 }
References vrprouting::vrp::Vehicle_node::arrival_time(), vrprouting::vrp::Vehicle_node::cargo(), vrprouting::vrp::Vehicle_node::cvTot(), vrprouting::vrp::Vehicle_node::departure_time(), vrprouting::vrp::Vehicle_node::has_twv(), vrprouting::vrp::Tw_node::service_time(), vrprouting::vrp::Vehicle_node::travel_time(), vrprouting::vrp::Vehicle_node::twvTot(), and vrprouting::vrp::Vehicle_node::wait_time().
operator<<() [9/9]
std::ostream& vrprouting::vrp::operator<< (std::ostream & os, const Base_node & node)
Definition at line 33 of file base_node.cpp.
{
     return os << node.id()
         << "(" << node.idx() << ")";
 }
References vrprouting::Identifier::id(), and vrprouting::Identifier::idx().