vrpRouting: pickDeliver_driver.cpp File Reference
pgr_pickDeliver/pickDeliver_driver.cpp File Reference
#include "drivers/pgr_pickDeliver/pickDeliver_driver.h"
#include <string.h>
#include <sstream>
#include <string>
#include <deque>
#include <vector>
#include <utility>
#include "c_types/pickDeliveryOrders_t.h"
#include "c_types/solution_rt.h"
#include "c_common/pgr_alloc.hpp"
#include "cpp_common/pgr_assert.h"
#include "problem/solution.h"
#include "initialsol/simple.h"
#include "optimizers/simple.h"
#include "problem/pickDeliver.h"
#include "initialsol/initials_code.h"
#include "problem/matrix.h"
Namespaces
anonymous_namespace{pickDeliver_driver.cpp}
Functions
void do_pgr_pickDeliver (struct PickDeliveryOrders_t customers_arr[], size_t total_customers, Vehicle_t *vehicles_arr, size_t total_vehicles, Matrix_cell_t *matrix_cells_arr, size_t total_cells, double factor, int max_cycles, int initial_solution_id, Solution_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
vrprouting::problem::Solution anonymous_namespace{pickDeliver_driver.cpp}::get_initial_solution (vrprouting::problem::PickDeliver *problem_ptr, int m_initial_id)
Function Documentation
do_pgr_pickDeliver()
void do_pgr_pickDeliver (struct PickDeliveryOrders_t customers_arr[], size_t total_customers, Vehicle_t * vehicles_arr, size_t total_vehicles, Matrix_cell_t * matrix_cells_arr, size_t total_cells, double factor, int max_cycles, int initial_solution_id, Solution_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 75 of file pgr_pickDeliver/pickDeliver_driver.cpp.
{
     std::ostringstream log;
     std::ostringstream notice;
     std::ostringstream err;
     try {
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(total_customers);
         pgassert(total_vehicles);
         pgassert(total_vehicles);
         pgassert(*return_count == 0);
         pgassert(!(*return_tuples));
         log << "do_pgr_pickDeliver\n";
         *return_tuples = nullptr;
         *return_count = 0;
         Identifiers<Id> node_ids;
         Identifiers<Id> order_ids;
         for (size_t i = 0; i < total_customers; ++i) {
             node_ids += customers_arr[i].pick_node_id;
             node_ids += customers_arr[i].deliver_node_id;
             order_ids += customers_arr[i].id;
         }
         for (size_t i = 0; i < total_vehicles; ++i) {
             auto vehicle = vehicles_arr[i];
             node_ids += vehicle.start_node_id;
             node_ids += vehicle.end_node_id;
         }
         log << node_ids;
         /*
          * transform to C++ containers
          */
         std::vector<Vehicle_t> vehicles(
                 vehicles_arr, vehicles_arr + total_vehicles);
         vrprouting::problem::Matrix time_matrix(
                 matrix_cells_arr,
                 total_cells,
                 node_ids,
                 static_cast<Multiplier>(factor));
 #if 0
         auto depot_node = vehicles[0].start_node_id;
         /*
          * This applies to the one depot problem
          */
         if ((Initials_code)(initial_solution_id) == Initials_code::OneDepot) {
             /*
              * All Vehicles must depart from same location
              */
             for (const auto &v : vehicles) {
                 if (v.start_node_id != depot_node && v.end_node_id != depot_node) {
                     err << "All vehicles must depart & arrive to same node";
                     *err_msg = pgr_msg(err.str().c_str());
                     return;
                 }
             }
             /*
              * All Orders must depart from depot
              */
             for (size_t i = 0; i < total_customers; ++i) {
                 if (customers_arr[i].pick_node_id != depot_node) {
                     err << "All orders must be picked at depot";
                     *err_msg = pgr_msg(err.str().c_str());
                     return;
                 }
             }
         }
 #endif
         if (!time_matrix.has_no_infinity()) {
             err << "An Infinity value was found on the Matrix. Might be missing information of a node";
             *err_msg = pgr_msg(err.str().c_str());
             return;
         }
         // TODO(vicky) wrap with a try and make a throw???
         // tried it is already wrapped
         log << "Initialize problem\n";
         vrprouting::problem::PickDeliver pd_problem(
                 customers_arr, total_customers,
                 vehicles_arr, total_vehicles,
                 time_matrix);
         err << pd_problem.msg.get_error();
         if (!err.str().empty()) {
             log << pd_problem.msg.get_log();
             *log_msg = pgr_msg(log.str().c_str());
             *err_msg = pgr_msg(err.str().c_str());
             return;
         }
         log << pd_problem.msg.get_log();
         log << "Finish Reading data\n";
         pd_problem.msg.clear();
 #if 0
         try {
 #endif
         using Initials_code = vrprouting::initialsol::simple::Initials_code;
             auto sol = get_initial_solution(&pd_problem, initial_solution_id);
             using Optimize = vrprouting::optimizers::simple::Optimize;
             sol = Optimize(sol, static_cast<size_t>(max_cycles), (Initials_code)initial_solution_id);
 #if 0
         } catch (AssertFailedException &except) {
             log << pd_problem.msg.get_log();
             pd_problem.msg.clear();
             throw;
         } catch(...) {
             log << "Caught unknown exception!";
             throw;
         }
 #endif
         log << pd_problem.msg.get_log();
         log << "Finish solve\n";
         pd_problem.msg.clear();
         auto solution = sol.get_postgres_result();
         log << pd_problem.msg.get_log();
         pd_problem.msg.clear();
         log << "solution size: " << solution.size() << "\n";
         if (!solution.empty()) {
             (*return_tuples) = pgr_alloc(solution.size(), (*return_tuples));
             int seq = 0;
             for (const auto &row : solution) {
                 (*return_tuples)[seq] = row;
                 ++seq;
             }
         }
         (*return_count) = solution.size();
         pgassert(*err_msg == NULL);
         *log_msg = log.str().empty()?
             nullptr :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             nullptr :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         if (*return_tuples) free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception& except) {
         if (*return_tuples) free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (const std::pair<std::string, std::string>& ex) {
         (*return_count) = 0;
         err << ex.first;
         log << ex.second;
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (const std::pair<std::string, int64_t>& ex) {
         (*return_count) = 0;
         err << ex.first;
         log << "FOOOO missing on matrix: id =  " << ex.second;
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         if (*return_tuples) free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }
References vrprouting::Pgr_messages::clear(), PickDeliveryOrders_t::deliver_node_id, vrprouting::Pgr_messages::get_error(), anonymous_namespace{pickDeliver_driver.cpp}::get_initial_solution(), vrprouting::Pgr_messages::get_log(), vrprouting::base::Base_Matrix::has_no_infinity(), PickDeliveryOrders_t::id, vrprouting::problem::PickDeliver::msg, vrprouting::initialsol::simple::OneDepot, pgassert, pgr_alloc(), pgr_msg(), PickDeliveryOrders_t::pick_node_id, and AssertFailedException::what().
Referenced by process().