vrpRouting: time_windows_input.h File Reference
time_windows_input.h File Reference
#include <stdbool.h>
#include <stddef.h>
#include "c_common/get_check_data.h"
#include "c_types/column_info_t.h"
#include "c_types/vroom/vroom_time_window_t.h"
Functions
void get_vroom_shipments_time_windows (char *time_windows_sql, Vroom_time_window_t **time_windows, size_t *total_time_windows, bool is_plain)
Reads the VROOM shipments time windows.
void get_vroom_time_windows (char *time_windows_sql, Vroom_time_window_t **time_windows, size_t *total_time_windows, bool is_plain)
Reads the VROOM time windows.
Function Documentation
get_vroom_shipments_time_windows()
void get_vroom_shipments_time_windows (char * sql, Vroom_time_window_t ** rows, size_t * total_rows, bool is_plain)
Reads the VROOM shipments time windows.
Parameters
[in] sql SQL query to execute
[out] rows C Container that holds the data
[out] total_rows Total rows recieved
Definition at line 242 of file time_windows_input.c.
                    {
   int kColumnCount = 4;
   Column_info_t info[kColumnCount];
   for (int i = 0; i < kColumnCount; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = INTEGER;
   }
   info[0].name = "id";
   info[1].name = "kind";
   info[2].name = "tw_open";
   info[3].name = "tw_close";
   info[0].eType = ANY_INTEGER;  // id
   info[1].eType = CHAR1;        // kind
   if (!is_plain) {
     info[2].eType = TIMESTAMP;  // tw_open
     info[3].eType = TIMESTAMP;  // tw_close
   }
   db_get_time_windows(sql, rows, total_rows, info, kColumnCount, 1, is_plain);
 }
References ANY_INTEGER, CHAR1, Column_info_t::colNumber, db_get_time_windows(), Column_info_t::eType, INTEGER, Column_info_t::name, Column_info_t::strict, TIMESTAMP, and Column_info_t::type.
Referenced by process().
get_vroom_time_windows()
void get_vroom_time_windows (char * sql, Vroom_time_window_t ** rows, size_t * total_rows, bool is_plain)
Reads the VROOM time windows.
Parameters
[in] sql SQL query to execute
[out] rows C Container that holds the data
[out] total_rows Total rows recieved
Definition at line 207 of file time_windows_input.c.
                    {
   int kColumnCount = 3;
   Column_info_t info[kColumnCount];
   for (int i = 0; i < kColumnCount; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = INTEGER;
   }
   info[0].name = "id";
   info[1].name = "tw_open";
   info[2].name = "tw_close";
   info[0].eType = ANY_INTEGER;  // id
   if (!is_plain) {
     info[1].eType = TIMESTAMP;  // tw_open
     info[2].eType = TIMESTAMP;  // tw_close
   }
   db_get_time_windows(sql, rows, total_rows, info, kColumnCount, 0, is_plain);
 }
References ANY_INTEGER, Column_info_t::colNumber, db_get_time_windows(), Column_info_t::eType, INTEGER, Column_info_t::name, Column_info_t::strict, TIMESTAMP, and Column_info_t::type.
Referenced by process().