vrpRouting: arrays_input.h File Reference
arrays_input.h File Reference
#include <stdint.h>
#include <postgres.h>
#include <utils/array.h>
Functions
int64_t * pgr_get_bigIntArray (size_t *arrlen, ArrayType *input)
enforces the input array to be NOT empty
int64_t * pgr_get_bigIntArray_allowEmpty (size_t *arrlen, ArrayType *input)
Allows the input array to be empty.
uint32_t * pgr_get_positiveIntArray_allowEmpty (size_t *arrlen, ArrayType *input)
Allows the input array, with non-negative elements to be empty.
Function Documentation
pgr_get_bigIntArray()
int64_t* pgr_get_bigIntArray (size_t * arrlen, ArrayType * input)
enforces the input array to be NOT empty
Definition at line 217 of file arrays_input.c.
{
     return pgr_get_bigIntArr(input, arrlen, false);
 }
References pgr_get_bigIntArr().
Referenced by spi_getBigIntArr().
pgr_get_bigIntArray_allowEmpty()
int64_t* pgr_get_bigIntArray_allowEmpty (size_t * arrlen, ArrayType * input)
Allows the input array to be empty.
Definition at line 223 of file arrays_input.c.
{
     return pgr_get_bigIntArr(input, arrlen, true);
 }
References pgr_get_bigIntArr().
Referenced by spi_getBigIntArr_allowEmpty().
pgr_get_positiveIntArray_allowEmpty()
uint32_t* pgr_get_positiveIntArray_allowEmpty (size_t * arrlen, ArrayType * input)
Allows the input array, with non-negative elements to be empty.
Definition at line 228 of file arrays_input.c.
{
     return pgr_get_positiveIntArr(input, arrlen, true);
 }
References pgr_get_positiveIntArr().
Referenced by spi_getPositiveIntArr_allowEmpty().