vrpRouting: Identifiers< T > Class Template Reference
Identifiers< T > Class Template Reference
#include "identifiers.hpp"
Public Types
typedef std::set< T >::const_iterator const_iterator
typedef std::set< T >::iterator iterator
Public Member Functions
constructors
Identifiers ()=default
Identifiers (const Identifiers< T > &)=default
Identifiers (const std::set< T > &data)
Identifiers (const size_t number)
Friends
std::ostream & operator<< (std::ostream &os, const Identifiers< T > &identifiers)
Prints the set of identifiers.
set like operators
std::set< T > m_ids
size_t size () const
bool empty () const
T front () const
T back () const
const_iterator begin () const
const_iterator end () const
void pop_front ()
void clear ()
iterator begin ()
iterator end ()
bool has (const T other) const
true ids() has element
bool operator== (const Identifiers< T > &rhs) const
true when both sets are equal
set UNION
Identifiers< T > & operator+= (const Identifiers< T > &other)
compound set UNION set
Identifiers< T > & operator+= (const T &element)
compound set UNION element
Identifiers< T > operator+ (const Identifiers< T > &lhs, const Identifiers< T > &rhs)
set UNION set
set INTERSECTION
Identifiers< T > & operator*= (const Identifiers< T > &other)
coumpound set INTERSECTION set
Identifiers< T > & operator*= (const T &element)
compund set INTERSECTION element
Identifiers< T > operator* (const Identifiers< T > &lhs, const Identifiers< T > &rhs)
set INTERSECTION
set DIFFERENCE
Identifiers< T > & operator-= (const Identifiers< T > &other)
compound set DIFFERENCE set
Identifiers< T > & operator-= (const T &element)
compund set DIFFERENCE element
Identifiers< T > operator- (const Identifiers< T > &lhs, const Identifiers< T > &rhs)
Detailed Description
template<typename T>
class Identifiers< T >
Definition at line 51 of file identifiers.hpp.
Member Typedef Documentation
const_iterator
template<typename T > typedef std::set<T>::const_iterator Identifiers< T >::const_iterator
Definition at line 54 of file identifiers.hpp.
iterator
template<typename T > typedef std::set<T>::iterator Identifiers< T >::iterator
Definition at line 53 of file identifiers.hpp.
Constructor & Destructor Documentation
Identifiers() [1/4]
template<typename T > Identifiers< T >::Identifiers () default
Identifiers() [2/4]
template<typename T > Identifiers< T >::Identifiers (const Identifiers< T > &) default
Identifiers() [3/4]
template<typename T > Identifiers< T >::Identifiers (const std::set< T > & data) inline explicit
Definition at line 61 of file identifiers.hpp.
{
         m_ids = data;
     }
Identifiers() [4/4]
template<typename T > Identifiers< T >::Identifiers (const size_t number) inline explicit
Definition at line 69 of file identifiers.hpp.
{
       std::generate_n(std::inserter(m_ids, m_ids.end()), number, [&]{ return m_ids.size(); });
     }
Member Function Documentation
back()
template<typename T > T Identifiers< T >::back () const inline
Definition at line 80 of file identifiers.hpp.
 {return *m_ids.end();}
Referenced by vrprouting::problem::Fleet::get_truck().
begin() [1/2]
template<typename T > iterator Identifiers< T >::begin () inline
Definition at line 87 of file identifiers.hpp.
 {return m_ids.begin();}
begin() [2/2]
template<typename T > const_iterator Identifiers< T >::begin () const inline
Definition at line 81 of file identifiers.hpp.
 {return m_ids.begin();}
Referenced by vrprouting::base::Base_Matrix::Base_Matrix(), vrprouting::initialsol::simple::Initial_solution::one_truck_all_orders(), and vrprouting::base::Base_Matrix::set_ids().
clear()
template<typename T > void Identifiers< T >::clear () inline
Definition at line 86 of file identifiers.hpp.
 {m_ids.clear();}
empty()
template<typename T > bool Identifiers< T >::empty () const inline
Definition at line 78 of file identifiers.hpp.
 {return m_ids.empty(); }
Referenced by anonymous_namespace{tabu.cpp}::are_all_served(), vrprouting::initialsol::simple::Initial_solution::do_while_foo(), vrprouting::problem::Orders::find_best_I(), vrprouting::problem::Orders::find_best_I_J(), vrprouting::problem::Orders::find_best_J(), vrprouting::initialsol::tabu::Initial_solution::Initial_solution(), vrprouting::initialsol::simple::Initial_solution::one_truck_all_orders(), and vrprouting::initialsol::tabu::Initial_solution::process_unassigned().
end() [1/2]
template<typename T > iterator Identifiers< T >::end () inline
Definition at line 88 of file identifiers.hpp.
 {return m_ids.end();}
end() [2/2]
template<typename T > const_iterator Identifiers< T >::end () const inline
Definition at line 82 of file identifiers.hpp.
 {return m_ids.end();}
Referenced by vrprouting::base::Base_Matrix::Base_Matrix(), and vrprouting::base::Base_Matrix::set_ids().
front()
template<typename T > T Identifiers< T >::front () const inline
Definition at line 79 of file identifiers.hpp.
 {return *m_ids.begin();}
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_foo(), vrprouting::problem::Orders::find_best_I(), vrprouting::problem::Orders::find_best_I_J(), vrprouting::problem::Orders::find_best_J(), vrprouting::problem::Fleet::get_truck(), and vrprouting::initialsol::simple::Initial_solution::one_truck_all_orders().
has()
template<typename T > bool Identifiers< T >::has (const T other) const inline
true ids() has element
Parameters
[in] other Identifier of type T
Definition at line 100 of file identifiers.hpp.
{
         return (m_ids.find(other) != m_ids.end());
     }
Referenced by do_optimize(), do_pickDeliver(), vrprouting::problem::Vehicle_pickDeliver::has_order(), Identifiers< size_t >::operator*=(), vrprouting::problem::Vehicle_pickDeliver::set_initial_solution(), anonymous_namespace{optimize_driver.cpp}::subdivide_processing(), and vrprouting::optimizers::tabu::Optimize::swap_between_routes().
operator*=() [1/2]
template<typename T > Identifiers<T>& Identifiers< T >::operator*= (const Identifiers< T > & other) inline
coumpound set INTERSECTION set
Parameters
[in] other is a set of identifiers of type Identifiers<T>
Definition at line 176 of file identifiers.hpp.
{
         *this = *this * other;
         return *this;
     }
operator*=() [2/2]
template<typename T > Identifiers<T>& Identifiers< T >::operator*= (const T & element) inline
compund set INTERSECTION element
Parameters
[in] element is an identifiers of type T
Definition at line 186 of file identifiers.hpp.
{
         if (has(element)) {
             m_ids.clear();
             m_ids.insert(element);
         } else {
             m_ids.clear();
         }
         return *this;
     }
operator+=() [1/2]
template<typename T > Identifiers<T>& Identifiers< T >::operator+= (const Identifiers< T > & other) inline
compound set UNION set
Parameters
[in] other set of identifiers
Definition at line 133 of file identifiers.hpp.
{
         m_ids.insert(other.m_ids.begin(), other.m_ids.end());
         return *this;
     }
operator+=() [2/2]
template<typename T > Identifiers<T>& Identifiers< T >::operator+= (const T & element) inline
compound set UNION element
Parameters
[in] element of type T
Definition at line 142 of file identifiers.hpp.
{
         m_ids.insert(element);
         return *this;
     }
operator-=() [1/2]
template<typename T > Identifiers<T>& Identifiers< T >::operator-= (const Identifiers< T > & other) inline
compound set DIFFERENCE set
Parameters
[in] other is a set of identifiers of type Identifiers<T> Replaces this set with the set difference between this set and other
Definition at line 226 of file identifiers.hpp.
{
         *this = *this - other;
         return *this;
     }
operator-=() [2/2]
template<typename T > Identifiers<T>& Identifiers< T >::operator-= (const T & element) inline
compund set DIFFERENCE element
Parameters
[in] element to be removed
Definition at line 235 of file identifiers.hpp.
{
             m_ids.erase(element);
         return *this;
     }
operator==()
template<typename T > bool Identifiers< T >::operator== (const Identifiers< T > & rhs) const inline
true when both sets are equal
Parameters
[in] rhs set of identifiers to be compared
Definition at line 109 of file identifiers.hpp.
{
         return m_ids.size() == rhs.m_ids.size() && std::equal(m_ids.begin(), m_ids.end(), rhs.m_ids.begin());
     }
pop_front()
template<typename T > void Identifiers< T >::pop_front () inline
Definition at line 84 of file identifiers.hpp.
 {m_ids.erase(m_ids.begin());}
Referenced by vrprouting::initialsol::simple::Initial_solution::one_truck_all_orders().
size()
template<typename T > size_t Identifiers< T >::size () const inline
Definition at line 77 of file identifiers.hpp.
 {return m_ids.size(); }
Referenced by vrprouting::problem::Fleet::clean(), do_optimize(), vrprouting::initialsol::simple::Initial_solution::do_while_foo(), vrprouting::problem::Fleet::get_truck(), vrprouting::problem::operator<<(), vrprouting::problem::Vehicle_pickDeliver::orders_size(), and anonymous_namespace{optimize_driver.cpp}::subdivide_processing().
Friends And Related Function Documentation
operator*
template<typename T > Identifiers<T> operator* (const Identifiers< T > & lhs, const Identifiers< T > & rhs) friend
set INTERSECTION
Parameters
[in] lhs Identifiers
[in] rhs Identifiers
Definition at line 161 of file identifiers.hpp.
{
             std::set<T> result;
             std::set_intersection(
                     lhs.m_ids.begin(), lhs.m_ids.end(),
                     rhs.m_ids.begin(), rhs.m_ids.end(),
                     std::inserter(result, result.begin()));
             return Identifiers<T>(result);
         }
operator+
template<typename T > Identifiers<T> operator+ (const Identifiers< T > & lhs, const Identifiers< T > & rhs) friend
set UNION set
Parameters
[in] lhs Identifiers
[in] rhs Identifiers
Definition at line 121 of file identifiers.hpp.
{
         Identifiers<T> union_ids(lhs);
         union_ids += rhs;
         return union_ids;
     }
operator-
template<typename T > Identifiers<T> operator- (const Identifiers< T > & lhs, const Identifiers< T > & rhs) friend
Definition at line 208 of file identifiers.hpp.
{
             std::set<T> result;
             std::set_difference(
                     lhs.m_ids.begin(), lhs.m_ids.end(),
                     rhs.m_ids.begin(), rhs.m_ids.end(),
                     std::inserter(result, result.begin()));
             return Identifiers<T>(result);
         }
operator<<
template<typename T > std::ostream& operator<< (std::ostream & os, const Identifiers< T > & identifiers) friend
Prints the set of identifiers.
Definition at line 245 of file identifiers.hpp.
{
             os << "{";
             for (auto identifier : identifiers.m_ids) {
                 os << identifier << ", ";
             }
             os << "}";
             return os;
         }
Member Data Documentation
m_ids
template<typename T > std::set<T> Identifiers< T >::m_ids private
Definition at line 93 of file identifiers.hpp.
Referenced by Identifiers< size_t >::back(), Identifiers< size_t >::begin(), Identifiers< size_t >::clear(), Identifiers< size_t >::empty(), Identifiers< size_t >::end(), Identifiers< size_t >::front(), Identifiers< size_t >::has(), Identifiers< size_t >::Identifiers(), Identifiers< size_t >::operator*=(), Identifiers< size_t >::operator+=(), Identifiers< size_t >::operator-=(), Identifiers< size_t >::operator==(), Identifiers< size_t >::pop_front(), and Identifiers< size_t >::size().
The documentation for this class was generated from the following file:
identifiers.hpp