vrpRouting: vrprouting::problem::PickDeliver Class Reference
vrprouting::problem::PickDeliver Class Reference
the pick deliver problem
#include "pickDeliver.h"
Public Member Functions
PickDeliver (PickDeliveryOrders_t *p_orders, size_t p_orders_size, Vehicle_t *p_vehicles, size_t p_vehicles_size, const Matrix &p_cost_matrix)
General Constructor.
PickDeliver (PickDeliveryOrders_t *p_orders, size_t p_orders_size, Vehicle_t *p_vehicles, size_t p_vehicles_size, std::vector< Short_vehicle > new_stops, const Matrix &p_cost_matrix)
Override stops constructor.
virtual ~PickDeliver ()=default
void add_node (const Vehicle_node &node)
add a node to the set of nodes
std::vector< CompatibleVehicles_rt > get_pg_compatibleVehicles () const
get the vehicles compatibility results as C++ container
size_t & node_id ()
const Orders & orders ()
const Matrix & time_matrix ()
const Fleet & vehicles ()
Public Attributes
const Matrix & m_cost_matrix
the cost matrix
Pgr_messages msg
message controller for all classes
Protected Attributes
Orders m_orders
the set of orders
Fleet m_trucks
the set of vehicles
Private Attributes
size_t m_node_id = 0
used to keep track of the next index the node gets
std::vector< Vehicle_node > m_nodes { }
set of vehicle nodes
Detailed Description
the pick deliver problem
Definition at line 50 of file pickDeliver.h.
Constructor & Destructor Documentation
PickDeliver() [1/2]
vrprouting::problem::PickDeliver::PickDeliver (PickDeliveryOrders_t * p_orders, size_t p_orders_size, Vehicle_t * p_vehicles, size_t p_vehicles_size, const Matrix & p_cost_matrix) inline
General Constructor.
Definition at line 53 of file pickDeliver.h.
                                      :
       m_cost_matrix(p_cost_matrix),
       m_orders(p_orders, p_orders_size, this),
       m_trucks(p_vehicles, p_vehicles_size, m_orders, m_nodes, m_node_id) {
     if (!msg.get_error().empty()) return;
     m_trucks.clean();
     m_orders.set_compatibles();
     m_trucks.set_compatibles(m_orders);
   }
References vrprouting::problem::Fleet::clean(), vrprouting::Pgr_messages::get_error(), m_orders, m_trucks, msg, vrprouting::problem::Orders::set_compatibles(), and vrprouting::problem::Fleet::set_compatibles().
PickDeliver() [2/2]
vrprouting::problem::PickDeliver::PickDeliver (PickDeliveryOrders_t * p_orders, size_t p_orders_size, Vehicle_t * p_vehicles, size_t p_vehicles_size, std::vector< Short_vehicle > new_stops, const Matrix & p_cost_matrix) inline
Override stops constructor.
Definition at line 67 of file pickDeliver.h.
                                      :
       m_cost_matrix(p_cost_matrix),
       m_orders(p_orders, p_orders_size, this),
       m_trucks(p_vehicles, p_vehicles_size, new_stops, m_orders, m_nodes, m_node_id) {
     if (!msg.get_error().empty()) return;
     m_trucks.clean();
     m_orders.set_compatibles();
     m_trucks.set_compatibles(m_orders);
   }
References vrprouting::problem::Fleet::clean(), vrprouting::Pgr_messages::get_error(), m_orders, m_trucks, msg, vrprouting::problem::Orders::set_compatibles(), and vrprouting::problem::Fleet::set_compatibles().
~PickDeliver()
virtual vrprouting::problem::PickDeliver::~PickDeliver () virtual default
Member Function Documentation
add_node()
void vrprouting::problem::PickDeliver::add_node (const Vehicle_node & node) inline
add a node to the set of nodes
Definition at line 108 of file pickDeliver.h.
 {m_nodes.push_back(node);}
References m_nodes.
get_pg_compatibleVehicles()
std::vector<CompatibleVehicles_rt> vrprouting::problem::PickDeliver::get_pg_compatibleVehicles () const inline
get the vehicles compatibility results as C++ container
Definition at line 84 of file pickDeliver.h.
{
       std::vector<CompatibleVehicles_rt> result;
       for (const auto& v : m_trucks) {
         if (v.is_phony()) continue;
         for (const auto o : v.feasible_orders()) {
           result.push_back({m_orders[o].id(), v.id()});
         }
       }
       return result;
     }
References m_orders, and m_trucks.
Referenced by do_compatibleVehicles().
node_id()
size_t& vrprouting::problem::PickDeliver::node_id () inline
Definition at line 104 of file pickDeliver.h.
 {return m_node_id;}
References m_node_id.
orders()
const Orders& vrprouting::problem::PickDeliver::orders () inline
Definition at line 95 of file pickDeliver.h.
 {return m_orders;}
References m_orders.
time_matrix()
const Matrix& vrprouting::problem::PickDeliver::time_matrix () inline
Definition at line 103 of file pickDeliver.h.
 {return m_cost_matrix;}
References m_cost_matrix.
vehicles()
const Fleet& vrprouting::problem::PickDeliver::vehicles () inline
Definition at line 96 of file pickDeliver.h.
 {return m_trucks;}
References m_trucks.
Member Data Documentation
m_cost_matrix
const Matrix& vrprouting::problem::PickDeliver::m_cost_matrix
the cost matrix
Definition at line 102 of file pickDeliver.h.
Referenced by time_matrix().
m_node_id
size_t vrprouting::problem::PickDeliver::m_node_id = 0 private
used to keep track of the next index the node gets
The first one will get 0
therefore the first one will be located at m_nodes[0]
Precondition
Status before constructors m_node_id == 0
Definition at line 118 of file pickDeliver.h.
Referenced by node_id().
m_nodes
std::vector<Vehicle_node> vrprouting::problem::PickDeliver::m_nodes { } private
set of vehicle nodes
Precondition
Status before constructors m_nodes.empty() == true
Definition at line 124 of file pickDeliver.h.
Referenced by add_node().
m_orders
Orders vrprouting::problem::PickDeliver::m_orders protected
the set of orders
Definition at line 128 of file pickDeliver.h.
Referenced by get_pg_compatibleVehicles(), orders(), and PickDeliver().
m_trucks
Fleet vrprouting::problem::PickDeliver::m_trucks protected
the set of vehicles
Definition at line 132 of file pickDeliver.h.
Referenced by get_pg_compatibleVehicles(), PickDeliver(), and vehicles().
msg
Pgr_messages vrprouting::problem::PickDeliver::msg
message controller for all classes
Definition at line 99 of file pickDeliver.h.
Referenced by do_compatibleVehicles(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pickDeliver(), anonymous_namespace{optimize_driver.cpp}::one_processing(), and PickDeliver().
The documentation for this class was generated from the following file:
pickDeliver.h