vrpRouting: vrprouting::Pgr_messages Class Reference
vrprouting::Pgr_messages Class Reference
Messages Handling.
#include "pgr_messages.h"
Public Member Functions
Pgr_messages ()=default
Pgr_messages (const Pgr_messages &)
void clear ()
Clears all the messages.
std::string get_error () const
gets the contents of error message
std::string get_log () const
gets the contents of log message
std::string get_notice () const
gets the contents of notice message
bool has_error () const
gets the contents of notice message
Pgr_messages & operator= (const Pgr_messages &)
Public Attributes
std::ostringstream error
Stores the error information.
std::ostringstream log
Stores the hint information.
std::ostringstream notice
Stores the notice information.
Detailed Description
Messages Handling.
A common structure to be used on the C++ code that stores messages intended for PostgreSQL
Messages currently handled: log notice error
Definition at line 52 of file pgr_messages.h.
Constructor & Destructor Documentation
Pgr_messages() [1/2]
vrprouting::Pgr_messages::Pgr_messages () default
Pgr_messages() [2/2]
vrprouting::Pgr_messages::Pgr_messages (const Pgr_messages &) inline
Definition at line 55 of file pgr_messages.h.
 {}
Member Function Documentation
clear()
void vrprouting::Pgr_messages::clear ()
Clears all the messages.
Definition at line 59 of file pgr_messages.cpp.
                     {
     log.str("");
     log.clear();
     notice.str("");
     notice.clear();
     error.str("");
     error.clear();
 }
References error, log, and notice.
Referenced by do_compatibleVehicles(), do_pgr_pickDeliver(), and do_pickDeliver().
get_error()
std::string vrprouting::Pgr_messages::get_error () const
gets the contents of error message
Returns
the current contents of error
Definition at line 53 of file pgr_messages.cpp.
{
     auto str = error.str();
     return str;
 }
References error.
Referenced by vrprouting::problem::Fleet::add_vehicle(), do_compatibleVehicles(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pickDeliver(), vrprouting::problem::Fleet::is_fleet_ok(), anonymous_namespace{optimize_driver.cpp}::one_processing(), and vrprouting::problem::PickDeliver::PickDeliver().
get_log()
std::string vrprouting::Pgr_messages::get_log () const
gets the contents of log message
Returns
the current contents of log
Definition at line 36 of file pgr_messages.cpp.
{
     auto str = log.str();
     return str;
 }
References log.
Referenced by do_compatibleVehicles(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pickDeliver(), vrprouting::problem::Fleet::get_unused_trucks(), vrprouting::problem::Fleet::invariant(), and anonymous_namespace{optimize_driver.cpp}::one_processing().
get_notice()
std::string vrprouting::Pgr_messages::get_notice () const
gets the contents of notice message
Returns
the current contents of notice
Definition at line 42 of file pgr_messages.cpp.
{
     auto str = notice.str();
     return str;
 }
References notice.
has_error()
bool vrprouting::Pgr_messages::has_error () const
gets the contents of notice message
Returns
true when error message is not empty
Definition at line 48 of file pgr_messages.cpp.
{
     return  !error.str().empty();
 }
References error.
operator=()
Pgr_messages& vrprouting::Pgr_messages::operator= (const Pgr_messages &) inline
Definition at line 56 of file pgr_messages.h.
 {return *this;}
Member Data Documentation
error
std::ostringstream vrprouting::Pgr_messages::error mutable
Stores the error information.
Definition at line 95 of file pgr_messages.h.
Referenced by vrprouting::problem::Fleet::add_vehicle(), clear(), get_error(), has_error(), vrprouting::problem::Fleet::is_fleet_ok(), and vrprouting::initialsol::tabu::Initial_solution::process_unassigned().
log
std::ostringstream vrprouting::Pgr_messages::log mutable
Stores the hint information.
Definition at line 91 of file pgr_messages.h.
Referenced by vrprouting::problem::Fleet::add_vehicle(), clear(), get_log(), vrprouting::problem::Fleet::get_unused_trucks(), vrprouting::optimizers::simple::Optimize::inter_swap(), vrprouting::problem::Fleet::invariant(), vrprouting::problem::Fleet::is_fleet_ok(), vrprouting::initialsol::simple::Initial_solution::one_truck_all_orders(), vrprouting::optimizers::simple::Optimize::Optimize(), vrprouting::optimizers::tabu::Optimize::Optimize(), vrprouting::optimizers::simple::Optimize::save_if_best(), vrprouting::problem::Fleet::set_compatibles(), vrprouting::problem::Vehicle_pickDeliver::set_initial_solution(), and vrprouting::problem::Vehicle_pickDeliver::set_unmovable().
notice
std::ostringstream vrprouting::Pgr_messages::notice mutable
Stores the notice information.
Definition at line 93 of file pgr_messages.h.
Referenced by clear(), and get_notice().
The documentation for this class was generated from the following files:
pgr_messages.h
pgr_messages.cpp