vrpRouting: vrprouting::problem::Solution Class Reference
vrprouting::problem::Solution Class Reference
#include "solution.h"
Public Member Functions
Solution ()=delete
constructor
Solution (const Solution &sol)=default
copy constructor
template<typename P >
Solution (P *p_problem)
constructor
std::tuple< int, int, size_t, TInterval, TInterval, TInterval > cost () const
Get all statistics in one cycle.
std::string cost_str () const
int cvTot () const
Total number of capacity constraint violations of the solution.
TInterval duration () const
Total duration of the solution.
const std::deque< Vehicle_pickDeliver > & fleet () const
Get the current fleet solution.
std::vector< Solution_rt > get_postgres_result () const
get solution like postgres needs it
std::vector< Short_vehicle > get_stops () const
get solution like postgres needs it
bool is_feasible () const
is the solution feasible?
Pgr_messages & msg ()
double objective () const
Get the value of the objective function.
bool operator< (const Solution &) const
Solution & operator= (const Solution &sol)=default
copy assignment
const Orders & orders () const
std::string tau (const std::string &title="Tau") const
writing the solution in compact form into a string
TInterval total_service_time () const
Total service time of the solution.
TInterval total_travel_time () const
Total travel time of the solution.
int twvTot () const
Total number of time windows constraint violations of the solution.
Fleet & vehicles ()
TInterval wait_time () const
Total waiting time of the solution.
Protected Attributes
std::deque< Vehicle_pickDeliver > m_fleet
The current solution.
Pgr_messages m_msg
Orders m_orders
the problem info
Fleet m_trucks
Friends
std::ostream & operator<< (std::ostream &log, const Solution &solution)
printing function
Detailed Description
Definition at line 50 of file solution.h.
Constructor & Destructor Documentation
Solution() [1/3]
vrprouting::problem::Solution::Solution () delete
constructor
Solution() [2/3]
template<typename P > vrprouting::problem::Solution::Solution (P * p_problem) inline explicit
constructor
Definition at line 57 of file solution.h.
                                       :
         m_orders(p_problem->orders()),
         m_trucks(p_problem->vehicles()),
         m_msg(p_problem->msg) { }
Solution() [3/3]
vrprouting::problem::Solution::Solution (const Solution & sol) default
copy constructor
Member Function Documentation
cost()
std::tuple< int, int, size_t, TInterval, TInterval, TInterval > Solution::cost () const
Get all statistics in one cycle.
Returns
totals of
idx variable
0 twv
1 cv
2 fleet size
3 waiting time
4 duration
5 travel time
std::get<idx>
Definition at line 218 of file solution.cpp.
                      {
   TInterval total_duration(0);
   TInterval total_wait_time(0);
   TInterval total_tt(0);
   int total_twv(0);
   int total_cv(0);
   /*
    * Cycle the fleet
    */
   for (const auto& v : m_fleet) {
     total_duration += v.duration();
     total_wait_time += v.total_wait_time();
     total_twv += v.twvTot();
     total_cv += v.cvTot();
     total_tt += v.total_travel_time();
   }
   /*
    * build the tuple
    */
   return std::make_tuple(
       total_twv, total_cv, m_fleet.size(),
       total_wait_time, total_duration,
       total_tt);
 }
References m_fleet.
Referenced by cost_str(), and operator<().
cost_str()
std::string Solution::cost_str () const
Returns
The costs in one string
Definition at line 246 of file solution.cpp.
{
   /*
    * get the cost
    */
   auto s_cost(cost());
   std::ostringstream log;
   /*
    * Build the string
    */
   log << std::fixed << std::setprecision(4)
     << "twv=" << std::get<0>(s_cost)
     << " cv=" << std::get<1>(s_cost)
     << " wait=" << std::get<3>(s_cost)
     << " duration=" << std::get<4>(s_cost)
     << " tt=" << std::get<5>(s_cost);
   return log.str();
 }
References cost().
Referenced by tau().
cvTot()
int Solution::cvTot () const
Total number of capacity constraint violations of the solution.
Returns
Total number of capacity violations The total capacity violations of the solution is the sum of the capacity violations of all vehicles
Definition at line 196 of file solution.cpp.
                       {
   return std::accumulate(begin(m_fleet), end(m_fleet), 0,
       [](int i, const Vehicle_pickDeliver& v) {return v.cvTot() + i;});
 }
References vrprouting::problem::Vehicle::cvTot(), and m_fleet.
Referenced by get_postgres_result().
duration()
TInterval Solution::duration () const
Total duration of the solution.
Returns
the solution's duration
The solution duration is the sum of the durations of all vehicles
Definition at line 140 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), static_cast<TInterval>(0),
       [](TInterval i, const Vehicle_pickDeliver& v) {return v.duration() + i;});
 }
References vrprouting::problem::Vehicle::duration(), and m_fleet.
Referenced by get_postgres_result(), vrprouting::optimizers::simple::Optimize::save_if_best(), and vrprouting::optimizers::simple::Optimize::swap_worse().
fleet()
const std::deque<Vehicle_pickDeliver>& vrprouting::problem::Solution::fleet () const inline
Get the current fleet solution.
Definition at line 107 of file solution.h.
 {return m_fleet;}
References m_fleet.
Referenced by vrprouting::optimizers::tabu::Optimize::intensify(), and vrprouting::optimizers::tabu::Optimize::Optimize().
get_postgres_result()
std::vector< Solution_rt > Solution::get_postgres_result () const
get solution like postgres needs it
Returns
container for postgres
Definition at line 61 of file solution.cpp.
{
   std::vector<Solution_rt> result;
   /* postgres numbering starts with 1 */
   int i(1);
   for (auto v : m_fleet) {
     v.evaluate(0);
     auto data = v.get_postgres_result(i);
     /*
      * Results adjusted for the depot and the first stop
      * So the vehicle waits on the depot not on the first stop
      */
     data[1].arrivalTime = data[1].operationTime;
     data[0].waitDuration = data[1].waitDuration;
     data[1].waitDuration = 0;
     data[0].departureTime = data[0].arrivalTime + data[0].waitDuration;
     result.insert(result.end(), data.begin(), data.end());
     ++i;
   }
   Solution_rt aggregates = {
     /*
      * Vehicle id = -2 indicates its an aggregate row
      *
      * (twv, cv, fleet, wait, duration)
      */
     -2,  // summary row on vehicle_number
     twvTot(),  // on vehicle_id
     cvTot(),   // on vehicle_seq
     -1,  // on order_id
     -1,  // on stop_id
     -2,  // on stop_type (gets increased later by one so it gets -1)
     -1,  // not accounting total loads
     static_cast<int64_t>(total_travel_time()),
     -1,  // not accounting arrival_travel_time
     static_cast<int64_t>(wait_time()),
     -1,  // not accounting operation time
     static_cast<int64_t>(total_service_time()),
     static_cast<int64_t>(duration()),
     cvTot(),
     twvTot()
   };
   result.push_back(aggregates);
   return result;
 }
References cvTot(), duration(), m_fleet, total_service_time(), total_travel_time(), twvTot(), and wait_time().
get_stops()
std::vector< Short_vehicle > Solution::get_stops () const
get solution like postgres needs it
Returns
container for postgres
Definition at line 49 of file solution.cpp.
{
   std::vector<Short_vehicle> result;
   for (auto v : m_fleet) {
     result.push_back(Short_vehicle{v.id(), v.get_stops()});
   }
   return result;
 }
References Short_vehicle::id, and m_fleet.
is_feasible()
bool Solution::is_feasible () const
is the solution feasible?
The solution is feasible when all vehicles are feasible.
Returns
true when all vehicles in solution are feasible
Definition at line 129 of file solution.cpp.
{
   return std::find_if(m_fleet.begin(), m_fleet.end(),
       [] (const Vehicle_pickDeliver& v) -> bool {return !v.is_feasible();}) == m_fleet.end();
 }
References m_fleet.
Referenced by vrprouting::optimizers::simple::Optimize::decrease_truck(), vrprouting::initialsol::simple::Initial_solution::do_while_feasible(), vrprouting::initialsol::simple::Initial_solution::do_while_foo(), vrprouting::initialsol::tabu::Initial_solution::Initial_solution(), vrprouting::initialsol::tabu::Initial_solution::process_given_solution_from_user(), and vrprouting::initialsol::tabu::Initial_solution::process_unassigned().
msg()
Pgr_messages& vrprouting::problem::Solution::msg () inline
Definition at line 119 of file solution.h.
 {return m_msg;}
References m_msg.
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_foo(), vrprouting::optimizers::simple::Optimize::inter_swap(), vrprouting::optimizers::tabu::Optimize::move_2_real(), vrprouting::initialsol::simple::Initial_solution::one_truck_all_orders(), vrprouting::optimizers::simple::Optimize::Optimize(), vrprouting::optimizers::tabu::Optimize::Optimize(), vrprouting::initialsol::tabu::Initial_solution::process_unassigned(), vrprouting::optimizers::simple::Optimize::save_if_best(), and vrprouting::optimizers::tabu::Optimize::tabu_search().
objective()
double vrprouting::problem::Solution::objective () const inline
Get the value of the objective function.
Definition at line 110 of file solution.h.
 {return static_cast<double>(total_travel_time());}
References total_travel_time().
Referenced by vrprouting::optimizers::tabu::Optimize::move_2_real(), vrprouting::optimizers::tabu::Optimize::single_pair_insertion(), vrprouting::optimizers::tabu::Optimize::swap_between_routes(), and vrprouting::optimizers::tabu::Optimize::tabu_search().
operator<()
bool Solution::operator< (const Solution & s_rhs) const
Definition at line 267 of file solution.cpp.
{
   auto lhs(cost());
   auto rhs(s_rhs.cost());
   /*
    * time window violations
    */
   if (std::get<0>(lhs) < std::get<0>(rhs))
     return true;
   if (std::get<0>(lhs) > std::get<0>(rhs))
     return false;
   /*
    * capacity violations
    */
   if (std::get<1>(lhs) < std::get<1>(rhs))
     return true;
   if (std::get<1>(lhs) > std::get<1>(rhs))
     return false;
   /*
    * fleet size
    */
   if (std::get<2>(lhs) < std::get<2>(rhs))
     return true;
   if (std::get<2>(lhs) > std::get<2>(rhs))
     return false;
   /*
    * waiting time
    */
   if (std::get<3>(lhs) < std::get<3>(rhs))
     return true;
   if (std::get<3>(lhs) > std::get<3>(rhs))
     return false;
   /*
    * duration
    */
   if (std::get<4>(lhs) < std::get<4>(rhs))
     return true;
   if (std::get<4>(lhs) > std::get<4>(rhs))
     return false;
   return false;
 }
References cost().
operator=()
Solution& vrprouting::problem::Solution::operator= (const Solution & sol) default
copy assignment
orders()
const Orders& vrprouting::problem::Solution::orders () const inline
Definition at line 120 of file solution.h.
 {return m_orders;}
References m_orders.
Referenced by vrprouting::optimizers::simple::Optimize::decrease_truck(), vrprouting::optimizers::tabu::Optimize::diversify(), vrprouting::optimizers::tabu::Optimize::move_2_real(), vrprouting::initialsol::tabu::Initial_solution::process_given_solution_from_user(), vrprouting::initialsol::tabu::Initial_solution::process_unassigned(), vrprouting::optimizers::tabu::Optimize::set_tabu_list_length(), vrprouting::optimizers::tabu::Optimize::single_pair_insertion(), and vrprouting::optimizers::tabu::Optimize::swap_between_routes().
tau()
std::string Solution::tau (const std::string & title = "Tau") const
writing the solution in compact form into a string
Parameters
[in] title Title to Use for the tau
Returns
The solution in one compacted string
Definition at line 116 of file solution.cpp.
{
   std::string str {"\n" + title + ": " + '\n'};
   for (const auto& v : m_fleet) str += ("\n" + v.tau());
   str += "\n" + cost_str() + "\n";
   return str;
 }
References cost_str(), and m_fleet.
Referenced by vrprouting::optimizers::simple::Optimize::inter_swap(), vrprouting::optimizers::simple::Optimize::Optimize(), and vrprouting::optimizers::tabu::Optimize::Optimize().
total_service_time()
TInterval Solution::total_service_time () const
Total service time of the solution.
Returns
the total service time of the solution
The total service time of the solution is the sum of the service times of all vehicles
Definition at line 174 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), static_cast<TInterval>(0),
       [](TInterval i, const Vehicle_pickDeliver& v) {return v.total_service_time() + i;});
 }
References m_fleet, and vrprouting::problem::Vehicle::total_service_time().
Referenced by get_postgres_result().
total_travel_time()
TInterval Solution::total_travel_time () const
Total travel time of the solution.
Returns
the total waiting time
The total travel time of the solution is the sum of the travel times of all vehicles
Definition at line 162 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), static_cast<TInterval>(0),
       [](TInterval i, const Vehicle_pickDeliver& v) {return v.total_travel_time() + i;});
 }
References m_fleet, and vrprouting::problem::Vehicle::total_travel_time().
Referenced by get_postgres_result(), and objective().
twvTot()
int Solution::twvTot () const
Total number of time windows constraint violations of the solution.
Returns
the total number of time window violations
The total time window violations of the solution is the sum of the time window violations of all vehicles
Definition at line 185 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), 0,
       [](int i, const Vehicle_pickDeliver& v) {return v.twvTot() + i;});
 }
References m_fleet, and vrprouting::problem::Vehicle::twvTot().
Referenced by get_postgres_result().
vehicles()
Fleet& vrprouting::problem::Solution::vehicles () inline
Definition at line 121 of file solution.h.
 {return m_trucks;}
References m_trucks.
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_foo(), vrprouting::initialsol::tabu::Initial_solution::Initial_solution(), vrprouting::initialsol::simple::Initial_solution::one_truck_all_orders(), vrprouting::initialsol::tabu::Initial_solution::process_given_solution_from_user(), and vrprouting::initialsol::tabu::Initial_solution::process_unassigned().
wait_time()
TInterval Solution::wait_time () const
Total waiting time of the solution.
Returns
the total waiting time
The total waiting time of the solution is the sum of the waiting time of all vehicles
Definition at line 151 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), static_cast<TInterval>(0),
       [](TInterval i, const Vehicle_pickDeliver& v) {return v.total_wait_time() + i;});
 }
References m_fleet, and vrprouting::problem::Vehicle::total_wait_time().
Referenced by get_postgres_result().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Solution & solution) friend
printing function
Definition at line 76 of file solution.h.
{
       for (const auto& vehicle : solution.m_fleet) log << vehicle;
       log << "\n SOLUTION:\n\n " << solution.tau();
       return log;
     }
Member Data Documentation
m_fleet
std::deque<Vehicle_pickDeliver> vrprouting::problem::Solution::m_fleet protected
The current solution.
Definition at line 125 of file solution.h.
Referenced by cost(), cvTot(), vrprouting::optimizers::simple::Optimize::decrease_truck(), vrprouting::optimizers::simple::Optimize::delete_empty_truck(), vrprouting::optimizers::tabu::Optimize::diversify(), vrprouting::initialsol::simple::Initial_solution::do_while_foo(), duration(), fleet(), get_postgres_result(), get_stops(), vrprouting::initialsol::tabu::Initial_solution::Initial_solution(), vrprouting::optimizers::tabu::Optimize::intensify(), vrprouting::optimizers::simple::Optimize::inter_swap(), is_feasible(), vrprouting::optimizers::tabu::Optimize::move_2_real(), vrprouting::initialsol::simple::Initial_solution::one_truck_all_orders(), vrprouting::optimizers::simple::Optimize::Optimize(), vrprouting::optimizers::tabu::Optimize::Optimize(), vrprouting::initialsol::tabu::Initial_solution::process_given_solution_from_user(), vrprouting::initialsol::tabu::Initial_solution::process_unassigned(), vrprouting::optimizers::simple::Optimize::save_if_best(), vrprouting::optimizers::tabu::Optimize::single_pair_insertion(), vrprouting::optimizers::simple::Optimize::sort_by_duration(), vrprouting::optimizers::simple::Optimize::sort_by_id(), vrprouting::optimizers::simple::Optimize::sort_by_size(), vrprouting::optimizers::tabu::Optimize::sort_by_size(), vrprouting::optimizers::simple::Optimize::sort_for_move(), vrprouting::optimizers::tabu::Optimize::swap_between_routes(), vrprouting::optimizers::tabu::Optimize::tabu_search(), tau(), total_service_time(), total_travel_time(), twvTot(), and wait_time().
m_msg
Pgr_messages vrprouting::problem::Solution::m_msg protected
Definition at line 130 of file solution.h.
Referenced by msg().
m_orders
Orders vrprouting::problem::Solution::m_orders protected
the problem info
Definition at line 128 of file solution.h.
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_feasible(), and orders().
m_trucks
Fleet vrprouting::problem::Solution::m_trucks protected
Definition at line 129 of file solution.h.
Referenced by vehicles().
The documentation for this class was generated from the following files:
solution.h
solution.cpp