vrpRouting: vrprouting::initialsol::simple::Initial_solution Class Reference
vrprouting::initialsol::simple::Initial_solution Class Reference
#include "simple.h"
Public Member Functions
Initial_solution ()=delete
Initial_solution (Initials_code, problem::PickDeliver *)
std::tuple< int, int, size_t, TInterval, TInterval, TInterval > cost () const
Get all statistics in one cycle.
std::string cost_str () const
int cvTot () const
Total number of capacity constraint violations of the solution.
TInterval duration () const
Total duration of the solution.
const std::deque< Vehicle_pickDeliver > & fleet () const
Get the current fleet solution.
std::vector< Solution_rt > get_postgres_result () const
get solution like postgres needs it
std::vector< Short_vehicle > get_stops () const
get solution like postgres needs it
void invariant () const
bool is_feasible () const
is the solution feasible?
Pgr_messages & msg ()
double objective () const
Get the value of the objective function.
bool operator< (const Solution &) const
const Orders & orders () const
std::string tau (const std::string &title="Tau") const
writing the solution in compact form into a string
TInterval total_service_time () const
Total service time of the solution.
TInterval total_travel_time () const
Total travel time of the solution.
int twvTot () const
Total number of time windows constraint violations of the solution.
Fleet & vehicles ()
TInterval wait_time () const
Total waiting time of the solution.
Protected Attributes
std::deque< Vehicle_pickDeliver > m_fleet
The current solution.
Pgr_messages m_msg
Orders m_orders
the problem info
Fleet m_trucks
Private Member Functions
void do_while_feasible (problem::Vehicle_pickDeliver &truck, Initials_code kind, Identifiers< size_t > &unassigned, Identifiers< size_t > &assigned)
void do_while_foo (int kind)
void one_truck_all_orders ()
Private Attributes
Identifiers< size_t > all_orders
Identifiers< size_t > assigned
Identifiers< size_t > unassigned
Detailed Description
Definition at line 45 of file initialsol/simple.h.
Constructor & Destructor Documentation
Initial_solution() [1/2]
vrprouting::initialsol::simple::Initial_solution::Initial_solution () delete
Initial_solution() [2/2]
vrprouting::initialsol::simple::Initial_solution::Initial_solution (Initials_code kind, problem::PickDeliver * problem_ptr)
Definition at line 46 of file initialsol/simple.cpp.
                                          :
     problem::Solution(problem_ptr),
     all_orders(m_orders.size()),
     unassigned(m_orders.size()),
     assigned() {
         invariant();
         pgassert(kind >= 0 && kind <= OneDepot);
         switch (kind) {
             case OneTruck:
                 one_truck_all_orders();
                 break;
             case OnePerTruck:
             case FrontTruck:
             case BackTruck:
             case BestInsert:
             case BestBack:
             case BestFront:
             case OneDepot:
                 do_while_foo(kind);
                 break;
             default: pgassert(false);
         }
     invariant();
 }
References vrprouting::initialsol::simple::BackTruck, vrprouting::initialsol::simple::BestBack, vrprouting::initialsol::simple::BestFront, vrprouting::initialsol::simple::BestInsert, do_while_foo(), vrprouting::initialsol::simple::FrontTruck, invariant(), one_truck_all_orders(), vrprouting::initialsol::simple::OneDepot, vrprouting::initialsol::simple::OnePerTruck, vrprouting::initialsol::simple::OneTruck, and pgassert.
Member Function Documentation
cost()
std::tuple< int, int, size_t, TInterval, TInterval, TInterval > Solution::cost () const inherited
Get all statistics in one cycle.
Returns
totals of
idx variable
0 twv
1 cv
2 fleet size
3 waiting time
4 duration
5 travel time
std::get<idx>
Definition at line 218 of file solution.cpp.
                      {
   TInterval total_duration(0);
   TInterval total_wait_time(0);
   TInterval total_tt(0);
   int total_twv(0);
   int total_cv(0);
   /*
    * Cycle the fleet
    */
   for (const auto& v : m_fleet) {
     total_duration += v.duration();
     total_wait_time += v.total_wait_time();
     total_twv += v.twvTot();
     total_cv += v.cvTot();
     total_tt += v.total_travel_time();
   }
   /*
    * build the tuple
    */
   return std::make_tuple(
       total_twv, total_cv, m_fleet.size(),
       total_wait_time, total_duration,
       total_tt);
 }
References vrprouting::problem::Solution::m_fleet.
Referenced by vrprouting::problem::Solution::cost_str(), and vrprouting::problem::Solution::operator<().
cost_str()
std::string Solution::cost_str () const inherited
Returns
The costs in one string
Definition at line 246 of file solution.cpp.
{
   /*
    * get the cost
    */
   auto s_cost(cost());
   std::ostringstream log;
   /*
    * Build the string
    */
   log << std::fixed << std::setprecision(4)
     << "twv=" << std::get<0>(s_cost)
     << " cv=" << std::get<1>(s_cost)
     << " wait=" << std::get<3>(s_cost)
     << " duration=" << std::get<4>(s_cost)
     << " tt=" << std::get<5>(s_cost);
   return log.str();
 }
References vrprouting::problem::Solution::cost().
Referenced by vrprouting::problem::Solution::tau().
cvTot()
int Solution::cvTot () const inherited
Total number of capacity constraint violations of the solution.
Returns
Total number of capacity violations The total capacity violations of the solution is the sum of the capacity violations of all vehicles
Definition at line 196 of file solution.cpp.
                       {
   return std::accumulate(begin(m_fleet), end(m_fleet), 0,
       [](int i, const Vehicle_pickDeliver& v) {return v.cvTot() + i;});
 }
References vrprouting::problem::Vehicle::cvTot(), and vrprouting::problem::Solution::m_fleet.
Referenced by vrprouting::problem::Solution::get_postgres_result().
do_while_feasible()
void vrprouting::initialsol::simple::Initial_solution::do_while_feasible (problem::Vehicle_pickDeliver & truck, Initials_code kind, Identifiers< size_t > & unassigned, Identifiers< size_t > & assigned) private
Definition at line 120 of file initialsol/simple.cpp.
{
     pgassert(is_feasible());
     auto current_feasible = vehicle.feasible_orders() * unassigned;
     while (!current_feasible.empty()) {
         auto order = m_orders[current_feasible.front()];
         switch (kind) {
             case OnePerTruck:
                 vehicle.push_back(order);
                 pgassert(is_feasible());
                 assigned += order.idx();
                 unassigned -= order.idx();
                 invariant();
                 return;
                 break;
             case FrontTruck:
                 vehicle.push_front(order);
                 break;
             case BackTruck:
                 vehicle.push_back(order);
                 break;
             case BestInsert:
                 vehicle.hillClimb(order);
                 break;
             case BestBack:
                 order = m_orders[m_orders.find_best_J(current_feasible)];
                 vehicle.hillClimb(order);
                 break;
             case BestFront:
                 order = m_orders[m_orders.find_best_I(current_feasible)];
                 vehicle.hillClimb(order);
                 break;
             case OneDepot:
                 vehicle.semiLIFO(order);
                 break;
             default: pgassert(false);
         }
         if (vehicle.orders_size() == 1 && !is_feasible()) {
             pgassert(false);
         }
         if (!is_feasible()) {
             vehicle.erase(order);
         } else if (vehicle.has_order(order)) {
             assigned += order.idx();
             unassigned -= order.idx();
             if (kind == BestBack) {
                 current_feasible = m_orders[order.idx()].subsetJ(
                         current_feasible);
             }
             if (kind == BestFront) {
                 current_feasible = m_orders[order.idx()].subsetI(
                         current_feasible);
             }
         }
         current_feasible -= order.idx();
         invariant();
     }
     pgassert(is_feasible());
     invariant();
 }
References assigned, vrprouting::initialsol::simple::BackTruck, vrprouting::initialsol::simple::BestBack, vrprouting::initialsol::simple::BestFront, vrprouting::initialsol::simple::BestInsert, vrprouting::problem::Vehicle_pickDeliver::erase(), vrprouting::problem::Vehicle_pickDeliver::feasible_orders(), vrprouting::problem::Orders::find_best_I(), vrprouting::problem::Orders::find_best_J(), vrprouting::initialsol::simple::FrontTruck, vrprouting::problem::Vehicle_pickDeliver::has_order(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), invariant(), vrprouting::problem::Solution::is_feasible(), vrprouting::problem::Solution::m_orders, vrprouting::initialsol::simple::OneDepot, vrprouting::initialsol::simple::OnePerTruck, vrprouting::problem::Vehicle_pickDeliver::orders_size(), pgassert, vrprouting::problem::Vehicle_pickDeliver::push_back(), vrprouting::problem::Vehicle_pickDeliver::push_front(), vrprouting::problem::Vehicle_pickDeliver::semiLIFO(), and unassigned.
Referenced by do_while_foo().
do_while_foo()
void vrprouting::initialsol::simple::Initial_solution::do_while_foo (int kind) private
Definition at line 76 of file initialsol/simple.cpp.
{
     invariant();
     pgassert(kind > 0 && kind <= OneDepot);
     Identifiers<size_t> notused;
     while (!unassigned.empty()) {
         auto current = unassigned.size();
         auto truck = vehicles().get_truck(unassigned.front());
         /*
          * kind 1 to 7 work with the same code structure
          */
         do_while_feasible(truck, (Initials_code)kind, unassigned, assigned);
         pgassertwm(current > unassigned.size(), msg().get_log().c_str());
         m_fleet.push_back(truck);
         invariant();
     }
     pgassertwm(true, msg().get_log().c_str());
     pgassert(is_feasible());
     invariant();
 }
References assigned, do_while_feasible(), Identifiers< T >::empty(), Identifiers< T >::front(), vrprouting::problem::Fleet::get_truck(), invariant(), vrprouting::problem::Solution::is_feasible(), vrprouting::problem::Solution::m_fleet, vrprouting::problem::Solution::msg(), vrprouting::initialsol::simple::OneDepot, pgassert, pgassertwm, Identifiers< T >::size(), unassigned, and vrprouting::problem::Solution::vehicles().
Referenced by Initial_solution().
duration()
TInterval Solution::duration () const inherited
Total duration of the solution.
Returns
the solution's duration
The solution duration is the sum of the durations of all vehicles
Definition at line 140 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), static_cast<TInterval>(0),
       [](TInterval i, const Vehicle_pickDeliver& v) {return v.duration() + i;});
 }
References vrprouting::problem::Vehicle::duration(), and vrprouting::problem::Solution::m_fleet.
Referenced by vrprouting::problem::Solution::get_postgres_result(), vrprouting::optimizers::simple::Optimize::save_if_best(), and vrprouting::optimizers::simple::Optimize::swap_worse().
fleet()
const std::deque<Vehicle_pickDeliver>& vrprouting::problem::Solution::fleet () const inline inherited
Get the current fleet solution.
Definition at line 107 of file solution.h.
 {return m_fleet;}
References vrprouting::problem::Solution::m_fleet.
Referenced by vrprouting::optimizers::tabu::Optimize::intensify(), and vrprouting::optimizers::tabu::Optimize::Optimize().
get_postgres_result()
std::vector< Solution_rt > Solution::get_postgres_result () const inherited
get solution like postgres needs it
Returns
container for postgres
Definition at line 61 of file solution.cpp.
{
   std::vector<Solution_rt> result;
   /* postgres numbering starts with 1 */
   int i(1);
   for (auto v : m_fleet) {
     v.evaluate(0);
     auto data = v.get_postgres_result(i);
     /*
      * Results adjusted for the depot and the first stop
      * So the vehicle waits on the depot not on the first stop
      */
     data[1].arrivalTime = data[1].operationTime;
     data[0].waitDuration = data[1].waitDuration;
     data[1].waitDuration = 0;
     data[0].departureTime = data[0].arrivalTime + data[0].waitDuration;
     result.insert(result.end(), data.begin(), data.end());
     ++i;
   }
   Solution_rt aggregates = {
     /*
      * Vehicle id = -2 indicates its an aggregate row
      *
      * (twv, cv, fleet, wait, duration)
      */
     -2,  // summary row on vehicle_number
     twvTot(),  // on vehicle_id
     cvTot(),   // on vehicle_seq
     -1,  // on order_id
     -1,  // on stop_id
     -2,  // on stop_type (gets increased later by one so it gets -1)
     -1,  // not accounting total loads
     static_cast<int64_t>(total_travel_time()),
     -1,  // not accounting arrival_travel_time
     static_cast<int64_t>(wait_time()),
     -1,  // not accounting operation time
     static_cast<int64_t>(total_service_time()),
     static_cast<int64_t>(duration()),
     cvTot(),
     twvTot()
   };
   result.push_back(aggregates);
   return result;
 }
References vrprouting::problem::Solution::cvTot(), vrprouting::problem::Solution::duration(), vrprouting::problem::Solution::m_fleet, vrprouting::problem::Solution::total_service_time(), vrprouting::problem::Solution::total_travel_time(), vrprouting::problem::Solution::twvTot(), and vrprouting::problem::Solution::wait_time().
get_stops()
std::vector< Short_vehicle > Solution::get_stops () const inherited
get solution like postgres needs it
Returns
container for postgres
Definition at line 49 of file solution.cpp.
{
   std::vector<Short_vehicle> result;
   for (auto v : m_fleet) {
     result.push_back(Short_vehicle{v.id(), v.get_stops()});
   }
   return result;
 }
References Short_vehicle::id, and vrprouting::problem::Solution::m_fleet.
invariant()
void vrprouting::initialsol::simple::Initial_solution::invariant () const
Definition at line 40 of file initialsol/simple.cpp.
{
     /* this checks there is no order duplicated */
     pgassert(all_orders == (assigned + unassigned));
     pgassert((assigned * unassigned).empty());
 }
References all_orders, assigned, pgassert, and unassigned.
Referenced by do_while_feasible(), do_while_foo(), Initial_solution(), and one_truck_all_orders().
is_feasible()
bool Solution::is_feasible () const inherited
is the solution feasible?
The solution is feasible when all vehicles are feasible.
Returns
true when all vehicles in solution are feasible
Definition at line 129 of file solution.cpp.
{
   return std::find_if(m_fleet.begin(), m_fleet.end(),
       [] (const Vehicle_pickDeliver& v) -> bool {return !v.is_feasible();}) == m_fleet.end();
 }
References vrprouting::problem::Solution::m_fleet.
Referenced by vrprouting::optimizers::simple::Optimize::decrease_truck(), do_while_feasible(), do_while_foo(), vrprouting::initialsol::tabu::Initial_solution::Initial_solution(), vrprouting::initialsol::tabu::Initial_solution::process_given_solution_from_user(), and vrprouting::initialsol::tabu::Initial_solution::process_unassigned().
msg()
Pgr_messages& vrprouting::problem::Solution::msg () inline inherited
Definition at line 119 of file solution.h.
 {return m_msg;}
References vrprouting::problem::Solution::m_msg.
Referenced by do_while_foo(), vrprouting::optimizers::simple::Optimize::inter_swap(), vrprouting::optimizers::tabu::Optimize::move_2_real(), one_truck_all_orders(), vrprouting::optimizers::simple::Optimize::Optimize(), vrprouting::optimizers::tabu::Optimize::Optimize(), vrprouting::initialsol::tabu::Initial_solution::process_unassigned(), vrprouting::optimizers::simple::Optimize::save_if_best(), and vrprouting::optimizers::tabu::Optimize::tabu_search().
objective()
double vrprouting::problem::Solution::objective () const inline inherited
Get the value of the objective function.
Definition at line 110 of file solution.h.
 {return static_cast<double>(total_travel_time());}
References vrprouting::problem::Solution::total_travel_time().
Referenced by vrprouting::optimizers::tabu::Optimize::move_2_real(), vrprouting::optimizers::tabu::Optimize::single_pair_insertion(), vrprouting::optimizers::tabu::Optimize::swap_between_routes(), and vrprouting::optimizers::tabu::Optimize::tabu_search().
one_truck_all_orders()
void vrprouting::initialsol::simple::Initial_solution::one_truck_all_orders () private
Definition at line 101 of file initialsol/simple.cpp.
{
     invariant();
     msg().log << "\nInitial_solution::one_truck_all_orders\n";
     auto truck = vehicles().get_truck();
     while (!unassigned.empty()) {
         auto order(truck.orders().at(*unassigned.begin()));
         truck.hillClimb(order);
         assigned += unassigned.front();
         unassigned.pop_front();
         invariant();
     }
     m_fleet.push_back(truck);
     invariant();
 }
References assigned, Identifiers< T >::begin(), Identifiers< T >::empty(), Identifiers< T >::front(), vrprouting::problem::Fleet::get_truck(), invariant(), vrprouting::Pgr_messages::log, vrprouting::problem::Solution::m_fleet, vrprouting::problem::Solution::msg(), Identifiers< T >::pop_front(), unassigned, and vrprouting::problem::Solution::vehicles().
Referenced by Initial_solution().
operator<()
bool Solution::operator< (const Solution & s_rhs) const inherited
Definition at line 267 of file solution.cpp.
{
   auto lhs(cost());
   auto rhs(s_rhs.cost());
   /*
    * time window violations
    */
   if (std::get<0>(lhs) < std::get<0>(rhs))
     return true;
   if (std::get<0>(lhs) > std::get<0>(rhs))
     return false;
   /*
    * capacity violations
    */
   if (std::get<1>(lhs) < std::get<1>(rhs))
     return true;
   if (std::get<1>(lhs) > std::get<1>(rhs))
     return false;
   /*
    * fleet size
    */
   if (std::get<2>(lhs) < std::get<2>(rhs))
     return true;
   if (std::get<2>(lhs) > std::get<2>(rhs))
     return false;
   /*
    * waiting time
    */
   if (std::get<3>(lhs) < std::get<3>(rhs))
     return true;
   if (std::get<3>(lhs) > std::get<3>(rhs))
     return false;
   /*
    * duration
    */
   if (std::get<4>(lhs) < std::get<4>(rhs))
     return true;
   if (std::get<4>(lhs) > std::get<4>(rhs))
     return false;
   return false;
 }
References vrprouting::problem::Solution::cost().
orders()
const Orders& vrprouting::problem::Solution::orders () const inline inherited
Definition at line 120 of file solution.h.
 {return m_orders;}
References vrprouting::problem::Solution::m_orders.
Referenced by vrprouting::optimizers::simple::Optimize::decrease_truck(), vrprouting::optimizers::tabu::Optimize::diversify(), vrprouting::optimizers::tabu::Optimize::move_2_real(), vrprouting::initialsol::tabu::Initial_solution::process_given_solution_from_user(), vrprouting::initialsol::tabu::Initial_solution::process_unassigned(), vrprouting::optimizers::tabu::Optimize::set_tabu_list_length(), vrprouting::optimizers::tabu::Optimize::single_pair_insertion(), and vrprouting::optimizers::tabu::Optimize::swap_between_routes().
tau()
std::string Solution::tau (const std::string & title = "Tau") const inherited
writing the solution in compact form into a string
Parameters
[in] title Title to Use for the tau
Returns
The solution in one compacted string
Definition at line 116 of file solution.cpp.
{
   std::string str {"\n" + title + ": " + '\n'};
   for (const auto& v : m_fleet) str += ("\n" + v.tau());
   str += "\n" + cost_str() + "\n";
   return str;
 }
References vrprouting::problem::Solution::cost_str(), and vrprouting::problem::Solution::m_fleet.
Referenced by vrprouting::optimizers::simple::Optimize::inter_swap(), vrprouting::optimizers::simple::Optimize::Optimize(), and vrprouting::optimizers::tabu::Optimize::Optimize().
total_service_time()
TInterval Solution::total_service_time () const inherited
Total service time of the solution.
Returns
the total service time of the solution
The total service time of the solution is the sum of the service times of all vehicles
Definition at line 174 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), static_cast<TInterval>(0),
       [](TInterval i, const Vehicle_pickDeliver& v) {return v.total_service_time() + i;});
 }
References vrprouting::problem::Solution::m_fleet, and vrprouting::problem::Vehicle::total_service_time().
Referenced by vrprouting::problem::Solution::get_postgres_result().
total_travel_time()
TInterval Solution::total_travel_time () const inherited
Total travel time of the solution.
Returns
the total waiting time
The total travel time of the solution is the sum of the travel times of all vehicles
Definition at line 162 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), static_cast<TInterval>(0),
       [](TInterval i, const Vehicle_pickDeliver& v) {return v.total_travel_time() + i;});
 }
References vrprouting::problem::Solution::m_fleet, and vrprouting::problem::Vehicle::total_travel_time().
Referenced by vrprouting::problem::Solution::get_postgres_result(), and vrprouting::problem::Solution::objective().
twvTot()
int Solution::twvTot () const inherited
Total number of time windows constraint violations of the solution.
Returns
the total number of time window violations
The total time window violations of the solution is the sum of the time window violations of all vehicles
Definition at line 185 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), 0,
       [](int i, const Vehicle_pickDeliver& v) {return v.twvTot() + i;});
 }
References vrprouting::problem::Solution::m_fleet, and vrprouting::problem::Vehicle::twvTot().
Referenced by vrprouting::problem::Solution::get_postgres_result().
vehicles()
Fleet& vrprouting::problem::Solution::vehicles () inline inherited
Definition at line 121 of file solution.h.
 {return m_trucks;}
References vrprouting::problem::Solution::m_trucks.
Referenced by do_while_foo(), vrprouting::initialsol::tabu::Initial_solution::Initial_solution(), one_truck_all_orders(), vrprouting::initialsol::tabu::Initial_solution::process_given_solution_from_user(), and vrprouting::initialsol::tabu::Initial_solution::process_unassigned().
wait_time()
TInterval Solution::wait_time () const inherited
Total waiting time of the solution.
Returns
the total waiting time
The total waiting time of the solution is the sum of the waiting time of all vehicles
Definition at line 151 of file solution.cpp.
{
   return std::accumulate(begin(m_fleet), end(m_fleet), static_cast<TInterval>(0),
       [](TInterval i, const Vehicle_pickDeliver& v) {return v.total_wait_time() + i;});
 }
References vrprouting::problem::Solution::m_fleet, and vrprouting::problem::Vehicle::total_wait_time().
Referenced by vrprouting::problem::Solution::get_postgres_result().
Member Data Documentation
all_orders
Identifiers<size_t> vrprouting::initialsol::simple::Initial_solution::all_orders private
Definition at line 66 of file initialsol/simple.h.
Referenced by invariant().
assigned
Identifiers<size_t> vrprouting::initialsol::simple::Initial_solution::assigned private
Definition at line 68 of file initialsol/simple.h.
Referenced by do_while_feasible(), do_while_foo(), invariant(), and one_truck_all_orders().
m_fleet
std::deque<Vehicle_pickDeliver> vrprouting::problem::Solution::m_fleet protected inherited
The current solution.
Definition at line 125 of file solution.h.
Referenced by vrprouting::problem::Solution::cost(), vrprouting::problem::Solution::cvTot(), vrprouting::optimizers::simple::Optimize::decrease_truck(), vrprouting::optimizers::simple::Optimize::delete_empty_truck(), vrprouting::optimizers::tabu::Optimize::diversify(), do_while_foo(), vrprouting::problem::Solution::duration(), vrprouting::problem::Solution::fleet(), vrprouting::problem::Solution::get_postgres_result(), vrprouting::problem::Solution::get_stops(), vrprouting::initialsol::tabu::Initial_solution::Initial_solution(), vrprouting::optimizers::tabu::Optimize::intensify(), vrprouting::optimizers::simple::Optimize::inter_swap(), vrprouting::problem::Solution::is_feasible(), vrprouting::optimizers::tabu::Optimize::move_2_real(), one_truck_all_orders(), vrprouting::optimizers::simple::Optimize::Optimize(), vrprouting::optimizers::tabu::Optimize::Optimize(), vrprouting::initialsol::tabu::Initial_solution::process_given_solution_from_user(), vrprouting::initialsol::tabu::Initial_solution::process_unassigned(), vrprouting::optimizers::simple::Optimize::save_if_best(), vrprouting::optimizers::tabu::Optimize::single_pair_insertion(), vrprouting::optimizers::simple::Optimize::sort_by_duration(), vrprouting::optimizers::simple::Optimize::sort_by_id(), vrprouting::optimizers::simple::Optimize::sort_by_size(), vrprouting::optimizers::tabu::Optimize::sort_by_size(), vrprouting::optimizers::simple::Optimize::sort_for_move(), vrprouting::optimizers::tabu::Optimize::swap_between_routes(), vrprouting::optimizers::tabu::Optimize::tabu_search(), vrprouting::problem::Solution::tau(), vrprouting::problem::Solution::total_service_time(), vrprouting::problem::Solution::total_travel_time(), vrprouting::problem::Solution::twvTot(), and vrprouting::problem::Solution::wait_time().
m_msg
Pgr_messages vrprouting::problem::Solution::m_msg protected inherited
Definition at line 130 of file solution.h.
Referenced by vrprouting::problem::Solution::msg().
m_orders
Orders vrprouting::problem::Solution::m_orders protected inherited
the problem info
Definition at line 128 of file solution.h.
Referenced by do_while_feasible(), and vrprouting::problem::Solution::orders().
m_trucks
Fleet vrprouting::problem::Solution::m_trucks protected inherited
Definition at line 129 of file solution.h.
Referenced by vrprouting::problem::Solution::vehicles().
unassigned
Identifiers<size_t> vrprouting::initialsol::simple::Initial_solution::unassigned private
Definition at line 67 of file initialsol/simple.h.
Referenced by do_while_feasible(), do_while_foo(), invariant(), and one_truck_all_orders().
The documentation for this class was generated from the following files:
initialsol/simple.h
initialsol/simple.cpp