vrpRouting: vrprouting::problem::Vehicle_pickDeliver Class Reference
vrprouting::problem::Vehicle_pickDeliver Class Reference
#include "vehicle_pickDeliver.h"
Public Member Functions
Vehicle_pickDeliver ()=delete
Vehicle_pickDeliver (const Vehicle_pickDeliver &)=default
Vehicle_pickDeliver (Idx p_idx, Id p_id, const Vehicle_node &p_starting_site, const Vehicle_node &p_ending_site, const std::vector< int64_t > &p_stops, PAmount p_capacity, Speed p_speed, const Orders &p_orders)
PAmount capacity () const
returns the capacity of the vehicle
int cvTot () const
TInterval duration () const
duration of vehicle while not in a "depot"
bool empty () const
bool empty () const
const Vehicle_node & end_site () const
void erase (const Order &order)
erases the order from the vehicle
void erase (const Vehicle_node &node)
deletes a node if it exists
void erase (size_t pos)
void evaluate ()
void evaluate (size_t from)
Identifiers< size_t > & feasible_orders ()
returns the set of feasible orders for modification
const Identifiers< size_t > & feasible_orders () const
returns the set of feasible orders
Order get_first_order () const
std::vector< Solution_rt > get_postgres_result (int vid) const
std::vector< Id > get_stops () const
bool has_cv () const
bool has_order (const Order &order) const
does the vehicle has the order?
bool has_twv () const
bool hillClimb (const Order &order)
Inserts an order with hill Climb approach.
void insert (size_t pos, const Vehicle_node &node)
void insert_node (size_t pos, const Vehicle_node &node)
void invariant () const
void invariant () const
bool is_feasible () const
bool is_feasible () const
bool is_ok () const
bool is_order_feasible (const Order &order) const
bool is_phony () const
bool is_real () const
size_t length () const
Pgr_messages & msg ()
double objective () const
Get the value of the objective function.
const Orders & orders () const
Identifiers< size_t > orders_in_vehicle () const
returns the number of orders in the vehicle
size_t orders_size () const
std::string path_str () const
size_t pop_back ()
size_t pop_front ()
void push_back (const Order &order)
puts an order at the end of the truck
void push_front (const Order &order)
Puts an order at the end front of the truck.
bool semiLIFO (const Order &order)
Inserts an order In semi-Lifo (almost last in first out) order.
void set_initial_solution (const Orders &, Identifiers< size_t > &, Identifiers< size_t > &, TTimestamp, bool)
sets the initial solution given by the user
void set_unmovable (TTimestamp execution_date)
sets as unmovable the orders that start before the execution date
Speed speed () const
the speed of the vehicle
const Vehicle_node & start_site () const
std::string tau () const
TInterval total_service_time () const
total time spent moving from one node to another
TInterval total_travel_time () const
total time spent moving from one node to another
TInterval total_wait_time () const
duration of vehicle while waiting for a node to open
int twvTot () const
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Inherited functions from Identifier
int64_t id () const
get the original id
size_t idx () const
get the internal index
void reset_id (int64_t)
change the original id
Protected Member Functions
std::pair< size_t, size_t > drop_position_limits (const Vehicle_node &node) const
void erase (const Vehicle_node &node)
deletes a node if it exists
void erase (size_t pos)
void erase_node (size_t pos)
void evaluate (size_t from)
size_t getDropPosLowLimit (const Vehicle_node &node) const
size_t getPosHighLimit (const Vehicle_node &node) const
Get the highest position on the path where node can be placed.
size_t getPosLowLimit (const Vehicle_node &node) const
Get the lowest position on the path where node can be placed.
void insert (size_t pos, const Vehicle_node &node)
void insert_node (size_t pos, const Vehicle_node &node)
std::pair< size_t, size_t > position_limits (const Vehicle_node &node) const
Get the limits to insert the node.
void push_back (const Vehicle_node &node)
void push_back_node (const Vehicle_node &node)
void push_front (const Vehicle_node &node)
void push_front_node (const Vehicle_node &node)
void swap (size_t i, size_t j)
Protected Attributes
T elements
STL member.
double m_cost
Identifiers< size_t > m_feasible_orders
orders that fit in the truck
Pgr_messages m_msg
Orders m_orders
Identifiers< size_t > m_orders_in_vehicle
orders inserted in this vehicle
int m_user_cv {0}
Time window violations on solution.
int m_user_twv {0}
Time window violations on solution.
Private Attributes
PAmount m_capacity
int64_t m_id
size_t m_idx
Speed m_speed = 1.0
std::vector< int64_t > m_stops
order ids of an initial solution given by the user [1,2,1,3,3,2] = P1 P2 D1 P3 D3 D2
Friends
std::ostream & operator<< (std::ostream &log, const Vehicle_pickDeliver &v)
Detailed Description
Definition at line 46 of file vehicle_pickDeliver.h.
Constructor & Destructor Documentation
Vehicle_pickDeliver() [1/3]
vrprouting::problem::Vehicle_pickDeliver::Vehicle_pickDeliver () delete
Vehicle_pickDeliver() [2/3]
vrprouting::problem::Vehicle_pickDeliver::Vehicle_pickDeliver (const Vehicle_pickDeliver &) default
Vehicle_pickDeliver() [3/3]
vrprouting::problem::Vehicle_pickDeliver::Vehicle_pickDeliver (Idx p_idx, Id p_id, const Vehicle_node & p_starting_site, const Vehicle_node & p_ending_site, const std::vector< int64_t > & p_stops, PAmount p_capacity, Speed p_speed, const Orders & p_orders) inline
Definition at line 82 of file vehicle_pickDeliver.h.
                                      :
          Vehicle(p_idx, p_id, p_starting_site, p_ending_site, p_capacity, p_speed),
          m_cost((std::numeric_limits<double>::max)()),
          m_orders_in_vehicle(),
          m_feasible_orders(),
          m_orders(p_orders),
          m_stops(p_stops) {}
Member Function Documentation
capacity()
PAmount vrprouting::problem::Vehicle::capacity () const inherited
returns the capacity of the vehicle
Returns
the capacity of the vehicle
Definition at line 66 of file vehicle.cpp.
 {return m_capacity;}
References vrprouting::problem::Vehicle::m_capacity.
Referenced by vrprouting::problem::Vehicle::evaluate().
cvTot()
int vrprouting::problem::Vehicle::cvTot () const inherited
Definition at line 94 of file vehicle.cpp.
 {return back().cvTot();}
Referenced by vrprouting::problem::Solution::cvTot(), vrprouting::problem::Vehicle::has_cv(), vrprouting::problem::operator<(), set_initial_solution(), and vrprouting::problem::Vehicle::tau().
drop_position_limits()
std::pair< size_t, size_t > vrprouting::problem::Vehicle::drop_position_limits (const Vehicle_node & node) const protected inherited
Definition at line 426 of file vehicle.cpp.
{
   size_t high = getPosHighLimit(node);
   size_t low = getDropPosLowLimit(node);
   return std::make_pair(low, high);
 }
References vrprouting::problem::Vehicle::getDropPosLowLimit(), and vrprouting::problem::Vehicle::getPosHighLimit().
Referenced by semiLIFO().
duration()
TInterval vrprouting::problem::Vehicle::duration () const inherited
duration of vehicle while not in a "depot"
Returns
0 when the Vehicle is phony
duration of vehicle while not in a stop or ending site
Definition at line 72 of file vehicle.cpp.
 {return is_phony()? 0 : back().arrival_time() - front().departure_time();}
References vrprouting::problem::Vehicle::is_phony().
Referenced by vrprouting::problem::Solution::duration(), vrprouting::problem::operator<(), and vrprouting::problem::Vehicle::tau().
empty() [1/2]
bool vrprouting::problem::Vehicle::empty
Definition at line 112 of file vehicle.cpp.
 {return size() <= 2;}
Referenced by vrprouting::optimizers::simple::Optimize::move_order(), and vrprouting::optimizers::tabu::Optimize::swap_between_routes().
empty() [2/2]
bool vrprouting::problem::Vehicle::empty () const inherited
Definition at line 112 of file vehicle.cpp.
 {return size() <= 2;}
Referenced by get_first_order(), pop_back(), and pop_front().
end_site()
const Vehicle_node & vrprouting::problem::Vehicle::end_site () const inherited
Definition at line 124 of file vehicle.cpp.
 {return back();}
Referenced by vrprouting::problem::Vehicle::is_ok().
erase() [1/5]
void vrprouting::problem::Vehicle_pickDeliver::erase (const Order & order)
erases the order from the vehicle
Parameters
[in] order order to be removed from the vehicle
Precondition
has_order(order)
Postcondition
!has_order(order)
Definition at line 154 of file vehicle_pickDeliver.cpp.
{
   pgassert(has_order(order));
   erase(order.pickup());
   erase(order.delivery());
   m_orders_in_vehicle -= order.idx();
   pgassert(!has_order(order));
 }
References vrprouting::problem::Order::delivery(), has_order(), vrprouting::Identifier::idx(), m_orders_in_vehicle, pgassert, and vrprouting::problem::Order::pickup().
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_feasible(), hillClimb(), vrprouting::optimizers::simple::Optimize::move_order(), pop_back(), pop_front(), semiLIFO(), set_initial_solution(), and vrprouting::optimizers::simple::Optimize::swap_order().
erase() [2/5]
void vrprouting::problem::Vehicle::erase
deletes a node if it exists
Parameters
[in] node
Precondition
the node can not be S or E
S .... [node.idx()] .... E
Postcondition
S .... .... E
Definition at line 184 of file vehicle.cpp.
{
   pgassert(!node.is_start() && !node.is_end());
 #if 0
   /* TODO this works, but somehow gives docqueries give different results */
   std::deque<Vehicle_node>::erase(
       std::remove_if(begin(), end(),
         [&](const Vehicle_node& n) {return n.idx() == idx();}), end());
   evaluate();
 #else
   for (size_t pos = 0 ; pos < size() ; ++pos) {
     if (node.idx() == at(pos).idx()) {
       erase(pos);
       break;
     }
   }
 #endif
 }
erase() [3/5]
void vrprouting::problem::Vehicle::erase (const Vehicle_node & node) protected inherited
deletes a node if it exists
Parameters
[in] node
Precondition
the node can not be S or E
S .... [node.idx()] .... E
Postcondition
S .... .... E
Definition at line 184 of file vehicle.cpp.
{
   pgassert(!node.is_start() && !node.is_end());
 #if 0
   /* TODO this works, but somehow gives docqueries give different results */
   std::deque<Vehicle_node>::erase(
       std::remove_if(begin(), end(),
         [&](const Vehicle_node& n) {return n.idx() == idx();}), end());
   evaluate();
 #else
   for (size_t pos = 0 ; pos < size() ; ++pos) {
     if (node.idx() == at(pos).idx()) {
       erase(pos);
       break;
     }
   }
 #endif
 }
References vrprouting::problem::Vehicle::erase(), vrprouting::problem::Vehicle::evaluate(), vrprouting::Identifier::idx(), vrprouting::problem::Tw_node::is_end(), vrprouting::problem::Tw_node::is_start(), and pgassert.
erase() [4/5]
void vrprouting::problem::Vehicle::erase
Definition at line 172 of file vehicle.cpp.
{
   erase_node(pos);
   evaluate(pos);
 }
erase() [5/5]
void vrprouting::problem::Vehicle::erase (size_t pos) protected inherited
Definition at line 172 of file vehicle.cpp.
{
   erase_node(pos);
   evaluate(pos);
 }
References vrprouting::problem::Vehicle::erase_node(), and vrprouting::problem::Vehicle::evaluate().
Referenced by vrprouting::problem::Vehicle::erase().
erase_node()
void vrprouting::problem::Vehicle::erase_node (size_t pos) protected inherited
Definition at line 152 of file vehicle.cpp.
{
   using difference_type = std::vector<double>::difference_type;
   pgassert(pos < size() - 1 && static_cast<difference_type>(pos) > 0);
   std::deque<Vehicle_node>::erase(std::deque<Vehicle_node>::begin() + static_cast<difference_type>(pos));
 }
References pgassert.
Referenced by vrprouting::problem::Vehicle::erase(), hillClimb(), vrprouting::problem::Vehicle::pop_back(), and vrprouting::problem::Vehicle::pop_front().
evaluate() [1/3]
void vrprouting::problem::Vehicle::evaluate
Definition at line 126 of file vehicle.cpp.
 {evaluate(0);}
evaluate() [2/3]
void vrprouting::problem::Vehicle::evaluate
Parameters
[in] from The position in the path for evaluation to the end of the path.
Definition at line 131 of file vehicle.cpp.
{
   invariant();
   // preconditions
   pgassert(from < size());
   using difference_type = std::vector<Vehicle_node>::difference_type;
   auto node = begin() + static_cast<difference_type>(from);
   while (node != end()) {
     if (node == begin()) {
       node->evaluate(capacity());
     } else {
       node->evaluate(*(node - 1), capacity(), speed());
     }
     ++node;
   }
   invariant();
 }
evaluate() [3/3]
void vrprouting::problem::Vehicle::evaluate (size_t from) protected inherited
Parameters
[in] from The position in the path for evaluation to the end of the path.
Definition at line 131 of file vehicle.cpp.
{
   invariant();
   // preconditions
   pgassert(from < size());
   using difference_type = std::vector<Vehicle_node>::difference_type;
   auto node = begin() + static_cast<difference_type>(from);
   while (node != end()) {
     if (node == begin()) {
       node->evaluate(capacity());
     } else {
       node->evaluate(*(node - 1), capacity(), speed());
     }
     ++node;
   }
   invariant();
 }
References vrprouting::problem::Vehicle::capacity(), vrprouting::problem::Vehicle::invariant(), pgassert, and vrprouting::problem::Vehicle::speed().
feasible_orders() [1/2]
Identifiers<size_t>& vrprouting::problem::Vehicle_pickDeliver::feasible_orders () inline
returns the set of feasible orders for modification
Definition at line 100 of file vehicle_pickDeliver.h.
 {return m_feasible_orders;}
References m_feasible_orders.
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_feasible(), vrprouting::problem::Fleet::feasible_orders(), and vrprouting::optimizers::tabu::Optimize::swap_between_routes().
feasible_orders() [2/2]
const Identifiers<size_t>& vrprouting::problem::Vehicle_pickDeliver::feasible_orders () const inline
returns the set of feasible orders
Definition at line 102 of file vehicle_pickDeliver.h.
 {return m_feasible_orders;}
References m_feasible_orders.
get_first_order()
Order vrprouting::problem::Vehicle_pickDeliver::get_first_order () const inline
Definition at line 131 of file vehicle_pickDeliver.h.
{
          pgassert(!empty());
          return orders()[at(1).idx()];
      }
References vrprouting::problem::Vehicle::empty(), orders(), and pgassert.
get_postgres_result()
std::vector< Solution_rt > vrprouting::problem::Vehicle::get_postgres_result (int vid) const inherited
Returns
the vehicle's path in a structure for postgres
Parameters
[in] vid it is the vid-th vehicle in the solution
Definition at line 292 of file vehicle.cpp.
{
   std::vector<Solution_rt> result;
   int stop_seq(1);
   for (const auto &p_stop : *this) {
     result.push_back(p_stop.get_postgres_result(vid, id(), stop_seq));
     ++stop_seq;
   }
   return result;
 }
get_stops()
std::vector< Id > vrprouting::problem::Vehicle::get_stops () const inherited
Returns
container for postgres
Definition at line 306 of file vehicle.cpp.
{
   if (is_phony()) return std::vector<Id>();
   std::vector<Id> result;
   for (const auto &p_stop : *this) {
     if (p_stop.is_start() || p_stop.is_end()) continue;
     result.push_back(p_stop.order());
   }
   return result;
 }
References vrprouting::problem::Vehicle::is_phony().
getDropPosLowLimit()
size_t vrprouting::problem::Vehicle::getDropPosLowLimit (const Vehicle_node & node) const protected inherited
Definition at line 331 of file vehicle.cpp.
{
   invariant();
   size_t low = 0;
   size_t high = size();
   size_t low_limit = high;
   /* J == m_path[low_limit - 1] */
   while (low_limit > low
       && at(low_limit - 1).is_compatible_IJ(nodeI, speed())
       && !at(low_limit - 1).is_pickup()) {
     --low_limit;
   }
   invariant();
   return low_limit;
 }
References vrprouting::problem::Vehicle::invariant(), and vrprouting::problem::Vehicle::speed().
Referenced by vrprouting::problem::Vehicle::drop_position_limits().
getPosHighLimit()
size_t vrprouting::problem::Vehicle::getPosHighLimit (const Vehicle_node & node) const protected inherited
Get the highest position on the path where node can be placed.
Definition at line 397 of file vehicle.cpp.
{
   invariant();
   size_t low = 0;
   size_t high = size();
   size_t high_limit = low;
   /* I == m_path[high_limit] */
   while (high_limit < high
       && nodeJ.is_compatible_IJ(at(high_limit), speed())) {
     ++high_limit;
   }
   invariant();
   return high_limit;
 }
References vrprouting::problem::Vehicle::invariant(), vrprouting::problem::Tw_node::is_compatible_IJ(), and vrprouting::problem::Vehicle::speed().
Referenced by vrprouting::problem::Vehicle::drop_position_limits(), and vrprouting::problem::Vehicle::position_limits().
getPosLowLimit()
size_t vrprouting::problem::Vehicle::getPosLowLimit (const Vehicle_node & nodeI) const protected inherited
Get the lowest position on the path where node can be placed.
Returns
the lowest position where the node can be placed
Parameters
[in] nodeI start searching from postition low = pos(E)
S 1 2 3 4 5 6 7 ..... E node -> E node -> ... node -> 7 node -> 6 node -> 5 node /-> 4
return low_limit = 5
Definition at line 366 of file vehicle.cpp.
{
   invariant();
   size_t low = 0;
   size_t high = size();
   size_t low_limit = high;
   /* J == m_path[low_limit - 1] */
   while (low_limit > low
       && at(low_limit - 1).is_compatible_IJ(nodeI)) {
     --low_limit;
   }
   invariant();
   return low_limit;
 }
References vrprouting::problem::Vehicle::invariant().
Referenced by vrprouting::problem::Vehicle::position_limits().
has_cv()
bool vrprouting::problem::Vehicle::has_cv () const inherited
Definition at line 98 of file vehicle.cpp.
 {return cvTot() > m_user_cv;}
References vrprouting::problem::Vehicle::cvTot(), and vrprouting::problem::Vehicle::m_user_cv.
Referenced by vrprouting::problem::Vehicle::is_feasible(), and semiLIFO().
has_order()
bool vrprouting::problem::Vehicle_pickDeliver::has_order (const Order & order) const inline
does the vehicle has the order?
Definition at line 108 of file vehicle_pickDeliver.h.
 {return m_orders_in_vehicle.has(order.idx());}
References Identifiers< T >::has(), vrprouting::Identifier::idx(), and m_orders_in_vehicle.
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_feasible(), erase(), hillClimb(), vrprouting::optimizers::simple::Optimize::move_order(), push_back(), push_front(), semiLIFO(), vrprouting::optimizers::simple::Optimize::swap_order(), and vrprouting::optimizers::simple::Optimize::swap_worse().
has_twv()
bool vrprouting::problem::Vehicle::has_twv () const inherited
Definition at line 96 of file vehicle.cpp.
 {return twvTot() > m_user_twv;}
References vrprouting::problem::Vehicle::m_user_twv, and vrprouting::problem::Vehicle::twvTot().
Referenced by vrprouting::problem::Vehicle::is_feasible(), and semiLIFO().
hillClimb()
bool vrprouting::problem::Vehicle_pickDeliver::hillClimb (const Order & order)
Inserts an order with hill Climb approach.
Parameters
[in] order to be inserted
Precondition
invariant(order)
!has_order(order)
Postcondition
has_order(order)
invariant(order)
Before: S ...... E
 After: S ....P .... D .... E
check pre conditions
Inserting the order
check post conditions
Definition at line 444 of file vehicle_pickDeliver.cpp.
{
   invariant();
   pgassert(!has_order(order));
   auto pick_pos(position_limits(order.pickup()));
   auto deliver_pos(position_limits(order.delivery()));
   if (pick_pos.second < pick_pos.first) {
     /*
      *  pickup generates twv everywhere
      */
     return false;
   }
   if (deliver_pos.second < deliver_pos.first) {
     /*
      *  delivery generates twv everywhere
      */
     return false;
   }
   /*
    * Because delivery positions were estimated without the pickup:
    *   - increase the upper limit position estimation
    */
   ++deliver_pos.first;
   ++deliver_pos.second;
   auto best_pick_pos = size();
   auto best_deliver_pos = size() + 1;
   auto current_objective(objective());
   auto min_delta_objective = (std::numeric_limits<double>::max)();
   auto found(false);
   // insert order.pickup() (that is, the order pickup node) into the earliest possible pick position
   insert(pick_pos.first, order.pickup());
   // while the pick is < latest pick
   while (pick_pos.first <= pick_pos.second) {
     auto deliver_range = deliver_pos;
     if (deliver_range.first <= pick_pos.first) deliver_range.first = pick_pos.first + 1;
     /*
      * hill climb
      *  - find the best position
      *  finds the best position based on objective.
      */
     insert(deliver_range.first, order.delivery());
     while (deliver_range.first <= deliver_range.second) {
       if (is_feasible()) {
         auto delta_objective = objective() - current_objective;
         if (delta_objective < min_delta_objective) {
           min_delta_objective = delta_objective;
           best_pick_pos = pick_pos.first;
           best_deliver_pos = deliver_range.first;
           found = true;
         }
       }
       if (at(deliver_range.first + 1).is_end()) break;
       swap(deliver_range.first, deliver_range.first + 1);
       ++deliver_range.first;
     }
     pgassert(at(deliver_range.first).order() == order.id());
     pgassert(at(pick_pos.first).order() == order.id());
     erase_node(deliver_range.first);
     if (at(pick_pos.first + 1).is_end()) break;
     swap(pick_pos.first, pick_pos.first + 1);
     ++pick_pos.first;
   }
   erase(pick_pos.first);
   if (!found) {
     /* order causes twv or cv */
     return false;
   }
   insert(best_pick_pos, order.pickup());
   insert(best_deliver_pos, order.delivery());
   m_orders_in_vehicle += order.idx();
   pgassert(is_feasible());
   invariant();
   return true;
 }
References vrprouting::problem::Order::delivery(), erase(), vrprouting::problem::Vehicle::erase_node(), has_order(), vrprouting::Identifier::id(), vrprouting::Identifier::idx(), vrprouting::problem::Vehicle::insert(), vrprouting::problem::Vehicle::invariant(), vrprouting::problem::Vehicle::is_feasible(), m_orders_in_vehicle, objective(), pgassert, vrprouting::problem::Order::pickup(), vrprouting::problem::Vehicle::position_limits(), and vrprouting::problem::Vehicle::swap().
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_feasible(), vrprouting::optimizers::simple::Optimize::move_order(), and vrprouting::optimizers::simple::Optimize::swap_order().
id()
int64_t vrprouting::Identifier::id () const inherited
get the original id
Definition at line 42 of file identifier.cpp.
                      {
     return m_id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::problem::Vehicle_node::get_postgres_result(), hillClimb(), vrprouting::problem::Vehicle::is_phony(), vrprouting::operator<<(), vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), set_initial_solution(), set_unmovable(), vrprouting::problem::Vehicle::tau(), and vrprouting::problem::Tw_node::travel_time_to().
idx()
size_t vrprouting::Identifier::idx () const inherited
get the internal index
Definition at line 37 of file identifier.cpp.
                       {
     return m_idx;
 }
References vrprouting::Identifier::m_idx.
Referenced by erase(), vrprouting::problem::Vehicle::erase(), has_order(), hillClimb(), vrprouting::operator<<(), vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), push_back(), push_front(), semiLIFO(), vrprouting::problem::Order::set_compatibles(), and vrprouting::problem::Vehicle::tau().
insert() [1/2]
void vrprouting::problem::Vehicle::insert
Definition at line 202 of file vehicle.cpp.
{
   insert_node(pos, node);
   evaluate(pos);
 }
insert() [2/2]
void vrprouting::problem::Vehicle::insert (size_t pos, const Vehicle_node & node) protected inherited
Definition at line 202 of file vehicle.cpp.
{
   insert_node(pos, node);
   evaluate(pos);
 }
References vrprouting::problem::Vehicle::evaluate(), and vrprouting::problem::Vehicle::insert_node().
Referenced by hillClimb(), semiLIFO(), and set_initial_solution().
insert_node() [1/2]
void vrprouting::problem::Vehicle::insert_node
Definition at line 158 of file vehicle.cpp.
{
   using difference_type = std::vector<double>::difference_type;
   pgassert(pos < size() && static_cast<difference_type>(pos) > 0);
   std::deque<Vehicle_node>::insert(std::deque<Vehicle_node>::begin() + static_cast<difference_type>(pos), node);
 }
insert_node() [2/2]
void vrprouting::problem::Vehicle::insert_node (size_t pos, const Vehicle_node & node) protected inherited
Definition at line 158 of file vehicle.cpp.
{
   using difference_type = std::vector<double>::difference_type;
   pgassert(pos < size() && static_cast<difference_type>(pos) > 0);
   std::deque<Vehicle_node>::insert(std::deque<Vehicle_node>::begin() + static_cast<difference_type>(pos), node);
 }
References pgassert.
Referenced by vrprouting::problem::Vehicle::insert(), push_back(), vrprouting::problem::Vehicle::push_back(), vrprouting::problem::Vehicle::push_back_node(), push_front(), vrprouting::problem::Vehicle::push_front(), and vrprouting::problem::Vehicle::push_front_node().
invariant() [1/2]
void vrprouting::problem::Vehicle::invariant
Definition at line 100 of file vehicle.cpp.
{
     pgassert(size() >= 2);
     pgassert(front().is_start());
     pgassert(back().is_end());
 }
invariant() [2/2]
void vrprouting::problem::Vehicle::invariant () const inherited
Definition at line 100 of file vehicle.cpp.
{
     pgassert(size() >= 2);
     pgassert(front().is_start());
     pgassert(back().is_end());
 }
References pgassert.
Referenced by vrprouting::problem::Vehicle::evaluate(), vrprouting::problem::Vehicle::getDropPosLowLimit(), vrprouting::problem::Vehicle::getPosHighLimit(), vrprouting::problem::Vehicle::getPosLowLimit(), hillClimb(), pop_back(), pop_front(), semiLIFO(), and vrprouting::problem::Vehicle::tau().
is_feasible() [1/2]
bool vrprouting::problem::Vehicle::is_feasible
Definition at line 120 of file vehicle.cpp.
 {return !(has_twv() ||  has_cv());}
Referenced by vrprouting::optimizers::simple::Optimize::swap_order().
is_feasible() [2/2]
bool vrprouting::problem::Vehicle::is_feasible () const inherited
Definition at line 120 of file vehicle.cpp.
 {return !(has_twv() ||  has_cv());}
References vrprouting::problem::Vehicle::has_cv(), and vrprouting::problem::Vehicle::has_twv().
Referenced by hillClimb(), semiLIFO(), and set_initial_solution().
is_ok()
bool vrprouting::problem::Vehicle::is_ok () const inherited
Definition at line 106 of file vehicle.cpp.
{
     return (start_site().opens() <= start_site().closes())
         && (end_site().opens() <= end_site().closes())
         && (m_capacity > 0);
 }
References vrprouting::problem::Tw_node::closes(), vrprouting::problem::Vehicle::end_site(), vrprouting::problem::Vehicle::m_capacity, vrprouting::problem::Tw_node::opens(), and vrprouting::problem::Vehicle::start_site().
is_order_feasible()
bool vrprouting::problem::Vehicle_pickDeliver::is_order_feasible (const Order & order) const
Returns
ture when the order is feasible on the vehicle
Parameters
[in] order to be tested
Precondition
vehicle is empty
Definition at line 334 of file vehicle_pickDeliver.cpp.
{
   auto test_truck =  *this;
   test_truck.push_back(order);
   return test_truck.is_feasible();
 }
is_phony()
bool vrprouting::problem::Vehicle::is_phony () const inherited
Definition at line 116 of file vehicle.cpp.
 {return id() < 0;}
References vrprouting::Identifier::id().
Referenced by vrprouting::problem::Vehicle::duration(), vrprouting::problem::Vehicle::get_stops(), vrprouting::problem::Vehicle::is_real(), vrprouting::optimizers::simple::Optimize::move_order(), objective(), vrprouting::optimizers::tabu::Optimize::swap_between_routes(), vrprouting::problem::Vehicle::total_service_time(), vrprouting::problem::Vehicle::total_travel_time(), and vrprouting::problem::Vehicle::total_wait_time().
is_real()
bool vrprouting::problem::Vehicle::is_real () const inherited
Definition at line 118 of file vehicle.cpp.
 {return !is_phony();}
References vrprouting::problem::Vehicle::is_phony().
length()
size_t vrprouting::problem::Vehicle::length () const inherited
Definition at line 114 of file vehicle.cpp.
 {return size() - 2;}
msg()
Pgr_messages& vrprouting::problem::Vehicle_pickDeliver::msg () inline
Definition at line 150 of file vehicle_pickDeliver.h.
 {return m_msg;}
References m_msg.
Referenced by set_initial_solution(), and set_unmovable().
objective()
double vrprouting::problem::Vehicle_pickDeliver::objective () const
Get the value of the objective function.
Returns
0 when the Vehicle is phony
the value of the objective function
Definition at line 321 of file vehicle_pickDeliver.cpp.
{
   return is_phony()?
     0 :
     static_cast<double>(total_travel_time());
 }
References vrprouting::problem::Vehicle::is_phony(), and vrprouting::problem::Vehicle::total_travel_time().
Referenced by hillClimb(), and vrprouting::optimizers::tabu::Optimize::swap_between_routes().
orders()
const Orders& vrprouting::problem::Vehicle_pickDeliver::orders () const inline
Definition at line 148 of file vehicle_pickDeliver.h.
 {pgassert(m_orders.size() != 0); return m_orders;}
References m_orders, and pgassert.
Referenced by get_first_order(), pop_back(), pop_front(), set_initial_solution(), set_unmovable(), and vrprouting::optimizers::simple::Optimize::swap_worse().
orders_in_vehicle()
Identifiers<size_t> vrprouting::problem::Vehicle_pickDeliver::orders_in_vehicle () const inline
returns the number of orders in the vehicle
Definition at line 105 of file vehicle_pickDeliver.h.
 {return m_orders_in_vehicle;}
References m_orders_in_vehicle.
Referenced by vrprouting::optimizers::simple::Optimize::move_reduce_cost(), vrprouting::optimizers::tabu::Optimize::swap_between_routes(), and vrprouting::optimizers::simple::Optimize::swap_worse().
orders_size()
size_t vrprouting::problem::Vehicle_pickDeliver::orders_size () const inline
Definition at line 110 of file vehicle_pickDeliver.h.
 {return m_orders_in_vehicle.size();}
References m_orders_in_vehicle, and Identifiers< T >::size().
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_feasible().
path_str()
std::string vrprouting::problem::Vehicle::path_str () const inherited
Definition at line 272 of file vehicle.cpp.
{
   std::ostringstream key;
   for (const auto &p_stop : *this) {
     if (!(p_stop == front())) key << ",";
     if (p_stop.is_start() || p_stop.is_end()) {
       key << p_stop.type_str();
     } else {
       key << p_stop.type_str() << p_stop.order();
     }
   }
   return key.str();
 }
pop_back()
size_t vrprouting::problem::Vehicle_pickDeliver::pop_back ()
Definition at line 95 of file vehicle_pickDeliver.cpp.
{
   invariant();
   pgassert(!empty());
   auto pick_itr = rbegin();
   while (pick_itr != rend() &&  !pick_itr->is_pickup()) {
     ++pick_itr;
   }
   pgassert(pick_itr->is_pickup());
   auto deleted_pick_idx = pick_itr->idx();
   for (const auto &o : this->orders()) {
     if (o.pickup().idx() == deleted_pick_idx) {
       erase(o);
       invariant();
       return o.idx();
     }
   }
   pgassert(false);
   return 0;
 }
References vrprouting::problem::Vehicle::empty(), erase(), vrprouting::problem::Vehicle::invariant(), orders(), and pgassert.
pop_front()
size_t vrprouting::problem::Vehicle_pickDeliver::pop_front ()
Definition at line 121 of file vehicle_pickDeliver.cpp.
{
   invariant();
   pgassert(!empty());
   auto pick_itr = begin();
   while (pick_itr != end() &&  !pick_itr->is_pickup()) {
     ++pick_itr;
   }
   pgassert(pick_itr->is_pickup());
   auto deleted_pick_idx = pick_itr->idx();
   for (const auto &o : this->orders()) {
     if (o.pickup().idx() == deleted_pick_idx) {
       erase(o);
       invariant();
       return o.idx();
     }
   }
   pgassert(false);
   return 0;
 }
References vrprouting::problem::Vehicle::empty(), erase(), vrprouting::problem::Vehicle::invariant(), orders(), and pgassert.
position_limits()
std::pair< size_t, size_t > vrprouting::problem::Vehicle::position_limits (const Vehicle_node & node) const protected inherited
Get the limits to insert the node.
Returns
the upper and lower position on the path where the node can be inserted
Parameters
[in] node to try to be tested
Definition at line 419 of file vehicle.cpp.
{
   size_t high = getPosHighLimit(node);
   size_t low = getPosLowLimit(node);
   return std::make_pair(low, high);
 }
References vrprouting::problem::Vehicle::getPosHighLimit(), and vrprouting::problem::Vehicle::getPosLowLimit().
Referenced by hillClimb().
push_back() [1/2]
void vrprouting::problem::Vehicle_pickDeliver::push_back (const Order & order)
puts an order at the end of the truck
Parameters
[in] order order to be pushed back
Precondition
!has_order(order)
Postcondition
has_order(order)
Before: S <nodes> E
 After: S <nodes> P D E
Postcondition
Can generate time window violation
Can generate capacity violation
Definition at line 57 of file vehicle_pickDeliver.cpp.
{
   pgassert(!has_order(order));
   m_orders_in_vehicle += order.idx();
   insert_node(size() - 1, order.pickup());
   insert_node(size() - 1, order.delivery());
   evaluate(size() - 3);
   pgassert(has_order(order));
 }
References vrprouting::problem::Order::delivery(), vrprouting::problem::Vehicle::evaluate(), has_order(), vrprouting::Identifier::idx(), vrprouting::problem::Vehicle::insert_node(), m_orders_in_vehicle, pgassert, and vrprouting::problem::Order::pickup().
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_feasible(), and vrprouting::initialsol::tabu::Initial_solution::process_unassigned().
push_back() [2/2]
void vrprouting::problem::Vehicle::push_back (const Vehicle_node & node) protected inherited
Definition at line 208 of file vehicle.cpp.
{
   insert_node(size() - 1, node);
   evaluate(size() - 2);
 }
References vrprouting::problem::Vehicle::evaluate(), and vrprouting::problem::Vehicle::insert_node().
push_back_node()
void vrprouting::problem::Vehicle::push_back_node (const Vehicle_node & node) protected inherited
Definition at line 164 of file vehicle.cpp.
{
   insert_node(1, node);
 }
References vrprouting::problem::Vehicle::insert_node().
push_front() [1/2]
void vrprouting::problem::Vehicle_pickDeliver::push_front (const Order & order)
Puts an order at the end front of the truck.
Precondition: !has_order(order)
Postcondition: has_order(order) !has_cv();
Before: S <nodes> E
  After: S P D <nodes> E
Can generate time window violation No capacity violation
Definition at line 84 of file vehicle_pickDeliver.cpp.
{
   pgassert(!has_order(order));
   m_orders_in_vehicle += order.idx();
   insert_node(1, order.delivery());
   insert_node(1, order.pickup());
   evaluate();
   pgassert(has_order(order));
 }
References vrprouting::problem::Order::delivery(), vrprouting::problem::Vehicle::evaluate(), has_order(), vrprouting::Identifier::idx(), vrprouting::problem::Vehicle::insert_node(), m_orders_in_vehicle, pgassert, and vrprouting::problem::Order::pickup().
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_feasible().
push_front() [2/2]
void vrprouting::problem::Vehicle::push_front (const Vehicle_node & node) protected inherited
Definition at line 213 of file vehicle.cpp.
{
   insert_node(1, node);
   evaluate();
 }
References vrprouting::problem::Vehicle::evaluate(), and vrprouting::problem::Vehicle::insert_node().
push_front_node()
void vrprouting::problem::Vehicle::push_front_node (const Vehicle_node & node) protected inherited
Definition at line 168 of file vehicle.cpp.
{
   insert_node(size() - 1, node);
 }
References vrprouting::problem::Vehicle::insert_node().
reset_id()
void vrprouting::Identifier::reset_id (int64_t _id) inherited
change the original id
Definition at line 47 of file identifier.cpp.
{
     m_id = _id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::problem::Tw_node::Tw_node().
semiLIFO()
bool vrprouting::problem::Vehicle_pickDeliver::semiLIFO (const Order & order)
Inserts an order In semi-Lifo (almost last in first out) order.
Precondition: !has_order(order)
Postcondition: has_order(order) !has_cv();
Before: S .... (P1 ....... P2) ... D2 .... D1 .... E
 After: S .... (P .. P1 .. P2) ... D2 .. D .. D1 .... E
push_back is performed when
drop generates a time window violation
Can generate time window violation No capacity violation
Definition at line 361 of file vehicle_pickDeliver.cpp.
{
   invariant();
   pgassert(!has_order(order));
   /*
    * Insert pick up as first picked
    */
   insert(1, order.pickup());
   auto deliver_pos(drop_position_limits(order.delivery()));
   /*
    * delivery generates twv in all positions
    */
   if (deliver_pos.second < deliver_pos.first) {
     /*
      * Remove inserted pickup
      */
     erase(1);
     invariant();
     return false;
   }
   pgassert(!has_order(order));
   while (deliver_pos.first <= deliver_pos.second) {
     insert(deliver_pos.second, order.delivery());
     if (is_feasible() && !at(deliver_pos.second + 1).is_pickup()) {
       /*
        * Found a position to insert the delivery
        */
       m_orders_in_vehicle += order.idx();
       /*
        * There is one more order in the vehicle
        */
       pgassert(has_order(order));
       pgassert(is_feasible());
       pgassert(!has_cv());
       pgassert(!has_twv());
       pgassert(has_order(order));
       invariant();
       return true;
     }
     /*
      * This position in path is not suitable
      */
     erase(deliver_pos.second);
     /*
      * got to next position
      */
     --deliver_pos.second;
   }
   /*
    * Order could not be inserted
    */
   erase(1);
   pgassert(!has_order(order));
   invariant();
   return false;
 }
References vrprouting::problem::Order::delivery(), vrprouting::problem::Vehicle::drop_position_limits(), erase(), vrprouting::problem::Vehicle::has_cv(), has_order(), vrprouting::problem::Vehicle::has_twv(), vrprouting::Identifier::idx(), vrprouting::problem::Vehicle::insert(), vrprouting::problem::Vehicle::invariant(), vrprouting::problem::Vehicle::is_feasible(), m_orders_in_vehicle, pgassert, and vrprouting::problem::Order::pickup().
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_feasible(), vrprouting::optimizers::simple::Optimize::move_order(), and vrprouting::optimizers::simple::Optimize::swap_order().
set_initial_solution()
void vrprouting::problem::Vehicle_pickDeliver::set_initial_solution (const Orders & orders, Identifiers< size_t > & assigned, Identifiers< size_t > & unassigned, TTimestamp execution_date, bool optimize)
sets the initial solution given by the user
Parameters
[in] orders from the problem
[in] assigned set of orders ids already assigned
[in] unassigned set of orders to be assigned
[in] execution_date reference date to set orders unmovable
[in] optimize flag to set up for optimization
check pre conditions
no stops -> exit
Cycle the stops
Find the order
its a drop off
its a pickup
Can not ignore user error when giving an initial solution
Removing movable orders
check post conditions
Definition at line 171 of file vehicle_pickDeliver.cpp.
                    {
   pgassert(this->m_user_twv == 0);
   pgassert(this->m_user_cv == 0);
   if (m_stops.empty()) return;
   std::vector<size_t> stops;
 #if 1
   msg().log << "\n******\n" << this->id() << "\t stops(o_id) -> ";
   for (const auto &s : m_stops) {
     msg().log << s << ", ";
   }
 #endif
   Identifiers<size_t> picked_orders;
   size_t i(0);
   for (const auto o_id : m_stops) {
     auto order = std::find_if(orders.begin(), orders.end(), [o_id]
         (const Order& o) -> bool {
           return o.id() == o_id;
         });
     pgassert(order != orders.end());
     if (assigned.has(order->idx())) {
       pgassertwm(false, "Assigning an order twice");
     }
     stops.push_back(order->idx());
     if (picked_orders.has(order->idx())) {
       insert(i + 1, order->delivery());
       picked_orders -= order->idx();
       m_orders_in_vehicle += order->idx();
       assigned += order->idx();
       unassigned -= order->idx();
     } else {
       insert(i + 1, order->pickup());
       picked_orders += order->idx();
     }
     ++i;
   }
   evaluate();
   set_unmovable(execution_date);
 #if 1
   msg().log << "\n" << this->id() << "\t (idx,id) -> ";
   for (const auto &s : stops) {
     msg().log << "(" << s << ", " << orders[s].id() << ")";
   }
 #endif
   if (!is_feasible()) {
     msg().log << "\n**********************************Vehicle is not feasible with initial orders";
     msg().log << "twvTot " << this->twvTot() << "\tm_user_twv" << this->m_user_twv << "\n";
     msg().log << "cvTot " << this->cvTot() << "\tm_user_cv" << this->m_user_cv << "\n";
     msg().log << "\nVehicle: " << this->id() << "Orders: ";
     for (const auto &s : m_stops) msg().log << s << ",";
     msg().log << "\n";
     msg().log << "\n" << *this;
     if (optimize) {
       auto orders_to_remove = m_orders_in_vehicle;
       for (const auto o : orders_to_remove) {
         auto order = this->orders();
         erase(this->orders()[o]);
         m_orders_in_vehicle -= o;
         assigned -= o;
         unassigned += o;
       }
     }
     this->m_user_twv = this->twvTot();
     this->m_user_cv = this->cvTot();
   }
   pgassert(is_feasible());
   msg().log << "\n" << this->tau();
 }
References vrprouting::problem::Vehicle::cvTot(), erase(), vrprouting::problem::Vehicle::evaluate(), Identifiers< T >::has(), vrprouting::Identifier::id(), vrprouting::problem::Vehicle::insert(), vrprouting::problem::Vehicle::is_feasible(), vrprouting::Pgr_messages::log, m_orders_in_vehicle, m_stops, vrprouting::problem::Vehicle::m_user_cv, vrprouting::problem::Vehicle::m_user_twv, msg(), orders(), pgassert, pgassertwm, set_unmovable(), vrprouting::problem::Vehicle::tau(), and vrprouting::problem::Vehicle::twvTot().
set_unmovable()
void vrprouting::problem::Vehicle_pickDeliver::set_unmovable (TTimestamp execution_date)
sets as unmovable the orders that start before the execution date
When order's open < execution date.
collects the idx()
removes the order idx from the m_orders_in_vehicle
Parameters
[in] execution_date orders starting before this time are marked as unmovable
For the optimizer is like the order does not exist
Definition at line 292 of file vehicle_pickDeliver.cpp.
{
   Identifiers<size_t> unmovable;
   msg().log << "\nVehicle: " << this->id() << "unmovable: {";
   for (const auto &o : m_orders_in_vehicle) {
     for (const auto &s : *this) {
       auto order = this->orders()[o];
       if (s.order() == order.id() && s.is_pickup()) {
         if (s.opens() < execution_date) {
           unmovable += o;
           msg().log << order.id() << ",";
         }
       }
     }
   }
   msg().log << "}";
   m_orders_in_vehicle -= unmovable;
 }
References vrprouting::Identifier::id(), vrprouting::Pgr_messages::log, m_orders_in_vehicle, msg(), and orders().
Referenced by set_initial_solution().
speed()
Speed vrprouting::problem::Vehicle::speed () const inherited
the speed of the vehicle
Returns
the value of the speed
When the matrix is a time matrix: speed should be in t / t^2 When the matrix is a distance matrix: speed should be in d / t^2
where: d = distance units t = time units
The calculated value of the traveling time will become tt(a, b) = matrix(a,b) / speed;
Definition at line 63 of file vehicle.cpp.
 {return m_speed;}
References vrprouting::problem::Vehicle::m_speed.
Referenced by vrprouting::problem::Vehicle::evaluate(), vrprouting::problem::Vehicle::getDropPosLowLimit(), and vrprouting::problem::Vehicle::getPosHighLimit().
start_site()
const Vehicle_node & vrprouting::problem::Vehicle::start_site () const inherited
Definition at line 122 of file vehicle.cpp.
 {return front();}
Referenced by vrprouting::problem::Vehicle::is_ok().
swap()
void vrprouting::problem::Vehicle::swap (size_t i, size_t j) protected inherited
Definition at line 228 of file vehicle.cpp.
{
   pgassert(i < size() - 1 && i > 0);
   pgassert(j < size() - 1 && j > 0);
   std::swap(at(i), at(j));
   i < j ? evaluate(i) : evaluate(j);
 }
References vrprouting::problem::Vehicle::evaluate(), and pgassert.
Referenced by hillClimb().
tau()
std::string vrprouting::problem::Vehicle::tau () const inherited
Definition at line 251 of file vehicle.cpp.
                    {
   invariant();
   std::ostringstream log;
   log << "truck " << id() << "(" << idx() << ")" << " (";
   for (const auto &p_stop : *this) {
     if (!(p_stop == front())) log << ", ";
     p_stop.is_start() || p_stop.is_end()?
       log << p_stop.type_str() << id() :
       log << p_stop.type_str() << p_stop.order();
   }
   log << std::fixed << std::setprecision(4) << ")\t"
     << "twv=" << twvTot()
     << " cv=" << cvTot()
     << " wait=" << total_wait_time()
     << " duration=" << duration()
     << " tt=" << total_travel_time()
     << "\t";
   return log.str();
 }
References vrprouting::problem::Vehicle::cvTot(), vrprouting::problem::Vehicle::duration(), vrprouting::Identifier::id(), vrprouting::Identifier::idx(), vrprouting::problem::Vehicle::invariant(), vrprouting::problem::Vehicle::total_travel_time(), vrprouting::problem::Vehicle::total_wait_time(), and vrprouting::problem::Vehicle::twvTot().
Referenced by set_initial_solution().
total_service_time()
TInterval vrprouting::problem::Vehicle::total_service_time () const inherited
total time spent moving from one node to another
Returns
duration of vehicle while moving for a node to open
0 when the Vehicle is phony
Definition at line 90 of file vehicle.cpp.
 {return is_phony()? 0 : back().total_service_time();}
References vrprouting::problem::Vehicle::is_phony().
Referenced by vrprouting::problem::Solution::total_service_time().
total_travel_time()
TInterval vrprouting::problem::Vehicle::total_travel_time () const inherited
total time spent moving from one node to another
Returns
total time vehicle spent moving from a node to another
0 when the Vehicle is phony
Definition at line 84 of file vehicle.cpp.
 {return is_phony()? 0 : back().total_travel_time();}
References vrprouting::problem::Vehicle::is_phony().
Referenced by objective(), vrprouting::problem::operator<(), vrprouting::problem::Vehicle::tau(), and vrprouting::problem::Solution::total_travel_time().
total_wait_time()
TInterval vrprouting::problem::Vehicle::total_wait_time () const inherited
duration of vehicle while waiting for a node to open
Returns
duration of vehicle while waiting for a node to open
0 when the Vehicle is phony
Definition at line 78 of file vehicle.cpp.
 {return is_phony()? 0 : back().total_wait_time(); }
References vrprouting::problem::Vehicle::is_phony().
Referenced by vrprouting::problem::operator<(), vrprouting::problem::Vehicle::tau(), and vrprouting::problem::Solution::wait_time().
twvTot()
int vrprouting::problem::Vehicle::twvTot () const inherited
Definition at line 92 of file vehicle.cpp.
 {return back().twvTot();}
Referenced by vrprouting::problem::Vehicle::has_twv(), vrprouting::problem::operator<(), set_initial_solution(), vrprouting::problem::Vehicle::tau(), and vrprouting::problem::Solution::twvTot().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Vehicle_pickDeliver & v) friend
Returns
The vehicle's information on the log
Parameters
[in,out] log place to store the vehicle's information
[in] v the vehicle to work with
Definition at line 64 of file vehicle_pickDeliver.h.
{
          int i(0);
          log << "\n\n****************** " << v.idx() << "th VEHICLE*************\n";
          log << "id = " << v.id()
              << "\tcapacity = " << v.capacity() << "\n";
          for (const auto &path_stop : v) {
              log << "Path_stop" << ++i << "\n";
              log << path_stop << "\n";
          }
          log << v.feasible_orders() << "\n";
          return log;
      }
Member Data Documentation
elements
T std::deque< T >::elements inherited
STL member.
m_capacity
PAmount vrprouting::problem::Vehicle::m_capacity private inherited
Definition at line 182 of file vehicle.h.
Referenced by vrprouting::problem::Vehicle::capacity(), and vrprouting::problem::Vehicle::is_ok().
m_cost
double vrprouting::problem::Vehicle_pickDeliver::m_cost protected
Definition at line 158 of file vehicle_pickDeliver.h.
m_feasible_orders
Identifiers<size_t> vrprouting::problem::Vehicle_pickDeliver::m_feasible_orders protected
orders that fit in the truck
Definition at line 164 of file vehicle_pickDeliver.h.
Referenced by feasible_orders().
m_id
int64_t vrprouting::Identifier::m_id private inherited
Definition at line 87 of file identifier.h.
Referenced by vrprouting::Identifier::id(), and vrprouting::Identifier::reset_id().
m_idx
size_t vrprouting::Identifier::m_idx private inherited
Definition at line 86 of file identifier.h.
Referenced by vrprouting::Identifier::idx().
m_msg
Pgr_messages vrprouting::problem::Vehicle_pickDeliver::m_msg protected
Definition at line 168 of file vehicle_pickDeliver.h.
Referenced by msg().
m_orders
Orders vrprouting::problem::Vehicle_pickDeliver::m_orders protected
Definition at line 166 of file vehicle_pickDeliver.h.
Referenced by orders().
m_orders_in_vehicle
Identifiers<size_t> vrprouting::problem::Vehicle_pickDeliver::m_orders_in_vehicle protected
orders inserted in this vehicle
Definition at line 161 of file vehicle_pickDeliver.h.
Referenced by erase(), has_order(), hillClimb(), orders_in_vehicle(), orders_size(), push_back(), push_front(), semiLIFO(), set_initial_solution(), and set_unmovable().
m_speed
Speed vrprouting::problem::Vehicle::m_speed = 1.0 private inherited
Definition at line 183 of file vehicle.h.
Referenced by vrprouting::problem::Vehicle::speed().
m_stops
std::vector<int64_t> vrprouting::problem::Vehicle_pickDeliver::m_stops private
order ids of an initial solution given by the user [1,2,1,3,3,2] = P1 P2 D1 P3 D3 D2
Definition at line 175 of file vehicle_pickDeliver.h.
Referenced by set_initial_solution().
m_user_cv
int vrprouting::problem::Vehicle::m_user_cv {0} protected inherited
Time window violations on solution.
The user can give a solution that has capacity violations
Definition at line 179 of file vehicle.h.
Referenced by vrprouting::problem::Vehicle::has_cv(), and set_initial_solution().
m_user_twv
int vrprouting::problem::Vehicle::m_user_twv {0} protected inherited
Time window violations on solution.
The user can give a solution that has time window violations
Definition at line 173 of file vehicle.h.
Referenced by vrprouting::problem::Vehicle::has_twv(), and set_initial_solution().
The documentation for this class was generated from the following files:
vehicle_pickDeliver.h
vehicle_pickDeliver.cpp