vrpRouting: vrprouting::problem::Tw_node Class Reference
vrprouting::problem::Tw_node Class Reference
Time window attributes of a node.
#include "tw_node.h"
Public Member Functions
Tw_node ()=delete
Creating a Tw_node is not permitted.
Tw_node (const Tw_node &)=default
Copy constructor.
Tw_node (size_t id, const PickDeliveryOrders_t &data, const NodeType &type)
Creating a Tw_node from a postgreSQL order.
Tw_node (size_t id, const Vehicle_t &data, const NodeType &type)
Creating a Tw_node from a postgreSQL vehicle.
TTimestamp arrival_j_closes_i (const Tw_node &I, Speed=1.0) const
arrival time at This node, when arrived at I at closing time TODO refine description
TTimestamp arrival_j_opens_i (const Tw_node &I, Speed=1.0) const
arrival time at This node, when arrived at I at opening time TODO refine description
TTimestamp closes () const
Returns the closing time.
Amount demand () const
Returns the demand associated with this node.
bool is_compatible_IJ (const Tw_node &I, Speed=1.0) const
is possible to arrive to this after visiting other?
bool is_delivery () const
Is the node a valid order's delivery node.
bool is_dump () const
Is the node a valid vehicle's dumping node.
bool is_early_arrival (TTimestamp arrival_time) const
True when arrivalTime is before it opens.
bool is_end () const
Is the node a valid vehicle's ending node.
bool is_late_arrival (TTimestamp arrival_time) const
True when arrivalTime is after it closes.
bool is_load () const
Is the node a valid vehicle's loading node.
bool is_on_time (TTimestamp arrival_time) const
True when arrivalTime in the time window.
bool is_partially_compatible_IJ (const Tw_node &I, Speed=1.0) const
can arrive to this after visiting as late as possible I? TODO refine description
bool is_partially_waitTime_compatible_IJ (const Tw_node &I, Speed=1.0) const
can arrive to this after visiting as late as possible I? TODO refine description
bool is_pickup () const
Is the node a valid order's pickup node.
bool is_start () const
Is the node a valid vehicle's starting node.
bool is_tight_compatible_IJ (const Tw_node &I, Speed=1.0) const
can arrive to this after visiting as late as possible I? TODO refine description
bool is_valid () const
is the node valid?
bool is_waitTime_compatible_IJ (const Tw_node &I, Speed=1.0) const
can arrive to this after visiting as late as possible I? TODO refine description
TTimestamp opens () const
Returns the opening time.
bool operator== (const Tw_node &rhs) const
equality operator
int64_t order () const
Returns the order to which it belongs.
TInterval service_time () const
Returns the service time for this node.
TInterval travel_time_to (const Tw_node &, TTimestamp, Speed=1.0) const
travel time to other node.
auto type () const
Returns the type of this node.
std::string type_str () const
returns a string code of the kind of node
TInterval window_length () const
Returns the length of time between the opening and closing.
Static Public Attributes
static const Matrix * m_time_matrix_ptr = nullptr
Protected Member Functions
void demand (Amount value)
Sets the demand value to a new value.
Private Attributes
TTimestamp m_closes
closing time of the node
Amount m_demand
The demand for the Node.
int64_t m_id
size_t m_idx
TTimestamp m_opens
opening time of the node
int64_t m_order { }
order to which it belongs (idx)
TInterval m_service_time
time it takes to be served
NodeType m_type
The kind of Node.
Friends
std::ostream & operator<< (std::ostream &, const Tw_node &)
Print the contents of a Twnode object.
Detailed Description
Time window attributes of a node.
A Time Window node is a Node with addition attributes and methods to to support Time Windows and to model a more complex Node need in many vehicle routing problems.
Most application specific code will extend this class and define the specific values and requirements for type and streetid.
Definition at line 54 of file tw_node.h.
Constructor & Destructor Documentation
Tw_node() [1/4]
vrprouting::problem::Tw_node::Tw_node () delete
Creating a Tw_node is not permitted.
Tw_node() [2/4]
vrprouting::problem::Tw_node::Tw_node (const Tw_node &) default
Copy constructor.
Tw_node() [3/4]
vrprouting::problem::Tw_node::Tw_node (size_t id, const PickDeliveryOrders_t & data, const NodeType & type)
Creating a Tw_node from a postgreSQL order.
Parameters
[in] id the internal id of the node
[in] data the postgrSQL order information
[in] type the kind of node to be created
Definition at line 313 of file tw_node.cpp.
                           :
   Identifier(id, data.pick_node_id),
   m_order(data.id),
   m_opens(data.pick_open_t),
   m_closes(data.pick_close_t),
   m_service_time(data.pick_service_t),
   m_demand(data.demand),
   m_type(type)  {
     if (m_type == kDelivery) {
       reset_id(data.deliver_node_id);
       m_opens = data.deliver_open_t;
       m_closes = data.deliver_close_t;
       m_service_time = data.deliver_service_t;
       m_demand *= -1;
     }
   }
References PickDeliveryOrders_t::deliver_close_t, PickDeliveryOrders_t::deliver_node_id, PickDeliveryOrders_t::deliver_open_t, PickDeliveryOrders_t::deliver_service_t, vrprouting::problem::kDelivery, m_closes, m_demand, m_opens, m_service_time, m_type, and vrprouting::Identifier::reset_id().
Tw_node() [4/4]
vrprouting::problem::Tw_node::Tw_node (size_t id, const Vehicle_t & data, const NodeType & type)
Creating a Tw_node from a postgreSQL vehicle.
Parameters
[in] id the internal id of the node
[in] data the postgrSQL vehicle information
[in] type the kind of node to be created
Definition at line 338 of file tw_node.cpp.
                           :
   Identifier(id, data.start_node_id),
   m_opens(data.start_open_t),
   m_closes(data.start_close_t),
   m_service_time(data.start_service_t),
   m_demand(0),
   m_type(type) {
     if (m_type == kEnd) {
       reset_id(data.end_node_id);
       m_opens = data.end_open_t;
       m_closes = data.end_close_t;
       m_service_time = data.end_service_t;
     }
   }
References Vehicle_t::end_close_t, Vehicle_t::end_node_id, Vehicle_t::end_open_t, Vehicle_t::end_service_t, vrprouting::problem::kEnd, m_closes, m_opens, m_service_time, m_type, and vrprouting::Identifier::reset_id().
Member Function Documentation
arrival_j_closes_i()
TTimestamp vrprouting::problem::Tw_node::arrival_j_closes_i (const Tw_node & I, Speed speed = 1.0) const
arrival time at This node, when arrived at I at closing time TODO refine description
Parameters
[in] I the previous node before this node
[in] speed - speed used for calculation
Returns
the arrival time at this node after visiting I node when I closes
I -> this Value of TWC when arriving to this node after visiting node I at closing time
Definition at line 81 of file tw_node.cpp.
{
   if (m_type == kStart) return  (std::numeric_limits<TTimestamp>::max)();
   return I.closes() + I.service_time() + I.travel_time_to(*this, I.closes() + I.service_time(), speed);
 }
References closes(), vrprouting::problem::kStart, m_type, service_time(), and travel_time_to().
Referenced by is_partially_compatible_IJ(), and is_tight_compatible_IJ().
arrival_j_opens_i()
TTimestamp vrprouting::problem::Tw_node::arrival_j_opens_i (const Tw_node & I, Speed speed = 1.0) const
arrival time at This node, when arrived at I at opening time TODO refine description
Parameters
[in] I the previous node before this node
[in] speed - speed used for calculation
Returns
the arrival time at this node after visiting I node when I opens
I -> this Value of TWC when arriving to this node after visiting node I at opening time
Definition at line 66 of file tw_node.cpp.
{
   if (m_type == kStart) return (std::numeric_limits<TTimestamp>::max)();
   return I.opens() + I.service_time() + I.travel_time_to(*this, I.opens() + I.service_time(), speed);
 }
References vrprouting::problem::kStart, m_type, opens(), service_time(), and travel_time_to().
Referenced by is_compatible_IJ(), is_partially_compatible_IJ(), is_partially_waitTime_compatible_IJ(), is_tight_compatible_IJ(), and is_waitTime_compatible_IJ().
closes()
TTimestamp vrprouting::problem::Tw_node::closes () const inline
Returns the closing time.
Definition at line 81 of file tw_node.h.
 {return m_closes;}
References m_closes.
Referenced by arrival_j_closes_i(), is_delivery(), is_dump(), is_end(), is_load(), vrprouting::problem::Vehicle::is_ok(), is_pickup(), and is_start().
demand() [1/2]
Amount vrprouting::problem::Tw_node::demand () const inline
Returns the demand associated with this node.
Definition at line 163 of file tw_node.h.
 {return m_demand;}
References m_demand.
Referenced by vrprouting::problem::Vehicle_node::evaluate(), is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), and is_start().
demand() [2/2]
void vrprouting::problem::Tw_node::demand (Amount value) inline protected
Sets the demand value to a new value.
Definition at line 170 of file tw_node.h.
 {m_demand = value;}
References m_demand.
id()
int64_t vrprouting::Identifier::id () const inherited
get the original id
Definition at line 42 of file identifier.cpp.
                      {
     return m_id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::problem::Vehicle_node::get_postgres_result(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::problem::Vehicle::is_phony(), vrprouting::operator<<(), vrprouting::problem::operator<<(), operator==(), vrprouting::problem::Vehicle_pickDeliver::set_initial_solution(), vrprouting::problem::Vehicle_pickDeliver::set_unmovable(), vrprouting::problem::Vehicle::tau(), and travel_time_to().
idx()
size_t vrprouting::Identifier::idx () const inherited
get the internal index
Definition at line 37 of file identifier.cpp.
                       {
     return m_idx;
 }
References vrprouting::Identifier::m_idx.
Referenced by vrprouting::problem::Vehicle_pickDeliver::erase(), vrprouting::problem::Vehicle::erase(), vrprouting::problem::Vehicle_pickDeliver::has_order(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::operator<<(), vrprouting::problem::operator<<(), operator==(), vrprouting::problem::Vehicle_pickDeliver::push_back(), vrprouting::problem::Vehicle_pickDeliver::push_front(), vrprouting::problem::Vehicle_pickDeliver::semiLIFO(), vrprouting::problem::Order::set_compatibles(), and vrprouting::problem::Vehicle::tau().
is_compatible_IJ()
bool vrprouting::problem::Tw_node::is_compatible_IJ (const Tw_node & I, Speed speed = 1.0) const
is possible to arrive to this after visiting other?
Parameters
[in] I node visited before visiting this node
[in] speed - speed used for calculation
Returns
true when arriving this node after visiting node I does not cause a time window violation
false this node is a starting node (no node can be visited before a starting node)
false I node is an ending node (no node can be visited after an ending node)
Definition at line 94 of file tw_node.cpp.
{
   /*
    * I /->  kStart
    */
   if (m_type == kStart) return false;
   /*
    * kEnd /-> (*this)
    */
   if (I.m_type == kEnd) return false;
   return !is_late_arrival(arrival_j_opens_i(I, speed));
 }
References arrival_j_opens_i(), is_late_arrival(), vrprouting::problem::kEnd, vrprouting::problem::kStart, and m_type.
Referenced by vrprouting::problem::Vehicle::getPosHighLimit(), is_partially_compatible_IJ(), is_partially_waitTime_compatible_IJ(), is_tight_compatible_IJ(), vrprouting::problem::Order::is_valid(), is_waitTime_compatible_IJ(), and vrprouting::problem::Order::isCompatibleIJ().
is_delivery()
bool vrprouting::problem::Tw_node::is_delivery () const
Is the node a valid order's delivery node.
Returns
true when the node is a delivery node and is valid
Definition at line 210 of file tw_node.cpp.
{
   return m_type == kDelivery
     && (opens() < closes())
     && (service_time() >= 0)
     && (demand() < 0);
 }
References closes(), demand(), vrprouting::problem::kDelivery, m_type, opens(), and service_time().
Referenced by vrprouting::problem::Order::is_valid(), and is_valid().
is_dump()
bool vrprouting::problem::Tw_node::is_dump () const
Is the node a valid vehicle's dumping node.
Returns
true when the node is a dump node and is valid
Definition at line 222 of file tw_node.cpp.
{
   return m_type == kDump
     && (opens() < closes())
     && (service_time() >= 0)
     && (demand() <= 0);
 }
References closes(), demand(), vrprouting::problem::kDump, m_type, opens(), and service_time().
Referenced by vrprouting::problem::Vehicle_node::evaluate(), and is_valid().
is_early_arrival()
bool vrprouting::problem::Tw_node::is_early_arrival (TTimestamp arrival_time) const inline
True when arrivalTime is before it opens.
Definition at line 126 of file tw_node.h.
{
          return arrival_time < m_opens;
      }
References m_opens.
Referenced by vrprouting::problem::Vehicle_node::evaluate(), is_on_time(), is_partially_compatible_IJ(), is_partially_waitTime_compatible_IJ(), is_tight_compatible_IJ(), and is_waitTime_compatible_IJ().
is_end()
bool vrprouting::problem::Tw_node::is_end () const
Is the node a valid vehicle's ending node.
Returns
true when the node is an end node and is valid
Definition at line 245 of file tw_node.cpp.
                       {
   return m_type == kEnd
     && (opens() < closes())
     && (service_time() >= 0)
     && (demand() == 0);
 }
References closes(), demand(), vrprouting::problem::kEnd, m_type, opens(), and service_time().
Referenced by vrprouting::problem::Fleet::add_vehicle(), vrprouting::problem::Vehicle::erase(), vrprouting::problem::Vehicle_node::has_cv(), and is_valid().
is_late_arrival()
bool vrprouting::problem::Tw_node::is_late_arrival (TTimestamp arrival_time) const inline
True when arrivalTime is after it closes.
Definition at line 121 of file tw_node.h.
{
          return arrival_time > m_closes;
      }
References m_closes.
Referenced by vrprouting::problem::Vehicle_node::deltaGeneratesTWV(), vrprouting::problem::Vehicle_node::has_twv(), is_compatible_IJ(), is_on_time(), is_partially_compatible_IJ(), and is_tight_compatible_IJ().
is_load()
bool vrprouting::problem::Tw_node::is_load () const
Is the node a valid vehicle's loading node.
Returns
true when the node is a load node and is valid
Definition at line 234 of file tw_node.cpp.
{
   return m_type == kLoad
     && (opens() < closes())
     && (service_time() >= 0)
     && (demand() >= 0);
 }
References closes(), demand(), vrprouting::problem::kLoad, m_type, opens(), and service_time().
Referenced by is_valid().
is_on_time()
bool vrprouting::problem::Tw_node::is_on_time (TTimestamp arrival_time) const inline
True when arrivalTime in the time window.
Definition at line 131 of file tw_node.h.
{
          return !is_early_arrival(arrival_time)
              && !is_late_arrival(arrival_time);
      }
References is_early_arrival(), and is_late_arrival().
is_partially_compatible_IJ()
bool vrprouting::problem::Tw_node::is_partially_compatible_IJ (const Tw_node & I, Speed speed = 1.0) const
can arrive to this after visiting as late as possible I? TODO refine description
Parameters
[in] I node visited before visiting this node
[in] speed - speed used for calculation
Returns
true when TODO TBD
false this node is TODO TBD
false I node is TODO TBD
Definition at line 116 of file tw_node.cpp.
{
   return
     is_compatible_IJ(I, speed)
     && !is_early_arrival(arrival_j_opens_i(I, speed))
     && is_late_arrival(arrival_j_closes_i(I, speed));
 }
References arrival_j_closes_i(), arrival_j_opens_i(), is_compatible_IJ(), is_early_arrival(), and is_late_arrival().
is_partially_waitTime_compatible_IJ()
bool vrprouting::problem::Tw_node::is_partially_waitTime_compatible_IJ (const Tw_node & I, Speed speed = 1.0) const
can arrive to this after visiting as late as possible I? TODO refine description
Parameters
[in] I node visited before visiting this node
[in] speed - speed used for calculation
Returns
true when TODO TBD
false this node is TODO TBD
false I node is TODO TBD
Definition at line 146 of file tw_node.cpp.
{
   return
     is_compatible_IJ(I, speed)
     && is_early_arrival(arrival_j_opens_i(I, speed));
 }
References arrival_j_opens_i(), is_compatible_IJ(), and is_early_arrival().
is_pickup()
bool vrprouting::problem::Tw_node::is_pickup () const
Is the node a valid order's pickup node.
Returns
true when the node is a pickup node and is valid
Definition at line 199 of file tw_node.cpp.
{
   return m_type == kPickup
     && (opens() < closes())
     && (service_time() >= 0)
     && (demand() > 0);
 }
References closes(), demand(), vrprouting::problem::kPickup, m_type, opens(), and service_time().
Referenced by vrprouting::problem::Order::is_valid(), and is_valid().
is_start()
bool vrprouting::problem::Tw_node::is_start () const
Is the node a valid vehicle's starting node.
Returns
true when the node is a starting node and is valid
Definition at line 187 of file tw_node.cpp.
{
   return
     m_type == kStart
     && (opens() < closes())
     && (service_time() >= 0)
     && (demand() == 0);
 }
References closes(), demand(), vrprouting::problem::kStart, m_type, opens(), and service_time().
Referenced by vrprouting::problem::Vehicle::erase(), vrprouting::problem::Vehicle_node::evaluate(), vrprouting::problem::Vehicle_node::has_cv(), and is_valid().
is_tight_compatible_IJ()
bool vrprouting::problem::Tw_node::is_tight_compatible_IJ (const Tw_node & I, Speed speed = 1.0) const
can arrive to this after visiting as late as possible I? TODO refine description
Parameters
[in] I node visited before visiting this node
[in] speed - speed used for calculation
Returns
true when TODO TBD
false this node is TODO TBD
false I node is TODO TBD
Definition at line 131 of file tw_node.cpp.
{
   return
     is_compatible_IJ(I, speed)
     && !is_early_arrival(arrival_j_opens_i(I, speed))
     && !is_late_arrival(arrival_j_closes_i(I, speed));
 }
References arrival_j_closes_i(), arrival_j_opens_i(), is_compatible_IJ(), is_early_arrival(), and is_late_arrival().
is_valid()
bool vrprouting::problem::Tw_node::is_valid () const
is the node valid?
Returns
true when the node depending on the kind is a valid node
Definition at line 274 of file tw_node.cpp.
{
   switch (type()) {
     case kStart:
       return is_start();
       break;
     case kEnd:
       return is_end();
       break;
     case kDump:
       return is_dump();
       break;
     case kDelivery:
       return is_delivery();
       break;
     case kPickup:
       return is_pickup();
       break;
     case kLoad:
       return is_load();
       break;
     default:
       return false;
       break;
   }
   return false;
 }
References is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), is_start(), vrprouting::problem::kDelivery, vrprouting::problem::kDump, vrprouting::problem::kEnd, vrprouting::problem::kLoad, vrprouting::problem::kPickup, vrprouting::problem::kStart, and type().
is_waitTime_compatible_IJ()
bool vrprouting::problem::Tw_node::is_waitTime_compatible_IJ (const Tw_node & I, Speed speed = 1.0) const
can arrive to this after visiting as late as possible I? TODO refine description
Parameters
[in] I node visited before visiting this node
[in] speed - speed used for calculation
Returns
true when TODO TBD
false this node is TODO TBD
false I node is TODO TBD
Definition at line 162 of file tw_node.cpp.
{
   return
     is_compatible_IJ(I, speed)
     && is_early_arrival(arrival_j_opens_i(I, speed));
 }
References arrival_j_opens_i(), is_compatible_IJ(), and is_early_arrival().
opens()
TTimestamp vrprouting::problem::Tw_node::opens () const inline
Returns the opening time.
Definition at line 78 of file tw_node.h.
 {return m_opens;}
References m_opens.
Referenced by arrival_j_opens_i(), vrprouting::problem::Vehicle_node::evaluate(), is_delivery(), is_dump(), is_end(), is_load(), vrprouting::problem::Vehicle::is_ok(), is_pickup(), and is_start().
operator==()
bool vrprouting::problem::Tw_node::operator== (const Tw_node & other) const
equality operator
Returns
true when the other node is the same as this node
Parameters
[in] other
Definition at line 258 of file tw_node.cpp.
{
   if (&other == this) return true;
   return m_order == other.m_order
     && m_opens == other.m_opens
     && m_closes == other.m_closes
     && m_service_time == other.m_service_time
     && m_demand == other.m_demand
     && m_type == other.m_type
     && id() == other.id()
     && idx() == other.idx();
 }
References vrprouting::Identifier::id(), vrprouting::Identifier::idx(), m_closes, m_demand, m_opens, m_order, m_service_time, and m_type.
order()
int64_t vrprouting::problem::Tw_node::order () const inline
Returns the order to which it belongs.
Definition at line 75 of file tw_node.h.
 {return m_order;}
References m_order.
Referenced by vrprouting::problem::Vehicle_node::get_postgres_result().
reset_id()
void vrprouting::Identifier::reset_id (int64_t _id) inherited
change the original id
Definition at line 47 of file identifier.cpp.
{
     m_id = _id;
 }
References vrprouting::Identifier::m_id.
Referenced by Tw_node().
service_time()
TInterval vrprouting::problem::Tw_node::service_time () const inline
Returns the service time for this node.
Definition at line 84 of file tw_node.h.
 {return m_service_time;}
References m_service_time.
Referenced by arrival_j_closes_i(), arrival_j_opens_i(), vrprouting::problem::Vehicle_node::evaluate(), vrprouting::problem::Vehicle_node::get_postgres_result(), is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), is_start(), and vrprouting::problem::operator<<().
travel_time_to()
TInterval vrprouting::problem::Tw_node::travel_time_to (const Tw_node & other, TTimestamp time, Speed speed = 1.0) const
travel time to other node.
Parameters
[in] other - pointer to the other Tw_node
[in] time - time of departure from previous node
[in] speed - speed used for calculation
Returns
the travel time from this to other]
Definition at line 51 of file tw_node.cpp.
{
   pgassert(speed != 0);
   return static_cast<TInterval>(static_cast<Speed>(m_time_matrix_ptr->travel_time(id(), other.id(), time)) / speed);
 }
References vrprouting::Identifier::id(), m_time_matrix_ptr, pgassert, and vrprouting::problem::Matrix::travel_time().
Referenced by arrival_j_closes_i(), arrival_j_opens_i(), and vrprouting::problem::Vehicle_node::evaluate().
type()
auto vrprouting::problem::Tw_node::type () const inline
Returns the type of this node.
Definition at line 87 of file tw_node.h.
 {return m_type;}
References m_type.
Referenced by vrprouting::problem::Vehicle_node::get_postgres_result(), is_valid(), and type_str().
type_str()
std::string vrprouting::problem::Tw_node::type_str () const
returns a string code of the kind of node
Returns
the short hand of the kind of node
Definition at line 171 of file tw_node.cpp.
{
   switch (type()) {
     case kStart: return "S";
     case kEnd: return "E";
     case kDump: return "D";
     case kLoad: return "L";
     case kPickup: return "P";
     case kDelivery: return "D";
     default: return "UNKNOWN";
   }
 }
References vrprouting::problem::kDelivery, vrprouting::problem::kDump, vrprouting::problem::kEnd, vrprouting::problem::kLoad, vrprouting::problem::kPickup, vrprouting::problem::kStart, and type().
Referenced by vrprouting::problem::operator<<().
window_length()
TInterval vrprouting::problem::Tw_node::window_length () const inline
Returns the length of time between the opening and closing.
Definition at line 90 of file tw_node.h.
 {return m_closes - m_opens;}
References m_closes, and m_opens.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Tw_node & n) friend
Print the contents of a Twnode object.
Returns
the printed information of the node
Parameters
[in] log
[in] n
Definition at line 362 of file tw_node.cpp.
{
   log << n.id()
     << "[opens = " << n.m_opens
     << "\tcloses = " << n.m_closes
     << "\tservice = " << n.m_service_time
     << "\tdemand = " << n.m_demand
     << "\ttype = " << n.type_str()
     << "]"
     << "\n";
   return log;
 }
Member Data Documentation
m_closes
TTimestamp vrprouting::problem::Tw_node::m_closes private
closing time of the node
Definition at line 180 of file tw_node.h.
Referenced by closes(), is_late_arrival(), vrprouting::problem::operator<<(), operator==(), Tw_node(), and window_length().
m_demand
Amount vrprouting::problem::Tw_node::m_demand private
The demand for the Node.
Definition at line 186 of file tw_node.h.
Referenced by demand(), vrprouting::problem::operator<<(), operator==(), and Tw_node().
m_id
int64_t vrprouting::Identifier::m_id private inherited
Definition at line 87 of file identifier.h.
Referenced by vrprouting::Identifier::id(), and vrprouting::Identifier::reset_id().
m_idx
size_t vrprouting::Identifier::m_idx private inherited
Definition at line 86 of file identifier.h.
Referenced by vrprouting::Identifier::idx().
m_opens
TTimestamp vrprouting::problem::Tw_node::m_opens private
opening time of the node
Definition at line 177 of file tw_node.h.
Referenced by is_early_arrival(), opens(), vrprouting::problem::operator<<(), operator==(), Tw_node(), and window_length().
m_order
int64_t vrprouting::problem::Tw_node::m_order { } private
order to which it belongs (idx)
Definition at line 174 of file tw_node.h.
Referenced by operator==(), and order().
m_service_time
TInterval vrprouting::problem::Tw_node::m_service_time private
time it takes to be served
Definition at line 183 of file tw_node.h.
Referenced by vrprouting::problem::operator<<(), operator==(), service_time(), and Tw_node().
m_time_matrix_ptr
const Matrix * vrprouting::problem::Tw_node::m_time_matrix_ptr = nullptr static
Definition at line 139 of file tw_node.h.
Referenced by vrprouting::problem::Orders::Orders(), and travel_time_to().
m_type
NodeType vrprouting::problem::Tw_node::m_type private
The kind of Node.
Definition at line 189 of file tw_node.h.
Referenced by arrival_j_closes_i(), arrival_j_opens_i(), is_compatible_IJ(), is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), is_start(), operator==(), Tw_node(), and type().
The documentation for this class was generated from the following files:
tw_node.h
tw_node.cpp