vrpRouting: vrprouting::problem::Orders Class Reference
vrprouting::problem::Orders Class Reference
#include "orders.h"
Public Member Functions
Orders ()=default
Orders (const Orders &)=default
template<typename PTR >
Orders (PickDeliveryOrders_t *p_orders, size_t p_size_orders, const PTR problem_ptr)
size_t find_best_I (const Identifiers< size_t > &within_this_set) const
find the best order -> this
size_t find_best_I_J (const Identifiers< size_t > &within_this_set) const
find the best order -> this -> order
size_t find_best_J (const Identifiers< size_t > &within_this_set) const
find the best order -> this -> order
bool is_valid (Speed=1.0) const
is the order valid?
void set_compatibles (Speed=1.0)
set the compatability between all orders
Public Attributes
T elements
STL member.
Private Member Functions
void add_order (const PickDeliveryOrders_t &order, const Vehicle_node &pick, const Vehicle_node &drop)
add in an order
template<typename PTR >
void build_orders (PickDeliveryOrders_t *, size_t, const PTR problem_ptr)
Friends
std::ostream & operator<< (std::ostream &log, const Orders &p_orders)
Detailed Description
Definition at line 48 of file orders.h.
Constructor & Destructor Documentation
Orders() [1/3]
vrprouting::problem::Orders::Orders () default
Orders() [2/3]
vrprouting::problem::Orders::Orders (const Orders &) default
Orders() [3/3]
template<typename PTR > vrprouting::problem::Orders::Orders (PickDeliveryOrders_t * p_orders, size_t p_size_orders, const PTR problem_ptr) inline
Definition at line 56 of file orders.h.
{
         Tw_node::m_time_matrix_ptr = &problem_ptr->time_matrix();
         build_orders(p_orders, p_size_orders, problem_ptr);
       }
References build_orders(), and vrprouting::problem::Tw_node::m_time_matrix_ptr.
Member Function Documentation
add_order()
void vrprouting::problem::Orders::add_order (const PickDeliveryOrders_t & order, const Vehicle_node & pick, const Vehicle_node & drop) inline private
add in an order
Definition at line 88 of file orders.h.
{
       push_back(Order(size(), order.id, pick, drop));
     }
References PickDeliveryOrders_t::id.
build_orders()
template<typename PTR > void vrprouting::problem::Orders::build_orders (PickDeliveryOrders_t * orders, size_t size_orders, const PTR problem_ptr) private
Parameters
[in] orders
[in] size_orders
[in] problem_ptr pointer to problem to get some needed information
Sort orders: ASC pick_open_t, deliver_close_t, id
Definition at line 102 of file orders.h.
{
   std::sort(orders, orders + size_orders,
       [] (const PickDeliveryOrders_t &lhs, const PickDeliveryOrders_t &rhs) {
         if (lhs.pick_open_t == rhs.pick_open_t) {
           if (lhs.deliver_close_t == rhs.deliver_close_t) {
             return lhs.id < rhs.id;
           } else {
             return lhs.deliver_close_t < rhs.deliver_close_t;
           }
         } else {
           return lhs.pick_open_t < rhs.pick_open_t;
         }
       });
   for (size_t i = 0; i < size_orders; ++i) {
     auto order = orders[i];
     Vehicle_node pick({problem_ptr->node_id()++, order, NodeType::kPickup});
     Vehicle_node drop({problem_ptr->node_id()++, order, NodeType::kDelivery});
     problem_ptr->add_node(pick);
     problem_ptr->add_node(drop);
     this->emplace_back(Order{size(), order.id, pick, drop});
   }
 }
References PickDeliveryOrders_t::pick_open_t.
Referenced by Orders().
find_best_I()
size_t vrprouting::problem::Orders::find_best_I (const Identifiers< size_t > & within_this_set) const
find the best order -> this
Returns
the index of the order within_this_set that has more possibilities of placing orders before it
Parameters
[in] within_this_set
Precondition
not within_this_set.empty()
Definition at line 68 of file orders.cpp.
{
     pgassert(!within_this_set.empty());
     auto best_order = within_this_set.front();
     size_t max_size = 0;
     for (const auto o : within_this_set) {
         auto size_I =  this->at(o).subsetI(within_this_set).size();
         if (max_size < size_I) {
             max_size = size_I;
             best_order = o;
         }
     }
     return best_order;
 }
References Identifiers< T >::empty(), Identifiers< T >::front(), and pgassert.
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_feasible().
find_best_I_J()
size_t vrprouting::problem::Orders::find_best_I_J (const Identifiers< size_t > & within_this_set) const
find the best order -> this -> order
Returns
the index of the order within_this_set that has more possibilities of placing orders before or after it
Parameters
[in] within_this_set
Precondition
not within_this_set.empty()
Definition at line 89 of file orders.cpp.
{
     pgassert(!within_this_set.empty());
     auto best_order = within_this_set.front();
     size_t max_size = 0;
     for (const auto o : within_this_set) {
         auto size_I =  this->at(o).subsetI(within_this_set).size();
         auto size_J =  this->at(o).subsetJ(within_this_set).size();
         if (max_size < (std::max)(size_I, size_J)) {
             max_size = (std::max)(size_I, size_J);
             best_order = o;
         }
     }
     return best_order;
 }
References Identifiers< T >::empty(), Identifiers< T >::front(), and pgassert.
find_best_J()
size_t vrprouting::problem::Orders::find_best_J (const Identifiers< size_t > & within_this_set) const
find the best order -> this -> order
Returns
the index of the order within_this_set that has more possibilities of placing orders after it
Parameters
[in] within_this_set
Precondition
not within_this_set.empty()
Definition at line 46 of file orders.cpp.
{
     pgassert(!within_this_set.empty());
     auto best_order = within_this_set.front();
     size_t max_size = 0;
     for (const auto o : within_this_set) {
         auto size_J =  this->at(o).subsetJ(within_this_set).size();
         if (max_size < size_J) {
             max_size = size_J;
             best_order = o;
         }
     }
     return best_order;
 }
References Identifiers< T >::empty(), Identifiers< T >::front(), and pgassert.
Referenced by vrprouting::initialsol::simple::Initial_solution::do_while_feasible().
is_valid()
bool vrprouting::problem::Orders::is_valid (Speed speed = 1.0) const
is the order valid?
Returns
true when each order from the set of orders is valid
Definition at line 110 of file orders.cpp.
{
     for (const auto &o : *this) {
         if (!o.is_valid(speed)) {
             return false;
         }
         pgassert(o.pickup().is_pickup());
         pgassert(o.delivery().is_delivery());
         /* P -> D */
         pgassert(o.delivery().is_compatible_IJ(o.pickup(), speed));
     }
     return true;
 }
References pgassert.
set_compatibles()
void vrprouting::problem::Orders::set_compatibles (Speed speed = 1.0)
set the compatability between all orders
Postcondition
For each order: order -> {J} is set
For each order: {I} -> order is set
Definition at line 128 of file orders.cpp.
{
     for (auto &I : *this) {
         for (const auto& J : *this) {
             I.set_compatibles(J, speed);
         }
     }
 }
Referenced by vrprouting::problem::PickDeliver::PickDeliver().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Orders & p_orders) friend
Definition at line 76 of file orders.h.
{
       log << "Orders\n";
       for (const auto &o : p_orders) log << o << "\n";
       log << "end Orders\n";
       return log;
     }
Member Data Documentation
elements
T std::vector< T >::elements inherited
STL member.
The documentation for this class was generated from the following files:
orders.h
orders.cpp