vrpRouting: vrprouting::problem::Vehicle_node Class Reference
vrprouting::problem::Vehicle_node Class Reference
Extend Tw_node to evaluate the vehicle at node level.
#include "vehicle_node.h"
Public Member Functions
Vehicle_node ()=delete
Construction without information is not allowed.
Vehicle_node (const Tw_node &node)
Construction of a Vehicle node based on a time windows node.
Vehicle_node (const Vehicle_node &)=default
Copy constructor.
TTimestamp arrival_j_closes_i (const Tw_node &I, Speed=1.0) const
arrival time at This node, when arrived at I at closing time TODO refine description
TTimestamp arrival_j_opens_i (const Tw_node &I, Speed=1.0) const
arrival time at This node, when arrived at I at opening time TODO refine description
TTimestamp arrival_time () const
Vehicle's arrival_time to this node.
TTimestamp closes () const
Returns the closing time.
Amount demand () const
Returns the demand associated with this node.
TTimestamp departure_time () const
Vehicle's departure_time from this node.
void evaluate (const Vehicle_node &pred, PAmount, Speed=1.0)
void evaluate (PAmount cargoLimit)
evaluate this node
Solution_rt get_postgres_result (int vid, int64_t v_id, int stop_seq) const
bool is_compatible_IJ (const Tw_node &I, Speed=1.0) const
is possible to arrive to this after visiting other?
bool is_delivery () const
Is the node a valid order's delivery node.
bool is_dump () const
Is the node a valid vehicle's dumping node.
bool is_early_arrival (TTimestamp arrival_time) const
True when arrivalTime is before it opens.
bool is_end () const
Is the node a valid vehicle's ending node.
bool is_late_arrival (TTimestamp arrival_time) const
True when arrivalTime is after it closes.
bool is_load () const
Is the node a valid vehicle's loading node.
bool is_on_time (TTimestamp arrival_time) const
True when arrivalTime in the time window.
bool is_partially_compatible_IJ (const Tw_node &I, Speed=1.0) const
can arrive to this after visiting as late as possible I? TODO refine description
bool is_partially_waitTime_compatible_IJ (const Tw_node &I, Speed=1.0) const
can arrive to this after visiting as late as possible I? TODO refine description
bool is_pickup () const
Is the node a valid order's pickup node.
bool is_start () const
Is the node a valid vehicle's starting node.
bool is_tight_compatible_IJ (const Tw_node &I, Speed=1.0) const
can arrive to this after visiting as late as possible I? TODO refine description
bool is_valid () const
is the node valid?
bool is_waitTime_compatible_IJ (const Tw_node &I, Speed=1.0) const
can arrive to this after visiting as late as possible I? TODO refine description
double objective () const
the basic objective function for this node
TTimestamp opens () const
Returns the opening time.
bool operator== (const Tw_node &rhs) const
equality operator
int64_t order () const
Returns the order to which it belongs.
TInterval service_time () const
Returns the service time for this node.
TInterval travel_time () const
Vehicle's travel_time from previous node to this node.
TInterval travel_time_to (const Tw_node &, TTimestamp, Speed=1.0) const
travel time to other node.
auto type () const
Returns the type of this node.
std::string type_str () const
returns a string code of the kind of node
TInterval wait_time () const
Vehicle's wait_time at this node.
TInterval window_length () const
Returns the length of time between the opening and closing.
Static Public Attributes
static const Matrix * m_time_matrix_ptr = nullptr
Protected Member Functions
void demand (Amount value)
Sets the demand value to a new value.
evaluation
bool has_twv () const
does the node violates the time windows constraints?
bool has_cv (PAmount cargoLimit) const
does the node violates the capacity constraints?
TInterval total_time () const
TInterval delta_time () const
delta_time = departure_time(this) - departure_time(previous)
bool deltaGeneratesTWV (TInterval delta_time) const
True when arrival_time + delta_time generates TWV.
State
bool feasible () const
True when the total count for violations are 0.
bool feasible (PAmount cargoLimit) const
True doesn't have twc nor cv (including total counts)
Private Attributes
TTimestamp m_closes
closing time of the node
Amount m_demand
The demand for the Node.
int64_t m_id
size_t m_idx
TTimestamp m_opens
opening time of the node
int64_t m_order { }
order to which it belongs (idx)
TInterval m_service_time
time it takes to be served
NodeType m_type
The kind of Node.
Node evaluation
TInterval m_travel_time
Travel time from last node.
TTimestamp m_arrival_time
Arrival time at this node.
TInterval m_wait_time
Wait time at this node.
TTimestamp m_departure_time
Departure time from this node.
TInterval m_delta_time
Departure time - last nodes departure time.
Friends
std::ostream & operator<< (std::ostream &log, const Vehicle_node &v)
Print the contents of a Vehicle_node object.
Accumulated evaluation
Amount m_cargo
Accumulated cargo.
int m_twvTot
Total count of TWV.
int m_cvTot
Total count of CV.
TInterval m_tot_wait_time
Accumulated wait time.
TInterval m_tot_travel_time
Accumulated travel time.
TInterval m_tot_service_time
Accumulated service time.
int twvTot () const
Vehicle's total times it has violated time windows.
int cvTot () const
Vehicle's total times it has violated cargo limits.
Amount cargo () const
Vehicle's total cargo after the node was served.
TInterval total_travel_time () const
_time spent moving between nodes by the truck
TInterval total_wait_time () const
_time spent by the truck waiting for nodes to open
TInterval total_service_time () const
_time spent by the truck servicing the nodes
Detailed Description
Extend Tw_node to evaluate the vehicle at node level.
This class extends Twnode by adding attributes to store information and to set and get these attribute values.
Definition at line 49 of file vehicle_node.h.
Constructor & Destructor Documentation
Vehicle_node() [1/3]
vrprouting::problem::Vehicle_node::Vehicle_node () delete
Construction without information is not allowed.
Vehicle_node() [2/3]
vrprouting::problem::Vehicle_node::Vehicle_node (const Vehicle_node &) default
Copy constructor.
Vehicle_node() [3/3]
vrprouting::problem::Vehicle_node::Vehicle_node (const Tw_node & node) explicit
Construction of a Vehicle node based on a time windows node.
Creates a disconnected vehicle node A node that is not served by any vehicle.
Parameters
[in] node Time window node
Definition at line 141 of file vehicle_node.cpp.
   : Tw_node(node),
   m_travel_time(0),
   m_arrival_time(0),
   m_wait_time(0),
   m_departure_time(0),
   m_delta_time(0),
   m_cargo(0),
   m_twvTot(0),
   m_cvTot(0),
   m_tot_wait_time(0),
   m_tot_travel_time(0),
   m_tot_service_time(0) {
   }
Member Function Documentation
arrival_j_closes_i()
TTimestamp vrprouting::problem::Tw_node::arrival_j_closes_i (const Tw_node & I, Speed speed = 1.0) const inherited
arrival time at This node, when arrived at I at closing time TODO refine description
Parameters
[in] I the previous node before this node
[in] speed - speed used for calculation
Returns
the arrival time at this node after visiting I node when I closes
I -> this Value of TWC when arriving to this node after visiting node I at closing time
Definition at line 81 of file tw_node.cpp.
{
   if (m_type == kStart) return  (std::numeric_limits<TTimestamp>::max)();
   return I.closes() + I.service_time() + I.travel_time_to(*this, I.closes() + I.service_time(), speed);
 }
References vrprouting::problem::Tw_node::closes(), vrprouting::problem::kStart, vrprouting::problem::Tw_node::m_type, vrprouting::problem::Tw_node::service_time(), and vrprouting::problem::Tw_node::travel_time_to().
Referenced by vrprouting::problem::Tw_node::is_partially_compatible_IJ(), and vrprouting::problem::Tw_node::is_tight_compatible_IJ().
arrival_j_opens_i()
TTimestamp vrprouting::problem::Tw_node::arrival_j_opens_i (const Tw_node & I, Speed speed = 1.0) const inherited
arrival time at This node, when arrived at I at opening time TODO refine description
Parameters
[in] I the previous node before this node
[in] speed - speed used for calculation
Returns
the arrival time at this node after visiting I node when I opens
I -> this Value of TWC when arriving to this node after visiting node I at opening time
Definition at line 66 of file tw_node.cpp.
{
   if (m_type == kStart) return (std::numeric_limits<TTimestamp>::max)();
   return I.opens() + I.service_time() + I.travel_time_to(*this, I.opens() + I.service_time(), speed);
 }
References vrprouting::problem::kStart, vrprouting::problem::Tw_node::m_type, vrprouting::problem::Tw_node::opens(), vrprouting::problem::Tw_node::service_time(), and vrprouting::problem::Tw_node::travel_time_to().
Referenced by vrprouting::problem::Tw_node::is_compatible_IJ(), vrprouting::problem::Tw_node::is_partially_compatible_IJ(), vrprouting::problem::Tw_node::is_partially_waitTime_compatible_IJ(), vrprouting::problem::Tw_node::is_tight_compatible_IJ(), and vrprouting::problem::Tw_node::is_waitTime_compatible_IJ().
arrival_time()
TTimestamp vrprouting::problem::Vehicle_node::arrival_time () const inline
Vehicle's arrival_time to this node.
Definition at line 68 of file vehicle_node.h.
 {return m_arrival_time;}
References m_arrival_time.
Referenced by evaluate(), get_postgres_result(), and vrprouting::problem::operator<<().
cargo()
Amount vrprouting::problem::Vehicle_node::cargo () const inline
Vehicle's total cargo after the node was served.
Definition at line 86 of file vehicle_node.h.
 {return m_cargo;}
References m_cargo.
Referenced by evaluate(), get_postgres_result(), and vrprouting::problem::operator<<().
closes()
TTimestamp vrprouting::problem::Tw_node::closes () const inline inherited
Returns the closing time.
Definition at line 81 of file tw_node.h.
 {return m_closes;}
References vrprouting::problem::Tw_node::m_closes.
Referenced by vrprouting::problem::Tw_node::arrival_j_closes_i(), vrprouting::problem::Tw_node::is_delivery(), vrprouting::problem::Tw_node::is_dump(), vrprouting::problem::Tw_node::is_end(), vrprouting::problem::Tw_node::is_load(), vrprouting::problem::Vehicle::is_ok(), vrprouting::problem::Tw_node::is_pickup(), and vrprouting::problem::Tw_node::is_start().
cvTot()
int vrprouting::problem::Vehicle_node::cvTot () const inline
Vehicle's total times it has violated cargo limits.
Definition at line 83 of file vehicle_node.h.
 {return m_cvTot;}
References m_cvTot.
Referenced by evaluate(), get_postgres_result(), and vrprouting::problem::operator<<().
delta_time()
TInterval vrprouting::problem::Vehicle_node::delta_time () const inline protected
delta_time = departure_time(this) - departure_time(previous)
Definition at line 120 of file vehicle_node.h.
 {return m_delta_time;}
References m_delta_time.
Referenced by deltaGeneratesTWV().
deltaGeneratesTWV()
bool vrprouting::problem::Vehicle_node::deltaGeneratesTWV (TInterval delta_time) const protected
True when arrival_time + delta_time generates TWV.
Definition at line 158 of file vehicle_node.cpp.
{
   return is_late_arrival(m_arrival_time + delta_time);
 }
References delta_time(), vrprouting::problem::Tw_node::is_late_arrival(), and m_arrival_time.
demand() [1/2]
Amount vrprouting::problem::Tw_node::demand () const inline inherited
Returns the demand associated with this node.
Definition at line 163 of file tw_node.h.
 {return m_demand;}
References vrprouting::problem::Tw_node::m_demand.
Referenced by evaluate(), vrprouting::problem::Tw_node::is_delivery(), vrprouting::problem::Tw_node::is_dump(), vrprouting::problem::Tw_node::is_end(), vrprouting::problem::Tw_node::is_load(), vrprouting::problem::Tw_node::is_pickup(), and vrprouting::problem::Tw_node::is_start().
demand() [2/2]
void vrprouting::problem::Tw_node::demand (Amount value) inline protected inherited
Sets the demand value to a new value.
Definition at line 170 of file tw_node.h.
 {m_demand = value;}
References vrprouting::problem::Tw_node::m_demand.
departure_time()
TTimestamp vrprouting::problem::Vehicle_node::departure_time () const inline
Vehicle's departure_time from this node.
Definition at line 74 of file vehicle_node.h.
 {return m_departure_time;}
References m_departure_time.
Referenced by evaluate(), get_postgres_result(), and vrprouting::problem::operator<<().
evaluate() [1/2]
void vrprouting::problem::Vehicle_node::evaluate (const Vehicle_node & pred, PAmount cargoLimit, Speed speed = 1.0)
Parameters
[in] pred The node preceding this node in the path.
[in] cargoLimit of the vehicle.
[in] speed value to use for calculations
Definition at line 81 of file vehicle_node.cpp.
       {
   /* time */
   m_travel_time    = pred.travel_time_to(*this, pred.departure_time(), speed);
   m_arrival_time   = pred.departure_time() + travel_time();
   m_wait_time      = is_early_arrival(arrival_time()) ?
     opens() - m_arrival_time :
     0;
   m_departure_time = arrival_time() + wait_time() + service_time();
   /* time aggregates */
   m_tot_travel_time = pred.total_travel_time() + travel_time();
   m_tot_wait_time    = pred.total_wait_time()    + wait_time();
   m_tot_service_time = pred.total_service_time() + service_time();
   /* cargo aggregates */
   if (is_dump() &&  pred.cargo() >= 0) {
     demand(-pred.cargo());
   }
   m_cargo = pred.cargo() + demand();
   /* violations aggregates */
   m_twvTot = has_twv() ? pred.twvTot() + 1 : pred.twvTot();
   m_cvTot = has_cv(cargoLimit) ? pred.cvTot() + 1 : pred.cvTot();
   m_delta_time = departure_time() - pred.departure_time();
 }
References arrival_time(), cargo(), cvTot(), vrprouting::problem::Tw_node::demand(), departure_time(), has_cv(), has_twv(), vrprouting::problem::Tw_node::is_dump(), vrprouting::problem::Tw_node::is_early_arrival(), m_arrival_time, m_cargo, m_cvTot, m_delta_time, m_departure_time, m_tot_service_time, m_tot_travel_time, m_tot_wait_time, m_travel_time, m_twvTot, m_wait_time, vrprouting::problem::Tw_node::opens(), vrprouting::problem::Tw_node::service_time(), total_service_time(), total_travel_time(), total_wait_time(), travel_time(), vrprouting::problem::Tw_node::travel_time_to(), twvTot(), and wait_time().
evaluate() [2/2]
void vrprouting::problem::Vehicle_node::evaluate (PAmount cargoLimit)
evaluate this node
Parameters
[in] cargoLimit of the vehicle
Precondition
node is a starting node
evaluates the node
starts the cumulative information
Definition at line 52 of file vehicle_node.cpp.
{
   pgassert(is_start());
   /* time */
   m_travel_time = 0;
   m_arrival_time = opens();
   m_wait_time = 0;
   m_departure_time = arrival_time() + service_time();
   /* time aggregates */
   m_tot_travel_time = 0;
   m_tot_wait_time = 0;
   m_tot_service_time = service_time();
   /* cargo aggregates */
   m_cargo = demand();
   /* violation aggregates */
   m_twvTot = m_cvTot = 0;
   m_cvTot = has_cv(cargoLimit) ? 1 : 0;
   m_delta_time = 0;
 }
References arrival_time(), vrprouting::problem::Tw_node::demand(), has_cv(), vrprouting::problem::Tw_node::is_start(), m_arrival_time, m_cargo, m_cvTot, m_delta_time, m_departure_time, m_tot_service_time, m_tot_travel_time, m_tot_wait_time, m_travel_time, m_twvTot, m_wait_time, vrprouting::problem::Tw_node::opens(), pgassert, and vrprouting::problem::Tw_node::service_time().
feasible() [1/2]
bool vrprouting::problem::Vehicle_node::feasible () const inline protected
True when the total count for violations are 0.
Definition at line 128 of file vehicle_node.h.
 {return m_twvTot == 0 &&  m_cvTot == 0;}
References m_cvTot, and m_twvTot.
Referenced by feasible().
feasible() [2/2]
bool vrprouting::problem::Vehicle_node::feasible (PAmount cargoLimit) const inline protected
True doesn't have twc nor cv (including total counts)
Definition at line 131 of file vehicle_node.h.
{
          return feasible() &&  !has_twv() &&  !has_cv(cargoLimit);
      }
References feasible(), has_cv(), and has_twv().
get_postgres_result()
Solution_rt vrprouting::problem::Vehicle_node::get_postgres_result (int vid, int64_t v_id, int stop_seq) const
Returns
the vehicle's path in a structure for postgres
Parameters
[in] vid it the vid-th vehicle in the solution
[in] v_id it the vehicle identifier of the current node
[in] stop_seq using this sequence value for the current node
Definition at line 193 of file vehicle_node.cpp.
{
   return Solution_rt{
     vid,
       v_id,
       stop_seq,
       /* order_id
        * The order_id is invalid for stops type 0 and 5
        */
       (type() == 0 || type() == 5)? -1 : order(),
       id(),
       type(),
       static_cast<int64_t>(cargo()),
       static_cast<int64_t>(travel_time()),
       static_cast<int64_t>(arrival_time()),
       static_cast<int64_t>(wait_time()),
       static_cast<int64_t>(arrival_time() + wait_time()),
       static_cast<int64_t>(service_time()),
       static_cast<int64_t>(departure_time()),
       cvTot(),
       twvTot()};
 }
References arrival_time(), cargo(), cvTot(), departure_time(), vrprouting::Identifier::id(), vrprouting::problem::Tw_node::order(), vrprouting::problem::Tw_node::service_time(), travel_time(), twvTot(), vrprouting::problem::Tw_node::type(), and wait_time().
has_cv()
bool vrprouting::problem::Vehicle_node::has_cv (PAmount cargoLimit) const protected
does the node violates the capacity constraints?
Parameters
[in] cargoLimit of the vehicle
Returns
true when the node violates the capacity constraints
A capacity violations happens when:
the node is a start or end node and the cargo is not 0
the node's cargo is greater than the limit or is negative
Definition at line 172 of file vehicle_node.cpp.
{
   return is_end() ||  is_start() ? m_cargo != 0
     : m_cargo > cargoLimit ||  m_cargo < 0;
 }
References vrprouting::problem::Tw_node::is_end(), vrprouting::problem::Tw_node::is_start(), and m_cargo.
Referenced by evaluate(), and feasible().
has_twv()
bool vrprouting::problem::Vehicle_node::has_twv () const protected
does the node violates the time windows constraints?
Returns
true when the arrival happens after the closing time
Definition at line 182 of file vehicle_node.cpp.
{
   return is_late_arrival(m_arrival_time);
 }
References vrprouting::problem::Tw_node::is_late_arrival(), and m_arrival_time.
Referenced by evaluate(), feasible(), and vrprouting::problem::operator<<().
id()
int64_t vrprouting::Identifier::id () const inherited
get the original id
Definition at line 42 of file identifier.cpp.
                      {
     return m_id;
 }
References vrprouting::Identifier::m_id.
Referenced by get_postgres_result(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::problem::Vehicle::is_phony(), vrprouting::operator<<(), vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), vrprouting::problem::Vehicle_pickDeliver::set_initial_solution(), vrprouting::problem::Vehicle_pickDeliver::set_unmovable(), vrprouting::problem::Vehicle::tau(), and vrprouting::problem::Tw_node::travel_time_to().
idx()
size_t vrprouting::Identifier::idx () const inherited
get the internal index
Definition at line 37 of file identifier.cpp.
                       {
     return m_idx;
 }
References vrprouting::Identifier::m_idx.
Referenced by vrprouting::problem::Vehicle_pickDeliver::erase(), vrprouting::problem::Vehicle::erase(), vrprouting::problem::Vehicle_pickDeliver::has_order(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::operator<<(), vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), vrprouting::problem::Vehicle_pickDeliver::push_back(), vrprouting::problem::Vehicle_pickDeliver::push_front(), vrprouting::problem::Vehicle_pickDeliver::semiLIFO(), vrprouting::problem::Order::set_compatibles(), and vrprouting::problem::Vehicle::tau().
is_compatible_IJ()
bool vrprouting::problem::Tw_node::is_compatible_IJ (const Tw_node & I, Speed speed = 1.0) const inherited
is possible to arrive to this after visiting other?
Parameters
[in] I node visited before visiting this node
[in] speed - speed used for calculation
Returns
true when arriving this node after visiting node I does not cause a time window violation
false this node is a starting node (no node can be visited before a starting node)
false I node is an ending node (no node can be visited after an ending node)
Definition at line 94 of file tw_node.cpp.
{
   /*
    * I /->  kStart
    */
   if (m_type == kStart) return false;
   /*
    * kEnd /-> (*this)
    */
   if (I.m_type == kEnd) return false;
   return !is_late_arrival(arrival_j_opens_i(I, speed));
 }
References vrprouting::problem::Tw_node::arrival_j_opens_i(), vrprouting::problem::Tw_node::is_late_arrival(), vrprouting::problem::kEnd, vrprouting::problem::kStart, and vrprouting::problem::Tw_node::m_type.
Referenced by vrprouting::problem::Vehicle::getPosHighLimit(), vrprouting::problem::Tw_node::is_partially_compatible_IJ(), vrprouting::problem::Tw_node::is_partially_waitTime_compatible_IJ(), vrprouting::problem::Tw_node::is_tight_compatible_IJ(), vrprouting::problem::Order::is_valid(), vrprouting::problem::Tw_node::is_waitTime_compatible_IJ(), and vrprouting::problem::Order::isCompatibleIJ().
is_delivery()
bool vrprouting::problem::Tw_node::is_delivery () const inherited
Is the node a valid order's delivery node.
Returns
true when the node is a delivery node and is valid
Definition at line 210 of file tw_node.cpp.
{
   return m_type == kDelivery
     && (opens() < closes())
     && (service_time() >= 0)
     && (demand() < 0);
 }
References vrprouting::problem::Tw_node::closes(), vrprouting::problem::Tw_node::demand(), vrprouting::problem::kDelivery, vrprouting::problem::Tw_node::m_type, vrprouting::problem::Tw_node::opens(), and vrprouting::problem::Tw_node::service_time().
Referenced by vrprouting::problem::Order::is_valid(), and vrprouting::problem::Tw_node::is_valid().
is_dump()
bool vrprouting::problem::Tw_node::is_dump () const inherited
Is the node a valid vehicle's dumping node.
Returns
true when the node is a dump node and is valid
Definition at line 222 of file tw_node.cpp.
{
   return m_type == kDump
     && (opens() < closes())
     && (service_time() >= 0)
     && (demand() <= 0);
 }
References vrprouting::problem::Tw_node::closes(), vrprouting::problem::Tw_node::demand(), vrprouting::problem::kDump, vrprouting::problem::Tw_node::m_type, vrprouting::problem::Tw_node::opens(), and vrprouting::problem::Tw_node::service_time().
Referenced by evaluate(), and vrprouting::problem::Tw_node::is_valid().
is_early_arrival()
bool vrprouting::problem::Tw_node::is_early_arrival (TTimestamp arrival_time) const inline inherited
True when arrivalTime is before it opens.
Definition at line 126 of file tw_node.h.
{
          return arrival_time < m_opens;
      }
References vrprouting::problem::Tw_node::m_opens.
Referenced by evaluate(), vrprouting::problem::Tw_node::is_on_time(), vrprouting::problem::Tw_node::is_partially_compatible_IJ(), vrprouting::problem::Tw_node::is_partially_waitTime_compatible_IJ(), vrprouting::problem::Tw_node::is_tight_compatible_IJ(), and vrprouting::problem::Tw_node::is_waitTime_compatible_IJ().
is_end()
bool vrprouting::problem::Tw_node::is_end () const inherited
Is the node a valid vehicle's ending node.
Returns
true when the node is an end node and is valid
Definition at line 245 of file tw_node.cpp.
                       {
   return m_type == kEnd
     && (opens() < closes())
     && (service_time() >= 0)
     && (demand() == 0);
 }
References vrprouting::problem::Tw_node::closes(), vrprouting::problem::Tw_node::demand(), vrprouting::problem::kEnd, vrprouting::problem::Tw_node::m_type, vrprouting::problem::Tw_node::opens(), and vrprouting::problem::Tw_node::service_time().
Referenced by vrprouting::problem::Fleet::add_vehicle(), vrprouting::problem::Vehicle::erase(), has_cv(), and vrprouting::problem::Tw_node::is_valid().
is_late_arrival()
bool vrprouting::problem::Tw_node::is_late_arrival (TTimestamp arrival_time) const inline inherited
True when arrivalTime is after it closes.
Definition at line 121 of file tw_node.h.
{
          return arrival_time > m_closes;
      }
References vrprouting::problem::Tw_node::m_closes.
Referenced by deltaGeneratesTWV(), has_twv(), vrprouting::problem::Tw_node::is_compatible_IJ(), vrprouting::problem::Tw_node::is_on_time(), vrprouting::problem::Tw_node::is_partially_compatible_IJ(), and vrprouting::problem::Tw_node::is_tight_compatible_IJ().
is_load()
bool vrprouting::problem::Tw_node::is_load () const inherited
Is the node a valid vehicle's loading node.
Returns
true when the node is a load node and is valid
Definition at line 234 of file tw_node.cpp.
{
   return m_type == kLoad
     && (opens() < closes())
     && (service_time() >= 0)
     && (demand() >= 0);
 }
References vrprouting::problem::Tw_node::closes(), vrprouting::problem::Tw_node::demand(), vrprouting::problem::kLoad, vrprouting::problem::Tw_node::m_type, vrprouting::problem::Tw_node::opens(), and vrprouting::problem::Tw_node::service_time().
Referenced by vrprouting::problem::Tw_node::is_valid().
is_on_time()
bool vrprouting::problem::Tw_node::is_on_time (TTimestamp arrival_time) const inline inherited
True when arrivalTime in the time window.
Definition at line 131 of file tw_node.h.
{
          return !is_early_arrival(arrival_time)
              && !is_late_arrival(arrival_time);
      }
References vrprouting::problem::Tw_node::is_early_arrival(), and vrprouting::problem::Tw_node::is_late_arrival().
is_partially_compatible_IJ()
bool vrprouting::problem::Tw_node::is_partially_compatible_IJ (const Tw_node & I, Speed speed = 1.0) const inherited
can arrive to this after visiting as late as possible I? TODO refine description
Parameters
[in] I node visited before visiting this node
[in] speed - speed used for calculation
Returns
true when TODO TBD
false this node is TODO TBD
false I node is TODO TBD
Definition at line 116 of file tw_node.cpp.
{
   return
     is_compatible_IJ(I, speed)
     && !is_early_arrival(arrival_j_opens_i(I, speed))
     && is_late_arrival(arrival_j_closes_i(I, speed));
 }
References vrprouting::problem::Tw_node::arrival_j_closes_i(), vrprouting::problem::Tw_node::arrival_j_opens_i(), vrprouting::problem::Tw_node::is_compatible_IJ(), vrprouting::problem::Tw_node::is_early_arrival(), and vrprouting::problem::Tw_node::is_late_arrival().
is_partially_waitTime_compatible_IJ()
bool vrprouting::problem::Tw_node::is_partially_waitTime_compatible_IJ (const Tw_node & I, Speed speed = 1.0) const inherited
can arrive to this after visiting as late as possible I? TODO refine description
Parameters
[in] I node visited before visiting this node
[in] speed - speed used for calculation
Returns
true when TODO TBD
false this node is TODO TBD
false I node is TODO TBD
Definition at line 146 of file tw_node.cpp.
{
   return
     is_compatible_IJ(I, speed)
     && is_early_arrival(arrival_j_opens_i(I, speed));
 }
References vrprouting::problem::Tw_node::arrival_j_opens_i(), vrprouting::problem::Tw_node::is_compatible_IJ(), and vrprouting::problem::Tw_node::is_early_arrival().
is_pickup()
bool vrprouting::problem::Tw_node::is_pickup () const inherited
Is the node a valid order's pickup node.
Returns
true when the node is a pickup node and is valid
Definition at line 199 of file tw_node.cpp.
{
   return m_type == kPickup
     && (opens() < closes())
     && (service_time() >= 0)
     && (demand() > 0);
 }
References vrprouting::problem::Tw_node::closes(), vrprouting::problem::Tw_node::demand(), vrprouting::problem::kPickup, vrprouting::problem::Tw_node::m_type, vrprouting::problem::Tw_node::opens(), and vrprouting::problem::Tw_node::service_time().
Referenced by vrprouting::problem::Order::is_valid(), and vrprouting::problem::Tw_node::is_valid().
is_start()
bool vrprouting::problem::Tw_node::is_start () const inherited
Is the node a valid vehicle's starting node.
Returns
true when the node is a starting node and is valid
Definition at line 187 of file tw_node.cpp.
{
   return
     m_type == kStart
     && (opens() < closes())
     && (service_time() >= 0)
     && (demand() == 0);
 }
References vrprouting::problem::Tw_node::closes(), vrprouting::problem::Tw_node::demand(), vrprouting::problem::kStart, vrprouting::problem::Tw_node::m_type, vrprouting::problem::Tw_node::opens(), and vrprouting::problem::Tw_node::service_time().
Referenced by vrprouting::problem::Vehicle::erase(), evaluate(), has_cv(), and vrprouting::problem::Tw_node::is_valid().
is_tight_compatible_IJ()
bool vrprouting::problem::Tw_node::is_tight_compatible_IJ (const Tw_node & I, Speed speed = 1.0) const inherited
can arrive to this after visiting as late as possible I? TODO refine description
Parameters
[in] I node visited before visiting this node
[in] speed - speed used for calculation
Returns
true when TODO TBD
false this node is TODO TBD
false I node is TODO TBD
Definition at line 131 of file tw_node.cpp.
{
   return
     is_compatible_IJ(I, speed)
     && !is_early_arrival(arrival_j_opens_i(I, speed))
     && !is_late_arrival(arrival_j_closes_i(I, speed));
 }
References vrprouting::problem::Tw_node::arrival_j_closes_i(), vrprouting::problem::Tw_node::arrival_j_opens_i(), vrprouting::problem::Tw_node::is_compatible_IJ(), vrprouting::problem::Tw_node::is_early_arrival(), and vrprouting::problem::Tw_node::is_late_arrival().
is_valid()
bool vrprouting::problem::Tw_node::is_valid () const inherited
is the node valid?
Returns
true when the node depending on the kind is a valid node
Definition at line 274 of file tw_node.cpp.
{
   switch (type()) {
     case kStart:
       return is_start();
       break;
     case kEnd:
       return is_end();
       break;
     case kDump:
       return is_dump();
       break;
     case kDelivery:
       return is_delivery();
       break;
     case kPickup:
       return is_pickup();
       break;
     case kLoad:
       return is_load();
       break;
     default:
       return false;
       break;
   }
   return false;
 }
References vrprouting::problem::Tw_node::is_delivery(), vrprouting::problem::Tw_node::is_dump(), vrprouting::problem::Tw_node::is_end(), vrprouting::problem::Tw_node::is_load(), vrprouting::problem::Tw_node::is_pickup(), vrprouting::problem::Tw_node::is_start(), vrprouting::problem::kDelivery, vrprouting::problem::kDump, vrprouting::problem::kEnd, vrprouting::problem::kLoad, vrprouting::problem::kPickup, vrprouting::problem::kStart, and vrprouting::problem::Tw_node::type().
is_waitTime_compatible_IJ()
bool vrprouting::problem::Tw_node::is_waitTime_compatible_IJ (const Tw_node & I, Speed speed = 1.0) const inherited
can arrive to this after visiting as late as possible I? TODO refine description
Parameters
[in] I node visited before visiting this node
[in] speed - speed used for calculation
Returns
true when TODO TBD
false this node is TODO TBD
false I node is TODO TBD
Definition at line 162 of file tw_node.cpp.
{
   return
     is_compatible_IJ(I, speed)
     && is_early_arrival(arrival_j_opens_i(I, speed));
 }
References vrprouting::problem::Tw_node::arrival_j_opens_i(), vrprouting::problem::Tw_node::is_compatible_IJ(), and vrprouting::problem::Tw_node::is_early_arrival().
objective()
double vrprouting::problem::Vehicle_node::objective () const
the basic objective function for this node
Returns
the value of the objective function for this node
Definition at line 39 of file vehicle_node.cpp.
{
   return static_cast<double>(travel_time());
 }
References travel_time().
opens()
TTimestamp vrprouting::problem::Tw_node::opens () const inline inherited
Returns the opening time.
Definition at line 78 of file tw_node.h.
 {return m_opens;}
References vrprouting::problem::Tw_node::m_opens.
Referenced by vrprouting::problem::Tw_node::arrival_j_opens_i(), evaluate(), vrprouting::problem::Tw_node::is_delivery(), vrprouting::problem::Tw_node::is_dump(), vrprouting::problem::Tw_node::is_end(), vrprouting::problem::Tw_node::is_load(), vrprouting::problem::Vehicle::is_ok(), vrprouting::problem::Tw_node::is_pickup(), and vrprouting::problem::Tw_node::is_start().
operator==()
bool vrprouting::problem::Tw_node::operator== (const Tw_node & other) const inherited
equality operator
Returns
true when the other node is the same as this node
Parameters
[in] other
Definition at line 258 of file tw_node.cpp.
{
   if (&other == this) return true;
   return m_order == other.m_order
     && m_opens == other.m_opens
     && m_closes == other.m_closes
     && m_service_time == other.m_service_time
     && m_demand == other.m_demand
     && m_type == other.m_type
     && id() == other.id()
     && idx() == other.idx();
 }
References vrprouting::Identifier::id(), vrprouting::Identifier::idx(), vrprouting::problem::Tw_node::m_closes, vrprouting::problem::Tw_node::m_demand, vrprouting::problem::Tw_node::m_opens, vrprouting::problem::Tw_node::m_order, vrprouting::problem::Tw_node::m_service_time, and vrprouting::problem::Tw_node::m_type.
order()
int64_t vrprouting::problem::Tw_node::order () const inline inherited
Returns the order to which it belongs.
Definition at line 75 of file tw_node.h.
 {return m_order;}
References vrprouting::problem::Tw_node::m_order.
Referenced by get_postgres_result().
reset_id()
void vrprouting::Identifier::reset_id (int64_t _id) inherited
change the original id
Definition at line 47 of file identifier.cpp.
{
     m_id = _id;
 }
References vrprouting::Identifier::m_id.
Referenced by vrprouting::problem::Tw_node::Tw_node().
service_time()
TInterval vrprouting::problem::Tw_node::service_time () const inline inherited
Returns the service time for this node.
Definition at line 84 of file tw_node.h.
 {return m_service_time;}
References vrprouting::problem::Tw_node::m_service_time.
Referenced by vrprouting::problem::Tw_node::arrival_j_closes_i(), vrprouting::problem::Tw_node::arrival_j_opens_i(), evaluate(), get_postgres_result(), vrprouting::problem::Tw_node::is_delivery(), vrprouting::problem::Tw_node::is_dump(), vrprouting::problem::Tw_node::is_end(), vrprouting::problem::Tw_node::is_load(), vrprouting::problem::Tw_node::is_pickup(), vrprouting::problem::Tw_node::is_start(), and vrprouting::problem::operator<<().
total_service_time()
TInterval vrprouting::problem::Vehicle_node::total_service_time () const inline
_time spent by the truck servicing the nodes
Definition at line 95 of file vehicle_node.h.
 {return m_tot_service_time;}
References m_tot_service_time.
Referenced by evaluate().
total_time()
TInterval vrprouting::problem::Vehicle_node::total_time () const inline protected
Definition at line 117 of file vehicle_node.h.
 {return m_departure_time - m_arrival_time;}
References m_arrival_time, and m_departure_time.
total_travel_time()
TInterval vrprouting::problem::Vehicle_node::total_travel_time () const inline
_time spent moving between nodes by the truck
Definition at line 89 of file vehicle_node.h.
 {return m_tot_travel_time;}
References m_tot_travel_time.
Referenced by evaluate().
total_wait_time()
TInterval vrprouting::problem::Vehicle_node::total_wait_time () const inline
_time spent by the truck waiting for nodes to open
Definition at line 92 of file vehicle_node.h.
 {return m_tot_wait_time;}
References m_tot_wait_time.
Referenced by evaluate().
travel_time()
TInterval vrprouting::problem::Vehicle_node::travel_time () const inline
Vehicle's travel_time from previous node to this node.
Definition at line 65 of file vehicle_node.h.
 {return m_travel_time;}
References m_travel_time.
Referenced by evaluate(), get_postgres_result(), objective(), and vrprouting::problem::operator<<().
travel_time_to()
TInterval vrprouting::problem::Tw_node::travel_time_to (const Tw_node & other, TTimestamp time, Speed speed = 1.0) const inherited
travel time to other node.
Parameters
[in] other - pointer to the other Tw_node
[in] time - time of departure from previous node
[in] speed - speed used for calculation
Returns
the travel time from this to other]
Definition at line 51 of file tw_node.cpp.
{
   pgassert(speed != 0);
   return static_cast<TInterval>(static_cast<Speed>(m_time_matrix_ptr->travel_time(id(), other.id(), time)) / speed);
 }
References vrprouting::Identifier::id(), vrprouting::problem::Tw_node::m_time_matrix_ptr, pgassert, and vrprouting::problem::Matrix::travel_time().
Referenced by vrprouting::problem::Tw_node::arrival_j_closes_i(), vrprouting::problem::Tw_node::arrival_j_opens_i(), and evaluate().
twvTot()
int vrprouting::problem::Vehicle_node::twvTot () const inline
Vehicle's total times it has violated time windows.
Definition at line 80 of file vehicle_node.h.
 {return m_twvTot;}
References m_twvTot.
Referenced by evaluate(), get_postgres_result(), and vrprouting::problem::operator<<().
type()
auto vrprouting::problem::Tw_node::type () const inline inherited
Returns the type of this node.
Definition at line 87 of file tw_node.h.
 {return m_type;}
References vrprouting::problem::Tw_node::m_type.
Referenced by get_postgres_result(), vrprouting::problem::Tw_node::is_valid(), and vrprouting::problem::Tw_node::type_str().
type_str()
std::string vrprouting::problem::Tw_node::type_str () const inherited
returns a string code of the kind of node
Returns
the short hand of the kind of node
Definition at line 171 of file tw_node.cpp.
{
   switch (type()) {
     case kStart: return "S";
     case kEnd: return "E";
     case kDump: return "D";
     case kLoad: return "L";
     case kPickup: return "P";
     case kDelivery: return "D";
     default: return "UNKNOWN";
   }
 }
References vrprouting::problem::kDelivery, vrprouting::problem::kDump, vrprouting::problem::kEnd, vrprouting::problem::kLoad, vrprouting::problem::kPickup, vrprouting::problem::kStart, and vrprouting::problem::Tw_node::type().
Referenced by vrprouting::problem::operator<<().
wait_time()
TInterval vrprouting::problem::Vehicle_node::wait_time () const inline
Vehicle's wait_time at this node.
Definition at line 71 of file vehicle_node.h.
 {return m_wait_time;}
References m_wait_time.
Referenced by evaluate(), get_postgres_result(), and vrprouting::problem::operator<<().
window_length()
TInterval vrprouting::problem::Tw_node::window_length () const inline inherited
Returns the length of time between the opening and closing.
Definition at line 90 of file tw_node.h.
 {return m_closes - m_opens;}
References vrprouting::problem::Tw_node::m_closes, and vrprouting::problem::Tw_node::m_opens.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Vehicle_node & v) friend
Print the contents of a Vehicle_node object.
Parameters
[in,out] log Place to store the printed status of the node
[in] v Vehicle node to print
Returns
the new string
Definition at line 119 of file vehicle_node.cpp.
{
   log << static_cast<const Tw_node&>(v)
     << " twv = " << v.has_twv()
     << ", twvTot = " << v.twvTot()
     << ", cvTot = " << v.cvTot()
     << ", cargo = " << v.cargo()
     << ", travel_time = " << v.travel_time()
     << ", arrival_time = " << v.arrival_time()
     << ", wait_time = " << v.wait_time()
     << ", service_time = " << v.service_time()
     << ", departure_time = " << v.departure_time();
   return log;
 }
Member Data Documentation
m_arrival_time
TTimestamp vrprouting::problem::Vehicle_node::m_arrival_time private
Arrival time at this node.
Definition at line 145 of file vehicle_node.h.
Referenced by arrival_time(), deltaGeneratesTWV(), evaluate(), has_twv(), and total_time().
m_cargo
Amount vrprouting::problem::Vehicle_node::m_cargo private
Accumulated cargo.
Definition at line 165 of file vehicle_node.h.
Referenced by cargo(), evaluate(), and has_cv().
m_closes
TTimestamp vrprouting::problem::Tw_node::m_closes private inherited
closing time of the node
Definition at line 180 of file tw_node.h.
Referenced by vrprouting::problem::Tw_node::closes(), vrprouting::problem::Tw_node::is_late_arrival(), vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), vrprouting::problem::Tw_node::Tw_node(), and vrprouting::problem::Tw_node::window_length().
m_cvTot
int vrprouting::problem::Vehicle_node::m_cvTot private
Total count of CV.
Definition at line 171 of file vehicle_node.h.
Referenced by cvTot(), evaluate(), and feasible().
m_delta_time
TInterval vrprouting::problem::Vehicle_node::m_delta_time private
Departure time - last nodes departure time.
Definition at line 157 of file vehicle_node.h.
Referenced by delta_time(), and evaluate().
m_demand
Amount vrprouting::problem::Tw_node::m_demand private inherited
The demand for the Node.
Definition at line 186 of file tw_node.h.
Referenced by vrprouting::problem::Tw_node::demand(), vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), and vrprouting::problem::Tw_node::Tw_node().
m_departure_time
TTimestamp vrprouting::problem::Vehicle_node::m_departure_time private
Departure time from this node.
Definition at line 154 of file vehicle_node.h.
Referenced by departure_time(), evaluate(), and total_time().
m_id
int64_t vrprouting::Identifier::m_id private inherited
Definition at line 87 of file identifier.h.
Referenced by vrprouting::Identifier::id(), and vrprouting::Identifier::reset_id().
m_idx
size_t vrprouting::Identifier::m_idx private inherited
Definition at line 86 of file identifier.h.
Referenced by vrprouting::Identifier::idx().
m_opens
TTimestamp vrprouting::problem::Tw_node::m_opens private inherited
opening time of the node
Definition at line 177 of file tw_node.h.
Referenced by vrprouting::problem::Tw_node::is_early_arrival(), vrprouting::problem::Tw_node::opens(), vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), vrprouting::problem::Tw_node::Tw_node(), and vrprouting::problem::Tw_node::window_length().
m_order
int64_t vrprouting::problem::Tw_node::m_order { } private inherited
order to which it belongs (idx)
Definition at line 174 of file tw_node.h.
Referenced by vrprouting::problem::Tw_node::operator==(), and vrprouting::problem::Tw_node::order().
m_service_time
TInterval vrprouting::problem::Tw_node::m_service_time private inherited
time it takes to be served
Definition at line 183 of file tw_node.h.
Referenced by vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), vrprouting::problem::Tw_node::service_time(), and vrprouting::problem::Tw_node::Tw_node().
m_time_matrix_ptr
const Matrix * vrprouting::problem::Tw_node::m_time_matrix_ptr = nullptr static inherited
Definition at line 139 of file tw_node.h.
Referenced by vrprouting::problem::Orders::Orders(), and vrprouting::problem::Tw_node::travel_time_to().
m_tot_service_time
TInterval vrprouting::problem::Vehicle_node::m_tot_service_time private
Accumulated service time.
Definition at line 180 of file vehicle_node.h.
Referenced by evaluate(), and total_service_time().
m_tot_travel_time
TInterval vrprouting::problem::Vehicle_node::m_tot_travel_time private
Accumulated travel time.
Definition at line 177 of file vehicle_node.h.
Referenced by evaluate(), and total_travel_time().
m_tot_wait_time
TInterval vrprouting::problem::Vehicle_node::m_tot_wait_time private
Accumulated wait time.
Definition at line 174 of file vehicle_node.h.
Referenced by evaluate(), and total_wait_time().
m_travel_time
TInterval vrprouting::problem::Vehicle_node::m_travel_time private
Travel time from last node.
Definition at line 142 of file vehicle_node.h.
Referenced by evaluate(), and travel_time().
m_twvTot
int vrprouting::problem::Vehicle_node::m_twvTot private
Total count of TWV.
Definition at line 168 of file vehicle_node.h.
Referenced by evaluate(), feasible(), and twvTot().
m_type
NodeType vrprouting::problem::Tw_node::m_type private inherited
The kind of Node.
Definition at line 189 of file tw_node.h.
Referenced by vrprouting::problem::Tw_node::arrival_j_closes_i(), vrprouting::problem::Tw_node::arrival_j_opens_i(), vrprouting::problem::Tw_node::is_compatible_IJ(), vrprouting::problem::Tw_node::is_delivery(), vrprouting::problem::Tw_node::is_dump(), vrprouting::problem::Tw_node::is_end(), vrprouting::problem::Tw_node::is_load(), vrprouting::problem::Tw_node::is_pickup(), vrprouting::problem::Tw_node::is_start(), vrprouting::problem::Tw_node::operator==(), vrprouting::problem::Tw_node::Tw_node(), and vrprouting::problem::Tw_node::type().
m_wait_time
TInterval vrprouting::problem::Vehicle_node::m_wait_time private
Wait time at this node.
0 when arrived after the node opens
>0 when arrived before the node opens
Definition at line 151 of file vehicle_node.h.
Referenced by evaluate(), and wait_time().
The documentation for this class was generated from the following files:
vehicle_node.h
vehicle_node.cpp