vrpRouting: vrprouting::Identifier Class Reference
vrprouting::Identifier Class Reference
Class that stores the information about identifiers.
#include "identifier.h"
Public Member Functions
Identifier ()=default
Identifier (const Identifier &v)=default
Identifier (size_t _idx, int64_t _id)
Private Attributes
int64_t m_id
size_t m_idx
Friends
std::ostream & operator<< (std::ostream &log, const Identifier &)
print the Identifier information
Detailed Description
Class that stores the information about identifiers.
Data comes with an identifier
does not check for uniquenes of those identifiers
it is responsibility of the database mantainers to give unique identifiers
Example use:
struct data_t {
 int64_t d_id;  // identifier value
 // other structure members
}
vector<data_t> foo;
foo.push_back({1234, ... })
Identifier i(0, 1234); // original identifier 1234 is located on position 0 of foo
Definition at line 65 of file identifier.h.
Constructor & Destructor Documentation
Identifier() [1/3]
vrprouting::Identifier::Identifier () default
Identifier() [2/3]
vrprouting::Identifier::Identifier (const Identifier & v) default
Identifier() [3/3]
vrprouting::Identifier::Identifier (size_t _idx, int64_t _id)
Definition at line 30 of file identifier.cpp.
                            :
     m_idx(_idx),
     m_id(_id) {}
Member Function Documentation
id()
int64_t vrprouting::Identifier::id () const
get the original id
Definition at line 42 of file identifier.cpp.
                      {
     return m_id;
 }
References m_id.
Referenced by vrprouting::problem::Vehicle_node::get_postgres_result(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::problem::Vehicle::is_phony(), vrprouting::operator<<(), vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), vrprouting::problem::Vehicle_pickDeliver::set_initial_solution(), vrprouting::problem::Vehicle_pickDeliver::set_unmovable(), vrprouting::problem::Vehicle::tau(), and vrprouting::problem::Tw_node::travel_time_to().
idx()
size_t vrprouting::Identifier::idx () const
get the internal index
Definition at line 37 of file identifier.cpp.
                       {
     return m_idx;
 }
References m_idx.
Referenced by vrprouting::problem::Vehicle_pickDeliver::erase(), vrprouting::problem::Vehicle::erase(), vrprouting::problem::Vehicle_pickDeliver::has_order(), vrprouting::problem::Vehicle_pickDeliver::hillClimb(), vrprouting::operator<<(), vrprouting::problem::operator<<(), vrprouting::problem::Tw_node::operator==(), vrprouting::problem::Vehicle_pickDeliver::push_back(), vrprouting::problem::Vehicle_pickDeliver::push_front(), vrprouting::problem::Vehicle_pickDeliver::semiLIFO(), vrprouting::problem::Order::set_compatibles(), and vrprouting::problem::Vehicle::tau().
reset_id()
void vrprouting::Identifier::reset_id (int64_t _id)
change the original id
Definition at line 47 of file identifier.cpp.
{
     m_id = _id;
 }
References m_id.
Referenced by vrprouting::problem::Tw_node::Tw_node().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Identifier & ident) friend
print the Identifier information
Definition at line 51 of file identifier.cpp.
{
     log << "id(idx) = " << ident.id() << "(" << ident.idx() << ")";
     return log;
 }
Member Data Documentation
m_id
int64_t vrprouting::Identifier::m_id private
Definition at line 87 of file identifier.h.
Referenced by id(), and reset_id().
m_idx
size_t vrprouting::Identifier::m_idx private
Definition at line 86 of file identifier.h.
Referenced by idx().
The documentation for this class was generated from the following files:
identifier.h
identifier.cpp