vrpRouting: compatibleVehicles_driver.cpp File Reference
compatibleVehicles_driver.cpp File Reference
#include "drivers/compatibleVehicles_driver.h"
#include <cstring>
#include <sstream>
#include <string>
#include <deque>
#include "problem/pickDeliver.h"
#include "problem/matrix.h"
#include "c_types/pickDeliveryOrders_t.h"
#include "c_types/compatibleVehicles_rt.h"
#include "c_types/vehicle_t.h"
#include "cpp_common/pgr_assert.h"
#include "c_common/pgr_alloc.hpp"
Functions
void do_compatibleVehicles (PickDeliveryOrders_t customers_arr[], size_t total_customers, Vehicle_t *vehicles_arr, size_t total_vehicles, Matrix_cell_t *matrix_cells_arr, size_t total_cells, Time_multipliers_t *multipliers_arr, size_t total_multipliers, double factor, CompatibleVehicles_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Driver for processing a "compatible vehicles" problem.
Function Documentation
do_compatibleVehicles()
void do_compatibleVehicles (PickDeliveryOrders_t customers_arr[], size_t total_customers, Vehicle_t * vehicles_arr, size_t total_vehicles, Matrix_cell_t * matrix_cells_arr, size_t total_cells, Time_multipliers_t * multipliers_arr, size_t total_multipliers, double factor, CompatibleVehicles_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Driver for processing a "compatible vehicles" problem.
Parameters
[in] customers_arr A C Array of pickup and dropoff orders
[in] total_customers size of the customers_arr
[in] vehicles_arr A C Array of vehicles
[in] total_vehicles size of the vehicles_arr
[in] matrix_cells_arr A C Array of the (time) matrix cells
[in] total_cells size of the matrix_cells_arr
[in] multipliers_arr A C Array of the multipliers
[in] total_multipliers size of the multipliers_arr
[in] factor A global multiplier for the (time) matrix cells
[out] return_tuples C array of contents to be returned to postgres
[out] return_count number of tuples returned
[out] log_msg special log message pointer
[out] notice_msg special message pointer to be returned as NOTICE
[out] err_msg special message pointer to be returned as ERROR
Precondition
The messages: log_msg, notice_msg, err_msg must be empty (=nullptr)
The C arrays: customers_arr, vehicles_arr, matrix_cells_arr must not be empty
The C array: return_tuples must be empty
Only matrix cells (i, i) can be missing and are considered as 0 (time units)
Postcondition
The C arrays: customers_arr, vehicles_arr, matrix_cells_arr Do not change
The C array: return_tuples contains the result for the problem given
The return_tuples array size is return_count
The return_tuples array size is return_count
err_msg is empty if no throw from the process is catched
log_msg contains some logging
notice_msg is empty
Definition at line 98 of file compatibleVehicles_driver.cpp.
{
     std::ostringstream log;
     std::ostringstream notice;
     std::ostringstream err;
     try {
         /*
          * verify preconditions
          */
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(total_customers);
         pgassert(total_vehicles);
         pgassert(total_vehicles);
         pgassert(*return_count == 0);
         pgassert(!(*return_tuples));
         log << "do_compatibleVehicles\n";
         Identifiers<Id> node_ids;
         for (size_t i = 0; i < total_customers; ++i) {
             node_ids += customers_arr[i].pick_node_id;
             node_ids += customers_arr[i].deliver_node_id;
         }
         for (size_t i = 0; i < total_vehicles; ++i) {
             node_ids += vehicles_arr[i].start_node_id;
             node_ids += vehicles_arr[i].end_node_id;
         }
         /*
          * Verify matrix cells preconditions
          */
         vrprouting::problem::Matrix cost_matrix(
             matrix_cells_arr, total_cells,
             multipliers_arr, total_multipliers,
             node_ids, static_cast<Multiplier>(factor));
 #if 0
         /*
          * Verify matrix triangle inequality
          */
         if (!cost_matrix.obeys_triangle_inequality()) {
             log << "[Compatible Vehicles] Fixing Matrix that does not obey triangle inequality ";
             log << cost_matrix.fix_triangle_inequality() << " cycles used";
             if (!cost_matrix.obeys_triangle_inequality()) {
                 log << "[Compatible Vehicles] Matrix Still does not obey triangle inequality";
             }
         }
 #endif
         if (!cost_matrix.has_no_infinity()) {
             err << "An Infinity value was found on the Matrix";
             *err_msg = pgr_msg(err.str());
             return;
         }
         /*
          * Construct problem
          */
         log << "Initialize problem\n";
         vrprouting::problem::PickDeliver pd_problem(
                 customers_arr, total_customers,
                 vehicles_arr, total_vehicles,
                 cost_matrix);
         err << pd_problem.msg.get_error();
         if (!err.str().empty()) {
             log << pd_problem.msg.get_log();
             *log_msg = pgr_msg(log.str());
             *err_msg = pgr_msg(err.str());
             return;
         }
         log << pd_problem.msg.get_log();
         log << "Finish Reading data\n";
         pd_problem.msg.clear();
         /*
          * Prepare results
          */
         auto solution = pd_problem.get_pg_compatibleVehicles();
         log << "solution size: " << solution.size() << "\n";
         log << "solution empty: " << solution.empty() << "\n";
         if (!solution.empty()) {
             log << "solution empty " << "\n";
             (*return_tuples) = pgr_alloc(solution.size(), (*return_tuples));
             int seq = 0;
             for (const auto &row : solution) {
                 (*return_tuples)[seq] = row;
                 ++seq;
             }
         }
         (*return_count) = solution.size();
         pgassert(*err_msg == nullptr);
         *log_msg = log.str().empty()?
             nullptr :
             pgr_msg(log.str());
         *notice_msg = notice.str().empty()?
             nullptr :
             pgr_msg(notice.str());
     } catch (AssertFailedException &except) {
         if (*return_tuples) free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str());
         *log_msg = pgr_msg(log.str());
     } catch (std::exception& except) {
         if (*return_tuples) free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str());
         *log_msg = pgr_msg(log.str());
     } catch(...) {
         if (*return_tuples) free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str());
         *log_msg = pgr_msg(log.str());
     }
 }
References vrprouting::Pgr_messages::clear(), PickDeliveryOrders_t::deliver_node_id, Vehicle_t::end_node_id, vrprouting::base::Base_Matrix::fix_triangle_inequality(), vrprouting::Pgr_messages::get_error(), vrprouting::Pgr_messages::get_log(), vrprouting::problem::PickDeliver::get_pg_compatibleVehicles(), vrprouting::base::Base_Matrix::has_no_infinity(), vrprouting::problem::PickDeliver::msg, vrprouting::base::Base_Matrix::obeys_triangle_inequality(), pgassert, pgr_alloc(), pgr_msg(), PickDeliveryOrders_t::pick_node_id, Vehicle_t::start_node_id, and AssertFailedException::what().
Referenced by process().