vrpRouting: get_check_data.c File Reference
get_check_data.c File Reference
#include <stdbool.h>
#include <time.h>
#include "c_common/postgres_connection.h"
#include <utils/date.h>
#include <utils/datetime.h>
#include "c_common/get_check_data.h"
#include "c_common/arrays_input.h"
#include "catalog/pg_type.h"
#include "c_common/debug_macro.h"
#include "c_types/typedefs.h"
Functions
static void check_any_integer_type (Column_info_t info)
static void check_any_integerarray_type (Column_info_t info)
static void check_any_numerical_type (Column_info_t info)
static void check_char_type (Column_info_t info)
static void check_integer_type (Column_info_t info)
static void check_integerarray_type (Column_info_t info)
static void check_interval_type (Column_info_t info)
static void check_jsonb_type (Column_info_t info)
static void check_text_type (Column_info_t info)
static void check_timestamp_type (Column_info_t info)
bool column_found (int colNumber)
Check whether the colNumber represent any specific column or NULL (SPI_ERROR_NOATTRIBUTE).
static bool fetch_column_info (Column_info_t *info)
Amount get_Amount (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, Amount opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
TravelCost get_Cost (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, TravelCost opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
Distance get_Distance (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, Distance opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
Duration get_Duration (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, Duration opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
Id get_Id (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, Id opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
Idx get_Idx (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, Idx opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
char get_Kind (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, char opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
MatrixIndex get_MatrixIndex (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, MatrixIndex opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
PAmount get_PositiveAmount (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, PAmount opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
TInterval get_PositiveTInterval (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, TInterval opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
TInterval get_PositiveTInterval_plain (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, TInterval opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
TTimestamp get_PositiveTTimestamp (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, TTimestamp opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
TTimestamp get_PositiveTTimestamp_plain (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, TTimestamp opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
Priority get_Priority (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, Priority opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
StepType get_StepType (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, StepType opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
TInterval get_TInterval (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, TInterval opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
TInterval get_TInterval_plain (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, TInterval opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
TTimestamp get_TTimestamp (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, TTimestamp opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
TTimestamp get_TTimestamp_plain (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, TTimestamp opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
void pgr_fetch_column_info (Column_info_t info[], int info_size)
Function tells expected type of each column and then check the correspondence type of each column.
static int64_t spi_getBigInt (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info)
int64_t * spi_getBigIntArr (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, size_t *the_size)
Function returns the values of specified columns in array.
int64_t * spi_getBigIntArr_allowEmpty (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, size_t *the_size)
Function returns the values of specified columns in array.
char spi_getChar (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, char default_value)
get value of specified column in char type.
Coordinate spi_getCoordinate (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, Coordinate opt_value)
get a coordinate value
double spi_getFloat8 (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info)
gets value of specified column in double type.
static int32_t spi_getInt (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info)
static TInterval spi_getInterval (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info)
int32_t spi_getMaxTasks (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info)
gets the vehicle max tasks value
int64_t * spi_getPositiveBigIntArr_allowEmpty (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, size_t *the_size)
Function returns the values of specified columns in array.
uint32_t * spi_getPositiveIntArr_allowEmpty (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, size_t *the_size)
Function returns the values of specified columns in array.
char * spi_getText (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info)
under development
static TTimestamp spi_getTimeStamp (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info)
TTimestamp timestamp_without_timezone (TTimestamp timestamp)
Steps: 1) Similar to: https://doxygen.postgresql.org/backend_2utils_2adt_2timestamp_8c.html#a52973f03ed8296b632d4028121f7e077 2) Using time.h to convert.
Function Documentation
check_any_integer_type()
static void check_any_integer_type (Column_info_t info) static
Definition at line 92 of file get_check_data.c.
{
   if (!(info.type == INT2OID
         || info.type == INT4OID
         || info.type == INT8OID)) {
     ereport(ERROR,
         (errmsg_internal("Unexpected type in column '%s'.", info.name),
          errhint("Expected ANY-INTEGER")));
   }
 }
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
check_any_integerarray_type()
static void check_any_integerarray_type (Column_info_t info) static
Definition at line 115 of file get_check_data.c.
{
   if (!(info.type == INT2ARRAYOID
         || info.type == INT4ARRAYOID
         || info.type == 1016)) {
     elog(ERROR,
         "Unexpected Column '%s' type. Expected ANY-INTEGER-ARRAY",
         info.name);
   }
 }
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
check_any_numerical_type()
static void check_any_numerical_type (Column_info_t info) static
Definition at line 127 of file get_check_data.c.
{
   if (!(info.type == INT2OID
         || info.type == INT4OID
         || info.type == INT8OID
         || info.type == FLOAT4OID
         || info.type == FLOAT8OID
         || info.type == NUMERICOID)) {
     ereport(ERROR,
         (errmsg_internal("Unexpected type in column '%s'.", info.name),
          errhint("Found: %lu\nExpected ANY-NUMERICAL", info.type)));
   }
 }
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
check_char_type()
static void check_char_type (Column_info_t info) static
Definition at line 58 of file get_check_data.c.
{
   if (!(info.type == BPCHAROID)) {
     elog(ERROR, "Unexpected Column '%s' type. Expected CHAR", info.name);
   }
 }
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
check_integer_type()
static void check_integer_type (Column_info_t info) static
Definition at line 82 of file get_check_data.c.
{
   if (!(info.type == INT2OID || info.type == INT4OID)) {
     ereport(ERROR,
             (errmsg_internal("Unexpected type in column '%s'.", info.name),
              errhint("Expected SMALLINT or INTEGER")));
   }
 }
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
check_integerarray_type()
static void check_integerarray_type (Column_info_t info) static
Definition at line 104 of file get_check_data.c.
{
   if (!(info.type == INT2ARRAYOID
         || info.type == INT4ARRAYOID)) {
     elog(ERROR,
         "Unexpected Column '%s' type. Expected SMALLINT-ARRAY or INTEGER-ARRAY",
         info.name);
   }
 }
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
check_interval_type()
static void check_interval_type (Column_info_t info) static
Definition at line 44 of file get_check_data.c.
{
   if (!(info.type == 1186)) {
     elog(ERROR,
         "Unexpected Column '%s' type. Expected INTERVAL",
         info.name);
   }
 }
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
check_jsonb_type()
static void check_jsonb_type (Column_info_t info) static
Definition at line 74 of file get_check_data.c.
{
   if (!(info.type == JSONBOID)) {
     elog(ERROR, "Unexpected Column '%s' type. Expected JSONB %ld", info.name, info.type);
   }
 }
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
check_text_type()
static void check_text_type (Column_info_t info) static
Definition at line 66 of file get_check_data.c.
{
   if (!(info.type == TEXTOID)) {
     elog(ERROR, "Unexpected Column '%s' type. Expected TEXT", info.name);
   }
 }
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
check_timestamp_type()
static void check_timestamp_type (Column_info_t info) static
Definition at line 142 of file get_check_data.c.
{
   if (!(info.type == 1114)) {
     elog(ERROR,
         "Unexpected Column '%s' type. Expected TIMESTAMP",
         info.name);
   }
 }
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
column_found()
bool column_found (int colNumber)
Check whether the colNumber represent any specific column or NULL (SPI_ERROR_NOATTRIBUTE).
Definition at line 900 of file get_check_data.c.
{
     return !(colNumber == SPI_ERROR_NOATTRIBUTE);
 }
Referenced by check_pairs(), db_get_vehicles(), fetch_breaks(), fetch_column_info(), fetch_euclidean(), fetch_jobs(), fetch_raw(), fetch_shipments(), fetch_timestamps(), fetch_vehicles(), get_Amount(), get_Cost(), get_Distance(), get_Duration(), get_Id(), get_Idx(), get_Kind(), get_MatrixIndex(), get_PositiveAmount(), get_Priority(), get_StepType(), get_TInterval(), get_TInterval_plain(), get_TTimestamp(), get_TTimestamp_plain(), and spi_getCoordinate().
fetch_column_info()
static bool fetch_column_info (Column_info_t * info) static
Definition at line 152 of file get_check_data.c.
{
   /*
    * [SPI_fnumber](https://www.postgresql.org/docs/12/spi-spi-fnumber.html)
    */
   info->colNumber =  SPI_fnumber(SPI_tuptable->tupdesc, info->name);
   if (info->strict && !column_found(info->colNumber)) {
     elog(ERROR, "Column '%s' not Found", info->name);
   }
   if (column_found(info->colNumber)) {
     /*
      * [SPI_gettypeid](https://www.postgresql.org/docs/12/spi-spi-gettypeid.html)
      */
     (info->type) = SPI_gettypeid(SPI_tuptable->tupdesc, (info->colNumber));
     PGR_DBG("%s %ld", info->name, info->type);
     if (SPI_result == SPI_ERROR_NOATTRIBUTE) {
       elog(ERROR, "Type of column '%s' not Found", info->name);
     }
     return true;
   }
   return false;
 }
References Column_info_t::colNumber, column_found(), Column_info_t::name, PGR_DBG, Column_info_t::strict, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
get_Amount()
Amount get_Amount (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, Amount opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
get Amount from data
Returns
The value found
opt_value when the column does not exist
Definition at line 619 of file get_check_data.c.
{
   return (Amount) column_found(info.colNumber)?
     spi_getBigInt(tuple, tupdesc, info)
     : opt_value;
 }
References Column_info_t::colNumber, column_found(), and spi_getBigInt().
Referenced by get_PositiveAmount().
get_Cost()
TravelCost get_Cost (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, TravelCost opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
get TravelCost from data
Returns
The value found
opt_value when the column does not exist
exceptions when the value is negative
Precondition
for non-negative values only
Definition at line 704 of file get_check_data.c.
{
   if (column_found(info.colNumber)) {
     int32_t value = spi_getInt(tuple, tupdesc, info);
     if (value < 0) elog(ERROR, "Unexpected Negative value in column %s", info.name);
     return (TravelCost)value;
   }
   return opt_value;
 }
References Column_info_t::colNumber, column_found(), Column_info_t::name, and spi_getInt().
Referenced by fetch_matrix().
get_Distance()
Distance get_Distance (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, Distance opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
get Distance from data
Returns
The value found
opt_value when the column does not exist
exceptions when the value is negative
Precondition
for non-negative values only
Definition at line 771 of file get_check_data.c.
{
   if (column_found(info.colNumber)) {
     int32_t value = spi_getInt(tuple, tupdesc, info);
     if (value < 0) elog(ERROR, "Unexpected Negative value in column %s", info.name);
     return (Distance) value;
   }
   return opt_value;
 }
References Column_info_t::colNumber, column_found(), Column_info_t::name, and spi_getInt().
get_Duration()
Duration get_Duration (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, Duration opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
get Duration from data
Returns
The value found
opt_value when the column does not exist
exceptions when the value is negative
Precondition
for non-negative values only
Definition at line 681 of file get_check_data.c.
{
   if (column_found(info.colNumber)) {
     int32_t value = spi_getInt(tuple, tupdesc, info);
     if (value < 0) elog(ERROR, "Unexpected Negative value in column %s", info.name);
     return (Duration) value;
   }
   return opt_value;
 }
References Column_info_t::colNumber, column_found(), Column_info_t::name, and spi_getInt().
Referenced by fetch_breaks(), fetch_jobs(), fetch_matrix(), fetch_shipments(), fetch_time_windows(), and fetch_vehicles().
get_Id()
Id get_Id (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, Id opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
get Id from data
Returns
The value found
opt_value when the column does not exist
Definition at line 562 of file get_check_data.c.
{
   return column_found(info.colNumber)?
     (Id)spi_getBigInt(tuple, tupdesc, info)
     : opt_value;
 }
References Column_info_t::colNumber, column_found(), and spi_getBigInt().
Referenced by fetch_euclidean(), fetch_plain(), fetch_raw(), fetch_timestamps(), and get_Idx().
get_Idx()
Idx get_Idx (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, Idx opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
get Idx from data
Returns
The value found
opt_value when the column does not exist
exceptions when the value is not positive
Precondition
for positive values only
Definition at line 581 of file get_check_data.c.
{
   Id value = get_Id(tuple, tupdesc, info, 0);
   if (value <= 0) elog(ERROR, "Unexpected Negative value or Zero in column %s", info.name);
   return column_found(info.colNumber)? (Idx) value : opt_value;
 }
References Column_info_t::colNumber, column_found(), get_Id(), and Column_info_t::name.
Referenced by fetch_breaks(), fetch_jobs(), fetch_shipments(), fetch_time_windows(), and fetch_vehicles().
get_Kind()
char get_Kind (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, char opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
get Kind from data
Returns
The value found
opt_value when the column does not exist
Definition at line 725 of file get_check_data.c.
{
   if (column_found(info.colNumber)) {
     char value = spi_getChar(tuple, tupdesc, info, opt_value);
     return value;
   }
   return opt_value;
 }
References Column_info_t::colNumber, column_found(), and spi_getChar().
Referenced by fetch_time_windows().
get_MatrixIndex()
MatrixIndex get_MatrixIndex (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, MatrixIndex opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
get MatrixIndex from data
Returns
The value found
opt_value when the column does not exist
exceptions when the value is not positive
Precondition
for positive values only
Definition at line 658 of file get_check_data.c.
{
   if (column_found(info.colNumber)) {
     int64_t value = spi_getBigInt(tuple, tupdesc, info);
     if (value < 0) elog(ERROR, "Unexpected Negative value in column %s", info.name);
     return (MatrixIndex) value;
   }
   return opt_value;
 }
References Column_info_t::colNumber, column_found(), Column_info_t::name, and spi_getBigInt().
Referenced by fetch_jobs(), fetch_matrix(), fetch_shipments(), and fetch_vehicles().
get_PositiveAmount()
PAmount get_PositiveAmount (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, PAmount opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
get positive Amount from data
Returns
The value found
opt_value when the column does not exist
exceptions when the value is negative
Precondition
for non-negative values only
Definition at line 638 of file get_check_data.c.
{
   Amount value = get_Amount(tuple, tupdesc, info, 0);
   if (value < 0) elog(ERROR, "Unexpected Negative value in column %s", info.name);
   return column_found(info.colNumber)? (PAmount) value : opt_value;
 }
References Column_info_t::colNumber, column_found(), get_Amount(), and Column_info_t::name.
Referenced by fetch_euclidean(), fetch_raw(), and fetch_timestamps().
get_PositiveTInterval()
TInterval get_PositiveTInterval (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, TInterval opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
gets an interval value from postgres type INTERVAL > 0
Returns
The value found
opt_value when the column does not exist
exceptions when the value is negative
Precondition
for positive values only
Definition at line 511 of file get_check_data.c.
{
   TInterval value = get_TInterval(tuple, tupdesc, info, opt_value);
   if (value < 0) elog(ERROR, "Unexpected Negative value in column %s", info.name);
   return (TInterval) value;
 }
References get_TInterval(), and Column_info_t::name.
Referenced by fetch_breaks(), fetch_jobs(), fetch_matrix(), fetch_shipments(), and fetch_timestamps().
get_PositiveTInterval_plain()
TInterval get_PositiveTInterval_plain (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, TInterval opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
gets an interval value from ANY-INTEGER > 0
Returns
The value found
opt_value when the column does not exist
exceptions when the value is negative
Precondition
for positive values only
Definition at line 546 of file get_check_data.c.
{
   TInterval value = get_TInterval_plain(tuple, tupdesc, info, opt_value);
   if (value < 0) elog(ERROR, "Unexpected Negative value in column %s", info.name);
   return (TInterval) value;
 }
References get_TInterval_plain(), and Column_info_t::name.
Referenced by fetch_euclidean(), fetch_plain(), and fetch_raw().
get_PositiveTTimestamp()
TTimestamp get_PositiveTTimestamp (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, TTimestamp opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
gets a timestamp value from postgres type TIMESTAMP >= 1970-01-01 00:00:00
Returns
The value found
opt_value when the column does not exist
exceptions when the value is negative
Precondition
for positive values only
Definition at line 476 of file get_check_data.c.
{
   TTimestamp value = get_TTimestamp(tuple, tupdesc, info, opt_value);
   if (value < 0) elog(ERROR, "Unexpected Negative value in column %s", info.name);
   return value;
 }
References get_TTimestamp(), and Column_info_t::name.
Referenced by fetch_time_windows(), and fetch_vehicles().
get_PositiveTTimestamp_plain()
TTimestamp get_PositiveTTimestamp_plain (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, TTimestamp opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
gets a timestamp value from ANY-INTEGER > 0
Returns
The value found
opt_value when the column does not exist
exceptions when the value is negative
Precondition
for positive values only
Definition at line 441 of file get_check_data.c.
{
   TTimestamp value = get_TTimestamp_plain(tuple, tupdesc, info, opt_value);
   if (value < 0) elog(ERROR, "Unexpected Negative value in column %s", info.name);
   return value;
 }
References get_TTimestamp_plain(), and Column_info_t::name.
get_Priority()
Priority get_Priority (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, Priority opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
get Priority from data
Returns
The value found
opt_value when the column does not exist
exceptions when the value is negative
Precondition
for non-negative values only
Definition at line 747 of file get_check_data.c.
{
   if (column_found(info.colNumber)) {
     int32_t value = spi_getInt(tuple, tupdesc, info);
     if (value < 0) elog(ERROR, "Unexpected Negative value in column %s", info.name);
     if (value > 100) elog(ERROR, "Priority exceeds the max priority 100");
     return (Priority) value;
   }
   return opt_value;
 }
References Column_info_t::colNumber, column_found(), Column_info_t::name, and spi_getInt().
Referenced by fetch_jobs(), and fetch_shipments().
get_StepType()
StepType get_StepType (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, StepType opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
get StepType from data
Returns
The value found
opt_value when the column does not exist
Definition at line 596 of file get_check_data.c.
{
   StepType step_type = column_found(info.colNumber)
                            ? spi_getInt(tuple, tupdesc, info)
                            : opt_value;
   StepType min_value = 1;
   StepType max_value = 6;
   if (step_type < min_value || step_type > max_value) {
     elog(ERROR, "Step value should lie between %d and %d", min_value, max_value);
   }
   return step_type;
 }
References Column_info_t::colNumber, column_found(), and spi_getInt().
get_TInterval()
TInterval get_TInterval (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, TInterval opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
gets an interval value from postgres type INTERVAL
Returns
The value found
opt_value when the column does not exist
Definition at line 492 of file get_check_data.c.
{
   return column_found(info.colNumber)?
     (TInterval)spi_getInterval(tuple, tupdesc, info)
     : opt_value;
 }
References Column_info_t::colNumber, column_found(), and spi_getInterval().
Referenced by fetch_timestamps(), and get_PositiveTInterval().
get_TInterval_plain()
TInterval get_TInterval_plain (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, TInterval opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
gets an interval value from ANY-INTEGER
Returns
The value found
opt_value when the column does not exist
Definition at line 527 of file get_check_data.c.
{
   return column_found(info.colNumber)?
     (TInterval)spi_getBigInt(tuple, tupdesc, info)
     : opt_value;
 }
References Column_info_t::colNumber, column_found(), and spi_getBigInt().
Referenced by fetch_euclidean(), fetch_raw(), and get_PositiveTInterval_plain().
get_TTimestamp()
TTimestamp get_TTimestamp (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, TTimestamp opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
gets a timestamp value from postgres type TIMESTAMP
Returns
The value found
opt_value when the column does not exist
Definition at line 457 of file get_check_data.c.
{
   return column_found(info.colNumber)?
     spi_getTimeStamp(tuple, tupdesc, info)
     : opt_value;
 }
References Column_info_t::colNumber, column_found(), and spi_getTimeStamp().
Referenced by fetch_timestamps(), and get_PositiveTTimestamp().
get_TTimestamp_plain()
TTimestamp get_TTimestamp_plain (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, TTimestamp opt_value)
@params [in] tuple @params [in] tupdesc @params [in] info about the column been fetched @params [in] opt_value default value when the column does not exist
gets a timestamp value from ANY-INTEGER
Returns
The value found
opt_value when the column does not exist
Definition at line 422 of file get_check_data.c.
{
   return column_found(info.colNumber)?
     (TTimestamp)spi_getBigInt(tuple, tupdesc, info)
     : opt_value;
 }
References Column_info_t::colNumber, column_found(), and spi_getBigInt().
Referenced by fetch_euclidean(), fetch_raw(), and get_PositiveTTimestamp_plain().
pgr_fetch_column_info()
void pgr_fetch_column_info (Column_info_t info[], int info_size)
Function tells expected type of each column and then check the correspondence type of each column.
Definition at line 905 of file get_check_data.c.
                    {
   for (int i = 0; i < info_size; ++i) {
     if (fetch_column_info(&info[i])) {
       switch (info[i].eType) {
         case INTEGER:
           check_integer_type(info[i]);
           break;
         case ANY_INTEGER:
           check_any_integer_type(info[i]);
           break;
         case ANY_NUMERICAL:
           check_any_numerical_type(info[i]);
           break;
         case TEXT:
           check_text_type(info[i]);
           break;
         case JSONB:
           check_jsonb_type(info[i]);
           break;
         case CHAR1:
           check_char_type(info[i]);
           break;
         case INTEGER_ARRAY:
           check_integerarray_type(info[i]);
           break;
         case ANY_INTEGER_ARRAY:
           check_any_integerarray_type(info[i]);
           break;
         case TIMESTAMP:
           check_timestamp_type(info[i]);
           break;
         case INTERVAL:
           check_interval_type(info[i]);
           break;
         default:
           elog(ERROR, "Unknown type of column %s", info[i].name);
       }
     }
   }
 }
References ANY_INTEGER, ANY_INTEGER_ARRAY, ANY_NUMERICAL, CHAR1, check_any_integer_type(), check_any_integerarray_type(), check_any_numerical_type(), check_char_type(), check_integer_type(), check_integerarray_type(), check_interval_type(), check_jsonb_type(), check_text_type(), check_timestamp_type(), fetch_column_info(), INTEGER, INTEGER_ARRAY, INTERVAL, JSONB, TEXT, and TIMESTAMP.
Referenced by db_get_breaks(), db_get_jobs(), db_get_matrix(), db_get_shipments(), db_get_time_windows(), db_get_vehicles(), get_matrixRows_general(), get_timeMultipliersGeneral(), and pgr_get_pd_orders_general().
spi_getBigInt()
static int64_t spi_getBigInt (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info) static
Definition at line 203 of file get_check_data.c.
{
   Datum binval;
   bool isnull;
   int64_t value = 0;
   binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isnull);
   if (isnull) elog(ERROR, "Unexpected Null value in column %s", info.name);
   switch (info.type) {
     case INT2OID:
       value = (int64_t) DatumGetInt16(binval);
       break;
     case INT4OID:
       value = (int64_t) DatumGetInt32(binval);
       break;
     case INT8OID:
       value = DatumGetInt64(binval);
       break;
     default:
     ereport(ERROR,
         (errmsg_internal("Unexpected type in column '%s'.", info.name),
          errhint("Found: %lu\nExpected ANY-INTEGER", info.type)));
   }
   return value;
 }
References Column_info_t::colNumber, Column_info_t::name, and Column_info_t::type.
Referenced by get_Amount(), get_Id(), get_MatrixIndex(), get_TInterval_plain(), and get_TTimestamp_plain().
spi_getBigIntArr()
int64_t* spi_getBigIntArr (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, size_t * the_size)
Function returns the values of specified columns in array.
Definition at line 336 of file get_check_data.c.
                       {
   bool is_null = false;
   Datum raw_array = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &is_null);
   /*
    * [DatumGetArrayTypeP](https://doxygen.postgresql.org/array_8h.html#aa1b8e77c103863862e06a7b7c07ec532)
    * [pgr_get_bigIntArray](http://docs.pgrouting.org/doxy/2.2/arrays__input_8c_source.html)
    */
   ArrayType *pg_array = DatumGetArrayTypeP(raw_array);
   return pgr_get_bigIntArray((size_t*)the_size, pg_array);
 }
References Column_info_t::colNumber, and pgr_get_bigIntArray().
spi_getBigIntArr_allowEmpty()
int64_t* spi_getBigIntArr_allowEmpty (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, size_t * the_size)
Function returns the values of specified columns in array.
Definition at line 354 of file get_check_data.c.
                       {
   bool is_null = false;
   Datum raw_array = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &is_null);
   /*
    * [DatumGetArrayTypeP](https://doxygen.postgresql.org/array_8h.html#aa1b8e77c103863862e06a7b7c07ec532)
    * [pgr_get_bigIntArray](http://docs.pgrouting.org/doxy/2.2/arrays__input_8c_source.html)
    */
   if (!raw_array) {
     *the_size = 0;
     return  NULL;
   }
   ArrayType *pg_array = DatumGetArrayTypeP(raw_array);
   return pgr_get_bigIntArray_allowEmpty(the_size, pg_array);
 }
References Column_info_t::colNumber, and pgr_get_bigIntArray_allowEmpty().
Referenced by fetch_euclidean(), fetch_raw(), fetch_timestamps(), and spi_getPositiveBigIntArr_allowEmpty().
spi_getChar()
char spi_getChar (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, char default_value)
get value of specified column in char type.
Definition at line 298 of file get_check_data.c.
{
   Datum binval;
   bool isNull;
   char value = default_value;
   binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isNull);
   if (!(info.type == BPCHAROID)) {
     elog(ERROR, "Unexpected Column type of %s. Expected CHAR", info.name);
   }
   if (!isNull) {
     value =  ((char*)binval)[1];
   } else {
     if (info.strict) {
       elog(ERROR, "Unexpected Null value in column %s", info.name);
     }
     value = default_value;
   }
   return value;
 }
References Column_info_t::colNumber, Column_info_t::name, Column_info_t::strict, and Column_info_t::type.
Referenced by get_Kind().
spi_getCoordinate()
Coordinate spi_getCoordinate (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, Coordinate opt_value)
get a coordinate value
Definition at line 819 of file get_check_data.c.
{
   return column_found(info.colNumber)?
     (Coordinate) spi_getFloat8(tuple, tupdesc, info)
     : opt_value;
 }
References Column_info_t::colNumber, column_found(), and spi_getFloat8().
Referenced by fetch_euclidean().
spi_getFloat8()
double spi_getFloat8 (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info)
gets value of specified column in double type.
Definition at line 782 of file get_check_data.c.
{
   Datum binval;
   bool isnull = false;
   double value = 0.0;
   binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isnull);
   if (isnull)
     elog(ERROR, "Unexpected Null value in column %s", info.name);
   switch (info.type) {
     case INT2OID:
       value = (double) DatumGetInt16(binval);
       break;
     case INT4OID:
       value = (double) DatumGetInt32(binval);
       break;
     case INT8OID:
       value = (double) DatumGetInt64(binval);
       break;
     case FLOAT4OID:
       value = (double) DatumGetFloat4(binval);
       break;
     case FLOAT8OID:
       value = DatumGetFloat8(binval);
       break;
     case NUMERICOID:
       /* Note: out-of-range values will be clamped to +-HUGE_VAL */
       value = (double) DatumGetFloat8(DirectFunctionCall1(numeric_float8_no_overflow, binval));
       break;
     default:
     ereport(ERROR,
         (errmsg_internal("Unexpected type in column '%s'.", info.name),
          errhint("Found: %lu\nExpected ANY-NUMERICAL", info.type)));
   }
   return value;
 }
References Column_info_t::colNumber, Column_info_t::name, and Column_info_t::type.
Referenced by fetch_euclidean(), fetch_raw(), fetch_timestamps(), fetch_vehicles(), and spi_getCoordinate().
spi_getInt()
static int32_t spi_getInt (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info) static
Definition at line 178 of file get_check_data.c.
{
   Datum binval;
   bool isnull;
   int32_t value = 0;
   binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isnull);
   if (isnull) elog(ERROR, "Unexpected Null value in column %s", info.name);
   switch (info.type) {
     case INT2OID:
       value = (int32_t) DatumGetInt16(binval);
       break;
     case INT4OID:
       value = (int32_t) DatumGetInt32(binval);
       break;
     default:
     ereport(ERROR,
         (errmsg_internal("Unexpected type in column '%s'.", info.name),
          errhint("Found: %lu\nExpected INTEGER", info.type)));
   }
   return value;
 }
References Column_info_t::colNumber, Column_info_t::name, and Column_info_t::type.
Referenced by get_Cost(), get_Distance(), get_Duration(), get_Priority(), get_StepType(), and spi_getMaxTasks().
spi_getInterval()
static TInterval spi_getInterval (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info) static
Definition at line 253 of file get_check_data.c.
{
   Datum binval;
   bool isnull;
   Interval*   interval;
   binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isnull);
   if (isnull) elog(ERROR, "Unexpected Null value in column %s", info.name);
   switch (info.type) {
     case INTERVALOID:
       interval = DatumGetIntervalP(binval);
       break;
     default:
       elog(ERROR,
           "[spi_getInterval] Unexpected type in column %s. found %ld expected %d",
           info.name, info.type, INTERVALOID);
   }
   PGR_DBG("time %ld secs %ld", interval->time,
       interval->time / 1000000
       + interval->day * SECS_PER_DAY
       + (int64_t)(interval->month * ((DAYS_PER_YEAR / (double) MONTHS_PER_YEAR) * SECS_PER_DAY)));
   return interval->time / 1000000
     + interval->day * SECS_PER_DAY
     + (int64_t)(interval->month * ((DAYS_PER_YEAR / (double) MONTHS_PER_YEAR) * SECS_PER_DAY));
 }
References Column_info_t::colNumber, Column_info_t::name, PGR_DBG, and Column_info_t::type.
Referenced by get_TInterval().
spi_getMaxTasks()
int32_t spi_getMaxTasks (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info)
gets the vehicle max tasks value
Definition at line 320 of file get_check_data.c.
{
   int32_t value = spi_getInt(tuple, tupdesc, info);
   if (value < 0) {
     ereport(
         ERROR,
         (errmsg("Invalid max_tasks value %d", value),
          errhint(
              "Maximum number of tasks must be greater than or equal to 0")));
   }
   return value;
 }
References spi_getInt().
Referenced by fetch_vehicles().
spi_getPositiveBigIntArr_allowEmpty()
int64_t* spi_getPositiveBigIntArr_allowEmpty (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, size_t * the_size)
Function returns the values of specified columns in array.
Definition at line 377 of file get_check_data.c.
                       {
   int64_t *array = spi_getBigIntArr_allowEmpty(tuple, tupdesc, info, the_size);
   for (size_t i = 0; i < *the_size; i++) {
     if (array[i] < 0) {
       elog(ERROR, "Unexpected Negative value %ld in array", array[i]);
     }
   }
   return array;
 }
References spi_getBigIntArr_allowEmpty().
Referenced by fetch_jobs(), fetch_shipments(), and fetch_vehicles().
spi_getPositiveIntArr_allowEmpty()
uint32_t* spi_getPositiveIntArr_allowEmpty (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, size_t * the_size)
Function returns the values of specified columns in array.
Definition at line 393 of file get_check_data.c.
                       {
   bool is_null = false;
   Datum raw_array = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &is_null);
   if (!raw_array) {
     *the_size = 0;
     return  NULL;
   }
   ArrayType *pg_array = DatumGetArrayTypeP(raw_array);
   return pgr_get_positiveIntArray_allowEmpty(the_size, pg_array);
 }
References Column_info_t::colNumber, and pgr_get_positiveIntArray_allowEmpty().
Referenced by fetch_jobs(), fetch_shipments(), and fetch_vehicles().
spi_getText()
char* spi_getText (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info)
under development
gets string representation of the value of specified column.
Definition at line 832 of file get_check_data.c.
{
   char *val = DatumGetCString(SPI_getvalue(*tuple, *tupdesc, info.colNumber));
   return val;
 }
References Column_info_t::colNumber.
Referenced by fetch_breaks(), fetch_jobs(), fetch_shipments(), and fetch_vehicles().
spi_getTimeStamp()
static TTimestamp spi_getTimeStamp (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info) static
Definition at line 231 of file get_check_data.c.
{
   Datum binval;
   bool isnull;
   TTimestamp value = 0;
   binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isnull);
   if (isnull) elog(ERROR, "Unexpected Null value in column %s", info.name);
   switch (info.type) {
     case 1114:
       value = timestamp_without_timezone((TTimestamp) Int64GetDatum(binval));
       break;
     default:
       elog(ERROR,
           "[SPI_getTimeStamp] Unexpected type in column %s. found %ld expected 1114",
           info.name, info.type);
   }
   return value;
 }
References Column_info_t::colNumber, Column_info_t::name, timestamp_without_timezone(), and Column_info_t::type.
Referenced by get_TTimestamp().
timestamp_without_timezone()
TTimestamp timestamp_without_timezone (TTimestamp timestamp)
Steps: 1) Similar to: https://doxygen.postgresql.org/backend_2utils_2adt_2timestamp_8c.html#a52973f03ed8296b632d4028121f7e077 2) Using time.h to convert.
Converts timestamp to timestamp without timezone.
from time.h struct tm timezone
Definition at line 847 of file get_check_data.c.
{
   /*
    * step 1
    */
   Timestamp date;
   Timestamp time = timestamp;
   TMODULO(time, date, USECS_PER_DAY);
   if (time < INT64CONST(0)) {
     time += USECS_PER_DAY;
     date -= 1;
   }
   date += POSTGRES_EPOCH_JDATE;
   /* Julian day routine does not work for negative Julian days */
   if (date < 0 || date > (Timestamp) INT_MAX) {
     ereport(ERROR,
         (errcode(ERRCODE_INTERNAL_ERROR),
          errmsg("Julian day routine does not work for negative Julian days")));
   }
   /*
    * using structure from time.h to store values
    */
   struct tm info;
   fsec_t fsec;
   /*
    * calling postgres functions
    */
   j2date((int) date, &info.tm_year, &info.tm_mon, &info.tm_mday);
   dt2time(time, &info.tm_hour, &info.tm_min, &info.tm_sec, &fsec);
   /*
    * adjust values before calling mktime
    */
   info.tm_isdst = -1;
   info.tm_year = info.tm_year - 1900;
   info.tm_mon = info.tm_mon - 1;
   /*
    * mktime & timezone are defined in time.h
    */
   return mktime(&info) - timezone;
 }
Referenced by process(), and spi_getTimeStamp().