vrpRouting: matrixRows_input.c File Reference
matrixRows_input.c File Reference
#include "c_common/matrixRows_input.h"
#include "c_types/column_info_t.h"
#include "c_types/matrix_cell_t.h"
#include "c_common/get_check_data.h"
Functions
static void fetch_plain (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[3], Matrix_cell_t *row)
static void fetch_timestamps (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[3], Matrix_cell_t *row)
void get_matrixRows (char *sql, Matrix_cell_t **rows, size_t *total_rows)
Get the travel time matrix.
static void get_matrixRows_general (char *sql, Column_info_t *info, const int kind, Matrix_cell_t **rows, size_t *total_rows)
bigint start_vid, bigint end_vid, float agg_cost,
void get_matrixRows_plain (char *sql, Matrix_cell_t **rows, size_t *total_rows)
Get the travel time matrix with numerical types.
void get_matrixRows_vroom_plain (char *sql, Matrix_cell_t **rows, size_t *total_rows)
Get the travel time matrix of vroom with integer types.
Function Documentation
fetch_plain()
static void fetch_plain (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[3], Matrix_cell_t * row) static
Definition at line 80 of file matrixRows_input.c.
{
     row->from_vid = get_Id(tuple, tupdesc,  info[0], -1);
     row->to_vid = get_Id(tuple, tupdesc,  info[1], -1);
     row->cost = get_PositiveTInterval_plain(tuple, tupdesc, info[2], 0);
 }
References Matrix_cell_t::cost, Matrix_cell_t::from_vid, get_Id(), get_PositiveTInterval_plain(), and Matrix_cell_t::to_vid.
Referenced by get_matrixRows_general().
fetch_timestamps()
static void fetch_timestamps (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[3], Matrix_cell_t * row) static
Definition at line 91 of file matrixRows_input.c.
{
     row->from_vid = get_Id(tuple, tupdesc,  info[0], -1);
     row->to_vid = get_Id(tuple, tupdesc,  info[1], -1);
     row->cost = get_PositiveTInterval(tuple, tupdesc, info[2], 0);
 }
References Matrix_cell_t::cost, Matrix_cell_t::from_vid, get_Id(), get_PositiveTInterval(), and Matrix_cell_t::to_vid.
Referenced by get_matrixRows_general().
get_matrixRows()
void get_matrixRows (char * sql, Matrix_cell_t ** rows, size_t * total_rows)
Get the travel time matrix.
Parameters
[in] sql SQL query that has the following columns: start_vid, end_vid, agg_cost
[out] rows C Container that holds all the matrix rows
[out] total_rows Total rows recieved
Definition at line 194 of file matrixRows_input.c.
{
   Column_info_t info[3];
   int i;
   for (i = 0; i < 3; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "start_vid";
   info[1].name = "end_vid";
   info[2].name = "travel_time";
   info[2].eType = INTERVAL;
   get_matrixRows_general(sql, info, 0, rows, total_rows);
 }
References ANY_INTEGER, Column_info_t::colNumber, Column_info_t::eType, get_matrixRows_general(), INTERVAL, Column_info_t::name, Column_info_t::strict, and Column_info_t::type.
Referenced by process().
get_matrixRows_general()
static void get_matrixRows_general (char * sql, Column_info_t * info, const int kind, Matrix_cell_t ** rows, size_t * total_rows) static
bigint start_vid, bigint end_vid, float agg_cost,
Definition at line 108 of file matrixRows_input.c.
{
 #ifdef PROFILE
   clock_t start_t = clock();
   PGR_DBG("%s", sql);
 #endif
   const int tuple_limit = 1000000;
   size_t total_tuples = 0;
   const int column_count = 3;
   void *SPIplan;
   SPIplan = pgr_SPI_prepare(sql);
   Portal SPIportal;
   SPIportal = pgr_SPI_cursor_open(SPIplan);
   bool moredata = true;
   (*total_rows) = total_tuples;
   while (moredata == true) {
     SPI_cursor_fetch(SPIportal, true, tuple_limit);
     if (total_tuples == 0)
       pgr_fetch_column_info(info, column_count);
     size_t ntuples = SPI_processed;
     total_tuples += ntuples;
     if (ntuples > 0) {
       if ((*rows) == NULL)
         (*rows) = (Matrix_cell_t *)palloc0(
             total_tuples * sizeof(Matrix_cell_t));
       else
         (*rows) = (Matrix_cell_t *)repalloc(
             (*rows), total_tuples * sizeof(Matrix_cell_t));
       if ((*rows) == NULL) {
         elog(ERROR, "Out of memory");
       }
       SPITupleTable *tuptable = SPI_tuptable;
       TupleDesc tupdesc = SPI_tuptable->tupdesc;
       size_t t;
       for (t = 0; t < ntuples; t++) {
         HeapTuple tuple = tuptable->vals[t];
         switch (kind) {
           case 0 : fetch_timestamps(&tuple, &tupdesc, info,
                        &(*rows)[total_tuples - ntuples + t]);
                    break;
           case 1 : fetch_plain(&tuple, &tupdesc, info,
                        &(*rows)[total_tuples - ntuples + t]);
                    break;
         }
       }
       SPI_freetuptable(tuptable);
     } else {
       moredata = false;
     }
   }
   SPI_cursor_close(SPIportal);
   if (total_tuples == 0) {
     (*total_rows) = 0;
     return;
   }
   (*total_rows) = total_tuples;
 #ifdef PROFILE
   time_msg(" reading time matrix", start_t, clock());
 #endif
 }
References fetch_plain(), fetch_timestamps(), PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), and time_msg().
Referenced by get_matrixRows(), get_matrixRows_plain(), and get_matrixRows_vroom_plain().
get_matrixRows_plain()
void get_matrixRows_plain (char * sql, Matrix_cell_t ** rows, size_t * total_rows)
Get the travel time matrix with numerical types.
Parameters
[in] sql SQL query that has the following columns: start_vid, end_vid, agg_cost
[out] rows C Container that holds all the matrix rows
[out] total_rows Total rows recieved
Definition at line 221 of file matrixRows_input.c.
{
   Column_info_t info[3];
   int i;
   for (i = 0; i < 3; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "start_vid";
   info[1].name = "end_vid";
   info[2].name = "agg_cost";
   info[2].eType = ANY_NUMERICAL;
   get_matrixRows_general(sql, info, 1, rows, total_rows);
 }
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, get_matrixRows_general(), Column_info_t::name, Column_info_t::strict, and Column_info_t::type.
Referenced by process().
get_matrixRows_vroom_plain()
void get_matrixRows_vroom_plain (char * sql, Matrix_cell_t ** rows, size_t * total_rows)
Get the travel time matrix of vroom with integer types.
Parameters
[in] sql SQL query that has the following columns: start_vid, end_vid, agg_cost
[out] rows C Container that holds all the matrix rows
[out] total_rows Total rows recieved
Definition at line 247 of file matrixRows_input.c.
{
   Column_info_t info[3];
   int i;
   for (i = 0; i < 3; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "start_vid";
   info[1].name = "end_vid";
   info[2].name = "agg_cost";
   info[2].eType = INTEGER;
   get_matrixRows_general(sql, info, 1, rows, total_rows);
 }
References ANY_INTEGER, Column_info_t::colNumber, Column_info_t::eType, get_matrixRows_general(), INTEGER, Column_info_t::name, Column_info_t::strict, and Column_info_t::type.
Referenced by process().