vrpRouting: matrixRows_input.h File Reference
matrixRows_input.h File Reference
#include <stddef.h>
Typedefs
typedef struct Matrix_cell_t Matrix_cell_t
Functions
void get_matrixRows (char *sql, Matrix_cell_t **rows, size_t *total_rows)
Get the travel time matrix.
void get_matrixRows_plain (char *sql, Matrix_cell_t **rows, size_t *total_rows)
Get the travel time matrix with numerical types.
Typedef Documentation
Matrix_cell_t
typedef struct Matrix_cell_t Matrix_cell_t
Definition at line 31 of file matrixRows_input.h.
Function Documentation
get_matrixRows()
void get_matrixRows (char * sql, Matrix_cell_t ** rows, size_t * total_rows)
Get the travel time matrix.
Parameters
[in] sql SQL query that has the following columns: start_vid, end_vid, agg_cost
[out] rows C Container that holds all the matrix rows
[out] total_rows Total rows recieved
Definition at line 176 of file matrixRows_input.c.
{
   Column_info_t info[3];
   int i;
   for (i = 0; i < 3; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "start_vid";
   info[1].name = "end_vid";
   info[2].name = "travel_time";
   info[2].eType = INTERVAL;
   get_matrixRows_general(sql, info, 0, rows, total_rows);
 }
References ANY_INTEGER, Column_info_t::colNumber, Column_info_t::eType, get_matrixRows_general(), INTERVAL, Column_info_t::name, Column_info_t::strict, and Column_info_t::type.
Referenced by process().
get_matrixRows_plain()
void get_matrixRows_plain (char * sql, Matrix_cell_t ** rows, size_t * total_rows)
Get the travel time matrix with numerical types.
Parameters
[in] sql SQL query that has the following columns: start_vid, end_vid, agg_cost
[out] rows C Container that holds all the matrix rows
[out] total_rows Total rows recieved
Definition at line 203 of file matrixRows_input.c.
{
   Column_info_t info[3];
   int i;
   for (i = 0; i < 3; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "start_vid";
   info[1].name = "end_vid";
   info[2].name = "agg_cost";
   info[2].eType = ANY_NUMERICAL;
   get_matrixRows_general(sql, info, 1, rows, total_rows);
 }
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, get_matrixRows_general(), Column_info_t::name, Column_info_t::strict, and Column_info_t::type.
Referenced by process().