vrpRouting: vrprouting::problem::anonymous_namespace{matrix.cpp} Namespace Reference
vrprouting::problem::anonymous_namespace{matrix.cpp} Namespace Reference
Functions
Multiplier get_tdm (const std::vector< std::tuple< TTimestamp, Multiplier >> &tdm, TTimestamp time)
Multiplier next_tdm (const std::vector< std::tuple< TTimestamp, Multiplier >> &tdm, TTimestamp time)
std::vector< std::tuple< TTimestamp, Multiplier > > set_tdm (Time_multipliers_t *p_multipliers, size_t size_multipliers)
TTimestamp time_change (const std::vector< std::tuple< TTimestamp, Multiplier >> &tdm, TTimestamp time)
Function Documentation
get_tdm()
Multiplier vrprouting::problem::anonymous_namespace{matrix.cpp}::get_tdm (const std::vector< std::tuple< TTimestamp, Multiplier >> & tdm, TTimestamp time)
Parameters
[in] tdm time dependant multiplier container
[in] time the time from where the multiplier is calculated
Returns
the multiplier corresponding to the time
Definition at line 78 of file matrix.cpp.
{
     pgassert(time >= 0);
     Multiplier coeff(1);
     for (const auto &e : tdm) {
         if (time < std::get<0>(e)) break;
         coeff = std::get<1>(e);
     }
     return coeff;
 }
References pgassert.
Referenced by vrprouting::problem::Matrix::travel_time().
next_tdm()
Multiplier vrprouting::problem::anonymous_namespace{matrix.cpp}::next_tdm (const std::vector< std::tuple< TTimestamp, Multiplier >> & tdm, TTimestamp time)
Parameters
[in] tdm time dependant multiplier container
[in] time the time from where the multiplier is calculated
Returns
the next multiplier corresponding to the time
Definition at line 94 of file matrix.cpp.
{
     Multiplier coeff(1);
     for (const auto &e : tdm) {
         coeff = std::get<1>(e);
         if (std::get<0>(e) >= time) break;
     }
     return coeff;
 }
Referenced by vrprouting::problem::Matrix::travel_time().
set_tdm()
std::vector<std::tuple<TTimestamp, Multiplier> > vrprouting::problem::anonymous_namespace{matrix.cpp}::set_tdm (Time_multipliers_t * p_multipliers, size_t size_multipliers)
Parameters
[in] p_multipliers time dependant multiplier data
[in] size_multipliers number of rows in the data
Returns
time dependant multiplier container
Definition at line 56 of file matrix.cpp.
{
     pgassert(size_multipliers > 1);
     std::vector<std::tuple<TTimestamp, Multiplier>> tdm;
     /*
      * Sort the multipliers info
      */
     std::sort(p_multipliers, p_multipliers + size_multipliers,
             [] (const Time_multipliers_t &lhs, const Time_multipliers_t &rhs) {
                 return lhs.start_time < rhs.start_time;
             });
     for (size_t i = 0; i < size_multipliers; ++i) {
         tdm.emplace_back(p_multipliers[i].start_time, p_multipliers[i].multiplier);
     }
     return tdm;
 }
References pgassert, and Time_multipliers_t::start_time.
time_change()
TTimestamp vrprouting::problem::anonymous_namespace{matrix.cpp}::time_change (const std::vector< std::tuple< TTimestamp, Multiplier >> & tdm, TTimestamp time)
Parameters
[in] tdm time dependant multiplier container
[in] time the time from where the multiplier is calculated
Returns
the time when multiplier change
Example with 3 time multiplier, no more multiplier after 11
0 9 11 |------------—|------------—|
time is 9:30 then the time change is the next one after that so 11 t_change = 0 0 < 9:30 true continue
t_change = 9 9 < 9:30 true
t_change = 11 11 < 9:30 false cycle breaks
return t_change = 11
time is 11:30
t_change = 0 0 < 11:30 true continue
t_change = 9 9 < 11:30 true
t_change = 11 11 < 11:30 true cycle ends naturally
return t_change = 11
post condition:
From first example t_change > time
from second example t_change is the last one on the list
Definition at line 154 of file matrix.cpp.
{
     TTimestamp t_change(0);
     for (const auto &e : tdm) {
         t_change = std::get<0>(e);
         if (time <= t_change) break;
     }
     pgassert((time <= t_change)
              || (t_change == std::get<0>(tdm[tdm.size() - 1 ])));
     return t_change;
 }
References pgassert.
Referenced by vrprouting::problem::Matrix::travel_time().