vrpRouting: vrprouting::optimizers::tabu Namespace Reference
vrprouting::optimizers::tabu Namespace Reference
Classes
class Move
The Move class defines moves that are evaluated and set as tabu.
class Optimize
Class that optimizes a solution.
class TabuList
The TabuList class defines the tabu list to be used in optimization.
Functions
std::ostream & operator<< (std::ostream &log, const Move &m)
std::ostream & operator<< (std::ostream &log, const TabuList &list)
bool operator== (const Move &a, const Move &b)
Function Documentation
operator<<() [1/2]
std::ostream& vrprouting::optimizers::tabu::operator<< (std::ostream & log, const Move & m)
Parameters
[in,out] log - where to write
[in] m - move to write
Returns
log with move information
Definition at line 66 of file move.cpp.
{
     log << m.m_oid1 << ":" << m.m_oid2 << ":"
       << m.m_vid1 << ":" << m.m_vid2 << ":"
       << m.m_is_swap;
     return log;
   }
References vrprouting::optimizers::tabu::Move::m_is_swap, vrprouting::optimizers::tabu::Move::m_oid1, vrprouting::optimizers::tabu::Move::m_oid2, vrprouting::optimizers::tabu::Move::m_vid1, and vrprouting::optimizers::tabu::Move::m_vid2.
operator<<() [2/2]
std::ostream& vrprouting::optimizers::tabu::operator<< (std::ostream & log, const TabuList & list)
Parameters
[in,out] log where the print takes place
[in] list The tabu list to be printed
Definition at line 140 of file tabu_list.cpp.
{
     log << "\nTabuList length: " << list.size()
         << "\n *><* *** tabu list start *** ";
     for (const auto &m : list) log << m << ' ';
     log << " *** tabu list end ***\n";
     return log;
 }
References vrprouting::optimizers::tabu::TabuList::size().
operator==()
bool vrprouting::optimizers::tabu::operator== (const Move & a, const Move & b)
Parameters
[in] a - left hand side move
[in] b - right hand side move
Returns
true when the left hand side move move is the same as the right hand side move
Definition at line 80 of file move.cpp.
{
     /*
      * possible cases are captured in TabuList::has_move and TabuList::has_swap:
      */
     return (
         a.oid1() == b.oid1()
         && a.oid2() == b.oid2()
         && a.vid1() == b.vid1()
         && a.vid2() == b.vid2()
 #if 0
         && a.to_objective() == b.to_objective()
         && a.from_objective() == b.from_objective()
 #endif
         && a.is_swap() == b.is_swap());
   }
References vrprouting::optimizers::tabu::Move::from_objective(), vrprouting::optimizers::tabu::Move::is_swap(), vrprouting::optimizers::tabu::Move::oid1(), vrprouting::optimizers::tabu::Move::oid2(), vrprouting::optimizers::tabu::Move::to_objective(), vrprouting::optimizers::tabu::Move::vid1(), and vrprouting::optimizers::tabu::Move::vid2().