vrpRouting: vrprouting::problem Namespace Reference
vrprouting::problem Namespace Reference
Namespaces
anonymous_namespace{matrix.cpp}
Classes
class Fleet
class Matrix
class Order
class Orders
class PickDeliver
the pick deliver problem
class Solution
class Tw_node
Time window attributes of a node.
class Vehicle
Vehicle with time windows.
class Vehicle_node
Extend Tw_node to evaluate the vehicle at node level.
class Vehicle_pickDeliver
Enumerations
enum NodeType {
kStart = 0, kPickup, kDelivery, kDump,
kLoad, kEnd
}
Functions
bool operator< (const Vehicle &lhs, const Vehicle &rhs)
std::ostream & operator<< (std::ostream &log, const Order &order)
Prints:
std::ostream & operator<< (std::ostream &log, const Tw_node &n)
std::ostream & operator<< (std::ostream &log, const Vehicle_node &v)
Enumeration Type Documentation
NodeType
enum vrprouting::problem::NodeType
Enumerator
kStart
starting site
kPickup
pickup site
kDelivery
delivery site
kDump
dump site, empties truck
kLoad
load site, fills the truck
kEnd
ending site
Definition at line 35 of file node_types.h.
                 {
     kStart = 0,
     kPickup,
     kDelivery,
     kDump,
     kLoad,
     kEnd
   };
Function Documentation
operator<()
bool vrprouting::problem::operator< (const Vehicle & lhs, const Vehicle & rhs)
Definition at line 433 of file vehicle.cpp.
{
   /*
    * capacity violations
    */
   if (lhs.cvTot() < rhs.cvTot()) return true;
   if (lhs.cvTot() > rhs.cvTot()) return false;
   /*
    * time window violations
    */
   if (lhs.twvTot() < rhs.twvTot()) return true;
   if (lhs.twvTot() > rhs.twvTot()) return false;
   /*
    * waiting time
    */
   if (lhs.total_wait_time() < rhs.total_wait_time()) return true;
   if (lhs.total_wait_time() > rhs.total_wait_time()) return false;
   /*
    * travel time
    */
   if (lhs.total_travel_time() < rhs.total_travel_time()) return true;
   if (lhs.total_travel_time() > rhs.total_travel_time()) return false;
   /*
    * duration
    */
   if (lhs.duration() < rhs.duration()) return true;
   if (lhs.duration() > rhs.duration()) return false;
   /*
    * truck size
    */
   if (lhs.size() < rhs.size()) return true;
   return false;
 }
References vrprouting::problem::Vehicle::cvTot(), vrprouting::problem::Vehicle::duration(), vrprouting::problem::Vehicle::total_travel_time(), vrprouting::problem::Vehicle::total_wait_time(), and vrprouting::problem::Vehicle::twvTot().
operator<<() [1/3]
std::ostream& vrprouting::problem::operator<< (std::ostream & log, const Order & order)
Prints:
Print the order.
the pickup
dropoff
Set of orders I than are I -> this
Set of orders J than are this -> I
Parameters
[in,out] log
[in] order
Returns
the ostream
Definition at line 77 of file order.cpp.
{
   log << "\n\nOrder "
     << static_cast<Identifier>(order) << ": \n"
     << "\tPickup: " << order.pickup() << "\n"
     << "\tDropoff: " << order.delivery() << "\n";
   log << "\nThere are | {I}| = "
     << order.m_compatibleI.size()
     << " -> order(" << order.idx()
     << ") -> | {J}| = " << order.m_compatibleJ.size()
     << "\n\n {";
   for (const auto o : order.m_compatibleI) {
     log << o << ", ";
   }
   log << "} -> " << order.idx() << " -> {";
   for (const auto o : order.m_compatibleJ) {
     log << o << ", ";
   }
   log << "}";
   return log;
 }
References vrprouting::problem::Order::delivery(), vrprouting::Identifier::idx(), vrprouting::problem::Order::m_compatibleI, vrprouting::problem::Order::m_compatibleJ, vrprouting::problem::Order::pickup(), and Identifiers< T >::size().
operator<<() [2/3]
std::ostream& vrprouting::problem::operator<< (std::ostream & log, const Tw_node & n)
Returns
the printed information of the node
Parameters
[in] log
[in] n
Definition at line 362 of file tw_node.cpp.
{
   log << n.id()
     << "[opens = " << n.m_opens
     << "\tcloses = " << n.m_closes
     << "\tservice = " << n.m_service_time
     << "\tdemand = " << n.m_demand
     << "\ttype = " << n.type_str()
     << "]"
     << "\n";
   return log;
 }
References vrprouting::Identifier::id(), vrprouting::problem::Tw_node::m_closes, vrprouting::problem::Tw_node::m_demand, vrprouting::problem::Tw_node::m_opens, vrprouting::problem::Tw_node::m_service_time, and vrprouting::problem::Tw_node::type_str().
operator<<() [3/3]
std::ostream& vrprouting::problem::operator<< (std::ostream & log, const Vehicle_node & v)
Parameters
[in,out] log Place to store the printed status of the node
[in] v Vehicle node to print
Returns
the new string
Definition at line 119 of file vehicle_node.cpp.
{
   log << static_cast<const Tw_node&>(v)
     << " twv = " << v.has_twv()
     << ", twvTot = " << v.twvTot()
     << ", cvTot = " << v.cvTot()
     << ", cargo = " << v.cargo()
     << ", travel_time = " << v.travel_time()
     << ", arrival_time = " << v.arrival_time()
     << ", wait_time = " << v.wait_time()
     << ", service_time = " << v.service_time()
     << ", departure_time = " << v.departure_time();
   return log;
 }
References vrprouting::problem::Vehicle_node::arrival_time(), vrprouting::problem::Vehicle_node::cargo(), vrprouting::problem::Vehicle_node::cvTot(), vrprouting::problem::Vehicle_node::departure_time(), vrprouting::problem::Vehicle_node::has_twv(), vrprouting::problem::Tw_node::service_time(), vrprouting::problem::Vehicle_node::travel_time(), vrprouting::problem::Vehicle_node::twvTot(), and vrprouting::problem::Vehicle_node::wait_time().