vrpRouting: anonymous_namespace{tabu.cpp} Namespace Reference
anonymous_namespace{tabu.cpp} Namespace Reference
Anonymus namespace for static functions.
Functions
bool are_all_served (const Identifiers< size_t > &unassigned)
Are all orders served?
Identifiers< size_t > set_unassignedOrders (const std::deque< vrprouting::problem::Vehicle_pickDeliver > &fleet)
set of unassigned orders
Detailed Description
Anonymus namespace for static functions.
Function Documentation
are_all_served()
bool anonymous_namespace{tabu.cpp}::are_all_served (const Identifiers< size_t > & unassigned)
Are all orders served?
Returns
false when a phony vehicle has an order
true when all phony vehicles have no orders
Parameters
[in] unassigned
Definition at line 63 of file optimizers/tabu.cpp.
{
     return unassigned.empty();
 }
References Identifiers< T >::empty().
Referenced by vrprouting::optimizers::tabu::Optimize::diversify(), vrprouting::optimizers::tabu::Optimize::intensify(), vrprouting::optimizers::tabu::Optimize::move_2_real(), and vrprouting::optimizers::tabu::Optimize::tabu_search().
set_unassignedOrders()
Identifiers<size_t> anonymous_namespace{tabu.cpp}::set_unassignedOrders (const std::deque< vrprouting::problem::Vehicle_pickDeliver > & fleet)
set of unassigned orders
Definition at line 48 of file optimizers/tabu.cpp.
{
     Identifiers<size_t> unassigned_orders;
     for (const auto &v : fleet) {
         if (v.is_phony()) unassigned_orders += v.orders_in_vehicle();
     }
     return unassigned_orders;
 }
Referenced by vrprouting::optimizers::tabu::Optimize::tabu_search().