vrpRouting: orders_input.h File Reference
orders_input.h File Reference
#include <stddef.h>
Typedefs
typedef struct PickDeliveryOrders_t PickDeliveryOrders_t
Functions
void get_shipments (char *, PickDeliveryOrders_t **, size_t *)
Reads the pick-Deliver shipments for timestams and intervals.
void get_shipments_euclidean (char *, PickDeliveryOrders_t **, size_t *)
Reads the pick-Deliver shipments for euclidean information.
void get_shipments_raw (char *, PickDeliveryOrders_t **, size_t *)
Reads the pick-Deliver shipments for raw data.
Typedef Documentation
PickDeliveryOrders_t
typedef struct PickDeliveryOrders_t PickDeliveryOrders_t
Definition at line 30 of file orders_input.h.
Function Documentation
get_shipments()
void get_shipments (char * sql, PickDeliveryOrders_t ** rows, size_t * total_rows)
Reads the pick-Deliver shipments for timestams and intervals.
Parameters
[in] sql SQL query to execute
[out] rows C Container that holds the data
[out] total_rows Total rows recieved
Definition at line 331 of file orders_input.c.
{
   const int column_count = 10;
   Column_info_t info[10];
   for (int i = 0; i < column_count; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "id";
   info[1].name = "amount";
   info[2].name = "p_id";
   info[3].name = "p_tw_open";
   info[4].name = "p_tw_close";
   info[5].name = "p_t_service";
   info[6].name = "d_id";
   info[7].name = "d_tw_open";
   info[8].name = "d_tw_close";
   info[9].name = "d_t_service";
   info[3].eType = TIMESTAMP;
   info[4].eType = TIMESTAMP;
   info[7].eType = TIMESTAMP;
   info[8].eType = TIMESTAMP;
   info[5].eType = INTERVAL;
   info[9].eType = INTERVAL;
   /* service is optional*/
   info[5].strict = false;
   info[9].strict = false;
   pgr_get_pd_orders_general(sql, rows, total_rows, info, column_count, 0);
 }
References ANY_INTEGER, Column_info_t::colNumber, Column_info_t::eType, INTERVAL, Column_info_t::name, pgr_get_pd_orders_general(), Column_info_t::strict, TIMESTAMP, and Column_info_t::type.
Referenced by process().
get_shipments_euclidean()
void get_shipments_euclidean (char * sql, PickDeliveryOrders_t ** rows, size_t * total_rows)
Reads the pick-Deliver shipments for euclidean information.
Parameters
[in] sql SQL query to execute
[out] rows C Container that holds the data
[out] total_rows Total rows recieved
Definition at line 414 of file orders_input.c.
{
   const int column_count = 12;
   Column_info_t info[12];
   for (int i = 0; i < column_count; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "id";
   info[1].name = "amount";
   info[2].name = "p_open";
   info[3].name = "p_close";
   info[4].name = "p_service";
   info[5].name = "d_open";
   info[6].name = "d_close";
   info[7].name = "d_service";
   info[8].name = "p_x";
   info[9].name = "p_y";
   info[10].name = "d_x";
   info[11].name = "d_y";
   /* service is optional*/
   info[4].strict = false;
   info[7].strict = false;
   /* (x,y) are ignored*/
   info[8].eType = ANY_NUMERICAL;
   info[9].eType = ANY_NUMERICAL;
   info[10].eType = ANY_NUMERICAL;
   info[11].eType = ANY_NUMERICAL;
   pgr_get_pd_orders_general(sql, rows, total_rows, info, column_count, 2);
 }
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, Column_info_t::name, pgr_get_pd_orders_general(), Column_info_t::strict, and Column_info_t::type.
Referenced by process().
get_shipments_raw()
void get_shipments_raw (char * sql, PickDeliveryOrders_t ** rows, size_t * total_rows)
Reads the pick-Deliver shipments for raw data.
Parameters
[in] sql SQL query to execute
[out] rows C Container that holds the data
[out] total_rows Total rows recieved
Definition at line 376 of file orders_input.c.
{
   const int column_count = 10;
   Column_info_t info[10];
   for (int i = 0; i < column_count; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "id";
   info[1].name = "amount";
   info[2].name = "p_open";
   info[3].name = "p_close";
   info[4].name = "p_service";
   info[5].name = "d_open";
   info[6].name = "d_close";
   info[7].name = "d_service";
   info[8].name = "p_id";
   info[9].name = "d_id";
   /* service is optional*/
   info[4].strict = false;
   info[7].strict = false;
   pgr_get_pd_orders_general(sql, rows, total_rows, info, column_count, 1);
 }
References ANY_INTEGER, Column_info_t::colNumber, Column_info_t::eType, Column_info_t::name, pgr_get_pd_orders_general(), Column_info_t::strict, and Column_info_t::type.
Referenced by process().