vrpRouting: shipments_input.c File Reference
shipments_input.c File Reference
#include "c_common/vroom/shipments_input.h"
Functions
static void db_get_shipments (char *shipments_sql, Vroom_shipment_t **shipments, size_t *total_shipments, Column_info_t *info, const int column_count, bool is_plain)
static void fetch_shipments (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t *info, Vroom_shipment_t *shipment, bool is_plain)
void get_vroom_shipments (char *sql, Vroom_shipment_t **rows, size_t *total_rows, bool is_plain)
Reads the VROOM shipments.
Function Documentation
db_get_shipments()
static void db_get_shipments (char * shipments_sql, Vroom_shipment_t ** shipments, size_t * total_shipments, Column_info_t * info, const int column_count, bool is_plain) static
Definition at line 119 of file shipments_input.c.
                    {
 #ifdef PROFILE
   clock_t start_t = clock();
   PGR_DBG("%s", shipments_sql);
 #endif
   const int tuple_limit = 1000000;
   size_t total_tuples;
   void *SPIplan;
   SPIplan = pgr_SPI_prepare(shipments_sql);
   Portal SPIportal;
   SPIportal = pgr_SPI_cursor_open(SPIplan);
   bool moredata = true;
   (*total_shipments) = total_tuples = 0;
   /* on the first tuple get the column numbers */
   while (moredata == true) {
     SPI_cursor_fetch(SPIportal, true, tuple_limit);
     if (total_tuples == 0) {
       pgr_fetch_column_info(info, column_count);
     }
     size_t ntuples = SPI_processed;
     total_tuples += ntuples;
     if (ntuples > 0) {
       if ((*shipments) == NULL)
         (*shipments) = (Vroom_shipment_t *)palloc0(
             total_tuples * sizeof(Vroom_shipment_t));
       else
         (*shipments) = (Vroom_shipment_t *)repalloc(
             (*shipments),
             total_tuples * sizeof(Vroom_shipment_t));
       if ((*shipments) == NULL) {
         elog(ERROR, "Out of memory");
       }
       size_t t;
       SPITupleTable *tuptable = SPI_tuptable;
       TupleDesc tupdesc = SPI_tuptable->tupdesc;
       for (t = 0; t < ntuples; t++) {
         HeapTuple tuple = tuptable->vals[t];
         fetch_shipments(&tuple, &tupdesc, info,
             &(*shipments)[total_tuples - ntuples + t], is_plain);
       }
       SPI_freetuptable(tuptable);
     } else {
       moredata = false;
     }
   }
   SPI_cursor_close(SPIportal);
   if (total_tuples == 0) {
     (*total_shipments) = 0;
     return;
   }
   (*total_shipments) = total_tuples;
 #ifdef PROFILE
   time_msg("reading shipments", start_t, clock());
 #endif
 }
References fetch_shipments(), PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), and time_msg().
Referenced by get_vroom_shipments().
fetch_shipments()
static void fetch_shipments (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t * info, Vroom_shipment_t * shipment, bool is_plain) static
Definition at line 83 of file shipments_input.c.
                    {
   shipment->id = get_Idx(tuple, tupdesc, info[0], 0);
   shipment->p_location_index = get_MatrixIndex(tuple, tupdesc, info[1], 0);
   shipment->d_location_index = get_MatrixIndex(tuple, tupdesc, info[3], 0);
   if (is_plain) {
     shipment->p_service = get_Duration(tuple, tupdesc, info[2], 0);
     shipment->d_service = get_Duration(tuple, tupdesc, info[4], 0);
   } else {
     shipment->p_service =
         (Duration)get_PositiveTInterval(tuple, tupdesc, info[2], 0);
     shipment->d_service =
         (Duration)get_PositiveTInterval(tuple, tupdesc, info[4], 0);
   }
   shipment->amount_size = 0;
   shipment->amount = column_found(info[5].colNumber) ?
     spi_getPositiveBigIntArr_allowEmpty(tuple, tupdesc, info[5], &shipment->amount_size)
     : NULL;
   shipment->skills_size = 0;
   shipment->skills = column_found(info[6].colNumber) ?
     spi_getPositiveIntArr_allowEmpty(tuple, tupdesc, info[6], &shipment->skills_size)
     : NULL;
   shipment->priority = get_Priority(tuple, tupdesc, info[7], 0);
 }
References Vroom_shipment_t::amount, Vroom_shipment_t::amount_size, column_found(), Vroom_shipment_t::d_location_index, Vroom_shipment_t::d_service, get_Duration(), get_Idx(), get_MatrixIndex(), get_PositiveTInterval(), get_Priority(), Vroom_shipment_t::id, Vroom_shipment_t::p_location_index, Vroom_shipment_t::p_service, Vroom_shipment_t::priority, Vroom_shipment_t::skills, Vroom_shipment_t::skills_size, spi_getPositiveBigIntArr_allowEmpty(), and spi_getPositiveIntArr_allowEmpty().
Referenced by db_get_shipments().
get_vroom_shipments()
void get_vroom_shipments (char * sql, Vroom_shipment_t ** rows, size_t * total_rows, bool is_plain)
Reads the VROOM shipments.
Parameters
[in] sql SQL query to execute
[out] rows C Container that holds the data
[out] total_rows Total rows recieved
Definition at line 200 of file shipments_input.c.
                    {
   int kColumnCount = 8;
   Column_info_t info[kColumnCount];
   for (int i = 0; i < kColumnCount; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = false;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "id";
   /* pickup shipments */
   info[1].name = "p_location_index";
   info[2].name = "p_service";
   /* delivery shipments */
   info[3].name = "d_location_index";
   info[4].name = "d_service";
   info[5].name = "amount";
   info[6].name = "skills";
   info[7].name = "priority";
   info[2].eType = INTEGER;            // p_service
   info[4].eType = INTEGER;            // d_service
   info[5].eType = ANY_INTEGER_ARRAY;  // amount
   info[6].eType = INTEGER_ARRAY;      // skills
   info[7].eType = INTEGER;            // priority
   if (!is_plain) {
     info[2].eType = INTERVAL;         // p_service
     info[4].eType = INTERVAL;         // d_service
   }
   /* id and location_index of pickup and delivery are mandatory */
   info[0].strict = true;
   info[1].strict = true;
   info[3].strict = true;
   db_get_shipments(sql, rows, total_rows, info, kColumnCount, is_plain);
 }
References ANY_INTEGER, ANY_INTEGER_ARRAY, Column_info_t::colNumber, db_get_shipments(), Column_info_t::eType, INTEGER, INTEGER_ARRAY, INTERVAL, Column_info_t::name, Column_info_t::strict, and Column_info_t::type.
Referenced by process().