vrpRouting: time_multipliers_input.h File Reference
time_multipliers_input.h File Reference
#include <stddef.h>
Typedefs
typedef struct Time_multipliers_t Time_multipliers_t
Functions
void get_timeMultipliers (char *sql, Time_multipliers_t **row, size_t *total_rows)
Get the time multipliers using interval.
void get_timeMultipliers_raw (char *sql, Time_multipliers_t **row, size_t *total_rows)
Get the time multipliers using bigint.
Typedef Documentation
Time_multipliers_t
typedef struct Time_multipliers_t Time_multipliers_t
Definition at line 35 of file time_multipliers_input.h.
Function Documentation
get_timeMultipliers()
void get_timeMultipliers (char * sql, Time_multipliers_t ** rows, size_t * total_rows)
Get the time multipliers using interval.
Parameters
[in] sql query that has the following columns: start_time, multiplier
[out] rows C Container that holds all the multipliers rows
[out] total_rows Total rows recieved
Definition at line 149 of file time_multipliers_input.c.
{
   Column_info_t info[2];
   int i;
   for (i = 0; i < 2; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = ANY_NUMERICAL;
   }
   info[0].name = "start_time";
   info[1].name = "multiplier";
   info[0].eType = TIMESTAMP;
   get_timeMultipliersGeneral(sql, info, 0, rows, total_rows);
 }
References ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, get_timeMultipliersGeneral(), Column_info_t::name, Column_info_t::strict, TIMESTAMP, and Column_info_t::type.
Referenced by process().
get_timeMultipliers_raw()
void get_timeMultipliers_raw (char * sql, Time_multipliers_t ** rows, size_t * total_rows)
Get the time multipliers using bigint.
Parameters
[in] sql query that has the following columns: start_time, multiplier
[out] rows C Container that holds all the multipliers
[out] total_rows Total rows recieved
Definition at line 175 of file time_multipliers_input.c.
{
   Column_info_t info[2];
   int i;
   for (i = 0; i < 2; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = ANY_NUMERICAL;
   }
   info[0].name = "start_value";
   info[1].name = "multiplier";
   info[0].eType = ANY_INTEGER;
   get_timeMultipliersGeneral(sql, info, 1, rows, total_rows);
 }
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, get_timeMultipliersGeneral(), Column_info_t::name, Column_info_t::strict, and Column_info_t::type.
Referenced by process().