vrpRouting: time_multipliers_input.c File Reference
time_multipliers_input.c File Reference
#include "c_common/time_multipliers_input.h"
#include "c_types/column_info_t.h"
#include "c_types/time_multipliers_t.h"
#include "c_common/get_check_data.h"
Functions
static void fetch_raw (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[2], Time_multipliers_t *row)
static void fetch_timestamps (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[2], Time_multipliers_t *row)
void get_timeMultipliers (char *sql, Time_multipliers_t **rows, size_t *total_rows)
Get the time multipliers using interval.
void get_timeMultipliers_raw (char *sql, Time_multipliers_t **rows, size_t *total_rows)
Get the time multipliers using bigint.
static void get_timeMultipliersGeneral (char *sql, Column_info_t *info, const int kind, Time_multipliers_t **rows, size_t *total_rows)
param [in] sql multipliers SQL param [in,out] rows catptured information param [in,out] total_rows total information captured
Function Documentation
fetch_raw()
static void fetch_raw (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[2], Time_multipliers_t * row) static
Definition at line 41 of file time_multipliers_input.c.
{
   row->start_time = get_TTimestamp_plain(tuple, tupdesc, info[0], 0);
   row->multiplier = spi_getFloat8(tuple, tupdesc,  info[1]);
 }
References get_TTimestamp_plain(), Time_multipliers_t::multiplier, spi_getFloat8(), and Time_multipliers_t::start_time.
Referenced by get_timeMultipliersGeneral().
fetch_timestamps()
static void fetch_timestamps (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[2], Time_multipliers_t * row) static
Definition at line 51 of file time_multipliers_input.c.
{
   row->start_time = get_TTimestamp(tuple, tupdesc, info[0], 0);
   row->multiplier = spi_getFloat8(tuple, tupdesc,  info[1]);
 }
References get_TTimestamp(), Time_multipliers_t::multiplier, spi_getFloat8(), and Time_multipliers_t::start_time.
Referenced by get_timeMultipliersGeneral().
get_timeMultipliers()
void get_timeMultipliers (char * sql, Time_multipliers_t ** rows, size_t * total_rows)
Get the time multipliers using interval.
Parameters
[in] sql query that has the following columns: start_time, multiplier
[out] rows C Container that holds all the multipliers rows
[out] total_rows Total rows recieved
Definition at line 149 of file time_multipliers_input.c.
{
   Column_info_t info[2];
   int i;
   for (i = 0; i < 2; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = ANY_NUMERICAL;
   }
   info[0].name = "start_time";
   info[1].name = "multiplier";
   info[0].eType = TIMESTAMP;
   get_timeMultipliersGeneral(sql, info, 0, rows, total_rows);
 }
References ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, get_timeMultipliersGeneral(), Column_info_t::name, Column_info_t::strict, TIMESTAMP, and Column_info_t::type.
Referenced by process().
get_timeMultipliers_raw()
void get_timeMultipliers_raw (char * sql, Time_multipliers_t ** rows, size_t * total_rows)
Get the time multipliers using bigint.
Parameters
[in] sql query that has the following columns: start_time, multiplier
[out] rows C Container that holds all the multipliers
[out] total_rows Total rows recieved
Definition at line 175 of file time_multipliers_input.c.
{
   Column_info_t info[2];
   int i;
   for (i = 0; i < 2; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = true;
     info[i].eType = ANY_NUMERICAL;
   }
   info[0].name = "start_value";
   info[1].name = "multiplier";
   info[0].eType = ANY_INTEGER;
   get_timeMultipliersGeneral(sql, info, 1, rows, total_rows);
 }
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, get_timeMultipliersGeneral(), Column_info_t::name, Column_info_t::strict, and Column_info_t::type.
Referenced by process().
get_timeMultipliersGeneral()
static void get_timeMultipliersGeneral (char * sql, Column_info_t * info, const int kind, Time_multipliers_t ** rows, size_t * total_rows) static
param [in] sql multipliers SQL param [in,out] rows catptured information param [in,out] total_rows total information captured
Definition at line 66 of file time_multipliers_input.c.
{
 #ifdef PROFILE
   clock_t start_t = clock();
   PGR_DBG("%s", sql);
 #endif
   const int tuple_limit = 1000000;
   size_t total_tuples = 0;
   const int column_count = 2;
   void *SPIplan;
   SPIplan = pgr_SPI_prepare(sql);
   Portal SPIportal;
   SPIportal = pgr_SPI_cursor_open(SPIplan);
   bool moredata = true;
   (*total_rows) = total_tuples;
   while (moredata == true) {
     SPI_cursor_fetch(SPIportal, true, tuple_limit);
     if (total_tuples == 0)
       pgr_fetch_column_info(info, column_count);
     size_t ntuples = SPI_processed;
     total_tuples += ntuples;
     if (ntuples > 0) {
       if ((*rows) == NULL)
         (*rows) = (Time_multipliers_t *)palloc0(
             total_tuples * sizeof(Time_multipliers_t));
       else
         (*rows) = (Time_multipliers_t *)repalloc(
             (*rows), total_tuples * sizeof(Time_multipliers_t));
       if ((*rows) == NULL) {
         elog(ERROR, "Out of memory");
       }
       SPITupleTable *tuptable = SPI_tuptable;
       TupleDesc tupdesc = SPI_tuptable->tupdesc;
       for (size_t t = 0; t < ntuples; t++) {
         HeapTuple tuple = tuptable->vals[t];
         switch (kind) {
           case 0 : fetch_timestamps(&tuple, &tupdesc, info,
                        &(*rows)[total_tuples - ntuples + t]);
                    break;
           case 1 : fetch_raw(&tuple, &tupdesc, info,
                        &(*rows)[total_tuples - ntuples + t]);
                    break;
         }
       }
       SPI_freetuptable(tuptable);
     } else {
       moredata = false;
     }
   }
   SPI_cursor_close(SPIportal);
   if (total_tuples == 0) {
     (*total_rows) = 0;
     return;
   }
   (*total_rows) = total_tuples;
 #ifdef PROFILE
   time_msg("reading time dependant multipliers", start_t, clock());
 #endif
 }
References fetch_raw(), fetch_timestamps(), PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), and time_msg().
Referenced by get_timeMultipliers(), and get_timeMultipliers_raw().