vrpRouting: vehicles_input.h File Reference
vehicles_input.h File Reference
#include <stddef.h>
#include <stdbool.h>
Typedefs
typedef struct Vehicle_t Vehicle_t
Functions
void get_vehicles (char *, Vehicle_t **, size_t *, bool)
Reads the vehicles information.
void get_vehicles_euclidean (char *, Vehicle_t **, size_t *, bool)
Reads the vehicles information.
void get_vehicles_raw (char *, Vehicle_t **, size_t *, bool)
Reads the vehicles information.
Typedef Documentation
Vehicle_t
typedef struct Vehicle_t Vehicle_t
Definition at line 32 of file vehicles_input.h.
Function Documentation
get_vehicles()
void get_vehicles (char * sql, Vehicle_t ** rows, size_t * total_rows, bool with_stops)
Reads the vehicles information.
Parameters
[in] sql SQL query to execute
[in] with_stops do not ignore stops column
[out] rows C Container that holds the data
[out] total_rows Total rows recieved
Definition at line 469 of file vehicles_input.c.
                      {
   const int column_count = 13;
   Column_info_t info[13];
   for (int i = 0; i < column_count; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = false;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "id";
   info[1].name = "capacity";
   info[2].name = "number";
   info[3].name = "speed";
   info[4].name = "stops";
   info[5].name = "s_id";
   info[6].name = "s_tw_open";
   info[7].name = "s_tw_close";
   info[8].name = "s_t_service";
   info[9].name = "e_id";
   info[10].name = "e_tw_open";
   info[11].name = "e_tw_close";
   info[12].name = "e_t_service";
   info[6].eType = TIMESTAMP;
   info[7].eType = TIMESTAMP;
   info[10].eType = TIMESTAMP;
   info[11].eType = TIMESTAMP;
   info[8].eType = INTERVAL;
   info[12].eType = INTERVAL;
   info[4].eType = ANY_INTEGER_ARRAY;  // stops
   info[3].eType = ANY_NUMERICAL;      // speed
   info[0].strict = true;
   info[1].strict = true;
   info[5].strict = true;
   db_get_vehicles(sql, rows, total_rows, info, column_count, 0, with_stops);
 }
References ANY_INTEGER, ANY_INTEGER_ARRAY, ANY_NUMERICAL, Column_info_t::colNumber, db_get_vehicles(), Column_info_t::eType, INTERVAL, Column_info_t::name, Column_info_t::strict, TIMESTAMP, and Column_info_t::type.
Referenced by process().
get_vehicles_euclidean()
void get_vehicles_euclidean (char * sql, Vehicle_t ** rows, size_t * total_rows, bool with_stops)
Reads the vehicles information.
Parameters
[in] sql SQL query to execute
[in] with_stops do not ignore stops column
[out] rows C Container that holds the data
[out] total_rows Total rows recieved
Definition at line 569 of file vehicles_input.c.
                      {
   const int column_count = 15;
   Column_info_t info[15];
   for (int i = 0; i < column_count; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = false;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "id";
   info[1].name = "capacity";
   info[2].name = "number";
   info[3].name = "speed";
   info[4].name = "s_open";
   info[5].name = "s_close";
   info[6].name = "e_open";
   info[7].name = "e_close";
   info[8].name = "stops";
   info[9].name = "s_service";
   info[10].name = "e_service";
   info[11].name = "s_x";
   info[12].name = "s_y";
   info[13].name = "e_x";
   info[14].name = "e_y";
   info[8].eType = ANY_INTEGER_ARRAY;  // stops
   info[11].eType = ANY_NUMERICAL;  // s_x
   info[12].eType = ANY_NUMERICAL;  // s_y
   info[13].eType = ANY_NUMERICAL;  // e_x
   info[14].eType = ANY_NUMERICAL;  // e_y
   info[0].strict = true;
   info[1].strict = true;
   info[11].strict = true;
   info[12].strict = true;
   db_get_vehicles(sql, rows, total_rows, info, column_count, 2, with_stops);
 }
References ANY_INTEGER, ANY_INTEGER_ARRAY, ANY_NUMERICAL, Column_info_t::colNumber, db_get_vehicles(), Column_info_t::eType, Column_info_t::name, Column_info_t::strict, and Column_info_t::type.
Referenced by process().
get_vehicles_raw()
void get_vehicles_raw (char * sql, Vehicle_t ** rows, size_t * total_rows, bool with_stops)
Reads the vehicles information.
Parameters
[in] sql SQL query to execute
[in] with_stops do not ignore stops column
[out] rows C Container that holds the data
[out] total_rows Total rows recieved
Definition at line 522 of file vehicles_input.c.
                      {
   const int column_count = 13;
   Column_info_t info[13];
   for (int i = 0; i < column_count; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = false;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "id";
   info[1].name = "capacity";
   info[2].name = "number";
   info[3].name = "speed";
   info[4].name = "stops";
   info[5].name = "s_id";
   info[6].name = "s_open";
   info[7].name = "s_close";
   info[8].name = "s_service";
   info[9].name = "e_id";
   info[10].name = "e_open";
   info[11].name = "e_close";
   info[12].name = "e_service";
   info[4].eType = ANY_INTEGER_ARRAY;  // stops
   info[3].eType = ANY_NUMERICAL;      // speed
   info[0].strict = true;
   info[1].strict = true;
   info[5].strict = true;
   db_get_vehicles(sql, rows, total_rows, info, column_count, 1, with_stops);
 }
References ANY_INTEGER, ANY_INTEGER_ARRAY, ANY_NUMERICAL, Column_info_t::colNumber, db_get_vehicles(), Column_info_t::eType, Column_info_t::name, Column_info_t::strict, and Column_info_t::type.
Referenced by process().