vrpRouting: vehicles_input.c File Reference
vroom/vehicles_input.c File Reference
#include "c_common/vroom/vehicles_input.h"
Functions
static void db_get_vehicles (char *vehicles_sql, Vroom_vehicle_t **vehicles, size_t *total_vehicles, Column_info_t *info, const int column_count, bool is_plain)
static void fetch_vehicles (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t *info, Vroom_vehicle_t *vehicle, bool is_plain)
void get_vroom_vehicles (char *sql, Vroom_vehicle_t **rows, size_t *total_rows, bool is_plain)
Reads the VROOM vehicles.
Function Documentation
db_get_vehicles()
static void db_get_vehicles (char * vehicles_sql, Vroom_vehicle_t ** vehicles, size_t * total_vehicles, Column_info_t * info, const int column_count, bool is_plain) static
Definition at line 132 of file vroom/vehicles_input.c.
                    {
 #ifdef PROFILE
   clock_t start_t = clock();
   PGR_DBG("%s", vehicles_sql);
 #endif
   const int tuple_limit = 1000000;
   size_t total_tuples;
   void *SPIplan;
   SPIplan = pgr_SPI_prepare(vehicles_sql);
   Portal SPIportal;
   SPIportal = pgr_SPI_cursor_open(SPIplan);
   bool moredata = true;
   (*total_vehicles) = total_tuples = 0;
   /* on the first tuple get the column numbers */
   while (moredata == true) {
     SPI_cursor_fetch(SPIportal, true, tuple_limit);
     if (total_tuples == 0) {
       /* Atleast one out of start_index or end_index must be present */
       info[1].colNumber = SPI_fnumber(SPI_tuptable->tupdesc, "start_index");
       info[2].colNumber = SPI_fnumber(SPI_tuptable->tupdesc, "end_index");
       if (!column_found(info[1].colNumber) && !column_found(info[2].colNumber)) {
         elog(ERROR, "At least one out of start_index or end_index must be present");
       }
       pgr_fetch_column_info(info, column_count);
     }
     size_t ntuples = SPI_processed;
     total_tuples += ntuples;
     if (ntuples > 0) {
       if ((*vehicles) == NULL)
         (*vehicles) = (Vroom_vehicle_t *)palloc0(
             total_tuples * sizeof(Vroom_vehicle_t));
       else
         (*vehicles) = (Vroom_vehicle_t *)repalloc(
             (*vehicles),
             total_tuples * sizeof(Vroom_vehicle_t));
       if ((*vehicles) == NULL) {
         elog(ERROR, "Out of memory");
       }
       size_t t;
       SPITupleTable *tuptable = SPI_tuptable;
       TupleDesc tupdesc = SPI_tuptable->tupdesc;
       for (t = 0; t < ntuples; t++) {
         HeapTuple tuple = tuptable->vals[t];
         fetch_vehicles(&tuple, &tupdesc, info,
             &(*vehicles)[total_tuples - ntuples + t], is_plain);
       }
       SPI_freetuptable(tuptable);
     } else {
       moredata = false;
     }
   }
   SPI_cursor_close(SPIportal);
   if (total_tuples == 0) {
     (*total_vehicles) = 0;
     return;
   }
   (*total_vehicles) = total_tuples;
 #ifdef PROFILE
   time_msg("reading vehicles", start_t, clock());
 #endif
 }
References Column_info_t::colNumber, column_found(), fetch_vehicles(), PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), and time_msg().
Referenced by get_vroom_vehicles().
fetch_vehicles()
static void fetch_vehicles (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t * info, Vroom_vehicle_t * vehicle, bool is_plain) static
Definition at line 86 of file vroom/vehicles_input.c.
                    {
   vehicle->id = get_Idx(tuple, tupdesc, info[0], 0);
   vehicle->start_index = get_MatrixIndex(tuple, tupdesc, info[1], -1);
   vehicle->end_index = get_MatrixIndex(tuple, tupdesc, info[2], -1);
   vehicle->capacity_size = 0;
   vehicle->capacity = column_found(info[3].colNumber) ?
     spi_getPositiveBigIntArr_allowEmpty(tuple, tupdesc, info[3], &vehicle->capacity_size)
     : NULL;
   vehicle->skills_size = 0;
   vehicle->skills = column_found(info[4].colNumber) ?
     spi_getPositiveIntArr_allowEmpty(tuple, tupdesc, info[4], &vehicle->skills_size)
     : NULL;
   if (is_plain) {
     vehicle->time_window_start = get_Duration(tuple, tupdesc, info[5], 0);
     vehicle->time_window_end = get_Duration(tuple, tupdesc, info[6], UINT_MAX);
   } else {
     vehicle->time_window_start =
         (Duration)get_PositiveTTimestamp(tuple, tupdesc, info[5], 0);
     vehicle->time_window_end =
         (Duration)get_PositiveTTimestamp(tuple, tupdesc, info[6], UINT_MAX);
   }
   if (vehicle->time_window_start > vehicle->time_window_end) {
     ereport(ERROR,
         (errmsg("Invalid time window (%d, %d)",
             vehicle->time_window_start, vehicle->time_window_end),
          errhint("Time window start time %d must be "
              "less than or equal to time window end time %d",
              vehicle->time_window_start, vehicle->time_window_end)));
   }
   vehicle->speed_factor = column_found(info[7].colNumber) ?
     spi_getFloat8(tuple, tupdesc, info[7])
     : 1.0;
 }
References Vroom_vehicle_t::capacity, Vroom_vehicle_t::capacity_size, column_found(), Vroom_vehicle_t::end_index, get_Duration(), get_Idx(), get_MatrixIndex(), get_PositiveTTimestamp(), Vroom_vehicle_t::id, Vroom_vehicle_t::skills, Vroom_vehicle_t::skills_size, Vroom_vehicle_t::speed_factor, spi_getFloat8(), spi_getPositiveBigIntArr_allowEmpty(), spi_getPositiveIntArr_allowEmpty(), Vroom_vehicle_t::start_index, Vroom_vehicle_t::time_window_end, and Vroom_vehicle_t::time_window_start.
Referenced by db_get_vehicles().
get_vroom_vehicles()
void get_vroom_vehicles (char * sql, Vroom_vehicle_t ** rows, size_t * total_rows, bool is_plain)
Reads the VROOM vehicles.
Parameters
[in] sql SQL query to execute
[out] rows C Container that holds the data
[out] total_rows Total rows recieved
id is mandatory. At least one out of start_index or end_index must be present, but that is checked later.
Definition at line 219 of file vroom/vehicles_input.c.
                    {
   int kColumnCount = 8;
   Column_info_t info[kColumnCount];
   for (int i = 0; i < kColumnCount; ++i) {
     info[i].colNumber = -1;
     info[i].type = 0;
     info[i].strict = false;
     info[i].eType = ANY_INTEGER;
   }
   info[0].name = "id";
   info[1].name = "start_index";
   info[2].name = "end_index";
   info[3].name = "capacity";
   info[4].name = "skills";
   info[5].name = "tw_open";
   info[6].name = "tw_close";
   info[7].name = "speed_factor";
   info[3].eType = ANY_INTEGER_ARRAY;  // capacity
   info[4].eType = INTEGER_ARRAY;      // skills
   info[5].eType = INTEGER;            // tw_open
   info[6].eType = INTEGER;            // tw_close
   info[7].eType = ANY_NUMERICAL;      // speed_factor
   if (!is_plain) {
     info[5].eType = TIMESTAMP;        // tw_open
     info[6].eType = TIMESTAMP;        // tw_close
   }
   info[0].strict = true;
   db_get_vehicles(sql, rows, total_rows, info, kColumnCount, is_plain);
 }
References ANY_INTEGER, ANY_INTEGER_ARRAY, ANY_NUMERICAL, Column_info_t::colNumber, db_get_vehicles(), Column_info_t::eType, INTEGER, INTEGER_ARRAY, Column_info_t::name, Column_info_t::strict, TIMESTAMP, and Column_info_t::type.
Referenced by process().