DROP SCHEMA if EXISTS onedepot CASCADE;
CREATE SCHEMA onedepot;

CREATE TABLE onedepot.orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount INTEGER,
    open_time INTEGER,
    close_time INTEGER,
    service_time INTEGER,
    x float8,
    y float8
);

COPY onedepot.orders
(x, y, amount, open_time, close_time, service_time) FROM stdin;
40.000000	50.000000	0	0	240	0
25.000000	85.000000	20	145	175	10
22.000000	75.000000	30	50	80	10
22.000000	85.000000	10	109	139	10
20.000000	80.000000	40	141	171	10
20.000000	85.000000	20	41	71	10
18.000000	75.000000	20	95	125	10
15.000000	75.000000	20	79	109	10
15.000000	80.000000	10	91	121	10
10.000000	35.000000	20	91	121	10
10.000000	40.000000	30	119	149	10
\.

CREATE TABLE onedepot.vehicles (
    vehicle_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacity INTEGER
);

copy onedepot.vehicles (capacity) from stdin;
200
200
200
\.

WITH
the_matrix_info AS (
  SELECT A.id AS start_vid, B.id AS end_vid, sqrt( (a.x - b.x) * (a.x - b.x) + (a.y - b.y) * (a.y - b.y)) AS agg_cost
    FROM onedepot.orders AS A, onedepot.orders AS B WHERE A.id != B.id
)
SELECT start_vid, end_vid, agg_cost::INTEGER
INTO onedepot.distances
FROM the_matrix_info;
