name: Publish Users Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    name: Publish Users Documentation
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get postgres version
        run: |
          sudo service postgresql start
          PGVER=$(psql --version | grep -Po '(?<=psql \(PostgreSQL\) )[^;]+(?=\.\d \()')
          PROJECT_VERSION=$(grep -Po '(?<=project\(VRPROUTING VERSION )[^;]+' CMakeLists.txt)
          echo "PGVER=${PGVER}" >> $GITHUB_ENV
          echo "PGPORT=5432" >> $GITHUB_ENV
          echo "PGIS=3" >> $GITHUB_ENV
          echo "PROJECT_VERSION=${PROJECT_VERSION}" >> $GITHUB_ENV

      - name: Extract branch name and commit hash
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "BRANCH=$branch" >> $GITHUB_ENV
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "GIT_HASH=$git_hash" >> $GITHUB_ENV

      - name: Add PostgreSQL APT repository
        run: |
          sudo apt-get install curl ca-certificates gnupg
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ \
            $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libboost-graph-dev \
            postgresql-${PGVER} \
            postgresql-${PGVER}-postgis-${PGIS} \
            postgresql-${PGVER}-postgis-${PGIS}-scripts \
            postgresql-server-dev-${PGVER} \
            graphviz \
            doxygen
          python -m pip install --upgrade pip
          pip install Sphinx
          pip install sphinx-bootstrap-theme
          pip list

      - name: Install VROOM dependencies
        run: |
          sudo apt-get install libssl-dev libasio-dev libglpk-dev

      - name: Build VROOM v1.10.0
        run: |
          wget https://github.com/VROOM-Project/vroom/archive/refs/tags/v1.10.0.tar.gz
          tar -zvxf v1.10.0.tar.gz
          cd vroom-1.10.0/src

          # Create object file with position independent code using -fPIC flag
          sed -i 's/CXXFLAGS = /CXXFLAGS = -fPIC /' makefile

          make
          cd ..
          echo "VROOM_INSTALL_PATH=$(pwd)" >> $GITHUB_ENV

      - name: Configure
        run: |
          export PATH=/usr/lib/postgresql/${PGVER}/bin:$PATH
          mkdir build
          cd build
          cmake -DPOSTGRESQL_VERSION=${PGVER} -DDOC_USE_BOOTSTRAP=ON -DWITH_DOC=ON -DBUILD_DOXY=ON -DCMAKE_BUILD_TYPE=Release -DES=ON -DVROOM_INSTALL_PATH=${VROOM_INSTALL_PATH} ..

      - name: Build
        run: |
          cd build
          make doc
          make doxy

      - name: Initialize mandatory git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update Users Documentation
        run: |
          if [[ "${{ env.BRANCH }}" == "main" ]]; then
            FOLDER_NAME="main"
          elif [[ "${{ env.BRANCH }}" == "develop" ]]; then
            FOLDER_NAME="dev"
          fi
          git checkout origin/gh-pages
          git checkout -b gh-pages
          rm -rf ${FOLDER_NAME}
          cp -r build/doc/html ${FOLDER_NAME}
          git add ${FOLDER_NAME}
          git diff-index --quiet HEAD || git commit -m "Update users documentation for ${PROJECT_VERSION} (${{ env.BRANCH }}): commit ${{ env.GIT_HASH }}"
          git fetch origin
          git rebase origin/gh-pages
          git push origin gh-pages
          git checkout @{-2}

      - name: Update Developers Documentation
        run: |
          if [[ "${{ env.BRANCH }}" == "main" ]]; then
            FOLDER_NAME="main"
          elif [[ "${{ env.BRANCH }}" == "develop" ]]; then
            FOLDER_NAME="dev"
          fi
          git checkout gh-pages
          rm -rf doxy/${FOLDER_NAME}
          cp -r build/doxygen/html doxy/${FOLDER_NAME}
          git add doxy/${FOLDER_NAME}
          git diff-index --quiet HEAD || git commit -m "Update developers documentation for ${PROJECT_VERSION} (${{ env.BRANCH }}): commit ${{ env.GIT_HASH }}"
          git fetch origin
          git rebase origin/gh-pages
          git push origin gh-pages
          git checkout @{-1}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
